influxdata/flux

stdlib/universe/schema_functions.go
stdlib/universe/schema_functions_deprecated.go
stdlib/universe/schema_functions_deprecated_test.go
stdlib/universe/schema_mutators.go

This changes the schema mutation functions to mutate the table in place
without requiring any copies to the data. The schema for the table will
be mutated by wrapping the table and manipulating the schema on the
`flux.Table` object instead of requiring a copy of the data. The retain
functions for arrays are used to facilitate this.
Then it uses the buffered table builder to append the buffers to each
other to perform the regrouping which mimics the same code that group
uses.
Fixes #2879.

feat(stdlib/universe): implement schema mutation functions without performing any copies

---

compiler/compiler.go
compiler/compiler_test.go

The array element type wouldn't substitute correctly because it compared
only one of the types with itself instead of comparing the two different
types.
The compiler has also been modified to catch when a required argument is
omitted within the go runtime compiler.

fix(compiler): substitute array element types correctly

---

compiler/compiler_test.go
compiler/runtime.go
interpreter/interpreter_test.go

This check was present for the interpreter only. Added tests for both
interpreter and evaluation.

fix: verify index expression bounds in evaluation

---

stdlib/sql/from_private_test.go

This test breaks on go 1.14 as the error message sqlite generates is
different. It was removed in this patch because it doesn't seem to
actually test any flux code, but asserts on code from the stdlib.
Asserting on code we don't own should be a thing that is done often, and
when it is done, should have well understood reasoning for, rather than
just defaulting.
Closes #2931

fix: remove bad_sqlite_path1 test

---

release.sh

This change makes it so that if local and remote tags do not match you can see the difference.

fix(release): add diff output to release script on error

---

docs/SPEC.md

Also add a link to the Unicode 8.0 standard.

fix: Correct typo in SPEC.md

---

lang/compiler.go
plan/rules_test.go

fix(lang): pass the context to the planner when using the table object compiler

---

execute/table.go
execute/table_test.go

When appending an array of boolean values, it was marking the wrong
indices as boolean by marking one after the value that was appended
rather than the one just appended. This resulted in other sections of
the code being wrong because the copied column was not copied correctly.
Related to influxdata/influxdb#18433.

fix(execute): appending an array of booleans with null values functions correctly

---

plan/logical.go

This just makes it so we use the proper Flux error package, and classify the error as a user error, not internal.

chore(plan): correctly classify "duplicate yield" error

---

stdlib/influxdata/influxdb/buckets_test.go
stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/from_test.go
stdlib/influxdata/influxdb/internal/testutil/testing.go
stdlib/influxdata/influxdb/rules_test.go
stdlib/influxdata/influxdb/source.go
stdlib/influxdata/influxdb/v1/databases_test.go

The remote influxdb queries are now formatted and issued with query text
instead of raw AST. This is because the query string is better supported
for all of the various different platforms. The influxdb 1.x integration
with flux doesn't support AST and the influxdb v2 official client
doesn't support using AST anyway.
We are still using our own HTTP calls at the moment instead of the
official v2 API because the official API doesn't support both `org` and
`orgID`. Since we are not certain if both of those query parameters will
be supported in the future, I am hesitant to switch to the official
client until that decision has been made and the client is either
updated to support only one of them or support both.
This change also removes the requirement for `org` or `orgID` to be
specified. …

fix(stdlib): use query strings instead of ast for remote influxdb queries

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/join_use_previous_test.flux

This patch adds a test for a coincidental fix that was added previously.
There was a correctness error when using boolean values when joining
that was made worse when using `usePrevious`.
Closes #2864

test: add test for join and usePrevious

---

internal/execute/table/buffered_builder_test.go
internal/execute/table/buffered_test.go
internal/execute/table/diff.go
internal/execute/table/diff_test.go
internal/execute/table/iterator.go
internal/execute/table/sort.go
internal/execute/table/stream_test.go
internal/execute/table/stringify.go
internal/execute/table/stringify_test.go
internal/execute/table/utils.go

This adds a `Stringify` method to the `internal/execute/table` package
to convert a table into a string that is easily diffable. It also
contains a `DiffIterator` method that will sort and then stringify each
table and then pass it through a line diff instead of `cmp.Diff`.
This should produce more readable results than `cmp.Diff`.

feat(execute/table): add stringify method for a table and a diff utility

---

libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/chobbs/discord/README.md
stdlib/contrib/chobbs/discord/discord.flux
stdlib/contrib/chobbs/discord/discord_test.go
stdlib/contrib/chobbs/discord/flux_gen.go

This PR adds a new endpoint function to flux contrib/chobbs/discord package + updates documentation and improves tests. This function is added in order to have the same capabilities as other notification packages (slack/pagerduty/teams/telegram) that are then used in InfluxDB.

feat(contrib/discord): add discord.endpoint fn

---

execute/executor.go
execute/source.go
lang/compiler.go
lang/execdeps/dependencies.go
metadata/metadata.go
mock/executor.go
query.go
stdlib/experimental/chain.go
stdlib/universe/dual_impl_spec.go
stdlib/universe/table_fns.go

`Metadata` is a key-value map stored with the query statistics.
It currently contains data for the sources, for example, "influxdb/scanned-bytes" and "influxdb/scanned-values".
The goal here is to add the query plan to query metadata, which is later accessed to generate the `query_log` entry.
Queries with functions like `tableFind()` and `experimental.chain()` will call into the execution engine more than once. The statistics of those additional calls won't be preserved so their query plans are lost.
The solution for it is temporarily caching their metadata in the execution dependency, and we will extract them at the time when the main query is executed. 
In this PR, `flux.Metadata` is moved to a standalone package to address a dependency cycle issue: `influxd -> flux -> flux/interpreter …

feat: add query plan to query metadata

---

execute/executetest/source.go
stdlib/socket/from_private_test.go
stdlib/sql/from_private_test.go

The socket and sql url validator tests would fail on linux systems
because the message returned from Go depended on the specific DNS
resolver being used. The test case now validates that the error comes
form the correct call to the validation path but does not otherwise care
about the specific wording used to indicate a DNS resolution failure.
Additionally the hostname used is guaranteed to not exist based on RFC
6761.

fix(deps): make socket/sql url test robust

---

compiler/compiler.go
compiler/compiler_test.go
semantic/monotype.go

This fixes a bug in the compiler for an example like this:
```
csv.from(csv: inData)
|> range(start: 2020-08-10T00:00:00Z)
|> filter(fn: (r) => r._measurement == "events" and r._field == "times")
|> map(fn: (r) => {
start = time(v: r._value)
stop = experimental.addDuration(to: start, d: 1h)
city = r.city
agg = csv.from(csv: inData)
|> range(start, stop)
|> filter(fn: (r) => r._measurement == "city_data" and r._field == "temp" and r.city == city)
|> mean()
|> findRecord(fn: (key) => true, idx: 0)
return {_time: stop, _value: agg._value, _field: "event_temp_mean"}
})
```
The issue was that if one uses the `|>` operator from inside a call to `map` (here we use the `compiler` to evaluate Flux, rather than the interpreter), it would not properly propagate the pipe argument for call …

fix(compiler): handle pipe arguments inside of compiler

---

docs/SPEC.md
internal/parser/grammar.md

We are standardizing on the language of record instead of object or row.
This change updates the SPEC accordingly.
See https://github.com/influxdata/flux/issues/2088

docs(spec): rewrite uses of object with record

---

ast/edit/task_editor.go
ast/edit/task_editor_test.go

This adds a new helper function to the `ast/edit` package that indicates whether or not an `ast.File` has duplicate `option` assignments for the same variable. The current evaluation behavior of Flux produces a runtime error when it sees multiple assignments to the same `option` variable. This will allow us to maintain parity with that behavior as we migrate to AST-based `option` extraction/updating for Task options.

feat(ast/edit): Add function to indicate duplicate option assignments

---

stdlib/universe/key_values.go
stdlib/universe/key_values_test.go

Previously `keyValues` would only output one row per distinct value among all of the `KeyColumns`. Now it will output one row per distinct value per each `KeyColumns` value. The necessary changes included updating the following map from
```Go
var intDistinct = map[int64]bool{}
```
to
```Go
var intDistinct = map[struct {
string
int64
}]bool{}
```
Fixes https://github.com/influxdata/influxdb/issues/19134.

fix: calculate distinct key values

---

compiler/runtime.go
compiler/runtime_test.go
interpreter/interpreter.go

This is a refactor that exposes code that implements the `interpreter.Resolver` interface so that it can be accessed via the `compiler` package. This code allows the `compiler.functionValue` struct also implement the interface.
This will let use handle queries like this one:
```
csv.from(csv: inData)
|> range(start: 2020-08-10T00:00:00Z)
|> filter(fn: (r) => r._measurement == "events" and r._field == "times")
|> map(fn: (r) => {
start = time(v: r._value)
stop = experimental.addDuration(to: start, d: 1h)
city = r.city
agg = csv.from(csv: inData)
|> range(start, stop)
|> filter(fn: (r) => r._measurement == "city_data" and r._field == "temp" and r.city == city)
|> mean()
|> findRecord(fn: (key) => true, idx: 0)
return {_time: stop, _value: agg._value, _field: "event_temp_mean"}
})
```
This …

refactor(interpreter): expose interpreter's resolver to compiler

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/table_fns_findcolumn_map_test.flux
stdlib/universe/table_fns_findrecord_map_test.flux

This just adds a couple test cases that use `findColumn` and `findRecord` inside a call to `map`.
~~This will in part help address #3057, but this test won't pass in influxdb, so I will skip it there and add a launcher test.~~
It turns out that this test case works okay in influxdb, so it is sufficient to fix #3057.

test(stdlib): add a test cases for using table functions inside map

---

dependencies/http/http_test.go
dependencies/url/validator_test.go

While chasing some issues with our http endpoint validation, I added
some tests and made some minor tweaks. The redirect test wasn't working,
because the original validation failed, so never got to the redirect, so
it needed to be adjusted.

test: add more precision to http protection tests

---

errors.go
internal/errors/errors.go
internal/errors/errors_test.go

This adds a DocURL field to flux errors which can be accessed by using
the `ErrorDocURL` function. The DocURL field is intended to be attached
to an error at the site it happens and `ErrorDocURL` is intended to
retrieve the most appropriate doc url for the ones that exist.
This does not modify the `errors` convenience functions in the
`internal/errors` package. We still haven't figured out how we want
those to look as part of this new pattern. For that reason, they have
not been modified especially since we would also have to change how they
are called.
Fixes #3092.

feat(errors): add a doc url field to flux errors

---

README.md

This PR makes various small edits and typo fixes.
The biggest change is breaking the "Getting started" section in two, with the basic steps to build and run the REPL coming first, followed by basic syntax, and then more advanced notes on the build process under "Contributing," since it would likely be developers consulting this info.

docs: Edit README

---

docs/SPEC.md

There was some confusion about the precedence of the `|>` operator. This change adds the operator to the precedence table to make it clear. Not code change needs to occur as this just reflects the current correct implementation.

docs(SPEC): add |> to operator precedence table

---

stdlib/universe/map.go
stdlib/universe/map_test.go

`map()` cannot generate a table with the following column data types:
* Bytes: `(r) => ({_value: bytes(v: "123")})`
* Duration: `(r) => ({_value: 1d})`
* Regexp: `(r) => ({_value: /ab?/})`
* Array: `(r) => ({_value: ["str"]})` <-- the one that caused our issue
* Object: `(r) => ({_value: {v: 1}})`
* Function: `(r) => ({_value: (p) => 1})`
When given properties with invalid type, Flux panics and it should instead give a friendly error message.

fix: panic when having invalid type in map object property

---

execute/executetest/source.go
execute/executor.go
execute/transport.go
lang/compiler_test.go
tracing.go

This turns experimental tracing from a global attribute to one that is set in the context. This will allow `influxdb` (OSS) to turn on experimental tracing in the context (or not) by looking at a feature flag.
This implements part of https://github.com/influxdata/influxdb/issues/16220.

feat(flux): make experimental tracing an attribute of the context

---

csv/result.go
stdlib/csv/from.go
stdlib/csv/from_test.go

The `csv.from()` call would deadlock when the next transformation
returned an error and did not consume the table. This is because it
ignored the context and did not cancel when told to. Instead, it kept
waiting for the next transformation to read the table even though that
transformation had already told it to exit.
This only happened when the number of rows exceeded the csv row buffer
limit.

fix(stdlib/csv): csv no longer deadlocks when next transformation does not consume table

---

compile.go
execute/executor.go
execute/transport.go
execute/window.go
internal/errors/errors.go
interpreter/interpreter.go
interpreter/interpreter_test.go
operation.go
plan/logical.go
plan/physical.go
plan/types.go
querytest/compile.go
stdlib/universe/window.go
stdlib/universe/window_test.go

This improves all of the window errors to ensure they produce source
information and doc urls for all of the failure locations.
This also introduces automatic line information for runtime errors that
are produced from a transformation. The stack is maintained by the
interpreter within the context. Each time a function is called, the
stack is retrieved a new entry is then injected into the context. This
stack is then included in the `flux.Spec` and then inserted onto the
planner nodes as they are created.
Nodes that are created from the planner that do not have a source
equivalent will not have a call stack and will not include an error
within the source.
Fixes #3085.

feat(stdlib): improve window errors

---

stdlib/universe/integral.go
stdlib/universe/integral_test.go

Integral gave an incorrect estimate for tables with just a single data point when using linear interpolation. This PR fixes the estimate by using the value of the single data point for the value at both the `_start` and `_stop` times of the range.

fix: single value integral interpolation

---

docs/SPEC.md
libflux/go/libflux/buildinfo.gen.go
libflux/src/core/semantic/builtins.rs
semantic/flatbuffers_test.go
stdlib/universe/range.go
stdlib/universe/range_test.go

BREAKING CHANGE: Remove timeColumn, startColumn and stopColumn arguments from
the range function and always use the defaults and update the type signature to
return a type based on the input. This eliminates return-type polymorphism from
the range function.
https://github.com/influxdata/flux/issues/2253

fix: remove time-column args from range function and update type sig

---

execute/bounds.go
execute/window.go
execute/window_test.go
internal/gen/input.go
plan/bounds_test.go
stdlib/date/date.go
stdlib/experimental/http/http_experimental.go
stdlib/sql/to_privates_test.go
stdlib/universe/sleep_test.go
stdlib/universe/typeconv.go
stdlib/universe/typeconv_test.go
stdlib/universe/window.go
stdlib/universe/window_test.go
time.go
values/binary.go
values/binary_test.go
values/time.go
values/time_test.go
values/values_test.go

Closes #3025. 
Adding testing to ensure that windows using monthly durations set bounds properly.

feat(execute): test support duration for agg window

---

csv/result.go
csv/result_test.go

Close #3161 
This PR ensures that "result" and "table" meta columns are never part of a group key (i.e. value in the #group annotation is always `false`)

fix(csv/result): ensure that meta columns are never part of group key

---

execute/window.go
execute/window_test.go
stdlib/date/date.go
stdlib/universe/window.go
stdlib/universe/window_test.go

The `NewWindow()` function includes a `months` param which is a bool that tells
whether months are included in a duration or not. This param is confusing and
unnecessary since we already have accessor functions for months and nsecs.
We also need to remove the normalize function and update related code to properly
calculate the offset.
This PR removes the `months` parameter and skips tests that fail because of normalize.

fix(stdlib): remove months param

---

execute/executor.go

Tracing in the `execute` package for sources did not propagate the context with a span to the call to the source's `Run(ctx)` method, so any additional spans created by the source did not have a parent. This fixes that.

fix(execute): propagate span context to source.Run

---

values/time.go

This is a helper function to create Durations when given the required `nsecs`, `months` and `negative` values. Its to support this PR https://github.com/influxdata/idpe/pull/8636 as seen in this example: https://github.com/influxdata/idpe/pull/8636/files#diff-8933e9d3894291e6c9aca3e7a3da1139R98-R99.

feat(values): add duration conversion

---

stdlib/experimental/join.go
stdlib/experimental/join_test.go

In `experimental.join`'s `fn` argument, if the specified property
doesn't exist in the column, be it left or right, this resulted in a
panic related to invalid column types. This patch checks the contents of
the function to ensure that references to column types in properties do
exist in the `ColMeta`.
Fixes #2809

fix: catch references to non-existent columns

---

compiler/compiler.go
compiler/compiler_test.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_field_type_change_test.flux

Fixes #3153.
This addresses an issue revealed by a test case like this one:
```
import "experimental/array"
array.from(rows: [{v: 0.1}])
|> map(fn: (r) => ({r with v: "foo"}))
|> filter(fn: (r) => r.v != "foo")
```
The output of `array.from` is `{v: float}`, and the output of map is `{v: string | v: float}`. This is strange but it's how records work in our type system. The first item `v: string` is the real type of `v` and the second item is just hanging around and is not generally useful.
The `filter` function invokes the "compiler" which uses the inferred type of the filter's `fn` argument to look for type errors. It ensures that column in the table have the expected type. However in this case `v` is expected to have both `string` and `float` types, which is impossible, and an error …

fix(compiler): fix compiler type inference with extended records

---

Dockerfile_build

Go 1.12 is no longer supported, so bump the test container to 1.13.
Certain downstream consumers *only* support 1.13+, so this will enable
running compatibility tests with those consumers.

chore: bump the go version of the docker container

---

ast/format.go
ast/format_test.go

📎 https://github.com/influxdata/flux/issues/3223
This adds escaping we do for `ast.StringLiteral` formatting to `ast.TextPart` as part of `ast.StringExpression` parts.

fix(ast): Ensure ast.TextPart is properly escaped when formatting

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/quantile.go
stdlib/universe/quantile_defaults_test.flux
stdlib/universe/quantile_test.go

The quantile method type signature specified that the "method" parameter
was optional but did not apply a default if it was missing. This change
now applies the default.
Fixes #2648

fix(quantile): sets default quantile method when not specified

---

libflux/go/libflux/buildinfo.gen.go
stdlib/testing/chronograf/aggregate_window_median_test.flux
stdlib/testing/chronograf/flux_test_gen.go

This is a PR to update `aggregate_window_median_test.flux` so that it will pass in influxDB. The ultimate plan is to cherry-pick this commit onto a release branch for v0.83.x and then create a patch release of v0.83.x. to use in influxDB.
The change was tested locally and [appears to resolve the issue](https://github.com/influxdata/influxdb/issues/19565) that this test was causing in influxDB.

feat(stdlib/testing): fix field type error in test

---

Dockerfile_build
go.mod
go.sum

This patch updates the dependencies to support go 1.15 and forces the
docker image to use 1.15.
Fixes #3210

chore: support go 1.15

---

go.mod
go.sum
stdlib/sql/from.go
stdlib/sql/from_private_test.go
stdlib/sql/hdb.go
stdlib/sql/hdb_test.go
stdlib/sql/source_validator.go
stdlib/sql/sql_test.go
stdlib/sql/to.go
stdlib/sql/to_privates_test.go
stdlib/sql/to_test.go

This PR add SAP HANA db support to Flux.
It uses older `v0.14.1` Go driver (Mar 16, 2019), because it is the last version that works with Go 1.12.

feat(stdlib/sql): add SAP HANA db support

---

Makefile
release.sh

This patch, first and foremost, removes `make release`, as it was only
calling a single script that contained the logic needed; calling the
script directly is just as verbose. This also allows for an override of
the script, where one can specify the tag rather than having it guessed
(it guesses wrong many times outside the happy path).
Additionally, the release script will now verify that the `HEAD`
revision is has a success status in github. There were instances where
a release was cut that wasn't passing those tests. As integration tests
become part of the CI, this will become more important.

chore: add release validation and overrides

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/flux_test_gen.go
stdlib/experimental/join_right_side_more_cols_test.flux

This PR just updates a test so that it uses a singular call to `range` so the source appears to be time-bounded in all environments.

test: make bounded test detectable as bounded

---

lang/compiler.go

The TableFlux experiment is not currently under active development. Remove the
call point from the compile command. This call transforms table flux code to
flux and was never meant to be a permanent part of the system.

chore: remove table flux hook

---

compiler/runtime_test.go
execute/dependencies.go
execute/executetest/compile.go
execute/profiler.go
execute/profiler_test.go
internal/spec/build.go
interpreter/interpreter.go
interpreter/package_test.go
lang/compiler.go
lang/execopts_test.go
repl/repl.go
runtime.go
runtime/global.go
runtime/importer.go
runtime/runtime.go
stdlib/date/date.go
stdlib/experimental/chain.go
stdlib/experimental/chain_test.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go

The interpreter now installs profilers into the execution dependencies. Doing
this directly from the interpreter is not possible due to the import cycle.
flux -> interpreter -> execute -> compiler -> interpreter -> execute
This is the same cycle that triggered the lifting of execution dependencies into
their own module. This time more of the execution state must get added in and
the simple lift fix doesn't work.
Instead adding an interface to the interpreter module that is specifically for
setting execution options. The lang package can then implement this interface
and install the options.
So this patch also includes the movement of execution dependencies back to the
execute module and using this new interface to also set the now option in the
execution dependencies.
Tested by setting …

feat: make profiler available to tableFind and friends

---

execute/profiler.go
execute/profiler_test.go

Closes #3203
Groups profiler results by operation type and label, and aggregates the results into count, min, max, sum, and mean.
Allows explicit times to be passed into `OperatorProfilerSpan.finish()` and `StartSpanFromContext` to make testing easier.
Adds `GetSortedResult()` method to the `Profiler` interface to allow for easier testing without requiring results to be sorted in production.

feat(profiler): Aggregate results for operator profiler

---

lang/compiler.go

fix: configure profiler even if operator profiler is not enabled

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
cmd/flux/main.go
csv/result.go
dependencies.go
dependencies/influxdb/errors.go
dependencies/influxdb/http.go
dependencies/influxdb/provider.go
dependencies/influxdb/provider_test.go
execute/executetest/table.go
libflux/go/libflux/buildinfo.gen.go
result.go
stdlib/influxdata/influxdb/cardinality.go
stdlib/influxdata/influxdb/cardinality_test.go
stdlib/influxdata/influxdb/flux_gen.go
stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/influxdb.flux
stdlib/influxdata/influxdb/internal/testutil/testing.go
stdlib/influxdata/influxdb/rules.go
stdlib/influxdata/influxdb/rules_test.go
stdlib/influxdata/influxdb/source.go

This adds a `cardinality()` function to the influxdb package to
determine the cardinality of a bucket with a filter for a specific
range. This is a source and can be chained to flux transformations.
To implement this, a dependency interface was created to act as an
influxdb provider. This dependency will cover reading and eventually
writing to influxdb. The interface allows us to define flux
transformations that interact with influxdb both in a remote way, such
as through http calls, and embedded within influxdb itself.
The interface is divided into a provider and a reader. The provider
contains a complete list of the different types of readers which is one
for each one. This provider is documented to be able to change and it is
advised to use the `UnimplementedProvider` as a base to …

feat: add series cardinality function to influxdb package

---

compiler/compiler_test.go
compiler/runtime.go

A string expression could be inferred as a string but evaluate to null.
It then caused a panic when it tried to access the value as a string.
This checks to see if the value is null and returns an error if it is.
Fixes #3284.

fix(compiler): do not panic when a string expression evaluates to null

---

execute/window.go
execute/window_test.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/window_aggregate_test.flux
values/time.go

fix: properly truncate timestamps to beginning of window bounds

---

execute/profiler.go
execute/profiler_test.go
internal/spec/build.go
lang/compiler.go
lang/query_test.go
libflux/go/libflux/buildinfo.gen.go
plan/physical.go
stdlib/influxdata/influxdb/rules.go
stdlib/influxdata/influxdb/rules_test.go
stdlib/influxdata/influxdb/v1/rules.go
stdlib/universe/join_two_same_sources_test.flux

A lot of our planner rules transform the existing plan nodes into completely different ones. For example, `PushDownGroupAggregateRule` collapses `range |> window |> agg` into `ReadWindowAggregate`.
In this process, we usually manually create the new physical nodes without numbering them. So if such planner rules are applied more than once in a query (a query with join or table functions or `chain()`), the plan nodes those rules created will have the same node ID and thus the same dataset ID. This will confuse the execution engine and generate undefined results.
This PR addresses it by introducing a new `CreateUniquePhysicalNode` method that can read the next plan node ID from the context and apply it.

feat: make sure the query plan nodes have unique ids

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/bare_last_test.flux
stdlib/planner/flux_test_gen.go

This is a regression test for descending array cursors. These cursors should exclude points that fall on the `_stop` time but include points that fall on the `_start` time.

test: bare last with points on range boundaries

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/flux_test_gen.go
stdlib/planner/group_agg_uneven_keys_test.flux

Added a test case for group-aggregage where tag key sets are uneven in length
among the input rows that are aggregate/selected in the output grouping.

test: added a test case for group-aggregate

---

libflux/Cargo.lock
libflux/go/libflux/buildinfo.gen.go
libflux/src/core/Cargo.toml
libflux/src/core/formatter/mod.rs
libflux/src/core/formatter/tests.rs

This change adds the ability to vertically align records that appear in
an array. It uses an implementation of the tabwriter from BurntSushi
that implements and _elastic tabstops_ algorithm. Basically it ensures
that tabstops vertically align instead of treating them as fixed width
columns. See http://nickgravgaard.com/elastic-tabstops/, this is the
same method Go uses for its formatter.
I also bench marked this change to the formatter as I would expect it to
slow it down considerably. A benchmark on formatting the everything.flux
file run 14% slower with this change. That seems tolerable for this kind
of change but am open to suggestions to improve it.
This PR is dependent on #3314  to add the benchmark, do NOT merge until then.

feat(formatter): use a tabwriter to vertically align tabstops

---

compile.go
compiler/runtime.go
go.mod
go.sum
internal/arrowutil/array_values.gen.go
internal/arrowutil/array_values.gen.go.tmpl
interpreter/interpreter.go
interpreter/package.go
semantic/monotype.go
semantic/semantictest/cmp.go
semantic/types.go
stdlib/json/encode.go
stdlib/universe/histogram.go
stdlib/universe/typeconv.go
values/array.go
values/dict.go
values/dict_test.go
values/function.go
values/object.go
values/objects/table.go
values/values.go

This adds a Dictionary interface and implementation to the `values`
package. It also updates all of the `values` and usages to acknowledge
that dictionaries exist.
BREAKING CHANGE: The `Value` interface has changed and will require changes to
existing implementations of the interface.
Fixes #3318.

feat(values): create a Dictionary interface and implementation

---

.circleci/config.yml
libflux/go/libflux/buildinfo.gen.go
libflux/src/core/formatter/mod.rs

Rust 1.48 was released a few days ago. This patch adds the fixes that
will get flux passing in CI again. The following things needed
addressed:
- There is a new lint introduced that checks for `push_str` on a
single char `str`, and recommends using `push` instead.
- There is an open issue with `sccache` and rust 1.48. As a result,
`sccache` is desabled for now. See https://github.com/mozilla/sccache/issues/887

chore: add support for rust 1.48

---

Dockerfile_build
libflux/Dockerfile

Installing colm and ragel 7 to /usr/local/ragel7 and putting the bindir on the
path after /usr/local/bin. This hides the ragel version 7 binary, but we only
need the ragel-rust binary.

feat: added ragel 7 to the Dockerfiles

---

Dockerfile_build

This patch installs a working `sccache` from the `master` branch. Once
this image is built, we can re-enable `sccache` in flux.

chore: install a working sccache

---

.circleci/config.yml

After the change in #3366, the docker container now has a working
`sccache` with rust 1.48. This patch reverts the patch that disabled
`sccache` so that we were unblocked.
This reverts commit 0d9d585f95fb7fc3148efeec5441a1e75999a4bc.
Fixes #3357

revert: re-enable sccache in ci

---

stdlib/strings/strings.go
stdlib/strings/strings_test.go

The substring method in the strings package now works properly when the
start or end index isn't within the bounds of the existing string. It
truncates these indices to be the start or end of the string. This
reduces the need to check the length of the string to get a substring of
a certain size and makes it work more similar to how the javascript
substring operates.
This also fixes the case where both the start and the end index are
zero. This was erroneously creating a string of 1 character when it
should have been zero.
Fixes #3368.

fix(stdlib/strings): substring method now works on more indices

---

compiler/compiler.go
compiler/compiler_test.go
compiler/runtime.go

When we retrieve a missing parameter from a record, we should not allow
it to return a null value if we know we are supposed to be returning one
of the container types (array, record, or dict). Those three are not
nullable so it is not valid for null to be returned. Instead, an error
is returned instead.
Fixes #3374.

fix(compiler): do not allow containers within a record to be null

---

cmd/flux/cmd/test.go
internal/errors/std.go

The test command can now execute tests from tar or zip archives. It can
also execute tests from individual `.flux` files that are specified on
the command line.
This can be used for downloading a zip archive of the flux source code
from github and then executing the tests without unzipping the file.
Fixes #3334.

feat(tests): add ways to execute tests from tar and zip archives

---

stdlib/contrib/chobbs/discord/README.md
stdlib/contrib/sranka/opsgenie/README.md
stdlib/contrib/sranka/sensu/README.md
stdlib/contrib/sranka/teams/README.md
stdlib/contrib/sranka/telegram/README.md

This PR repairs examples in `stdlib/contrib` packages, a pipe destination must be a function call.

fix(stdlib/contrib): repair endpoint examples

---

libflux/go/libflux/buildinfo.gen.go
stdlib/strings/strings_test.flux

This patch removes a redundant `testcase_subset` test that I noticed
as I was working to run these tests in idpe.

chore: remove redundant test

---

libflux/fluxdoc/templates/base.html

The bootstrap <link> tag appears to be using smart quotes, this replaces them with normal ones

Feat/fluxdoc Fix bootstrap link quotes

---

dependencies/http/http.go
dependencies/http/http_test.go
dependencies/url/validator.go
go.mod
go.sum
stdlib/http/post.go
stdlib/http/post_test.go

The dialer provides a function that gets called after DNS resolution, but
before the network connection is initiated. Use that to validate IP addresses.
This replaces URL-based validation where the IP address is resolved before the
post, and during any redirects. This method prevents attacks where the IP
address is changed between validation and connect. Fixes influxdata/idpe#9480.

feat: validate IP addresses from the dialer Control function

---

libflux/Cargo.lock
libflux/core/Cargo.toml
libflux/core/benches/scanner.rs
libflux/go/libflux/buildinfo.gen.go

This patch adds a benchmark test to the core library specifically for
`core::scanner::Scanner::scan` as well as
`core::scanner::rust::Scanner::scan`, with the assumption that thet
latter will be removed when the rust scanner implementation replaces the
current scanner implementation.

test: add benchmark tests for Scanner

---

internal/errors/std.go
semantic/monotype.go
values/values.go
values/values_test.go

The `values.Value` interface represents a flux value and it is used by a
large number of runtime functions. The default implementation of the
basic values implements the data access functions, such as `Float()` and
`Int()`, for those respective types.
These access functions were deemed too complex to inline and so
performance was worse for accessing this data.
values/values.go:69:6: cannot inline value.Float: function too complex: cost 135 exceeds budget 80
One reason is because `semantic.MonoType` required accessing the
flatbuffers data to determine the type nature. Instead of looking up the
type nature through a large function, this lookup has been moved to the
creation of the `semantic.MonoType` so that checking the nature is
accessing a member variable. For basic types, which …

feat(values): improve performance for accessing data within a Value

---

execute/group_key.go
execute/group_lookup.go
go.mod
go.sum
stdlib/kafka/to.go

This improves the performance of the random access group lookup by
utilizing xxhash to perform the hashing instead of relying on the hash
for a string value.
The primary benefit for this is that xxhash can compute a hash value
while maintaining a constant buffer and memory size. The previous
implementation utilized a string builder which could potentially result
in more allocations. This allows us to put an item into the Go map using
a uint64 key instead of relying on the string key.
It also is able to add that uint64 key to the group key itself with
minimal disruption. This helps with the common pattern of `Lookup`
followed by `Set` to prevent recomputing the hash twice.

feat(execute): improve performance of random access group lookup by utilizing xxhash

---

go.mod
go.sum
values/dict.go

The latest version of v0.3.0 made a breaking API change with the v0.2.1
version.
Fixes #3411.

fix: upgrade github.com/benbjohnson/immutable to v0.3.0

---

cmd/flux/cmd/test.go

This patch changes the default test path from `./stdlib` to `.`. After
implementing the test runners downstream, the original path was a bad
default.

fix: change the default test discovery path

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/join_panic_test.flux

Reproduces and mitigates this panic https://github.com/influxdata/idpe/issues/6597. 
There are two sets of input data. One to trigger the panic and one that bypasses the panic. The cause is still unknown, but this evidence may be helpful.

test: add join panic test case

---

go.mod
go.sum
stdlib/universe/quantile.go
stdlib/universe/quantile_test.go

Closes #3455 
~Requires https://github.com/influxdata/tdigest/pull/27 to merge first.~
- Uses `tdigest`'s new `ByteSizeForCompression` function to get the appropriate byte size to pass to the allocator.
- Moves creation of a digest from `QuantileAgg.Copy()` to `createQuantileTransformation` and simply resets the digest every time the aggregate is copied.
- Adds a NewQuantileAgg function for convenience in testing.
***Benchmarks before change:***
```
go test -bench=Quantile$ -run=^Benchmark -benchmem ./stdlib/universe
goos: linux
goarch: amd64
pkg: github.com/influxdata/flux/stdlib/universe
BenchmarkQuantile-24                   6         188348059 ns/op         1513738 B/op        137 allocs/op
PASS
ok      github.com/influxdata/flux/stdlib/universe      4.296s
```
***Benchmarks after …

fix(quantile): Track and reduce memory used by tdigest

---

libflux/core/src/semantic/convert.rs
libflux/go/libflux/buildinfo.gen.go

Using HashMap results in a prelude.data and stdlib.data that varies from build to
build, given the same source. This breaks reproducible builds and adds churn to
the deployments process. The variation is caused by iterating the HashMap,
which doesn't guarantee any particular order.
Helps with influxdata/idpe#6331

fix: switch from HashMap to BTreeMap in ast/semantic conversion functions

---

CONTRIBUTING.md

Add instructions for when to run `make generate`.

docs: Document running `make generate` in CONTRIBUTING.md

---

libflux/core/src/lib.rs
libflux/fluxdoc/src/main.rs
libflux/go/libflux/buildinfo.gen.go

The latest clippy version introduced the `unnecessary_wraps` linter, which errors when an `Option` or `Result` return value is always populated with `Some` or `Result`. 
We do want to try and allow this linter in the future, but for now we are disabling it and [creating an issue](https://github.com/influxdata/flux/issues/3528 ) to fix our generated `ast` and `semantic` flatbuffers code to support this.

fix: disable wrap linter

---

csv/result.go
csv/result_test.go

Previously the NoHeader setting for the csv.ResultDecoderConfig had no
tests and did not work. This fixes it and adds tests.

fix(csv): add tests and fix the NoHeader config for the csv decoder

---

dependencies/filesystem/ioutil.go
stdlib/csv/from.go

Prior to this change the contents of a CSV file was read into memory in
its entirety. Now if a file is provided the file is read off disk in
batches as the parsing dictates.

fix(csv): update csv to handle large files

---

csv/result.go
csv/result_test.go

Previously if a data row in a csv file had the wrong number of fields
the error would not be caught and the csv parser would get stuck in an
infinite loop.

fix(csv): add error handling for wrong number of fields for raw csv

---

compiler/compiler_test.go
docs/SPEC.md
interpreter/interpreter.go
interpreter/interpreter_test.go
values/values.go

For null values passed into string interpolation, the null value is represented as the `<null>` string when displayed.

feat(interpreter/compiler): added support for null values in string interpolation

---

result.go

The error is only guaranteed to be populated after `Release()` is called
on the `ResultIterator`. The `DelimitedMultiResultEncoder` now releases
the result iterator after it has finished reading to guarantee that the
error has been set.

fix: delimited multi result encoder properly releases results before checking error

---

lang/compiler.go
lang/query.go
lang/query_test.go

Now as part of the query Done method testing checks are verified.
This avoids a race where the query was started but the results had not
been consumed before the checks were verified.
Fixes #3567

fix(lang): perform testing checks as part of query done

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/merge_filter_test.flux

Downstream consumers haven't yet enabled this functionality, and thus
have no way to pass this test.

test: comment out merge_filter test

---

cmd/flux/cmd/test.go

If the path specified is a test root, the current code will try to add
that path twice which results in a duplicate test root error.
The parent root search is intended to find directories above the
filepath and not within the filepath. So this is now changed to find the
absolute path and then start with the parent directory of that path.
For the directory search, this means the parent directory. For the file
search, this means the directory that the file is located in.

fix(cmd/test): find parent root should skip the current directory

---

Dockerfile_build

The current rustup install command uses SSL v3.0 by default in `curl`.
SSL v3 has been EOL'd for quite some time, and even TLS 1.2 was EOL'd
last year. It *appears* that the migration/update policy with regard to
the rustup.rs server is to fail occasionally on the older protocols,
more often and often until it fails for good.
This patch updates the rustup commands to specifically use tls 1.2 as
described on [rustup.rs](http://rustup.rs). This change has already been
made in idpe.
Additionally, I discovered `libflux/Dockerfile`, which had a manually
specified rust version like in the flux-build image. I updated that and
added a note to ensure that we don't get drift between them again. The
_right_ fix here might actually just be to either (a) delete
`libflux/Dockerfile` altogether, or have …

chore: update rustup install command

---

libflux/core/src/ast/mod.rs
libflux/go/libflux/buildinfo.gen.go

On current nightly, this fixes a warning:
error: derive helper attribute is used before it is introduced
It goes on to say
= warning: this was previously accepted by the compiler but is being phased out;
it will become a hard error in a future release!
This change gets ahead of the issue.
I tend to always be using nightly... If this kind of change is valuable, perhaps this could be useful as an early warning system?

fix(libflux): move derive helper attribute after derive macro

---

libflux/flux-core/src/lib.rs

Adds an introduction to the crate giving an overview
of its structure. Gives some information about
which modules are responsible for the different phases
of compilation and analysis.

docs(libflux): add top-level crate documentation

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

Our version of pretty_assertions was using a [dependency with a RUSTSEC
advisory](https://rustsec.org/advisories/RUSTSEC-2020-0095). This patch
updates to a version without that dependency.

chore: update pretty_assertions

---

libflux/flux-core/src/semantic/env.rs
libflux/go/libflux/buildinfo.gen.go

Documents all items in the module.

docs(libflux): Document `fluxcore::semantic::env`

---

libflux/flux-core/src/semantic/flatbuffers/mod.rs
libflux/go/libflux/buildinfo.gen.go

Allow missing docs in generated code.

docs(libflux): allow missing docs in `fluxcore::semantic::flatbuffers`

---

go.mod
go.sum

See https://github.com/denisenkom/go-mssqldb/pull/642 for details.

fix(dep): upgrade mssqldb dependency for go 1.16

---

libflux/flux-core/src/semantic/sub.rs
libflux/go/libflux/buildinfo.gen.go

Removes `#![allow(missing_docs)]`.

docs(libflux): document `fluxcore::semantic::sub` module

---

libflux/flux-core/src/semantic/check.rs
libflux/go/libflux/buildinfo.gen.go

Makes a few formatting and punctuation changes.
Removes `#![allow(missing_docs)]`.

docs(libflux): document the `fluxcore::semantic::check` module

---

repl/repl.go
stdlib/math/math_test.go
stdlib/sql/sql_test.go
values/array.go
values/dict.go
values/display.go
values/display_test.go
values/function.go
values/object.go
values/values.go

Prior to this change it was not clear how to display a values.Value into
a string. The intended method was to type assert to the
values.ValueStringer interface and call String().
Since values.ValueStringer was not part of the values.Value interface it
was optional to implement the String() method and it was required that
it was implemented on each implementation of the various values. This
meant that it was easy to forget to add String() support to new value
types (see #3687) and that if anyone wrapped the types in their own
implementation they would loose this ability.
This change instead adds a explicit Display functions to the package
that consume a given value. This way the Display code is clearly marked
and easily tested. When adding a new type it will be clear that Display
has not …

fix(values): add new display API for values

---

libflux/flux-core/src/semantic/nodes.rs
libflux/go/libflux/buildinfo.gen.go

This PR:
- Removes `#![allow(missing_docs)]`, requiring docs for all items.
- Adds `#[allow(missing_docs)]` to all undocumented items
- Adds and edits some already existing docs.

docs(libflux): require docs in `fluxcore::semantic::nodes` module

---

Dockerfile_build

`rust` 1.52.0 was released today. This patch updates the build file.

chore: update rust version to 1.52.0

---

.circleci/config.yml

In CI, often times a lot of the heavy lifting is done before
`make checkgenerate` is run. If generated files aren't updated, there's
no real guarantee we're checking the right files. This patch promotes
`checkgenerate` to being run first, to fail fast.

chore: run checkgenerate first

---

Makefile
cmd/flux/cmd/fmt.go
etc/checkfmt.sh

1) -c (check) option is added to flux fmt cli command
2) updates make fmt target to also format the flux source code
3) added a step to etc/checkfmt.sh to validate all flux source code is
formatted.
Fixes: #3559

feat(fluxcli): add flux fmt step to CI

---

execute/dispatcher.go
execute/dispatcher_test.go

If the dispatcher had an error, such as a panic, while stopping, it
would attempt to set the error on the dispatcher. The `Stop()` method,
which could be triggered by a previous error, would take the lock and
then wait for the workers to finish.
But a worker could then try to set the error before it exited and
setting an error also attempted to take the lock. This created a
deadlock where stopping required waiting for the worker, but the worker
was waiting for stop to release the lock.
This modifies the dispatcher so that it does not hold the lock while it
is waiting and only holds it while using the shared state.

fix(execute): remove deadlock when an error happens while the dispatcher is stopping

---

libflux/flux-core/src/semantic/bootstrap.rs
libflux/go/libflux/buildinfo.gen.go

Removes `#![allow(missing_docs)]`.
The meaning of this module was not entirely clear to me. Can we say more about what "bootstrap" means here? 🤔

docs(libflux): document `fluxcore::semantic::bootsrap` module

---

.goreleaser.yml
Dockerfile_build

This patch does a number of things in the spirit of cleaning up and
simplifying the build system. It does the following:
- Use the upstream rust image to get rust bootstrap tooling, including
`rustc`, `cargo`, and `rustup`. This was the driving force behind
this patch, and fixes #3721.
- Removes the superseded ragel 6 install. We originally installed
ragel 6 and 7 in parallel so we had a migration path. We are now
fully using ragel 7 for our build, so ragel 6 is no longer needed.
- Remove support for cross compiling. The InfluxDB edge team has their
own setup for cross compiling, so we no longer need to maintain the
tooling for doing cross compiled binaries. This includes changes to
the goreleaser configs so that releases don't try to build those
binaries anymore.

fix: audit and clean up docker build image

---

Dockerfile_build

The current docker image can't build rust libraries because CARGO_HOME
is set to a read-only directory. This patch fixes that.

fix: set CARGO_HOME after privilege drop

---

libflux/Cargo.lock
libflux/fluxdoc/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

As reported in [RUSTSEC-2021-0063](https://rustsec.org/advisories/RUSTSEC-2021-0063), the version of comrak
we use in `fluxdoc` has an XSS vulnerability. This patch updates comrak
to a version without the vulnerability.

fix: update comrak

---

ast/ast.go
ast/astutil/format_test.go
ast/json_test.go
libflux/flux-core/src/ast/tests.rs
libflux/go/libflux/buildinfo.gen.go

In the `TestCaseStmt` statement, `id` & `block` are missing in the flux file because of which we are getting the following error. 
`format_test.go:206: missing field `id` at line 1 column 3335`
` format_test.go:206: missing field `block` at line 1 column 3335 `
Adding default to struct TestCaseStmt fixes the issue. 
fixes: #3715

fix: Odd behaviour when going over the Go Rust boundary multiple times using JSON serialization.

---

libflux/flux-core/src/semantic/nodes.rs
libflux/go/libflux/buildinfo.gen.go

Removes leftover attributes from `semantic::nodes`.

docs(libflux): remove unneeded `allow(missing_docs)` attributes

---

ast/errors.go
ast/fbuffers.go
plan/physical.go
plan/rules_test.go
stdlib/sql/sqlite_test.go
tracing.go

Fixed following static check linter failures -
1) should not use built-in type string as key for value; define your own type to avoid collisions (SA1029)
2) unnecessary use of fmt.Sprintf (S1039)

fix: staticcheck linter failures

---

libflux/flux-core/src/ast/mod.rs
libflux/go/libflux/buildinfo.gen.go

docs(libflux): cleanup docs for AST `base` methods

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/group_min_max_table_test.flux

The `group_no_agg_table` acceptance test would return in an inconsistent
order if the groups arrived in a different order. This adds a sort to
the end so it is consistent across all test environments.

fix(stdlib): update group_no_agg_table acceptance test for consistent order

---

stdlib/universe/map.go

This patch reclassifies a map evaluation error as `Invalid` rather than
as `Internal`.

fix: reclassify map type error as user error

---

csv/result.go
csv/result_test.go

Prior to this change csv that had annotations with less than three
fields would cause the csv decoder to panic. Now an appropriate error
message is returned.

fix(csv): adds length check to csv annotation parsing

---

stdlib/universe/histogram.go

Prior to this change the histogram would report an internal error when
the data was out of range for the histogram bins. Now a correct error
code is reported.

fix(universe): report correct error code for histogram error

---

Dockerfile_build

This patch updates the version of `flatc` availabale in the flux-build
docker image.

feat: update flatc in flux-build image

---

Dockerfile_build

Reverts influxdata/flux#3810; we need to wait for docker to support rust 1.53

revert: update to rust 1.53

---

libflux/flux/FLUXDOC.md
libflux/go/libflux/buildinfo.gen.go

Adds a document containing the specification for the new Flux doc comments, as per #3770
There were a lot of comments on the PR with the rough draft of this document. I opened this new PR with the updated version to make any future conversations in the comments easier to follow.
[Original PR here.](https://github.com/influxdata/flux/pull/3786)

chore: Add spec for flux doc comments

---

execute/dispatcher.go
execute/dispatcher_test.go
execute/ring.go
execute/ring_test.go

This modifies the dispatcher to make the work queue dynamically increase
when the amount of work exceeds the default size.
Previously, the work queue was implemented with a channel. Channels have
a static size and it was possible for a worker, which reads from the
work queue, to also attempt to add to the work queue and this resulted
in a deadlock.
This updates the work queue to be a dynamically sized ring to avoid a
deadlock when the amount of work exceeds the size of the work queue.

fix(execute): allow work queue to be resized when work exceeds queue length

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/distinct_test.flux

The distinct testcase relies on nulls existing but `testing.load()` does
not support loading null values. Do not use `testing.load()` for this
testcase.

fix(stdlib): distinct testcase should not use testing.load()

---

Dockerfile_build

In order to run the wasm tests for the new flux-doc generator in CI, our docker container needs to have node installed. Otherwise, we get failures like this: https://app.circleci.com/pipelines/github/influxdata/flux/9788/workflows/8ee4530f-6899-467a-98c9-ec6a93217e33/jobs/28634

chore: Install nodejs and npm in dockerfile

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/group_agg_test.flux

This just adds a few tests for `group` and `count` or `sum` used together, in preparation for adding these pushdowns to OSS.
In TSM1 the `_field` attribute of a series is treated differently than other tag keys (unlike in TSM2) so I wanted to be sure to hit all the different combinations of grouping and filtering on `_field`.

test: add group tests for count and sum

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/group_agg_test.flux

This PR removes some of the tests that I added yesterday in #3860 since they took too long to run in `influxdb`.
I also added `|> yield()` to each test query, since extending the test in `influxdb` seems to require it.
Finally I used `array.from()` to create the input data since that is possible to do now, and it's more readable.

test: fix group_agg_test to yield data and use array.from for input

---

etc/checkfmt.sh

This PR is to fix the error in the CI while running checkfmt at the integration phase.
Error - 
```
./etc/checkfmt.sh: line 41: flux: command not found
CircleCI received exit code 0
```

chore: make checkfmt always runs current formatter

---

stdlib/experimental/to.go
stdlib/experimental/to_test.go
stdlib/influxdata/influxdb/consts.go
stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/provider.go
stdlib/influxdata/influxdb/rowmetric.go
stdlib/influxdata/influxdb/to.go
stdlib/influxdata/influxdb/to_test.go

This ports `experimental.to()` from its home in influxdb OSS and the
cloud product to being included within the flux repository. The flux
version will use the `influxdb.Provider` that is in the dependencies.

feat(stdlib): port experimental.to() and adapt to use the influxdb provider

---

libflux/go/libflux/buildinfo.gen.go
stdlib/planner/group_first_last_test.flux

This PR adds some tests for `group` with `first` and `last` selectors. These tests will be extended in OSS in order to provide test coverage for push downs.

test: add acceptance tests for group with first and last

---

semantic/monotype.go
semantic/monotype_test.go

It seems that the code to copy a monotype did not copy the monotype
properly when the type was a record and it did not extend another
record. This causes compiler substitution to mark itself as extending
`t0` when the original was a fully qualified type with no record
extension.
This may have affected the `map()` call which could possibly heavily
rely on this code or it could have affected some other part of the
compiler infrastructure.
This was found while testing some code for an experiment so I don't have
a reproducer for how this would affect a live system.

fix(semantic): properly copy record types with no extends parameter

---

libflux/go/libflux/README.md
libflux/go/libflux/analyze.go
libflux/go/libflux/parser.go

The libflux package was modified to manually specify `CFLAGS` for the
include path. This worked for local builds where the files were located
in the source directory, but didn't work for builds that used flux as a
dependency like influxdb.
This restores the old behavior that uses the `/include` directory as the
base of the include path and includes `"influxdata/flux.h"` instead of
directly including `"flux.h"`. This should restore the previous
behavior.
It is up to `pkg-config` to produce a usable include path.

fix(libflux): restore the previous libflux include paths to use pkg-config

---

libflux/flux-core/src/parser/mod.rs
libflux/go/libflux/buildinfo.gen.go

This patch enables libflux to build on rust 1.54. The detection of
`dead_code` has gotten better, and discovered a struct property that we
set but never read. This patch removes it.
This patch specifically doesn't update the rust version in CI, as I
think these updates can and should be independent of each other.

chore(libflux): support rust 1.54

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/schema/show_fields_with_meas_pred_test.flux

While working on https://github.com/influxdata/influxdb/pull/21962, I found that the existing `show_fields_xxx.flux` tests did not include one where there is only a single predicate of `_measurement`. `show_fields_with_pred_test.flux` has a predicate of `_measurement` as well as one for an additional tag, and `show_fields_test.flux` does not have a filter.
This additional test will cover the case of only having a predicate of `_measurement`. It is primarily useful to me since I am planning to tweak the OSS logic related to a query like this.

test: test query fields with only a measurement predicate

---

stdlib/contrib/README.md

Slightly tweak in verbiage to clarify we don't maintain contrib packages, but stand behind and support contrib packages

docs(contrib): support user-contributed packages

---

.circleci/config.yml
Dockerfile_build

Add an explicit `rustup default` call to the Windows CI logic, to ensure new versions aren't used accidentally.
I couldn't think of a way to declare the `RUST_VERSION` constant in a single place without significantly refactoring the existing docker-based environment setup, so I settled for adding a comment above each spot the version appears referring to the other location.

build: re-enable build-windows, pin rust version

---

execute/transport.go
execute/transport_internal_test.go
execute/transport_test.go

The `execute.Message` interface has been expanded with `Ack()` and
`Dup()` methods.
The `Ack()` method is meant to acknowledge that the message has been
received by a `Transport` and the contents of the message can be
released.
The `Dup()` method is meant to copy the inner contents of a message into
a new message. Both messages must be acked separately. The
implementation of `Dup()` may involve incrementing a reference count
instead of a full deep copy.
These lifetimes will allow messages to contain data that has to be
released.
Fixes #3884.

feat(execute): expand message interface with message lifetime controls

---

execute/table/chunk.go
execute/transport.go
execute/transport_internal_test.go
execute/transport_test.go

This adds two additional message types: `ProcessTableChunk` and `FlushKey`.
The `ProcessTableChunk` message represents that a chunk of a table is
ready to be processed by the transformation. It contains a reference to
the table chunk which is an arrow table buffer.
The `FlushKey` message represents that a group key has been finished and
is ready to flush any data stored in an associated dataset.
Closes #3885.

feat(execute): add two additional message types

---

stdlib/universe/pivot.go
stdlib/universe/pivot_test.go

There's a pipeline test for this transformation that was failing because of improper registration and a logic error. This PR fixes those.

fix(stdlib): fix pivot when no data left

---

execute/executor.go
execute/transformation.go
execute/transport.go
execute/transport_internal_test.go
execute/transport_test.go
mock/transformation.go

The `Transport` interface is now just `ProcessMessage` which can be
implemented directly by a transformation rather than using the
`Transformation` interface.
A transformation adapter has been created to wrap the older
`Transformation` into a `Transport` to support the new message types and
adapt them for the `Transformation` interface.
`consecutiveTransport` has been updated to implement both `Transport`
and `Transformation` to allow it to be used with either a
`Transformation` or a `Transport` and to forward the message to the
appropriate methods.
Closes #3886.

feat(execute): simplify the transport interface and add a transformation adapter

---

execute/dataset.go
execute/dataset_test.go
mock/transport.go

The transport-aware dataset, or `TransportDataset`, can be used to send
messages directly to downstream transports. The `TransportDataset`
implements the `Dataset` interface and can be used in any place that
requires a Dataset.
If the downstream transformation implements the `Transport` interface,
the messages will be sent directly. If the downstream transformation
only implements the transformation interface, the transformation will be
wrapped in the transport adapter and that will be used instead.
If there are multiple downstream nodes, messages will be automatically
duplicated.
Closes #3887.

feat(execute): add transport-aware dataset

---

execute/narrow_transformation.go
execute/narrow_transformation_test.go
execute/table/static/static.go
execute/table/stringify_test.go
mock/transformation.go

This creates a transport implementation for narrow transformations. A
narrow transformation is one that does not modify the group key or keep
any state.
In order to use this, you would implement the `NarrowTransformation`
interface and then use `NewNarrowTransformation` to create the dataset
and transformation.
Closes #3927.

feat(execute): add narrow transformation transport

---

execute/table/builder_cache.go
execute/transport.go
execute/transport_test.go

The transformation adapter would respond to the flush key message by
attempting to create a table for the key. If there was no table builder
associated with the key, it would cause an error instead of just
ignoring the message.
This updates the transformation adapter to ignore flush key messages for
keys that don't correspond to an existing table builder.

fix(execute): transformation adapter does not error when receiving a flush key for a table that is not present

---

.circleci/config.yml
Dockerfile_build

The comment-based approach of keeping `Dockerfile_build` and `.circleci/config.yml` in-sync turned out to be... ineffective. This eliminates the duplication so we don't have to worry about it in the future.

build: only declare RUST_VERSION in one place

---

dependencies/feature/flagger.go
execute/executetest/dependencies.go
internal/execute/table/chunk.go
internal/feature/flags.go
internal/feature/flags.yml
internal/pkg/feature/feature_test.go
stdlib/universe/filter.go

This updates filter to use the `NarrowTransformation` transformation
interface instead of the stream table.
Closes #3936.

feat(stdlib): update filter to use narrow transformation

---

stdlib/universe/die.go
stdlib/universe/die_test.go

Previously the error code returned from the "die" function was
"Internal". Internal errors represent a bad state or system failure,
since a user can call the die function it is not indicative of an
internal error rather a user error as the system is behaving
appropriately when it returns the error. The change make the error code
"Invalid" instead of "Internal".

fix(stdlib): change die error code to invalid

---

stdlib/regexp/regexp.go
stdlib/regexp/regexp_test.go

An interface value consists of a "concrete value" and a "dynamic type": [Value, Type]
In regex functions, we were checking dynamic type only. So added nil check for concrete value as well
fixes: https://github.com/influxdata/idpe/issues/11423

fix(stdlib): panic Interface conversion error in queryd when calling regexp fn

---

stdlib/strings/strings.go
stdlib/strings/strings_test.go

An interface value consists of a "concrete value" and a "dynamic type": [Value, Type]
In strings functions, we were checking dynamic type only. So added nil check for concrete value as well
Also, added test using the interface as a function parameters
fixes: https://github.com/influxdata/flux/pull/1856 https://github.com/influxdata/flux/issues/2036

fix(stdlib): interface conversion interface {} is nil, not string

---

stdlib/universe/fill.go
stdlib/universe/fill_test.go

This PR will add a new null column if the fill column is entirely absent and then populate the fill value into it
The test cases have been added for each type
fixes: #3521

fix(stdlib): fill function fails when col to fill is entirely absent

---

stdlib/universe/limit.go
stdlib/universe/limit_test.go

The `limit()` function had two code paths. One path would decrement the
offset if the offset was greater than the length of the buffer so it
could track when it should stop discarding data. The second path would
process a partial buffer when the offset was less than the length of the
buffer.
Unfortunately, the second case had an error where it would not reset the
offset to zero after processing a partial buffer. It was supposed to
reset it to zero so that future buffers would be processed starting from
index zero.

fix(stdlib): limit now resets the offset after processing a partial buffer

---

go.mod
go.sum

Bump x/sys so that this project supports go 1.17.
More context: https://github.com/Homebrew/homebrew-core/pull/83413
Without this fix running a binary can cause a panic, see upstream go issue: https://github.com/golang/go/issues/45702

chore(deps): Update x/sys to support go 1.17

---

stdlib/universe/reduce.go
stdlib/universe/reduce_test.go

if the reduce function has null value, the query is panicking with unkonown type.
So check has been added for nulls and if it exists, return the appropriate error message to the user.
fixes: #3976

fix(stdlib): panic with unknown type invalid in reduce function

---

parser/strconv.go
parser/strconv_test.go

Added FormatDuration method which can be exported from other repo.

fix: added FormatDuration method which can be exported in other repo

---

execute/group_transformation.go
execute/group_transformation_test.go
mock/transformation.go

Adds a `GroupTransformation` interface as per #3928 
Spent a while trying to implement this myself before realizing that the work in https://github.com/influxdata/flux/pull/3944 is virtually identical to what needed to be done here. As a result, this PR is mostly just a copy+paste of the code for the new `NarrowTransformation` transport, with some small tweaks.

feat(execute): Add GroupTransformation transport

---

Dockerfile_build

This patch updates the required rust to 1.55. This update did not
require code changes in libflux, so we can safely bump the required
docker rust tooling without issue.

chore: update to rust 1.55

---

execute/narrow_state_transformation.go
execute/narrow_state_transformation_test.go
execute/narrow_transformation_test.go
mock/transformation.go

The narrow state transformation transport implements the transport
interface for narrow transformations where state is maintained between
table chunks.
This also fixes some areas in the tests where double releases were
happening accidentally due to forwarding a table chunk that did not have
a proper retained reference. It also fixes the narrow transformation
test with flush key which erroneously did not test narrow
transformations.
Fixes #3933.

feat(execute): add narrow state transformation transport

---

.circleci/config.yml
Dockerfile_build

This upgrades to go 1.17 for ci but does not modify the base `go.mod`
version as `go 1.16` can still be used with flux.
It also modifies the windows build to use `--allow-downgrade` with choco
so that upstream releases don't cause our builds to break.

ci: upgrade to go 1.17 for ci

---

Dockerfile_build

This reverts commit b899d8bd6a35797d52964c71a21d192ceda40611.
The upgrade to rust 1.55 was causing build errors in the flux release for influxdb. We've confirmed that downgrading to rust 1.54 resolves the issues: https://app.circleci.com/pipelines/github/influxdata/influxdb/24024/workflows/09396d1f-5b38-4c4c-ba55-a62006c9cfe8

revert: update to rust 1.55 (#4027)

---

array/repeat.gen.go
array/repeat.gen.go.tmpl
array/repeat_test.go
arrow/repeat.go
execute/aggregate.go
execute/table/buffered_test.go
execute/table/static/static.go
internal/execute/table/stream_test.go
internal/gen/input.go
libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/jsternberg/aggregate/table.go
stdlib/universe/pivot.go
stdlib/universe/sort2.go
stdlib/universe/sort2_test.flux

This change is to add null support to optimized repeat function for arrow arrays
Also did some refactoring of the existing code
This was caught with the bug linked to this issue, aggregateWindow()
function with 'createEmpty: true' was returning empty tables which were
generating rows with null values when piped with group and sort(test
case added)
fixes: https://github.com/influxdata/idpe/issues/11589

fix(array): add null support to optimized repeat function

---

stdlib/sql/from_private_test.go
stdlib/sql/source_validator.go

By abusing support for MySQL's LOAD DATA LOCAL INFILE statement in the golang MySQL driver we use, an attacker can use Flux's sql.from() to leak the contents of local files on Cloud 2's queryd-pull-external pods.
The golang MySQL driver we use has no specific facility for disabling INFILE support in code. We can, however, reject connection strings that set allowAllFiles=true in stdlib/sql/source_validator.go#L30 since we already parse it into a configuration struct.
fixes: https://github.com/influxdata/idpe/issues/11716

fix(sql): disallow setting allowAllFiles parameter in MySQL DSNs

---

internal/feature/flags.go
internal/feature/flags.yml
plan/physical.go

This adds a feature flag to allow the concurrency quota to be equal to
the number of transformation nodes in the graph instead of equal to the
number of roots. This functionality gets enabled when the
`queryConcurrencyLimit` is set to a value higher than zero. This number
limits the maximum concurrency too.

feat(plan): allow the query concurrency to be set to the number of nodes in the graph

---

libflux/flux-core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

perf: Avoid allocating temporary `Vec`s in max_tvars

---

libflux/flux-core/src/parser/mod.rs
libflux/go/libflux/buildinfo.gen.go

Reduces the runtime of the benchmark on `everything.flux` by ~25%.
Just poking around trying to understand the structure of the project(s), noticed that a lot of time were spent cloning `Token` (which is a rather large and expensive to clone struct).
Seeing some (unrelated) test failures locally but haven't understood why those happen yet

perf: Avoid cloning in Parser::peek

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/derivative2.go
stdlib/universe/derivative_test.flux

The optimized derivative attempted to replicate a bug with the existing
derivative where it wouldn't error if the column was not a compatible
type with derivative. This is because I saw an issue detailing this and
I did not see where the check was.
A test was created to verify the bad behavior with a note to fix it in
the future with the issue.
After seeing this test fail when used with the older derivative, it came
to my attention that the bug had already been fixed and so the newer
derivative didn't have to replicate the bug.
This removes the test and adds the necessary code to mark the condition
with the same error.

fix(stdlib): optimized derivative attempted to replicate a bug that didn't exist

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/schema/show_tag_values_measurement_or_predicate_test.flux

This adds test cases to cover the bug described by https://github.com/influxdata/influxdb/issues/22385, which was closed in OSS PR https://github.com/influxdata/influxdb/pull/22500 and did not exist on cloud. It involved some more complex predicates for a "show tag values" type of metaquery. I am opening a PR to add these tests here since they seem like they would be useful to catch regressions more broadly outside of OSS only.

test: add test cases for show tag values

---

execute/executetest/source.go

Message - type assertion to the same type: bufTable already has type flux.BufferedTable (S1040)

fix: staticcheck linter fix in executetest

---

internal/zoneinfo/LICENSE
internal/zoneinfo/export_test.go
internal/zoneinfo/internal_test.go
internal/zoneinfo/zoneinfo.go
internal/zoneinfo/zoneinfo_read.go
internal/zoneinfo/zoneinfo_test.go
internal/zoneinfo/zoneinfo_unix.go
internal/zoneinfo/zoneinfo_windows.go

This copies over the location related code from the Go standard library
and removes some of the unused features from it. We remove the platforms
we do not support and remove concepts like `Local` because support for
that doesn't make sense anyway in a server context.
Fixes #4057.

feat(zoneinfo): copy over location related code from the Go time package

---

interval/bounds.go
interval/window.go
interval/window_test.go

This adds the location functionality to the interval package using the
`zoneinfo.Location` struct from the `zoneinfo` package.
The interval package now translates an input time from the local clock
time to the utc clock time if a location has been specified. It performs
the same time math it previously did and then it will convert the times
back to the local clock time before returning them.
If the default `NewWindow` is used or the location is nil, it continues
to use the old behavior which does not translate for zone offsets.
Fixes #4059.

feat(interval): add location functionality to interval package

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/mqtt/flux_gen.go
stdlib/experimental/mqtt/mqtt.flux
stdlib/experimental/mqtt/mqtt.go
stdlib/experimental/mqtt/publish.go
stdlib/experimental/mqtt/publish_test.go
stdlib/experimental/mqtt/to.go
stdlib/experimental/mqtt/to_test.go

This PR 
- adds `retain` parameter to `to` function (closes #3836)
- adds `publish` function (closes #3825 and closes #3917) and removes `message` parameter from `to` function
Sends query result to a broker. The result (Flux tables) is encoded as InfluxDB [line protocol](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/). Each table is sent per one MQTT message.
Changes:
* added optional boolean `retain` parameter (default `false`) fo setting MQTT message `retained` flag.
* it is a pipeline function intended to send query result (tables), it makes no sense to have a parameter for sending arbitrary data, therefore `message` parameter is removed
_Other parameters not changed._
Example:
```
from(bucket: "example-bucket")
|> range(start: -5m)
|> filter(fn: (r) => …
```

fix(experimental/mqtt): add retain option and publish function

---

csv/result.go
csv/result_test.go

This fixes a bug where while encoding tables to CSV, if the columns in a table stay the same, but the group key changes, we don't output more annotation lines like `#group`, `#datatype`, `#default`.
Fixes #4053.

fix(csv): create new annotations when only group key changes

---

execute/aggregate.go
execute/aggregate_test.go
execute/disposable.go
execute/group_transformation.go
execute/group_transformation_test.go
execute/narrow_state_transformation.go
execute/narrow_state_transformation_test.go
execute/narrow_transformation.go
execute/narrow_transformation_test.go
mock/transformation.go
stdlib/universe/derivative2.go
stdlib/universe/filter.go
stdlib/universe/group.go

This adds a `Disposable` interface to each of the new transformation
types and implements the usage of that interface.
The `Dispose` method signals that a resource is unused and can be
disposed of. An implementation of this can also use the method to signal
that it should be reused.
All transformations now require this method to be implemented.
The `Dispose` method is also utilized by stateful transformations to
dispose of the state if the interface is implemented. This includes both
the aggregate and narrow state transformations.

feat(execute): add disposable interface for transformations

---

libflux/Cargo.lock
libflux/flux/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

This dep isn't used anymore, and builds a dependency tree that's deeper
than needed, so we should just drop it.

chore: remove tero dependency

---

dependencies/bigtable/bigtable.go
dependencies/influxdb/provider.go
dependencies/mqtt/mqtt.go
dependencies/url/validator.go

Trying to wrap my head around how dependencies work and I think I added these as #4147 prescribes.
I am a bit worried about how dependencies are provided/accessed however. It seems that the `func GetProvider` (or equivalent) defaults to returning the default implementation that has side effects. So if you forget to specify these added error versions you will unwittingly run with side effects. We may want to change this to return erroring dependencies by default or we could change the `func init` for these packages such that they take the `Provider`  explicitly as an argument instead so that callers have to be explicit about what they need. (On another, but similiar note, I would argue that we should also remove the `Default` runtime and instead take that as an argument to all of the …

feat: Add erroring versions for each dependency

---

internal/execute/groupkey/groupkey.go
libflux/go/libflux/buildinfo.gen.go
result.go
stdlib/universe/join.go
stdlib/universe/join_unsorted_columns_test.flux

Fixes #4150
~This patch takes advantage of the fact that `execute.groupKey` already has a list of sorted indices that can be used to access its elements in lexicographical order, without altering the underlying contents. It introduces a new `SortedGroupKey` interface, which functions much like the normal `GroupKey` interface, except that its public methods always operate on sorted columns.~
EDIT: This patch adds a new method to the `GroupKey` interface called `EqualTrueNulls`, which should be functionally identical to `Equal`, except that it never counts two nulls as equal. This new method is then used to compare the join keys for `universe.join` (thereby replacing the problematic `equalJoinkeys` function) as a solution to #4150.
The key to reproducing the original bug is to pay attention …

fix(join): Compare sorted join keys

---

libflux/flux-core/src/bin/fluxdoc.rs
libflux/go/libflux/buildinfo.gen.go

User can pass `--limit=0` to display all errors.

feat(fluxdoc): Allow reporting unlimited diagnostics

---

compiler/compiler.go
compiler/runtime.go
execute/row_fn.go
stdlib/universe/filter.go

When executing `Process` on a table with few rows the time to `Compile`
the function before execution ends up dominating the total execution
time. This is an issue for data produced by `csv.from` which creates one
`Table` per row and might be for other sources as well though I have no
idea how common it would be.
For running the following query on a file with 500k lines this change
reduces the runtime from ~38s to ~16s.
```
import "csv"
csv.from(file: "../indata_dup.csv")
|> filter(fn: (r) => r.Animal_name == "crow")
|> count()
```
To make `compileFn` immutable after compilation (at least as far as I
and `make test` understands) I changed it to only hold the parent scope
and only construct the scope used during evaluation when `Eval` is
actually called.

perf(execute): Avoid recompiling types for every Process call

---

CONTRIBUTING.md
docs/fluxdoc.md

This change adds documentation about inline standard library documentation and fluxdoc-compliant formatting. It also updates the contributing guide to point to the new fluxdoc formatting guide.

feat(docs): add fluxdoc formatting documentation

---

execute/aggregate.go
execute/aggregate_test.go

fix(execute): catch when an aggregate input type is unsupported in simple aggregate transformation

---

interpreter/interpreter.go
libflux/flux-core/src/parser/tests/errors.rs
libflux/go/libflux/buildinfo.gen.go
stdlib/array/array_test.flux

Before it was just using the statically determined type which causes functions like `array.from` to fail as they would see the type variable from the generic function instead of the actual type.
Fixes #3858

fix: Propagate the element type through array constructors

---

stdlib/experimental/geo/geo.go

queryd was panicking with error `error="panic: interface conversion: interface {} is nil, not float64"`
as null was getting passed for latitude and longitude fields. So added
check with a proper user error message.
fixes: https://github.com/influxdata/idpe/issues/12312

fix(geo): queryd panic in flux geo package

---

cmd/flux/cmd/execute.go
dependencies.go
dependencies/bigtable/bigtable.go
dependencies/bigtable/provider_test.go
dependencies/dependencies.go
dependencies/dependenciestest/dependencies.go
dependencies/influxdb/http_test.go
dependencies/influxdb/provider.go
dependencies/influxdb/provider_test.go
dependencies/mqtt/dialer_test.go
dependencies/mqtt/mqtt.go
execute/executetest/source.go
execute/executetest/transformation.go
internal/cmd/flux/main.go
stdlib/experimental/to_test.go
stdlib/influxdata/influxdb/secrets/get_test.go

Reduces the risk of accidentally running with side effects in environments that should not run them.
Closes #4218

feat: Default to erroring dependencies 

---

stdlib/json/encode.go
stdlib/json/encode_test.go

Avoid panicking when an array-like table stream is passed to the `json.encode()` function. Instead emit a Flux error.

fix(stdlib): `json.encode()` should not panic given a table stream

---

stdlib/universe/length.go
stdlib/universe/length_test.go

Avoid panicking when an array-like table stream is passed to the `length()` function. Instead emit a Flux error.

fix(stdlib): `length()` should not panic given a table stream

---

Dockerfile_build

This patch updates the required rust to 1.56.
This update did not require any code changes in libflux, so should be safe.

chore: update to rust 1.56

---

rust-toolchain.toml

As we're using `rust-toolchain.toml` to manage our toolchain, there's
some implicit changes that come along with it. In the case of cloud, the
build system is set up for rust 1.55, but when `rustup` sees the
toolchain file, it opts to use `1.56`, which doesn't have the components
needed in it. This patch specifically adds the targets for which we need
to fetch the stdlib.

fix: add targets to rust-toolchain

---

CODEOWNERS

The `/` syntax didn't work using `*` as the examples show should work.

chore(codeowners): use glob instead of root dir

---

.circleci/config.yml
Dockerfile_build

I think that this will address the `permission denied` failures that we've been seeing in the nightly integration tests.
It seems that the image `golang:1.17` is set up to run with user `root` and `GOPATH` set to `/go`.  However our build container creates a new user, but does not update `GOPATH`. So commands like `go get ...` will fail when they try to write with the Go cache.
I noticed that `.circleci/config.yml` sets `GOPATH` and `GOCACHE` explicitly, but it seems like just setting `GOPATH` is enough, and that we want to do that right in `Dockerfile_build` so it just works everywhere.
The only thing I can't figure out is how the nightly integration tests ever worked, since nothing seems to have changed recently to cause them to fail.

fix: set GOPATH in Dockerfile_build

---

libflux/flux-core/src/semantic/mod.rs
libflux/flux-core/src/semantic/tests.rs
libflux/go/libflux/buildinfo.gen.go

Prior to these message you could not extract the location information
separate from the error message for semantic Errors. Now you can get the
location information explicitly allowing for passing rich diagnostics
in the LSP.

feat: add location/message methods to semantic::Error

---

execute/executetest/transformation.go
stdlib/testing/diff.go

The default epsilon was too precise for our test cases. Changing the
epsilon to `1e-6` from `1e-9` to allow for the tests to pass on both
amd64 and arm64.

fix(stdlib): change the default epsilon for testing.diff to 1e-6

---

rust-toolchain.toml

~Attempting to address CI failures for the `v0.143.1` release in OSS: https://github.com/influxdata/influxdb/pull/22916~
This solves some of the CI failures we were seeing for the `v0.145.0` flux release.
PR here: https://github.com/influxdata/influxdb/pull/22972
Previous CI failures: https://app.circleci.com/pipelines/github/influxdata/influxdb/26288/workflows/97f36a33-418c-4622-b0eb-0e45831fe709

chore: Add more targets to rust-toolchain.toml

---

compile.go
compiler/runtime.go
compiler/runtime_test.go
interpreter/interpreter.go
lang/compiler.go
semantic/semantictest/cmp.go
stdlib/array/from.go
stdlib/array/from_test.go
stdlib/contrib/jsternberg/influxdb/influxdb.go
stdlib/contrib/sranka/opsgenie/responders_to_json.go
stdlib/experimental/geo/geo.go
stdlib/experimental/mqtt/to.go
stdlib/influxdata/influxdb/to.go
stdlib/json/encode.go
stdlib/kafka/to.go
stdlib/pagerduty/pagerduty.go
stdlib/strings/strings.go
stdlib/strings/strings__test.go
stdlib/universe/contains.go
stdlib/universe/contains_test.go
stdlib/universe/join.go
stdlib/universe/length.go
values/array.go
values/display.go
values/display_test.go
values/values.go
values/values_test.go

`TableObject` currently implements the `Array` interface but all the
methods panic, explaining they are unsupported.
This change aims to avoid panicking and instead give an error message
suited to each case.
A new interface is introduced, `values.TableObject,` which allows type
assertions to be made without importing `flux` (to get access to
`flux.TableObject`). This is a tactic to avoid cyclical imports. For
cases where the module already had access to `flux.TableObject`, it's
used directly. For most other cases, `values` was already imported
making the interface available. For other cases, `values.TableObject`
is favored to avoid more contention on `flux`.
Each place where we make a type assertion, there's a link to #4343 which hopes to help track down all these checks for removal …

fix: ensure arrays are not table streams before calling `Len()`

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/formatter/mod.rs
libflux/flux-core/src/formatter/tests.rs
libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/from_test.go

This wasn't noticed before as the code will keep any already multiline pipe chain on multiple lines, so this only occured if the entire chain was on a single line, but couldn't actually fit.

fix: Split the entire pipe chain on multiple if necessary

---

stdlib/universe/union2.go

fix(stdlib): optimized union needs the mutex earlier to avoid a data race

---

execute/aggregate.go
execute/aggregate_test.go
execute/closer.go
execute/disposable.go
execute/group_transformation.go
execute/group_transformation_test.go
execute/narrow_state_transformation.go
execute/narrow_state_transformation_test.go
execute/narrow_transformation.go
execute/narrow_transformation_test.go
libflux/go/libflux/analyze.go
mock/transformation.go
stdlib/universe/derivative.go
stdlib/universe/filter.go
stdlib/universe/group.go
stdlib/universe/quantile.go
stdlib/universe/shift2.go
stdlib/universe/union2.go

We will need the ability to return an error from places where dispose
would have been called so renaming this to `Closer` to match `io.Closer`
and changing the signature to return an error.
This does not use `io.Closer` to differentiate the interface from the
one in the standard library, but it is identical.

refactor(execute): refactor the disposable interface to closer

---

stdlib/http/post.go
stdlib/http/post_test.go

The errors returned by the HTTP Client will have a few extra layers
around them when the initial error comes from its control function.
Since the control function is where we run our IP validation, the error
code information was being "lost" at the point where it would be reported.
This change attempts to unwrap the outer layers of the Error so we can
preserve the initial cause. If the nesting is not the expected
structure, return the root error as we did before.

fix(stdlib/http): IP validation failures should be classified as Invalid

---

libflux/go/libflux/buildinfo.gen.go
stdlib/types/is_type_test.flux

These new tests will be extended to test out pushing down type predicates into the storage tier.
Part of #2159.

test: add a table stream test for is_type, to test push downs

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/sort.go
stdlib/universe/sort_limit.go
stdlib/universe/sort_limit_test.flux
stdlib/universe/sort_limit_test.go

The optimized sort limit will take the pattern `sort |> limit` when
limit has no offset and will replace it with an optimized version that
performs the sorting continuously as data comes in rather than
performing a sort on all of the data and then doing the limit.
This is most analogous to performing a merge sort on each incoming
chunk of data.
Fixes #4397.

feat(stdlib): create an optimized sort limit

---

array/array.go
array/array_test.go

This allows us to create a `String` (which is a wrapper around the Arrow array type that also allows for a compressed representation of arrays when all the elements are the same) from a native Arrow array. This change is necessary to bring arrays coming form Arrow Flight into Flux.

chore: add a method to create a String given an existing array

---

libflux/flux-core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

Had a need for `paramter` in `flux-lsp` (https://github.com/influxdata/flux-lsp/pull/367)

feat: Expose MonoType::parameter and MonoType::field

---

etc/spawn-dbs.sh

Testing postgres for #4389 and had issues downloading the SAP hana image so I tweaked the script so that you can chose to only start a subset of databases.

chore: Allow the integration databases to be started separately

---

execute/dispatcher.go
execute/executor.go
execute/recover.go
execute/recover_debug.go

When there's a panic in a transformation, it's sometimes useful to
either get a stack trace or have the panic bubble up so it can be seen
in the debugger. I very commonly end up deleting the recover from the
dispatcher so I can see what the panic was without guessing where it
might have happened based on the message.
This change moves the recover methods into its own file with a build tag
that changes whether recover is used at all. In order to get a version
of flux that panics, the `debug` tag can be used.

refactor(execute): create a non-recover version of recovery methods for debugging

---

rust-toolchain.toml

With [CVE-2022-21658](https://blog.rust-lang.org/2022/01/20/cve-2022-21658.html), rust 1.58 is no longer safe. This patch updates to use 1.58.1

fix: update to rust 1.58.1

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/contains.go
stdlib/universe/contains_test.flux

Flux treats the access of a missing field in the `value` parameter for `contains` as a hard error, whereas similar access in `filter` is treated as "falsy."
As noted in <https://github.com/influxdata/influxdb/issues/23025>, it's possible the error behavior was introduced as a breaking change accidentally in <https://github.com/influxdata/flux/pull/2696> since a user raised the issue as something that worked previously but  no longer does.
This patch checks to see if `value` is invalid and immediately returns `false` if it is, sidestepping the type check between the `value` and `set` parameters that produces the error.
Refs:
- <https://github.com/influxdata/flux/issues/4381>
- <https://github.com/influxdata/influxdb/issues/23025>
- <https://github.com/influxdata/flux/pull/2696>

fix(universe): return false if contains gets invalid value

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
dependencies.go
dependencies/dependencies.go
dependencies/mqtt/dialer_test.go
dependencies/mqtt/mqtt.go
dependency/dependency.go
dependency/dependency_test.go
execute/executetest/dependencies.go
internal/cmd/flux/main.go
internal/cmd/flux/repl.go
internal/feature/flags.go
internal/feature/flags.yml
interpreter/interpreter_test.go
lang/compiler.go
repl/repl.go

This adds hooks to the dependency subsystem to run certain actions at
certain times of the execution. At present, the only hook is the
`OnFinish` hook which runs when execution has finished.
The mqtt dependency has been modified to use a pool dialer by default.
The pool dialer will retrieve an `mqtt.Client` that has the same options
and brokers that was previously "closed" to avoid establishing a new
connection. This means repeated calls to `mqtt.publish()` will use the
same client.
Pooled clients are cleaned up when `OnFinish()` is called.
Fixes #4278.

feat(dependency): add dependency hooks to the dependency subsystem

---

dependencies/dependencies.go

This reverts the change to the dependencies package. The change switched
the package to return a more generic interface rather than the struct
that held all of the dependencies, but there was existing code that used
this struct that was not easily refactorable.
The original version of the PR that introduced this change needed the
change to simplify a large change, but we ended up doing a different
change instead so this reverts the small section of the change back to
its original form just to simplify the area where this function was
consumed.

fix(dependencies): revert update to the dependencies package

---

cmd/flux/main.go

The rule is _only enabled_ here in the CLI, making the behavior
inconsistent with other envs.
The rule is specifically problematic because it can cause some queries
to fail even when written explicitly to avoid type check failures.
The rule could be re-enabled at a later date if we can figure out a way
to get the type checking to be permissive enough in this case.
Refs: #4378
Fixes: #4436
To verify the patch, I didn't add any new tests since it felt wrong to base test cases on a behavior determined by which rules are registered or not. Instead I checked the work in the REPL.
```
> import "influxdata/influxdb/sample"
>
> // Looking at _value in the first filter breaks (as expected) 
> sample.data(set: "usgs") |> filter(fn: (r) => r._field == "mag" and r._measurement == "earthquake" and …
```

chore: disable MergeFiltersRule

---

internal/pkg/feature/feature_test.go
internal/pkg/feature/flag.go

The int type for feature flags has been switched from int32 to int since
it is more consistent. Additionally, if a float value is returned and is
meant to be interpreted as an int, the conversion now happens. This can
sometimes happen because feature flag libraries may transfer the data as
JSON and JSON doesn't have an integer type instead treating them as
floats.

fix(feature): int feature flags work properly when returned as floats

---

plan/plantest/rules.go

Normal go errors can't be compared unless you pass in an appropriate `cmp.Option`
which meant that `ValidateError` could only be used for errors created by the internal
flux error type. By adding in `cmp.Options` from the caller, we can allow other errors to be checked.

test(plan): Use cmp.Options when comparing `ValidateError`

---

execute/bounds.go
plan/bounds.go
stdlib/influxdata/influxdb/cardinality.go
stdlib/influxdata/influxdb/from.go
stdlib/universe/range.go

Not sure why there are multiple versions of `Bounds` but this removes some duplication which
will also be useful for `iox.from`

feat: Add conversion from flux.Bounds to plan/execute.Bounds

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/ast/mod.rs
libflux/flux/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

The `lsp` feature was added previously to the `flux-core` crate, but it
wasn't exposed via `flux`. This patch exposes that, and also adds one
more `Into` implementation to simplify `flux-lsp` a bit.

feat: connect lsp feature through the flux crate

---

.circleci/config.yml

Enables the `assert` tag on `test` and `test-race` jobs which makes arrow assert that reference
counted values are not double released.
(Does not cover any calls to `Release` functions defined in flux itself)
Closes #2846

test: Check for double Release on arrow arrays

---

execute/source_iterator.go
stdlib/array/from.go
stdlib/internal/gen/tables.go

`TransformationSet`'s implementation does the iteration automatically

refactor: Use TransformationSet's methods instead of iterating

---

execute/profiler.go
internal/cmd/flux/main.go
lang/compiler_test.go
tracing.go

The detailed query traces weren't really practical as they commonly
caused the tracing program, jaeger, to fall over with traces that were
too large.
This removes the code from the engine because we can't practically turn
it on.

refactor: remove detailed query traces

---

lang/compiler_test.go
libflux/flux-core/src/semantic/tests.rs
libflux/flux-core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

This should address part of https://github.com/influxdata/flux/issues/4451, by adding a name for type instead of relying on the user knowing what the symbols mean (easier to google a name, if nothing else).
It is still a bit confusing that arrays and streams of tables are both "array", but that is a different change (https://github.com/influxdata/flux/issues/4275)
cc @rickspencer3

feat: Explain what [A], [A:B] etc means in errors

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/schema/schema_test.flux

Test that are extended need to use an explicit yield, these tests are
extended in order to validate their planner rules.

fix(schema): update tests to use explicit yield

---

dependencies/feature/flagger.go
internal/feature/flags.go
internal/pkg/feature/cmd/feature/main.go
internal/pkg/feature/flag.go
internal/pkg/feature/metrics.go
internal/pkg/feature/metrics_test.go

This allows feature flags to record that a metric has been accessed
through an interface that is set by the user. By default, this interface
discards the metric. This can be configured in order to allow an
application to gather things like prometheus metrics from accessing
feature flags.

feat(feature): allow feature flags to record metrics if configured

---

stdlib/influxdata/influxdb/to.go
stdlib/influxdata/influxdb/to_test.go

The `to()` transformation may need to compute the `TagColumns`. Currently this is
written into the Spec object. In order to support parallel execution of to(),
where multiple execution nodes are derived from the same spec, copy the tag
columns into the transformation object and edit them there.

fix: TagColumns in to() might get modified, copy them into the transformation

---

internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/difference.go
stdlib/universe/difference_test.go

I were a bit worried about how this would handle schema mismatches but it seems like each new table resets the state anyway so the state will get reset just the same as the old implementation (I added a test since there wasn't one before).
Do we want a feature flag for this change?
Closes #3942

perf: Update the difference transformation to use narrow transformation

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/bin/fluxdoc.rs
libflux/flux-core/src/doc/example.rs
libflux/go/libflux/buildinfo.gen.go

Gathers up the result of each individual test and prints them at the top level
Adds rayon as a dependency to run each tested package in parallel which cuts down the test time a bit. Adds some complexity to ensure that the test results are still printed in the same order.

test(doc): Improve doc tests

---

compile.go
compiler/runtime.go
interpreter/interpreter.go
lang/compiler.go
stdlib/array/from.go
stdlib/contrib/sranka/opsgenie/responders_to_json.go
stdlib/experimental/geo/geo.go
stdlib/experimental/mqtt/to.go
stdlib/influxdata/influxdb/to.go
stdlib/kafka/to.go
stdlib/pagerduty/pagerduty.go
stdlib/strings/strings.go
stdlib/universe/contains.go
stdlib/universe/join.go
stdlib/universe/length.go
values/array.go
values/display.go
values/display_test.go
values/values.go

Now that the type system can distinguish between streams (aka tables)
and vanilla arrays we no longer need the TableObject interface and its
associated type guards.
Fixes #4343

fix(length): removes unnecessary TableObject guards

---

csv/result.go
csv/result_test.go

Added a note about using the `mode: "raw"` for csv that is not expected to have annotations.
Closes https://github.com/influxdata/idpe/issues/13332

fix: reclasify csv decoding errors as user errors

---

execute/dataset.go
execute/executetest/source.go
execute/executetest/table.go
execute/executor.go
execute/parallel_test.go
execute/transformation.go
mock/administration.go
plan/attributes.go
plan/physical.go
stdlib/universe/parallel.go

This PR expands the definition of an attribute on a physical plan node to a
collection of named simple interfaces:
```
type PhysicalAttributes map[string]PhysicalAttr
```
The `PhysicalAttr` interface allows arbitrary data structures to be installed as
attribute values.
This PR then adds two attribute types:
1. `ParallelRun` - indicates that a plan node should be instantiated multiple
times when creating the execution graph. Each instantiation will handle
some subset of the data. In the code we call this the parallel group. If
the node is a source node, it should restrict source data to the specified
group it has been assigned. If it is a non-source node, it should expect to
receive parallel data (the group), and produce parallel data.
2. `ParallelMerge` - indicates that plan node should …

feat: add an attribute-based instantiation of parallel execution nodes

---

internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/fill.gen.go
stdlib/universe/fill.gen.go.tmpl
stdlib/universe/fill.go
stdlib/universe/fill_test.go

This updates fill to use the `NarrowStateTransformation` transformation interface instead of the stream table.
Closes #3938

feat(stdlib): update fill to use narrow transformation

---

plan/physical.go

If a plan node is to be executed in parallel, the node should contribute to the
concurrency quota by the same amount as the parallelization factor. The factor
specifies that the node will be instantiated factor times, and we want quota
for each instantiation.
In the first iteration of the parallelization work, the plan nodes were copied N times and the concurrency calculation was appropriate. Now the plan nodes are not copied, they just carry some attributes to indicate they will be instantiated multiple times when the execution graph is made, so we need to use the attribute as a factor when adding to the concurrency quota.

feat: factor parallel execution into the concurrency quota calculation

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

One of the updated map tests put the range before `testing.load()` which
messed with the test. This swaps them so that range is after
`testing.load()` so the test works properly in influxdb.

fix(stdlib): one of the updated map tests used range incorrectly

---

etc/checkdocs.sh
etc/gen_docs.sh
libflux/flux-core/src/bin/fluxdoc.rs
libflux/go/libflux/buildinfo.gen.go

Now all Flux packages must pass Flux docs lints and tests without
exception.
Fixes #4141

chore(fluxdocs): remove exception list from docs

---

plan/plantest/plan.go

The physical attributes must be copied when copying a plantest.PlanSpec if we
want to be able to set NoChange to true in RuleTestCase

test: need to copy physical attributes when we copy a plantest.PlanSpec

---

execute/executor.go
execute/executor_test.go
lang/compiler_test.go
lang/query_test.go
plan/logical.go
plan/logical_test.go
plan/rules_test.go

refs: #4465
Previously, terminal nodes (nodes without children) fell into 3
categories:
- those that _are literal yields_
- those that _have side-effects_
- everything else
In the planner, the first two cases are marked as "roots" which
contribute to the query's concurrecy quota.
The "everything else" case would add an implicit yield to the end of the
chain, which itself is marked as a "root." This essentially funnels the
"everything else" nodes into the "literal yields" category.
Later on in the executor, literal yields generate "results" and
separately, so are the nodes that _have side-effects_.
---
This diff aims to simplify the roles and responsibilities played by each
of the planner and executor.
At a high-level, the diff marks _all terminal nodes_ as "roots" in the
planner. In the …

refactor: move implicit result generation to executor

---

docs/fluxdoc.md
etc/checkprepared.sh
etc/fixup_docs_version.sh
libflux/flux-core/src/doc/mod.rs
libflux/go/libflux/buildinfo.gen.go

Adds support for deprecated: NEXT the same as introduced: NEXT.
Additionally document that `## Metadata` is needed to delimit the
metadata section of docs.

chore(fluxdoc): add support for deprecated: NEXT

---

dependencies/mqtt/mqtt.go
internal/feature/flags.go
internal/feature/flags.yml

Previously we had implemented a way to allow flux to reuse client
connections to mqtt across calls to `mqtt.publish`, but it was hidden
behind a feature flag pending verification of the new behavior.
After some manual testing, things appear to be in good shape. By
inspecting a mosquitto mqtt broker's server log, and toggling the flag
off/on, we could see that when the feature is enabled there's a single
client connection and serveral publishes (versus one connection per
publish when the flag is off).
This diff removes the feature flag, turning the new code path on for
everyone.

feat(mqtt): enable dialer pool for everyone

---

execute/executor.go
execute/parallel_test.go

If a node is a parallel merge then it was added by the planner and might be a
successor of a node with side effects. In order to preserve behaviour, skip
these parallel merge nodes and check if the predecessor has side effects. If
so, use that node name instead.

fix: skip parallel merge nodes when selecting the result name

---

execute/dependencies.go
execute/executor.go
execute/options_test.go
lang/compiler.go
lang/compiler_test.go
plan/physical.go
plan/physical_test.go
plan/plantest/spec.go
plan/plantest/spec/mock.go
plan/plantest/spec/plan.go

Pull the `concurrencyLimit` from feature flags at the start of the execution
process, before planning, and stash it in the `ExecutionOptions`, which live in
the `ExecutionDependencies`. From there it can then be modified by planner rules.
This allows parallelization rules to raise the limit if they parallelize a
query.
At the same time we move the `defaultMemoryLimit` from the planner and into the
execution options. We also move the computation of memory limit and concurrency
quota from the planner and into the executor.
Included are test cases covering the existing and the new method of
determining query concurrency.

feat: take the concurrencyLimit from feature flags and keep in dependencies

---

libflux/go/libflux/buildinfo.gen.go
stdlib/strings/strings.go
stdlib/strings/strings_test.flux

This causes the substring function to check the lower bound to make sure
it's not greater than the length of the string. Previously, this was
just sometimes working because strings will sometimes have a larger
capacity than the actual length of the string.

fix(stdlib): check length boundary for lower bound of substring

---

array/array_test.go
compiler/vectorized_test.go
execute/dataset_test.go
execute/executetest/table.go
execute/table_test.go
go.mod
internal/feature/flags.go
internal/feature/flags.yml
lang/compiler.go
lang/query.go
memory/allocator.go
memory/allocator_test.go
stdlib/universe/holt_winters_test.go
values/vector_test.go

Instead of manual `Retain` and `Release` calls. I left those calls in right now, but since `Free` no longer actually frees the memory we can still see this works by observing the actual free being don in the finalizer.
As we can see from the repeated `GC` calls (and from being forced to manually GC in the first place), the maximum memory in use at any time will be larger and garbage collection may only clear up part of what is unreachable.
cc #4486

feat: Track freed memory with SetFinalizer

---

execute/transport.go
lang/compiler_test.go

This PR builds on previous PRs (#4616, #4618) to fix the opentracing spans generated for transformations.
Previously, we would not create a transformation span using the existing span in the context as the parent. This lead to orphan spans, where the transformation spans were not connected to the rest of the query trace in the Jaeger UI.
This change set addresses this and also adds more testing to verify the behavior.

fix: create spans for transforms using context

---

cmd/flux/cmd/test.go

Fixes #4576
While looping over the discovered tests, mark them as skipped if they
are listed on the CLI as such.
Later, while summarizing the test outcome, report the counts for the total,
failures and skipped tests.
---
Since the change was to the test runner itself, I wasn't sure of the best verification strategy. I setup a manual test using the following method.
First, I created an isolated test root with the following file:
```
$ cat test-root/reporting_test.flux 
package skipping
import "array"
import "testing"
input = () => array.from(rows: [{x: 1}])
testcase works {
testing.diff(want: input(), got: input()) |> yield()
}
testcase breaks {
want = input()
got = input() |> filter(fn: (r) => false)
testing.diff(want: want, got: got) |> yield()
}
```
The idea being it contains one test …

feat(test): report skipped tests

---

libflux/flux/src/cffi.rs
libflux/go/libflux/buildinfo.gen.go

Panicking across an FFI boundary leads to crashes that are hard to understand as the backtrace seem to get suppressed. Better to catch and return a normal error to go and let it deal with it like any other error.

chore: Catch panics in the FFI

---

execute/executor.go

`getResourceLimits(int64, int)` tries to `return 0, math.MaxInt64` which,
in 32-bit architectures causes an overflow.

fix(executor): do not assume ints are 64bits

---

array/array_test.go
compiler/vectorized_test.go
execute/dataset_test.go
execute/executetest/table.go
execute/table_test.go
lang/compiler.go
lang/query.go
memory/allocator.go
memory/allocator_test.go
values/vector_test.go

This removes GcAllocator from all tests but still provides a way to inject it temporarily
for testing.
@jsternberg I think something like this is what you wanted?

refactor: Add NewFluxAllocator as an injection point for the GcAllocator

---

stdlib/universe/map2.go

This statement must have been used in development but the template file
was ultimately removed. This causes an error when you use go generate.

fix(stdlib): remove an extraneous go generate statement

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

This was mostly spurred by needing to update `lsp-types`, which is
preventing an update to `tower-lsp` in `flux-lsp`.

chore: update dependencies

---

cmd/flux/main.go

feat(cmd): add trace option to the flux cli

---

internal/execute/groupkey/groupkey.go

Calling `atomic.LoadUint64(()` on `groupKey.hash` resulted in an alignment panic in armv7, due to it not being 64bit aligned.
Declaring it first in the struct solved it.
See https://pkg.go.dev/sync/atomic#pkg-note-BUG fore more details
For context: I already fixed a similar issue at https://github.com/influxdata/influxdb/pull/23260

fix(execute): remove 64bit misalignment

---

.circleci/config.yml
Dockerfile_build

This only affects the builders. The version of go that we dictate ourselves to be compatible with is go 1.17. This is in preparation of switching to a minimum version of go 1.18.

chore(ci): upgrade go version to 1.18 in dockerfile and windows build

---

stdlib/strings/strings.go
stdlib/strings/strings_test.go

After the fix, the below query returns a type error rather than panicking.
```
import "strings"
import "array"
import "internal/debug"
arr = array.from(rows: [{x: 1}])
arr |> debug.opaque() |> map(fn: (r) => ({r with _field: strings.joinStr(arr: ["mean", r._field], v: "_")}))
```
```
Result: _result
Error: runtime error @5:26-5:109: map: failed to evaluate map function: expected elements of argument "arr" to be of type string, got type string value <nil>
```
fixes: https://github.com/influxdata/flux/issues/4554 https://github.com/influxdata/EAR/issues/3066

fix(stdlib/strings): strings.joinStr panic when receives nil values

---

libflux/flux-core/src/ast/tests.rs
libflux/flux-core/src/parser/mod.rs
libflux/flux-core/src/parser/tests.rs
libflux/flux-core/src/parser/tests/errors.rs
libflux/go/libflux/buildinfo.gen.go

A common pattern we have is this:
parse_string("".to_string(), "from(...) |> range(...) |> filter(...)")
That first argument is supposed to serve as the filename and, in
general, we don't care about it. However, the `BaseLocation.file` has a
`#[serde(skip_serializing_if = "skip_string_option")]` on it, which
means that when we go over the serialization boundary,
`BaseLocation.file` is no longer `Some("")` but `None`. It's probably
not a huge deal, but when the result is inconsistent going over the
serialization boundary, that becomes an issue.
This patch fixes that by only assigning `BaseLocation.file` to a `Some`
value when the string is not empty. Otherwise, assign it as a `None`.

fix: don't set BaseLocation.file to Some("")

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/sort.go
stdlib/universe/sort_limit_test.flux

This PR adds a bit of logic to our handling of `sort |> limit` to catch the case where we have received an empty table. The code the does merging did not expect to have to deal with zero-row tables, and wound up in an infinite loop.

fix(universe): fix SortLimit for empty input group

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/covariance_test.go
stdlib/universe/join.go
stdlib/universe/join_test.flux
stdlib/universe/join_test.go

Fixes: #4692
When a `join` is used in conjunction with a `tableFind`, the input tables
are copied and given new operation IDs. This causes problems in
`createMergeJoinTransformation` where we rely on a mapping of
`TableNames` to associate the inputs to `join` with the corresponding
datasets.
The assumption violated in this situation is we expect the number of
"parents" to be the same as the number of tracked "table names." When
this does not hold true, we panic. Formerly the panic came from an out
of bounds index, but with this diff this is more explicit.
Ideally, I think it would be better to perform a deep copy on the join's
`JoinOpSpec` for the sub-program we build via `tableFind` such that the
"sub join" is entirely different and can hold references to the "sub
inputs."
In practice …

fix(universe/join): remove `JoinOpSpec.TableNames` and favor `JoinOpSpec.params` to stay consistent inside `tableFind`

---

execute/executor.go
execute/profiler.go
execute/profiler_test.go
execute/transport.go
lang/compiler_test.go

This PR has two commits:
The first is a refactoring that decouples opentracing spans from operator profiling. At one time we used operator profiling to also generate opentracing spans, but this has been disabled for several months now. This mechanism generated too many spans (one per table) which would overwhelm the tracing infrastructure. It's also the case that we might want to look at a trace for a query that has not been profiled. Since tracing is an internal tool, and profiling is an external one, it makes sense to keep them separate.
The second commit adds an opentracing span for each source in a query, and makes a corresponding update to tests.

Add opentracing spans for sources

---

docs/SPEC.md

While working on converting the EBNF for use with Grammar-Kit, I noticed
the `MultiplicativeOperator` was "unused." Seems like this is where it
should go.

fix(SPEC): use MultiplicativeOperator in MultiplicativeExpression

---

stdlib/universe/aggregate_window.go

This exposes some of the fields in the aggregate window spec so that planner rules outside of the universe package have access to the attributes and can make planner decisions. Before, only rules defined in the universe package would have access to these fields so it would be impossible to write a planner rule that references this procedure spec.

feat(stdlib): expose aggregate window spec fields for use by the planner

---

stdlib/universe/aggregate_window.go

The aggregate window rule used the wrong condition for the infinite
window at the end because I was swapping the logical operators and
forgot one.
Additionally, `table.fill` needs to be included in the procedure spec.
This will be needed when this optimized aggregate window uses selectors,
but is mostly just needed to preserve the attribute so the influxdb push
downs can be properly formed no matter which direction the planner goes.

fix(stdlib): logic error in aggregate window rule and preserve whether table.fill is present

---

internal/feature/flags.go
internal/feature/flags.yml
lang/compiler.go
lang/query.go
memory/allocator.go
memory/allocator_test.go

Every time we allocate an arrow array we check that we do not exceed the maximum memory limit.
Since this limit check is before the allocation step (and garbage collection) we inevitably
end up in a situation where the limit gets exceeded before the garbage collector has a chance
to run. Worse, go's garbage collector is highly incremental so even when it does run, we can
still end up allocating more than we collect, thereby exceeding the limit.
The only way I can see this allocator working is if the limit is so far above the amount of
memory actually being in use, which would let the garbage collector keep up. However in that case
the memory limit wouldn't really relate to how much memory were actually in use making it rather arbitrary.
Closes #4486

chore: Remove the experimental SetFinalizer allocator

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/hour_selection.go
stdlib/universe/hour_selection_test.flux
stdlib/universe/hour_selection_test.go

The fix is to provide [`hourSelection`](https://docs.influxdata.com/flux/v0.x/stdlib/universe/hourselection/) function to select data from a nighttime range, such as 10 pm to 6 am.
**Example query-** 
```
...
|> range(start: 2018-12-01T00:00:00Z)
|> hourSelection(start: 22, stop: 6, timeColumn: "_time")
```
**Input -** 
```
,result,table,_measurement,_field,_time,_value
,,0,Sgf,DlXwgrw,2018-12-18T06:11:05Z,70
,,0,Sgf,DlXwgrw,2018-12-18T16:11:15Z,48
,,0,Sgf,DlXwgrw,2018-12-18T17:11:25Z,33
,,0,Sgf,DlXwgrw,2018-12-19T18:11:35Z,63
,,0,Sgf,DlXwgrw,2018-12-19T19:11:45Z,48
,,0,Sgf,DlXwgrw,2018-12-19T22:11:55Z,63
```
**Output -**
```
,result,table,_start,_stop,_measurement,_field,_time,_value
,,0,2018-12-01T00:00:00Z,2030-01-01T00:00:00Z,Sgf,DlXwgrw,2018-12-18T06:11:05Z,70 …
```

fix(stdlib): hourSelection does not allow for selecting overnight time ranges

---

rust-toolchain.toml

Fixes an issue with the OSS build.
Nb. the `Dockerfile_build` rust version (which normally has to be in
lock-step with the `rust-toolchain.toml` _because of reasons_) was
already at 1.58. This is why the version isn't changing in this diff.
Separately, could the drift between these 2 have contributed to the
break in the OSS build?

build: downgrade rust to v1.58

---

plan/heuristic_planner.go
plan/heuristic_planner_test.go

In the case of a half diamond of logical nodes in a plan the same
logical node could be added to the node stack during traversal, however
the visited map to avoid double traversing the same node only contained
physical nodes as such the second logical node would be visited twice.

fix(plan): fix panic with half diamond logical plan

---

plan/heuristic_planner.go
plan/heuristic_planner_test.go
plan/plantest/rules.go
plan/types.go

Recently an issue occurred where a planner rule returned a `nil` value for its `newNode` return when no change was made tot he plan. This is pretty reasonable to do, but the planner was not robust to it.
This change makes it so rules can return a `nil` value for the new plan node, and if no change was made to the plan, it works just fine.

chore: make planner robust to rules that return nil values

---

semantic/utils.go

fix(semantic): attach type when constructing logical expressions

---

execute/executor.go
execute/profiler.go
execute/profiler_test.go
execute/transport.go
lang/compiler.go
lang/query_test.go
mock/executor.go
query.go

The operator profile is now always computed and it is part of the
`flux.Statistics` struct that is returned by the query. The operator
profile now uses that to return the profile instead of using Go channels
and the execution dependency injected into the context.
This allows the results of the operator profile to be present without it
being tied directly to the profiler return.
It has also been refactored to remove the use of channels for sending
span data and aggregating in a goroutine to instead just aggregate the
results as part of the source/transport code. This should simplify and
speed up those calculations as the overall time should be equivalent but
without the overhead of Go channels and only requiring a short-lived
lock for appending the source profiles in the executor.

feat(execute): refactor the operator profile to be in the statistics

---

dependencies/http/http.go
dependencies/http/http_test.go

issue:
The flux HTTP client [limits response sizes](https://github.com/influxdata/flux/blob/master/dependencies/http/http.go#L18) to 100 MB. If a user runs a query that results in a large HTTP response, the resulting failure can manifest in a number of different error messages for the user, not all of which are helpful in effectively communicating the actual problem.
Another possible manifestation of this is truncated CSV, which produces a confusing error.
fixes: https://github.com/influxdata/flux/issues/4607

fix: return a more helpful error message to the user when an http response exceeds maxResponseBody(100MB)

---

query.go

fix: add json tags for the transport profiles in statistics

---

execute/vector_fn.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map2.go
stdlib/universe/map_test.flux
values/object.go

The vectorized version of map did not properly handle shadowed columns
the way the row based one worked. This copies over some of that code so
that it follows the correct logic. It also copies over the same logic
that is used to determine the column type when type inference does not
properly tell us the type.
This also fixes a bug in building objects that caused a bug in the
compiler. When a `with` is evaluated, the attributes from the original
record are copied over first and then overwritten values are assigned.
This overwriting did not properly release the values that were being
overwritten resulting in a memory leak.
Fixes #4812.

fix(stdlib): vectorized map properly handles shadowed columns

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

With the switch back down to `lspower` in `flux-lsp`, `flux` is now
requiring too new of a `lsp-types` for `flux-lsp` to use. `flux-lsp`
needs `lsp-types 0.92`, and flux is using `0.93`. This patch downgrades
this requirement.

fix: require an earlier minimum lsp types

---

libflux/flux-core/src/semantic/nodes.rs
libflux/flux-core/src/semantic/tests/labels.rs
libflux/go/libflux/buildinfo.gen.go

Forgetting to add the `Label` constraint leads to confusing typechecking failures down the line as
it becomes possible to pass non-labels and string literals ends up treated as strings instead of labels.

fix: Make it an error to use a label variable without the Label constraint

---

Makefile
execute/executetest/selector.go
execute/table/copy.go
execute/table_test.go
internal/debug/assert_off.go
internal/debug/assert_on.go
internal/debug/util.go

Refs #4780
When the tables sent into `tableFind` include a yield, the result generated by the yield can cause the tables to be released before `tableFind` can use them.
`tableFind` will make its own copy, but prior to this change the copy operation would hand back the input directly when it was already buffered. In effect, this means we produce references to the same underlying buffers without us incrementing the ref count.
~~With this diff, for the case where we try to copy an already buffered table, we call its own `Copy()` method which will `Retain()` each of the internal buffers.~~
After a few twists and turns, the fixes for this issue came from:
- making `tableBuffer`'s `Do` and `Done` idempotent such that calling `Done` after `Do` would not release the underlying arrow arrays …

fix: ensure buffers are retained when copying an already buffered table

---

docs/StandardLibrary.md
libflux/go/libflux/buildinfo.gen.go
stdlib/testing/testing.flux

This has been replaced by `csv.from() |> testing.load()`
BREAKING CHANGE:
Use `csv.from() |> testing.load()` instead
Part of https://github.com/influxdata/flux/issues/4768

feat: Remove testing.loadStorage

---

cmd/flux/cmd/test.go

Sometimes it is unclear where to find a failing test. By prepending the filename in the output log
we should have more clarity.

chore: Report the filename + test name on test failures

---

execute/aggregate.go
execute/aggregate_test.go
mock/transformation.go
stdlib/universe/aggregate_window.gen.go
stdlib/universe/aggregate_window.gen.go.tmpl
stdlib/universe/aggregate_window.go

Aggregate transformations can now be given multiple parents and will
work in parallel. To define an aggregate transformation as
parallelizable, a `Merge()` method must be implemented on the
transformation.
This can only happen if a planner rule modifies the plan so that a node
which normally has one parent will have multiple parents instead. This
allows aggregate transformations that implement this interface to act as
merge nodes.

feat(execute): add method to parallelize aggregate transformations

---

plan/heuristic_planner.go
plan/heuristic_planner_test.go

Patches the traversal from sinks to sources and implements a fix
for panics in half diamond DAGs by tracking visitation using node
instead of newNode, but also, prohibits visiting a node if
succesors were not yet visited.
Indexing visitation by node instead of the newNode fixes a panic
for half diamonds DAGs caused by revisitations of updated nodes.
However, it creates a problem of revisiting a newNode with multiple
succesors, because only the first succcesor sees the initial node.
Thus traversal is constrained to nodes with visited successors so
traversal can safely rule out one successor misidentifying a
predecessor as unvisited.

fix(plan): visit successors before continuing DFS on node

---

interpreter/interpreter_test.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/universe.flux

This adds an example to the `aggregateWindow()` documentation that shows how to adjust the start day of weekly (`1w`) windows. It also replaces "window and aggregate" with "downsample" to better match the purpose of the function and what users are actually searching for.

chore(docs): add example and update language in aggregateWindow

---

libflux/flux-core/src/semantic/nodes.rs
libflux/flux-core/src/semantic/tests.rs
libflux/go/libflux/buildinfo.gen.go

We can probably explain this even better, but just changing this to point to `yield()` instead of `findColumn` seems a good start.

fix: Point to the function being piped to on argument mismatches

---

internal/spec/build.go
internal/spec/build_test.go
lang/compiler.go
spec_test.go

Refs #4813 
Table functions (ie tableFind) don't have any way to prioritize the use
of one result or another when they consume tables as input. For tables
that produce more than 1 result, the receiver would essentially use only
the first found result, which is non-deterministic.
In many cases, this can lead to errors at runtime where the output from
the table function does not match the expected schema. Perhaps worse,
it's possible you'd just get an incorrect answer rather than an error.
This refactor adds a new `skipYields` parameter to `spec.FromEvaluation`
which will produce a simplified spec when `true` by omitting any yields
encountered while walking the input tables.
With yields taken out of the picture, the only results we should see would
come from whatever the terminal node is, …

refactor: skip yields in input tables for cases like tableFind

---

Dockerfile_build

go 1.18 no longer allows `go get` to be used for installing binaries. We
also can't use it outside of a repository without a version specifier.
This modifies the build to use the version in `go.mod` for installing
`pkg-config` and installs it in an alternate and safer way.

ci: fix the docker image build for go 1.18

---

README.md
cmd/flux/main.go
cmd/flux/repl.go
interpreter/interpreter_test.go
repl/repl.go

Added in a new flag to run the repl with suggestions and by default the real will start without suggestions. Addressed issue #4836. Updated docs to remove old argument in running the repl and showed how to run repl with the new flag.
``` ./repl --enable-suggestions ``` 
```./repl```

feat(repl): Suggestions now start off by default and added a new flag

---

plan/plantest/rules.go
stdlib/influxdata/influxdb/rules_test.go
stdlib/universe/filter_test.go
stdlib/universe/sort_limit_test.go

Previously by default we would not perform validation steps
in physical planner tests since it presented a burden on the
test writer to make realistic plans and spend time on things
they are not actually testing.
This is an additive change that makes it so by default validation is
performed on the resulting plan, but it may be skipped if needed.
For tests that began failing due to validation failures, I have skipped
them.
Validation is a step performed after planning to make sure the plan
that is about to be executed is in fact sane. Validation will become more
important as we increase the use of physical attributes, as we will for #4678.

test(plan): make planner test helper validate by default

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.flux

The code for `findColumn` was not dealing with tables with multiple buffers, and each subsequent buffer would overwrite the answer for the previous. This PR addresses that and adds some more tests.
Fixes #4884.

fix(table_fns): make findColumn() able to handle multi-buffer tables

---

stdlib/experimental/http/requests/requests_test.go

On my Mac running Go 1.18.1 I see this test failing with an error
message that is different than expected. This adds to the
expected error messages so that the test passes.

test(experiemntal/http): add expected error message

---

libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

I believe this changed due to the downgrade to `lspower`. Having a version range here is ok
since the only two types we use in `flux-core` do not change between these versions (and I don't think they have ever changed since the first release of `lsp-types`).
cc https://github.com/influxdata/flux-lsp/pull/488

chore: Expand the lsp-types range to accept the 0.91 version flux-lsp needs

---

stdlib/join/sort_merge_join.go
stdlib/join/sort_merge_join_test.go

I found this issue while working on #4902. The list of columns to be sorted by in generated sort nodes included an initial set of empty strings. This would not have resulted in incorrect behavior I don't think, but it was confusing when I encountered it.

fix(stdlib): fix a bug in how sort nodes created for new join

---

cmd/flux/main.go
cmd/flux/repl.go
interpreter/interpreter_test.go
repl/repl.go

This uses the option pattern to configure the repl with enabling
suggestions as the currently available option. This option defaults to
false. The `repl.New()` function has also been changed back to accept
only a single argument, but to also allow an optional set of options to
configure the REPL.

fix(repl): replace extra boolean parameter for suggestions with repl options

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/csv/csv.flux

`experimental.csv` only provides a simple way to query a URL and parse
as CSV, now that `requests` package is complete its best to use and
compose this logic as needed. As it stands `experimental.csv` can't
check the HTTP status code and so its best this is left to the developer
writing the code.
Depends on https://github.com/influxdata/flux/pull/4921 merging first.

feat(stdlib): deprecate experimental.csv 

---

libflux/go/libflux/buildinfo.gen.go
stdlib/join/join_fn.go
stdlib/join/join_test.flux
stdlib/join/merge_join_test.go

Return an error if a user defines an `as` function that returns a record that is missing a group key column.
Fixes #4909

fix(join): return error if user modifies group key

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/http/http.flux

Use `http/requests` instead of `experimental/http.get`.
Depends on https://github.com/influxdata/flux/pull/4921 merging first.

feat(stdlib): deprecate experimental/http.get

---

Makefile
ast/edit/task_editor.go
ast/testcase/testcase.go
ast/testcase/testcase_test.go
cmd/flux/cmd/test.go
cmd/flux/main.go
cmd/flux/test_test.go
cmd/flux/testdata/fluxtest.root
cmd/flux/testdata/pkga/fluxtest.root
cmd/flux/testdata/pkga/pkga_test.flux
cmd/flux/testdata/test_test.flux
libflux/go/libflux/buildinfo.gen.go
stdlib/testing/testing.flux

Now you can add tags to test cases and pass tags to the `flux test`
command to only run specific tests.
Additionally unit tests have been added for the `flux test` command.
Fixes #4577
Fixes #4574 
Fixes #4575 
Not tags are added or changed with this PR, that will come as a follow on PR.

feat(test/tags): adds tagging support to flux test

---

plan/attributes.go
plan/format.go
plan/format_test.go

In order to determine if a query plan has been parallelized, we have been using
the presence of a `partitionMerge` node in the plan. With the emergence of a new
technique of merging in `aggregateWindow` nodes, and possibly soon `pivot` nodes as
well, we can no longer use this test.
This PR allows physical plan attributes to contribute to plan details. First
the spec is consulted, then any physical attributes that are present. Any node
with the `ParallelMerge` attribute can then indicate it is a merge node.

feat: allow physical plan attributes to contribute to formatter details

---

plan/plantest/rules.go

If they aren't passed, we get confusing error messages about `cmp.Option` instead of the actual mismatch

chore: Accept cmp.Option when diffing the RuleTestCase.ValidateError

---

dependencies/influxdb/http.go
stdlib/influxdata/influxdb/to.go
stdlib/influxdata/influxdb/wide_to.go

The to function is intended to skip tags that are empty since that is
how tags with an empty value are represented in influxdb.
The old implementation would also skip keys that are empty, but I think
this behavior isn't correct so this will retain the behavior of erroring
on the tag key being invalid.

fix(stdlib): to function should skip empty tag values

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/aggregate_window.gen.go
stdlib/universe/aggregate_window.gen.go.tmpl
stdlib/universe/aggregate_window_test.flux

The native aggregate window implementations of mean and sum now properly
work with null values and the mean implementation now uses the mean of
means method of calculation rather than just `sum / count`.
The null values ensures that it properly acts when there are null values
or when the interval is only null values.
The change to use a mean of means method of calculation helps to prevent
infinite values from showing up in the result when the sum overflows
because we keep a mean of each interval with the count so that we can
merge two means.
Fixes #4945.

fix(stdlib): aggregate window mean and sum work properly with null values

---

.circleci/config.yml

I've got a PR open against the upstream, but in the mean time this aims
to use our patched version rather than the published one.
Ref: <https://github.com/camilohe/rustup.install/pull/7>
See this linked PR for details on what broke and steps I took to mitigate.
If/when the PR merges we can revert the change here and return to just installing `rustup.install` with the rest of our regular chocolatey packages.
---
N.b. I noticed there was some log output complaining about the `pkgconfiglite` we are installing. There might be some needed maintenance there :thinking: 
---
Testing-wise, I basically force-pushed changes to this branch until the windows build seemed to get past the rustup install.

build(windows): use patched rustup.install chocolatey package

---

execute/executetest/source.go
execute/executor.go
execute/parallel_test.go
plan/attributes.go
plan/attributes_test.go
plan/collation.go
plan/format.go
plan/format_test.go
plan/parallel.go
plan/physical.go
plan/plantest/cmp.go
plan/plantest/rules.go
plan/plantest/spec/mock.go
plan/plantest/spec/plan.go
plan/types.go
stdlib/influxdata/influxdb/to.go
stdlib/join/sort_merge_join.go
stdlib/universe/aggregate_window.go
stdlib/universe/filter.go
stdlib/universe/group.go
stdlib/universe/parallel.go
stdlib/universe/sort.go

This set of changes creates a framework whereby plan nodes can model characteristics of the data they consume and produce. These characteristics are called `attributes` in the code and currently there are three different kinds:
- `collation` to indicate data that is collated (sorted) by particular columns
- `parallel-run` to indicate that operations are run in parallel
- `parallel-merge` to indicate a plan node that represents a merging of parallel data streams
The parallel attributes were previously existing, but with this set of changes it is the procedure specs themselves that describe whether run in parallel or if they merge parallel streams.
Different attributes being produced or required by a particular operation is expressed by implementing interfaces. The comment at the top of …

feat(plan): generalize attributes in planner

---

libflux/go/libflux/buildinfo.gen.go
stdlib/join/join_test.flux
stdlib/join/merge_join.go

Fixes a bug where join could not produce any output if a given group key existed on only one side of a join. Keeps track of a union of all schemas the join transformation has seen from each parent. If a group key is missing, that schema information is used in place of the schema tracked by the `joinState` so that compilation can finish successfully.

fix(join): provide a default schema for unmatched group keys

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/experimental/diff.go
stdlib/testing/diff.go

This causes the `_diff` function to use the diff implementation in
`experimental` as the base diff implementation when the feature flag is
set.
This will cause diff to use a longest common subsequence algorithm to
compute the diff.
This is behind a feature flag in case it has some unknown complication.
Fixes #924 and #4815.

feat(stdlib): switch testing.diff to use experimental.diff as its base

---

execute/transport.go
stdlib/join/merge_join.go

The process message method is intended to ignore messages it does not
understand rather than actively return an error. This removes the error
from join for an invalid message.

fix(stdlib): ignore unknown messages rather than erroring

---

libflux/go/libflux/buildinfo.gen.go
stdlib/pagerduty/pagerduty.flux
stdlib/pagerduty/pagerduty_test.go

By capturing the response body, debugging becomes easier in the case that pagerduty rejects the alert. This also truncates the summary if it is too large for pagerduty to accept, preemptively handling a failure scenario.
I have had difficulty with this working in practice (manually updating the vendored flux library and deploying), but running manual queries in query explorer with the changes to the `pagerduty.flux` file result in working/expected results. I can redact and post that query here if needed.

chore(pagerduty): limit length of pagerduty summary and capture response body

---

execute/executetest/result.go
execute/executetest/source.go
execute/executetest/transformation.go
stdlib/universe/holt_winters_test.go

Some test flakiness has been reported for the holt winter test.
```
--- FAIL: TestHoltWinters_Process (35.48s)
--- FAIL: TestHoltWinters_Process/NOAA_water_-_with_nulls_and_missing_-_no_seasonal (17.15s)
holt_winters_test.go:903: unexpected tables -want/+got
[]*executetest.Table{
&{
... // 2 identical fields
KeyValues: nil,
ColMeta:   {{Label: "_time", Type: s"time"}, {Label: "_value", Type: s"float"}, {Label: "minSSE", Type: s"float"}},
Data: [][]any{
{
s"2015-08-27T22:13:00.000000000Z",
-                           float64(6.517746679116747),
+                           float64(6.517761275336982),
-                           float64(30.52018686151099),
+                           float64(30.520187390109854),
},
```
In the testing framework, we have epsilon value defaults to …

fix: passing epsilon value from go test to test framework

---

repl/repl.go

Closes https://github.com/influxdata/flux/issues/5016
Helps with https://github.com/influxdata/flux/issues/5021

fix(repl): repl uses unique planner node ids

---

execute/aggregate.go
execute/executetest/dependencies.go
execute/selector.go
internal/feature/flags.go
internal/feature/flags.yml
libflux/go/libflux/buildinfo.gen.go
plan/attributes.go
plan/attributes_test.go
stdlib/internal/debug/pass.go
stdlib/join/sort_merge_join.go
stdlib/universe/aggregate_window.go
stdlib/universe/pivot.gen.go
stdlib/universe/pivot.gen.go.tmpl
stdlib/universe/pivot.go
stdlib/universe/range.go
stdlib/universe/sort.go
stdlib/universe/sort_rules_test.flux

This PR is part of #4628.
Like the title says, this adds a planner rule (behind a feature flag) and associated tests that demonstrate sort nodes being removed.
I did a quick pass over our transformations to find the ones that preserve collation, and added `PassThroughAttributer` implementations as needed. For the case of `aggregateWindow` it always generates rows sorted by `_time` so I implemented `OutputAttirbuter` for that transformation as well.

feat(plan): add a rule to remove redundant sort nodes

---

stdlib/join/merge_join.go

Previously, join was only guarding the `processChunk` method with a locked mutex. Recent changes to flux have revealed that that was not enough. This patch ensures that the handlers for the `FlushKey` and `Finish` messages are also behind a mutex.

fix(join): Guard message processing with mutex

---

.github/pull_request_template.md

While flux is in the pre-1.0 stage it can be difficult to make changes to APIs offered by the stdlib _once they are introduced_.
In an effort to encourage a more measured approach when introducing new packages to the flux standard library, the team discussed specifically calling this act out in the PR template. Specifically, we want _new packages_ to be introduced first under the `experimental/` directory since we have a more permissive social contract there as far as making breaking API changes go.
Checklist items that aren't relevant to the diff can be checked but should also be acknowledged by noting them as **N/A**, or otherwise making remarks in the PR description itself.
As an interesting edge case, here's the new checklist in action for a PR that doesn't actually contain any code. …

chore: update PR template to encourage safe stdlib additions

---

libflux/go/libflux/buildinfo.gen.go
stdlib/strings/strings.go
stdlib/strings/strings_test.flux
stdlib/strings/strings_test.go

Inputs that contain non-breaking spaces (NBSP), and assumedly a host of
other unicode characters caused `strings.substring` to panic when it
tried to index into an array of runes taken from a (seemingly larger)
string.
Failures looked like:
```
panic: runtime error: slice bounds out of range [:33] with capacity 32
```
This only seemed to panic when the inputs were "of a certain size" and
I'm not sure why that would be. Perhaps there are distinct thresholds
where the input causes the capacity to be just close enough to the
actual size of the rune count, but less than the string length in bytes.
Not sure.
The testcase added used an input seen in the wild and panicked prior to
the code change to substring.
Dear Author :wave:, the following checks should be completed (or explicitly dismissed) …

fix: check bounds using rune array instead of string len in substring

---

libflux/go/libflux/buildinfo.gen.go
stdlib/pagerduty/pagerduty.flux

A recent change updated the HTTP call inside sendEvent to use requests
instead of the old http package which accidentally introduced a breaking
change by switching the return from an int (status code) to a record
(http response).
This diff will rename the new (response object) version of `sendEvent`
to `_sendEvent` so it can be used in `endpoint()`. `sendEvent` will then
call `_sendEvent` and return only the `statusCode` field to restore the
original signature.
Refs: <https://github.com/influxdata/flux/pull/5006>
Regarding tests -- I struggled to figure out a way to write a test for this which wouldn't depend on making a request to a live pagerduty. I filed #5059 which would help me today, but  maybe in the future.
The old tests continue to pass, but they also passed with the breaking …

fix: restore int return value for `pagerduty.sendEvent`

---

cmd/flux/cmd/test.go
cmd/flux/main.go
libflux/flux-core/src/bin/fluxdoc.rs
libflux/go/libflux/buildinfo.gen.go

Matches how features can be passed to the flux REPL/script runner. I don't really need this as but I didn't realize that until after I had this written already :shrug: Seems useful/consistent with the REPL at least.

feat: Accept flux feature flags to the test command

---

cmd/flux/cmd/test.go

Personally if I have specified `--test` I am only interested in the test(s) I have
specified so seeing 800 other lines reporting all the skipped tests is just noise.
The final summary still reports the number of success/skip/failures so skips are still reported, just not as heavily

test: Don't report skips when --test is used

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

This does not work as I would hope (see https://github.com/rust-lang/cargo/issues/9029) so we need
to restrict this to just the same version that lspower uses (for the sake of the LSP). This is bad in its own way though as lspower does not adhere to semver which can cause its own breakages.
Personally I'd like use to remove the `From` implementations we provided here and let the LSP have its own, explicit conversions so we could avoid this churn :shrug:.

chore: Remove the version range from lsp-types

---

cmd/flux/cmd/test.go

This just makes the output of `flux test` be more readable, e.g.,
```
failures:
stdlib/universe/aggregate_window_test.flux: aggregate_window_predecessor_multi_successor ... fail: Table: keys: [t0]
t0:string            _diff:string                      _time:time                  _value:int
----------------------  ----------------------  ------------------------------  --------------------------
a-1                       -  2019-11-25T00:01:00.000000000Z                           6
a-1                       +  2019-11-25T00:01:00.000000000Z                           5
Table: keys: [t0]
t0:string            _diff:string                      _time:time                  _value:int
----------------------  ----------------------  ------------------------------  --------------------------
a-z …
```

chore: make flux test use pretty formatting for diffs

---

lang/query_test.go
libflux/go/libflux/buildinfo.gen.go
plan/format.go
plan/format_test.go
plan/heuristic_planner.go
plan/types.go
stdlib/universe/aggregate_window.go
stdlib/universe/aggregate_window_test.flux

This PR fixes an issue with the planner rules that replace the composite `aggregateWindow` operation (composed of `window |> fill |> agg |> duplicate |> window(inf)`) with a unified `aggregateWindow` operation.
This rule was assuming that the predecessor to the pattern had just one successor. If this was not the case, the plan would become corrupt and planning would fail. This was being hidden before #5047 merged because a pattern that had a predecessor with multiple successors would never be reported as a match.
There are also some changes in this PR to improve diagnostics when things go wrong in the planner, and to improve the DOT representation of query plans.
Dear Reviewer(s) :wave:, …

fix: fix aggregate window rules that left plan in bad state

---

libflux/go/libflux/buildinfo.gen.go
stdlib/internal/debug/debug.flux
stdlib/internal/debug/null.go

Allow null values to be created explicitly in flux code. We could always create nulls by using `csv.from` however that format is pretty hard to read compared to `array.from` but since the latter could not create streams with nulls we were forced to use `csv.from`. With this we can use `array.from` in cases where nulls are needed in the test.

test: Add debug.null()

---

libflux/go/libflux/buildinfo.gen.go
libflux/go/libflux/internal/buildinfo/main.go
plan/heuristic_planner.go

ci throws an error comparing `buildinfo.gen.go` file when my local go version is 1.19 and ci is on the previous version.
This is because `gofmt` is changed in 1.19 and now reformats doc comments with an extra line. https://tip.golang.org/doc/go1.19#go-doc So reformatted the comments itself to work with current and previous versions.

fix(build): update buildinfo doc comments to match latest gofmt

---

dependencies/testing/testing.go
dependencies/testing/testing_test.go
lang/query_test.go

I am surprised no-one has ran into this before, wondering which plan did not run correctly.
Closes #5064 (Because I do not understand why the test becomes flaky in that PR)

test: Display which planner rule ran an unexpected number of times

---

execute/table/chunk.go

This function provides some utility to output a debug friendly output if needed when testing. It's not meant to be used for anything beyond that.
Closes #5080

feat(execute/table): add a Stringify utility function for table.Chunk

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/ast/mod.rs
libflux/go/libflux/buildinfo.gen.go

~The default attribute does the same thing so no need for this dependency. (The crate seems to have been added in the original creation of the AST, maybe `default` didn't exist then or something https://github.com/influxdata/flux/pull/1418 )~
The default attribute only handles undefined fields, not null fields. But the function is so simple
to add that we do not need an dependency really.

refactor: Remove serde-aux

---

Makefile
libflux/flux/src/cffi.rs
libflux/go/libflux/buildinfo.gen.go
rust-toolchain.toml

Didn't think about us being locked to 1.58 when I created https://github.com/influxdata/flux/pull/4939 so I updated rust to fix the bug with the `undocumented_unsafe_blocks` lint. This downgrades rust again and adds an allow to work around it.
cc https://github.com/influxdata/flux/pull/5084#issuecomment-1216836856

chore: Downgrade rust to 1.58 again

---

Dockerfile_build
rust-toolchain.toml

This just adds a comment to `Dockerfile_build` and `rust-toolchain.toml` about how we're blocked on this issue:
https://github.com/rust-lang/rust/issues/97117
I attempted to reproduce with Rust 1.63.0 and the issue is still occurs there.

chore: add comment regarding Rust version to docker and toolchain files

---

internal/execute/groupkey/groupkey.go
internal/execute/groupkey/groupkey_test.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/pivot_col_order_test.flux

The flux pivot() function uses a string representation of
the group key to keep track of what columns it has seen.
Sometimes the columns of the group key can appear in a different order
even if the set of columns and their values are the same. when this
happens, pivot() panics as it uses a map that assumes all group
keys have a canonical representation.
So the `groupKeyString` that is computed here:
https://github.com/influxdata/flux/blob/cf5caf06789c3e6995998a077ffc411f80582c2f/stdlib/universe/pivot.go#L264
Is later used here to access a map in a map-of-maps:
https://github.com/influxdata/flux/blob/cf5caf06789c3e6995998a077ffc411f80582c2f/stdlib/universe/pivot.go#L307
And sometimes it may happen that the string value used to create an entry in the
outer map may be different than the …

fix: sort columns when printing group key

---

semantic/format.go

Got an error for this when output the query plan. Easy enough to just handle the node

fix: Don't error when formatting boolean literals

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/experimental_test.flux
stdlib/experimental/unpivot.go

The pivoted data we get from IOx may contain fields with nulls which we must exclude from the unpivoted chunk so they do not show up as extra rows with `null` as the `_value`.
Based on #5079 #5081

fix: Don't include null columns when unpivoting

---

stdlib/universe/schema_functions.go
stdlib/universe/schema_functions_test.go
stdlib/universe/schema_mutators.go

No need for the type switch here when we can just type two functions precisely instead :shrug: 

refactor: Remove type switch in schema_mutators

---

execute/narrow_state_transformation.go
execute/narrow_state_transformation_test.go
mock/transformation.go
stdlib/experimental/preview.go
stdlib/universe/cumulative_sum.go
stdlib/universe/derivative.go
stdlib/universe/difference.go
stdlib/universe/fill.go
stdlib/universe/limit.go
stdlib/universe/moving_average.go
stdlib/universe/state_tracking.go

This modifies the narrow state transformation to use generics instead of
`interface{}` for its implementation. This should allow us to write code
more easily as it will remove the boilerplate to do a type cast at the
beginning of process.
None of the transformations that use this have been modified. Instead,
they use the generic method but use `interface{}` as their type
parameter.

refactor(execute): transition narrow state transformation to use generics

---

libflux/go/libflux/buildinfo.gen.go
plan/types.go
stdlib/universe/sort_limit_test.flux

Fixes #5114.
This PR addresses an issue that has existed for a long time, but did not manifest until #5047 was merged. 
The issue was in a `plan` helper method that merges two nodes. If the predecessor to one of the nodes had a predecessor with multiple successors, we were not updating edges correctly and we put the plan graph into an inconsistent state.
Previously this issue could not be hit because we did not allow many rules to match in multi-successor scenarios, and this bug is particular to that situation.

fix(plan): fix logic bug in planner helper method

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/universe.flux

Related to https://github.com/influxdata/docs-v2/pull/4373
Fixes a typo and removes code block syntax from aggregateWindow documentation. The `js` code block syntax was preventing the example from rendering correctly in the generated docs.

chore(docs): fix typo and example in aggregateWindow

---

internal/function/arguments.go
internal/function/function.go
stdlib/bitwise/bitwise.go
stdlib/date/durations.go
stdlib/dict/dict.go
stdlib/dict/dict_test.go
stdlib/experimental/iox/iox.go
stdlib/timezone/timezone.go

The function package now uses its own arguments struct. This is to
eventually remove the `interpreter.Arguments` interface. An interface is
a poor choice for that type because interfaces with that many methods
cannot be changed or adapted easily.
At some point, the function package will be used for all situations
instead of the raw register methods.

feat(function): update function library to have its own arguments struct

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/polyline/polyline.flux
stdlib/experimental/polyline/polyline_test.flux
stdlib/experimental/polyline/rdp.go
stdlib/experimental/polyline/rdp/rdp.go
stdlib/packages.go

Added a new package containing functions for polyline simplification. The RDP algorithm enables the downsampling of data by retaining the variations in the curve to create visually indistinguishable graphs.

feat: add new package for downsampling data

---

internal/cmd/headless_repl/main.go

Added in the existing code for the repl and modified existing repl methods so that the communication was done via the stdin and out. Related to : #4793 .
``` {"jsonrpc":"2.0","method":"Service.DidOutput","params":[{"input":"x=1"}]}```

feat: add "headless" json-rpc based REPL

---

internal/cmd/headless_repl/main.go

`Spec` was moved during <https://github.com/influxdata/flux/pull/5116>.
This diff updates the import path in the headeless repl to match.
Currently there are no unit tests for this binary, so I had to manually verify the change:
```
$ go run internal/cmd/headless_repl/main.go                                                                                                                
{"jsonrpc":"2.0","method":"Service.DidOutput","params":[{"input":"now()"}]}                                                                                
{"id":null,"result":{"Result":"2022-08-26T21:07:16.304361483Z"},"error":null}                                                                              
^C^C^C^\SIGQUIT: quit
```
Dear Author :wave:, the following checks should be completed (or …

fix: update package for `Spec` in headless repl

---

.circleci/config.yml

We see windows builds timeout all the time.
CircleCI has a deadline for how long a job can run without printing
anything. The default is 10m, so this diff doubles it at 20m.
Hopefully we will waste fewer CI cycles this way by reducing the number
of restarted jobs required for a green run.

build: extend deadline for windows builds

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/diff.go
stdlib/experimental/diff_test.flux

With `diff.Len()` being zero due to the `NewArray` call `arrow.Repeat` only constructed empty arrays.
The specialization of string arrays had special handling which caused it to work only for that array (and strings are the usual group keys).

fix: Don't lose the values of non-string group keys in experimental.diff

---

libflux/flux-core/src/parser/mod.rs
libflux/flux-core/src/parser/tests/errors.rs
libflux/go/libflux/buildinfo.gen.go

It is common for users to write `x.` and then query for completion, in which case we should not try to consume the next, non-identifier token as that will likely causing further parse failures.

fix: Handle a missing property on member expressions better

---

cmd/flux/cmd/test.go

Skips tend to bloat the test output and since tests are always skipped through explicit opt-in behavior I don't think it is very valuable.

chore: Don't report skips in fluxtest

---

compiler/runtime.go
libflux/flux-core/src/semantic/tests/vectorize.rs
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_vectorize_conditionals_test.flux

Fixes https://github.com/influxdata/flux/issues/5155
...which shows a runtime error when nesting a logical expression inside a conditional expression.
When in the `test` position, we'd get:
```
cannot use test of type vector in conditional expression; expected boolean
```
Originally, `logicalVectorEvaluator` advertised a runtime type of bool, which is inconsistent with reality since it is actually a vector of bool.
The error message we saw in this situation stemmed from the fact we choose either the vectorized or row-based conditional evaluator with this check here:
https://github.com/influxdata/flux/blob/df2b4c404e81d39cadef7456c4a3aacf55d3638a/compiler/compiler.go#L657-L669
Since `test` in this case was a `logicalVectorEvaluator` with incorrect (bool) typing, this check failed and we …

fix: correct inconsistent runtime typing for `logicalVectorEvaluator`

---

array/binary.gen.go
array/binary.gen.go.tmpl
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

In the row-based division, we check to see if the divisor is 0 and return an error when this is the case.
This check was missed in the vectorized division, leading to a panic.
This diff adds the check for division for uint and int. For whatever reason, zero division with float produces an `Inf+` and there is no such guard in the row-based version so no updates were made there on the vectorized side.

fix: vectorized division by zero should error not panic

---

array/array.go
array/array_test.go
array/builder.gen.go
array/builder.gen.go.tmpl
array/builder.go
go.mod
stdlib/experimental/unpivot.go

When pushing down aggregate functions the time field is not included in the output so we need to tweak unpivot to work without the time column. Changing the order seemed like the simplest solution however that exposed a bug in the current implementation where the full `time` column were copied over as any nulls only existed in the value column

feat: Allow unpivot to work when the time field is missing 

---

cmd/flux/cmd/test.go

It is useful to be able to insert `yield(name: ...)` to inspect a test but the output of the yield were just ignored. This collects and displays the output without causing any test failures due to this extra output.
- [x ] 🏃 Test cases are included to exercise the new code

feat: Display yields in fluxtest

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/fill.gen.go
stdlib/universe/fill.gen.go.tmpl
stdlib/universe/join_fill_panic_test.flux

Closes #5127
`fill()` was incorrectly setting `fillValueTime` as an int64, which caused a panic the next time `fillTimeColumn` was called and tried to coerce `fillValueTime` into a `values.Time`. This only manifested when processing a table that spanned multiple table chunks (i.e., when `fillTimeColumn` was called with a `fillValue` that was already set).
This patch sets `fillValueTime` to be a `values.Time`, which avoids the bad type coercion and thereby also avoids the panic.

fix(fill): correct type for fillValueTime

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/diff.go
stdlib/experimental/diff_test.flux

Before they would be displayed as the zero-value of whatever type the column is which is rather confusing. Now it is left empty instead (or should we display `<nil>` or something instead?)

feat: Don't display nulls as 0 in diff

---

libflux/go/libflux/buildinfo.gen.go
stdlib/join/join_fn.go
stdlib/join/join_test.flux

fix(join): better error when joining empty table

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

This is mostly just to check for regressions (the fix was already made in #5160).
Prior to the fix in #5160, this test would fail with:
```
runtime error: cannot use operand of type vector with logical or; expected boolean
```
Today, the test passes and all is well.

test: vectorized nested logical ops

---

docs/SPEC.md

Discovered these typos while working on describing Flux syntax in https://github.com/pierwill/flux-redex.

fix: Fix typo in SPEC.md

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/sort_limit_test.flux

Removed debug.pass() from the test as https://github.com/influxdata/flux/issues/4699 has been fixed.

chore: removed debug.pass as planner rules issue has been fixed.

---

libflux/flux-core/src/parser/mod.rs
libflux/flux-core/src/parser/tests/errors.rs
libflux/go/libflux/buildinfo.gen.go

Thought this would be necessary for https://github.com/influxdata/flux-lsp/pull/580 but it seems like the completions works regardless. Still, this corrects `expect_or_skip` since I'd say we shouldn't use the token if we "skip" it.

fix: Don't include the opening parenthesis in invalid call expressions

---

docs/SPEC.md

Rename some rules for the builtin statement to avoid ambiguity.
Closes #5186.
N/A
N/A
No feature changes, but this does update the specification.

fix(spec): Fix duplicate definitions

---

docs/SPEC.md

I've update the links to point to the issues in this repo.
A few have been closed; I've removed those links.
No changes to lang, but this does update SPEC.md.

fix(docs): Update issue links in SPEC.md

---

docs/SPEC.md

Fix typo in spec. Closes #5187.

fix(spec): Fix typo in specification of operator precedence

---

array/binary.go
compiler/compiler.go
compiler/runtime.go
compiler/vectorized_test.go
execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
interpreter/interpreter.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

Fixes #5188
During an earlier attempt #5181 to fix a type-error problem in the vectorized logical operator implementation, we identified some deviation from the spec in how it worked with respect to `null` inputs. We also found the standard row-based version of logical ops _also deviated_ but in different ways.
This diff attempts to align all logical operator implementations (vectorized, row-based, as well as "in the interpreter") to be representative of what we have in the spec.
In addition to adhering to the spec re: nulls, this diff also adds short-circuiting support to the vectorized implementation in a similar fashion to vectorized conditionals.
This is achieved by checking the left-hand-side vector to see if all the elements are a single value. When this is the case and the value …

fix: logical null handling

---

libflux/flux-core/src/bin/analyze_query_log.rs
libflux/go/libflux/buildinfo.gen.go

Adds the capability to just print the queries run through `analyze_query_log` since the input formats (csv or sqlite) aren't as easy to read.

chore(query_analyzer): Add an option to just print the source for each logged query

---

libflux/flux-core/src/parser/tests/errors.rs

The error for this was changed by https://github.com/influxdata/flux/pull/4957 and was noticed downstream.

test: Add a parse error test for option

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/sort.go
stdlib/universe/sort_limit.go
stdlib/universe/sort_limit_test.flux

The sort limit code did not skip chunks with no rows which caused it to
attempt to compare invalid chunks with each other. This skips those rows
but still ensures that the schema is created for them.
This is similar to the same problem that was identified in #4701. That
PR only addressed when the last or only chunk was zero while this one
ensures that the aggregation step also handles this situation properly.
Fixes #5020.

fix(stdlib): sort limit skips chunks with no rows

---

libflux/flux-core/src/ast/mod.rs
libflux/flux-core/src/parser/tests.rs
libflux/flux-core/src/parser/tests/arrow_function.rs
libflux/flux-core/src/parser/tests/errors.rs
libflux/flux-core/src/parser/tests/from.rs
libflux/flux-core/src/parser/tests/literals.rs
libflux/flux-core/src/parser/tests/objects.rs
libflux/flux-core/src/parser/tests/operator_precedence.rs
libflux/flux-core/src/parser/tests/property_list.rs
libflux/flux-core/src/parser/tests/strings.rs
libflux/flux-core/src/parser/tests/types.rs
libflux/go/libflux/buildinfo.gen.go

By shrinking the size of `Debug` printed AST's  it becomes possible to use `expect_test` for the parser tests instead of manually writing it out without ballooning the test size to much. Using expect_test to generate the expected value lets us avoid manually writing it, which is tedious when adding tests and also very brittle since any change to one of the AST types may lead to several tests needing to be manually update.
The change size here is huge, but there really isn't a need to go through and compare everything here as I have taken care to not mix changes to tests and "real code", so with each test conversion was done without changing any actual behavior.
If we would like, we might use [expect_file](https://docs.rs/expect-test/latest/expect_test/macro.expect_file.html) instead to …

chore: Convert all parser test to use expect_test

---

compiler/compiler.go
compiler/runtime.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

Not yet sure this is a problem or not, but the thinking is the feature flag check we do inside the new strict null logical evaluator is too expensive to tolerate.
Selecting the original evaluator will bypass the feature flag check so we can watch the perf impact and learn if it is truly too expensive :sweat: 
Testcases that depend on the (newer) strict null version have been skipped to allow the CI to pass.

fix: skip strict null logicals

---

docs/SPEC.md

regexp abbreviation is used in the rest of the text, fixing for consistency.

Spelling fix

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/universe.flux

the documentation generated from this file has `inf` on this line as `**inf**`, i don't know what caused that markup to be applied and cannot be sure it will still be after this change
side note: i assume this refers to either positive or negative infinity, would it be useful to state that?
though looking a bit closer (i'm not familiar with the language this is written in), it seems to be of type `duration`, rather than a float, as stated by the comment, maybe someone can clarify?
- i hope the title suffices
- none found
- i'm unfamiliar with your test infrastructure, and don't know if any tests apply to this change

fix: "infinte" typo

---

compiler/compiler.go
compiler/compiler_test.go
compiler/runtime.go
compiler/vectorized_test.go
execute/row_fn.go
execute/row_fn_test.go
execute/vector_fn.go
stdlib/array/array.go
stdlib/contrib/jsternberg/aggregate/table.go
stdlib/experimental/join.go
stdlib/generate/from.go
stdlib/influxdata/influxdb/to.go
stdlib/join/join_fn.go
stdlib/join/merge_join.go
stdlib/universe/filter.go
stdlib/universe/map.go
stdlib/universe/map_vectorized.go
stdlib/universe/reduce.go
stdlib/universe/schema_functions.go
stdlib/universe/schema_mutators.go
stdlib/universe/state_tracking.go
stdlib/universe/table_fns.go

Should make it possible to enable the strict null logical ops when compiling the executor instead of branching inside the executor itself.

refactor: Pass the context to the executor compiler

---

execute/executetest/dependencies.go

Test harnesses in other envs don't currently have good ways to "inherit" the default flagger we set here for vanilla flux.
External test harnesses like the one in OSS can configure the same flux flags we set here for vanilla flux if we make them available.
By exposing the flagger defaults with a public function, we can improve the POC here <https://github.com/influxdata/influxdb/pull/23762> which will help us avoid having to skip tests just because flags are not enabled.
This is a bit of a stop-gap and will eventually be made redundant by https://github.com/influxdata/flux/issues/4777 since the default flagger will be removed entirely. When #4777 is completed, testcases will manage their own flags.
--- 
No new tests have been added for this change since the new func is used for the …

chore(executetest): expose default test flagger

---

execute/executetest/source.go
stdlib/csv/from_test.go

This change is to pass context param in the `runSourceHelper` so that `Run` method can use the passed context rather overwriting to default`context.Background()`
Required for writing go test in https://github.com/influxdata/idpe/pull/15867

fix: passing context in the run source helper

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/dynamic/dynamic.flux
stdlib/experimental/dynamic/dynamic.go
stdlib/experimental/dynamic/dynamic_test.flux
stdlib/packages.go

Originally planned as a part of #5143, this diff adds a new builtin to the `experimental/dynamic` package which wraps an existing value in a `Dynamic`.
This implementation is weak, probably incomplete, and hard to test without additional work since part of the contract of our "restrictive" dynamic type is you can't really do much with it until you cast it to some other value. 
_The buried lede is: we haven't implemented the dynamic support for the standard cast fns yet._
At this early stage the best I can offer in terms of testing is this short REPL session:
```
❯ go run ./cmd/flux
> import dyn "experimental/dynamic"
> dyn.dynamic(v: 123)
<unknown value>
> dyn.dynamic(v: 123) == dyn.dynamic(v: 123)
Error: unsupported binary expression dynamic == dynamic
>
```
> I went ahead and added the …

feat(dynamic): add dynamic wrapper function

---

values/display.go
values/display_test.go

These changes make it so `display` (the Flux stdlib function and also the way values are shown in the REPL) shows something meaningful for dynamic values.
I also made it so that arrays represented on multiple lines don't add a space after the comma, which makes it easier to use display output for tests.
This is part of work in progress for #5141.

chore: display dynamic values

---

libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/jsternberg/aggregate/aggregate.flux

Closes influxdata/docs-v2#4504
This change fixes input and output indicates that were reversed in the `aggregate.table` example.
---

chore(docs): fixed reverse inputs and outputs in example

---

libflux/flux-core/src/formatter/mod.rs
libflux/flux-core/src/formatter/tests.rs
libflux/go/libflux/buildinfo.gen.go

It is possible to write floating point literals which cannot be represented exactly by a `f64`. When passing source code through the formatter we lose any extra precision. This uses the literal source text to format instead (if it exists).

fix: Don't lose extra precision in floats when run through the formatter

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/sort.go

The work of #4628 was to create a planner rule that removes unnecessary sort nodes. This rule has been gated by a feature flag, and the flag has been on in production without issue for a few months now.
This PR removes the feature flag as it is no longer needed.

chore: delete feature flag that removes redundant sort nodes

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/array/array_test.flux

The `array.toUInt()` test utilized conversion behavior and assumed that
conversion behavior was the same for floats to uints as ints to uints.
Floats to uints is implemented differently than ints to uints especially
on the ARM platform. On ARM, a negative float converts to zero. While we
may want to change Flux to define a specific behavior for this
conversion in the long run, this is just going to fix the test so it
consistently uses floats for now so the test passes appropriately on all
architectures.

fix(stdlib): array touint test utilized conversion behavior incorrectly

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/dynamic/dynamic_test.flux
stdlib/universe/typeconv.go

Fixes #5143
By adding a branch at the top of the following functions we can pull out the inner value of a dynamic and then run the rest of the default implementation as is:
- `bool()`
- `bytes()`
- `duration()`
- `float()`
- `int()`
- `string()`
- `time()`
- `uint()`
The tests added look to make sure at least one conversion or extraction works as expected and at least one error case is hit reliably. The dynamic code path relies on the current behavior of `Dynamic.IsNull` for null propagation so I added a test for each function to show `dynamic(null)` does in fact produce a `null`.
Otherwise, I didn't think we should need to chase total coverage of the original function, just that the dynamic is indeed being unwrapped.
Since #5143 is the last piece of planned work for this initial push …

feat(dynamic): add support dynamic support for standard type conversion functions

---

libflux/flux/src/cffi.rs
libflux/go/libflux/buildinfo.gen.go

As of rustc 1.64, Box::from_raw is #[must_use].
```
error: unused return value of `Box::<T>::from_raw` that must be used
--> flux/src/cffi.rs:100:5
|
100 |     Box::from_raw(cstr);
|     ^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> flux/src/lib.rs:1:38
|
1   | #![cfg_attr(feature = "strict", deny(warnings, missing_docs))]
|                                      ^^^^^^^^
= note: `#[deny(unused_must_use)]` implied by `#[deny(warnings)]`
= note: call `drop(from_raw(ptr))` if you intend to drop the `Box`
error: could not compile `flux` due to previous error
```
Dear Reviewer(s) :wave:, you are responsible (among others) for ensuring the completeness and quality of the above …

fix compile error with Rust 1.64

---

libflux/go/libflux/buildinfo.gen.go
stdlib/date/date.flux

A user submitted documentation feedback requesting information about what days the return values of `date.weekDay` represent. This PR adds a table to `date.weekDay` and `date.month` to show what day/month each return value represents.
---

chore(docs): update date package docs to address user feedback

---

libflux/flux-core/src/semantic/tests.rs
libflux/flux-core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

These errors are usually because someone has made a typo or forgotten the name of an argument so reminding them of what the valid arguments are is helpful.

feat: Recommend valid arguments in extra argument errors

---

dependencies.go
dependencies/influxdb/http.go
dependencies/influxdb/http_provider_test.go

Adds the `PrivateClient` struct which wraps the default client. Behaves identically to the default client except that it obscures error messages that may contain sensitive information.
Also exposes a `PrivateHTTPClient()` method to the `Dependencies` struct. If an `HttpProvider` is created and no host is specified in the config, this method is called in place of `HTTPClient()`.

refactor(deps): Add private http client

---

compiler/runtime.go
interpreter/interpreter.go
libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/dynamic/dynamic_test.flux

Partially fixes #5276 
Member expressions on dynamic values started out very loose. Originally, any dynamic would just hand back a `dynamic(null)` when the property lookup failed. This means getting good feedback from the runtime was much harder as nulls could just bleed through.
This diff aims to ensure we give better feedback - especially for cases where the dynamic inner value is some non-object (int, float, null, and so on).
In these situations a property lookup would never make sense. This indicates the underlying data structure is probably unexpected to the script author and updates to the program will be needed.
Overall this should be a safer initial implementation at the language level since it is "more regular" and less exotic. We can add API to improve the developer experience …

refactor(dynamic): member expr should error when inner is not obj

---

dependencies.go
dependencies/http/http.go

Exposes the `newPrivateClient` function so that it can be used in external implementations of flux packages.

refactor(deps): expose NewPrivateClient function

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/sample/sample.flux

Fixes a single typo in the description of the `influxdata/influxdb/sample` package.
---

chore(docs): fix typo in influxdata/influxdb/sample package

---

install_flatc.sh

Update the `flatc` version referenced in `install_flatc.sh`, as well as the checksum. This should update the version of flatc our CI docker image uses so that https://github.com/influxdata/flux/pull/5296 can pass.

chore: update flatc version

---

interpreter/interpreter_test.go
libflux/go/libflux/buildinfo.gen.go
stdlib/universe/universe.flux

Discourage use of `window` and `aggregateWindow` when `_time` is in the group key.
The reason is that even when we get a right answer, the output is confusing. At other times we hit this bug:
https://github.com/influxdata/flux/issues/5260

docs: update docs with windowing caveats

---

repl/repl.go

This just adds a root tracing span to the REPL so that any spans produced during execution have a common parent span. This makes generated traces more readable.

chore: create a root span for REPL input

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This should create a standard environment for contributors to load up
the project and use vscode to modify it and have a usable environment
for compiling and running the program.
It still leaves a lot to be desired. For whatever reason, loading the
project takes forever. `rust-analyzer` takes a very long time and the go
tools aren't presently installed by default. We can iterate on the
container to make it quicker to load and a more desirable environment to
work in.

chore(dev): first attempt at a vscode devcontainer for the project

---

compile.go
execute/dependencies.go
execute/metadata.go
internal/operation/spec.go
internal/spec/build.go
lang/compiler.go
lang/compiler_test.go
metadata/metadata.go
stdlib/universe/aggregate_window.go
stdlib/universe/window.go
stdlib/universe/window_test.go

This detects two undesirable patterns so that we can remove them later.
The first is the `_time` parameter being in the group key when window is
used. This wasn't really intended and should have been an error, but it
may have accidentally been done and it's not explicitly an error. We
want to detect it happening so we can communicate those scripts need to
be fixed so we can turn it into an error without disruption.
The second is an undesirable interaction with table find. When table
find is used, the plan is immediately created and evaluated. But, when
this interacts with another plan evalutation, the operation will be
duplicated. This can create inconsistencies from how other parts of the
engine work. We've chosen to have this interaction be an error, but we
want to detect if it's …

feat: detect certain undesirable patterns so we can remove them later

---

libflux/go/libflux/analyze.go

This change just makes it so we will set the `salsaDatabase` feature based off of what's in the context when calling into Rust to analyze a Flux program. Unless I'm mistaken I think this was just an omission from #5201.

fix: add salsaDatabase to list of feature passed to Rust

---

docs/SPEC.md

This change adds the details of how Flux editions will work and their intent. One small parser change is proposed to enable an edition directly within the script.

docs(SPEC): add specification of editions

---

csv/dialect.go
csv/result.go

Part of https://github.com/influxdata/idpe/issues/16210
Per feedback from the automation team (see this PR https://github.com/influxdata/idpe/pull/16212), and with approval of @nathanielc , making changes to the csv Dialect to add download headers.
* we are doing direct filesystem download of data in the UI, bypassing browser memory.
* With this approach, the download filename is only configured with content-disposition headers.
* Made changes in queryrouterd to add the headers.
* Per automation team's request, pushing the header change into the csv Dialect.
* did not add Headers test to this repo, since I didn't see other headers tested.
* Did add an idpe test case, which has already been successfully run with local changes in this package. Confirmed works.

feat(csv): add download headers within csv dialect

---

docs/SPEC.md

The implementation of this work is still in-progress see https://github.com/influxdata/flux/issues/4296

docs(SPEC): add specification of modules

---

dependencies/iox/client.go
stdlib/experimental/iox/source.go

This updates the IOx client abstraction to produce a reader that has an `Err()` method (which the Flight implementation does), and updates the implementation of `iox.sql` to check it for errors.
Prior to this change, midstream errors would be ignored and the result would be truncated.
These changes address a defect found in the cloud product, with tests added to the PR there.
BREAKING CHANGE: breaks the Go API for the IOx client dependency.

fix: update iox.sql to detect midstream errors

---

libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/qxip/hash/README.md
stdlib/contrib/qxip/hash/cityhash.go
stdlib/contrib/qxip/hash/hash.flux
stdlib/contrib/qxip/hash/hash.go
stdlib/contrib/qxip/hash/hash_test.go
stdlib/packages.go

This PR adds `contrib/qxip/hash` package exposing basic go hashing functions to flux scripts.
Included readme explains the functionality.
This proposal might require adaptions and is very much intended for discussion and extension as core maintainers see fit.
Done checklist:

feat(contrib/qxip): add contrib/qxip/hash package

---

libflux/go/libflux/buildinfo.gen.go
stdlib/date/date.flux

The `date.monthDay` documentation contained a table that should be in the `date.month` documentation. This PR fixes that.
Resolves #5364
---

chore(docs): move date.month table to correct function docs

---

libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/qxip/hash/README.md
stdlib/contrib/qxip/hash/hash.flux
stdlib/contrib/qxip/hash/hash.go
stdlib/contrib/qxip/hash/hash_test.go

This PR extends the `contrib/qxip/hash` package with additional functions for `sha1`, `base64`, `md5`, `hmac`
Note: The primary goal of this extension is powering flux native extensions dealing with auth token calculation etc. _(ie: s3 client we're working on)_ without having to use or import additional go code.

feat(contrib/qxip/hash): add sha1, md5, base64, hmac

---

array/array.go
array/array_test.go
array/binary.gen.go
array/binary.go
array/binary.tmpldata
array/builder.go
array/repeat.go
array/repeat_test.go
execute/executetest/allocator.go
execute/executetest/transformation.go
execute/format.go
stdlib/experimental/diff.go
stdlib/universe/group.go
stdlib/universe/moving_average.go

The optimized string array, which is used whan all column values are identical, was caching the string value that was passed to it. If this value came from an arrow String array then the string's data would be in the buffer backing that array. Once the array is finished with and freed the new string array containing the reference to the data buffer remains and prevents the entire buffer from being garbage collected.
The changes to the executetest package show that this is the case by scribbling over a buffer's memory when it is reported as free. This caused a number of tests to fail with strings that contain the data pattern rather than the expected result.
This could cause a correctness error if one uses a more sophisticated allocator that maintains a backing buffer. This would be a …

fix(array): use-after-free in optimized String array

---

libflux/go/libflux/analyze.go

Package path names may contain platform-dependent path separators, i.e. they can contain backslashes on Windows. This breaks SemanticPackages() on Windows, because it uses path.Dir() to extract a package name from a path. path.Dir() expects an all-slashes path, however.
Fix this be using filepath.ToSlash() before passing the path to path.Dir().
Fixes #5380

fix(libflux): Convert platform-dependent path separators to slashes

---

Dockerfile_build

Use a newer rust container to build flux, enabling dependencies to bulid correctly.

chore: update the version of rust used in the CI build

---

libflux/flux/src/cffi.rs
libflux/go/libflux/buildinfo.gen.go
libflux/go/libflux/parser_test.go

An audit discovered a few places where we could be more rigorous about checking inputs for valid data. This PR addresses the issues and adds tests for them.

fix: make C FFI more robust with respect to malformed input

---

libflux/flux/src/cffi.rs
libflux/go/libflux/buildinfo.gen.go

This PR builds upon my last PR #5408 to use the expected form of AST to hold an error produced my invalid UTF8. The function `flux_ast_get_error` wants the error to be in the base node of the first file, rather than in the package itself.
This produces a nicer error message when clients pass in Flux code with invalid UTF-8.

refactor: improve "error package" returned when bad UTF-8

---

libflux/flux-core/src/parser/mod.rs
libflux/flux-core/src/parser/tests/arrow_function.rs
libflux/flux-core/src/parser/tests/attributes.rs
libflux/flux-core/src/parser/tests/literals.rs
libflux/flux-core/src/parser/tests/types.rs
libflux/go/libflux/buildinfo.gen.go

Update all loops using self.more in the parser to detect if they get stuck attempting to process the same token multiple times. This has been observed to cause the parser to get into an infinite loop with some erroneus inputs.
The protection code was copied from the parse_array_items_rest and applied everywhere the parser could conceivably get stuck. It is not clear that it is possible to get stuck in all the places that the protection was added.

fix(flux-core): infinite loop protection in the parser

---

libflux/flux/src/lib.rs
libflux/go/libflux/buildinfo.gen.go

Closes: #5438
This a trivial patch to fix an issue with rust-1.72.0 (see linked issue).

fix: libflux build error on >= rust-1.72.0

---

execute/allocator.go
execute/table.go
execute/table_test.go

Update the string column builder to account for the memory for the string contents. This is part of an effort to reduce the prevelence of OOMs caused by unaccounted memory data See influxdata/idpe#18697.

feat(execute): allocate memory for string content.

---

array/array.go
array/repeat.go
arrow/arrow_test.go
csv/result.go
execute/executetest/allocator.go
execute/executetest/table.go
execute/table.go
execute/table/stringify.go
internal/arrowutil/array_values.gen.go
internal/arrowutil/compare.gen.go
internal/arrowutil/copy.gen.go
internal/arrowutil/filter.gen.go
internal/arrowutil/iterator.gen.go
internal/arrowutil/types.tmpldata
internal/moving_average/array_container.go
result_iterator_test.go
semantic/semantictest/cmp.go
stdlib/experimental/mqtt/to.go
stdlib/influxdata/influxdb/to.go
stdlib/kafka/to.go
stdlib/sql/to.go
stdlib/universe/distinct.go
stdlib/universe/key_values.go
stdlib/universe/mode.go
stdlib/universe/pivot.go
stdlib/universe/table_fns.go

Undo the main change introduced in #5377 so that by default strings returned from `array.Strings` use the internal memory of the stored data. This means that it is more likely that there are some cases of use-after-free errors in the flux executor, the trade-off being that there is less likely to be a proliferation of memory allocation due to string copying. Overall use-after-free errors will not cause incorrect results with regard to strings as they are read only and the Go runtime will only free the memory once the garbage collector has determined it is unused.
Dear Reviewer(s) :wave:, you are responsible (among others) for ensuring the completeness and quality of the above before …

feat: return to internal string references

---

go.mod
go.sum
values/dict.go

Newer versions of this package were changed to use generics, making them incompatible with the current code. Update to the newest version. This has the nice side effect of reducing the amount of type assertions.
Closes #5477

feat: upgrade github.com/benbjohnson/immutable

---

stdlib/influxdata/influxdb/source.go

Update the influxdb from command to support URLs with a trailing slash.

fix(stdlib): join path correctly in influxdb source

---

stdlib/universe/typeconv.go
stdlib/universe/typeconv_test.go

Avoid a panic if the bytes conversion function receives a string typed NULL value. The function now returns the same error as for other NULL values.

fix: null string to bytes conversions

---

stdlib/influxdata/influxdb/wide_to.go
stdlib/influxdata/influxdb/wide_to_test.go

Update the wideTo function to cope with tables with a null tag value. In these cases the tag is skipped when writing to influxdb.

fix(stdlib/influxdata/wideto): panic with null string key

---

libflux/flux/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

By inheriting the value of `strict` it is simpler to build `flux` in cases where warnings are acceptable without needing to patch the `flux-core` `Cargo.toml` or source.
The changes can be tested by adding a dead function to `flux-core` e.g. `fn dead_code() {}` and compiling `flux` with `--no-default-features`.

fix(libflux): only compile `flux-core` with `strict` if enabled in `flux`

---

execute/allocator.go
execute/table.go
execute/table_test.go

This reverts commit bea958616a673ef6b07bb9d469634d0134e900c9.
This PR attempted to reduce the amount of un-accounted memory use. In doing so it introduced a significant amount of data copying. This has made the performance unacceptable. Reverting this change in order to come up with a better plan.

fix: Revert "feat(execute): allocate memory for string content. (#5482)"

---

array/array_test.go
array/builder.go

Change the StringBuilder to only create an arrow builder when it becomes necessary. Whist the StringBuilder has only a single distinct value it will just record how long the array is. Creating an arrow.StringBuilder when a second distinct value is added.

fix: Make fewer copies when building a string array

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/formatter/tests.rs
libflux/flux-core/src/parser/strconv.rs
libflux/flux-core/src/parser/tests/literals.rs
libflux/flux-core/src/semantic/tests/vectorize.rs
libflux/flux/Cargo.toml
libflux/go/libflux/buildinfo.gen.go
rust-toolchain.toml

Update the rust version to 1.72, this is the earliest version that can be linked to musl 1.2.4.

build(deps): update rust version

---

Dockerfile_build

Update the version of Go used to build flux to go1.24. This version is still receiving security updates and is required for some newer packages that dependbot wants to merge.

build: Update the go version used to build flux

---

Dockerfile_build

Some of the rust components that are added to the build image need a newer rust version. Update the rust version used.

fix: use rust 1.85 in build image

---

go.mod
internal/cmd/influxql-decode/main.go
stdlib/internal/promql/date_functions.go
stdlib/internal/promql/empty_table.go
stdlib/internal/promql/histogram_quantile_test.go

Remove usage of now archived github.com/pkg/errors package with stdlib

chore(deps): replace usage of github.com/pkg/errors with stdlib

---

dependencies/iox/client.go
go.mod
go.sum

The github.com/influxdata/influxdb-iox-client-go module has been archived and is no longer receiving any updates. Flux depended on this simply for an enum-style type import. The ColumnType type in question has been copied into the flux code, removing the need for the dependency.

feat: remove influxdb-iox-client-go dependency

---

arrow/table_buffer.go
execute/table/buffered_builder.go
execute/table/buffered_builder_test.go

An empty arrow.TableBuffer can panic when calling Len() if it is in the process of being appended to by a table.BufferBuilder. Normally the TableBuffer maintains the invariant that the size of Columns is the same as the size if Values so to check one is equivalent to checkint the other. However when a BufferBuilder is merging buffers with different schema it will add new null-valued columns to the TableBuffer. This checks the TableBuffer.Len() between adding the column and adding the null-valued column.
In the case that the TableBuffer is empty, but the Columns array is a zero-length slice, rather than nil, a panic occurs.
There are two fixes here. Either of which fix the symptom, but both are worthwhile changes. TableBuffer.Len() now checks the length of the slice it is attempting to …

fix: panic in arrow table buffer

---

Dockerfile_build

A new relese of Debian (trixie) has recently been released and this is the version backing the go:1.24 base image. This new debian version does not have a libtinfo5 package, but instead has a libtinfo6 package. Update to use the new package.

build: Update libtinfo package version
