influxdata/flux

csv/result.go
csv/result_test.go
functions/testdata/drop_after_rename.out.csv
functions/testdata/drop_before_rename.out.csv
functions/testdata/drop_newname_before.out.csv
functions/testdata/drop_referenced.out.csv

This fixes the csv decoder so it recognizes and decodes the error
annotation.
Also fixes an error in the multi result decoder because it didn't share
the `csv.Reader` instance across results which caused buffered data to
be discarded.

fix: decode the error annotation in the csv format

---

planner/planner.go
planner/rules.go

Introduces two interfaces: `Rule` and `Planner`. `Rule` specifies a transformation rule between two equivalent query operations. `Planner` defines behavior for a rule-based planner.

interface for abstract transformation rules

---

docs/SPEC.md

I treated `join()` as a template where applicable, and included an example so semantics are clear.
Question: should the parameter name be called `streams` instead of `tables`?  This question applies to `join()` too.

Add Flux function `union` to SPEC

---

planner/logical_test.go
planner/plannertest/cmp.go
planner/plannertest/walk.go

This PR:
* Creates a query plan walker that traverses a plan in a depth-first fashion and visits each node exactly once
* Uses this walker to simplify query plan comparisons

improve query plan comparison

---

planner/logical.go
planner/plan_traversal_test.go
planner/planner.go
planner/plantest/cmp.go
planner/plantest/plan.go
planner/plantest/walk.go
planner/types.go

This is a straightforward renaming of `QueryPlan` to `PlanSpec`, so that when we alias imports in `control` and `execute` to use `planner` in place of `plan`, it tries to compile against our new plan structure.

Rename QueryPlan to PlanSpec

---

functions/inputs/buckets.go

In line with having a logical/physical split of influxdb-dependent sources, the logical parts of the proposed buckets() function will be placed here, while there will be separate implementations for each of platform/idpe  and influxdb.

 Moved logical parts of buckets() function to flux

---

compile.go
functions/transformations/yield_test.go
interpreter/interpreter.go

Fixes #103 
This commit fixes how the compiler compares TableObjects
and, as a result, how it constructs a Flux Spec. This
fixes an error where queries with multiple yields were
having all but one of those yields stripped during compilation.

fix how specs are constructed from table objects

---

control/controller.go
execute/executor.go
execute/executor_test.go
planner/heuristic_planner.go
planner/logical.go
planner/logical_test.go
planner/physical.go
planner/physical_test.go
planner/plantest/plan.go
planner/types.go
planner/walk_test.go

* Remove yields during physical planning
* Build execution graph assuming no yield nodes
* Update `plantest` with a `LogicalPlanSpec` and `PhysicalPlanSpec` for testing both phases

remove yields from physical plan

---

bounds.go
bounds_test.go
execute/executor.go
functions/transformations/range.go
functions/transformations/shift.go
planner/bounds.go
planner/bounds_test.go
planner/logical.go
planner/logical_test.go
planner/physical.go
planner/plantest/cmp.go
planner/registration.go
planner/types.go

This PR gives a `PlanNode` time bounds. Originally I had tried to make bounds plan node statistics. However, because the execution engine uses the bounds associated with each plan node, the execution engine would also have to have access to input statistics for each node. To go that direction would require more design, so instead I made bounds a property of the node itself. Thoughts?

give plan nodes bounds

---

compile.go
compiler/compiler_test.go
compiler/runtime.go
complete/complete_test.go
csv/result.go
execute/executetest/table.go
execute/group_key_builder_test.go
execute/group_lookup_test.go
execute/row_fn.go
execute/table.go
functions/inputs/from_generator.go
functions/transformations/data_test.go
functions/transformations/histogram.go
functions/transformations/map.go
functions/transformations/range_test.go
functions/transformations/schema_functions_test.go
functions/transformations/schema_mutators.go
functions/transformations/set.go
functions/transformations/shift.go
functions/transformations/system_time.go
functions/transformations/typeconv.go
functions/transformations/window.go
functions/transformations/window_test.go
interpreter/interpreter.go
interpreter/interpreter_test.go
spec_test.go
values/binary.go
values/values.go
values/values_test.go

The values package will now construct values with `NewXXX` instead of
`NewXXXValue`. The `Value` at the end was redundant since this is in the
`values` package. It also modifies the `NewValue` function to just take
the interface and infer the type from that.

refactor: simplify the values package

---

compiler/compiler_test.go
csv/result.go
execute/group_key_builder.go
execute/row_fn.go
execute/table.go
functions/transformations/join.go
functions/transformations/map.go

Some of the current code was reusing switch statements that were already
placed into utilities to avoid requiring the switch statement to be
used. We should minimize the use of switch statements on the type to
only places that need the actual type for whatever reason to make the
code easier to follow.

refactor: use AppendValue in more places where it is useful

---

array/base.go
array/bool.go
array/float.go
array/int.go
array/string.go
array/time.go
array/uint.go
internal/staticarray/bool.go
internal/staticarray/doc.go
internal/staticarray/float.go
internal/staticarray/int.go
internal/staticarray/string.go
internal/staticarray/time.go
internal/staticarray/uint.go

The interfaces here match pretty closely with the equivalent arrow array
type and will act as a suitable interface between the two. Some
algorithms may have to type switch for performance reasons, but these
interfaces should work in most scenarios to abstract away the current
way that data is being stored.
This commit does not migrate to using those interfaces. It creates the
interface so we can begin integration and it provides an internal
package that implements the interface using slices (like the current
implementation uses).

feat: add interfaces for reading array data

---

functions/outputs/to_http.go
internal/pkg/syncutil/wait_group.go

The `to_http` function did not report some errors during execution.
This commit also adds a utility package for wait groups that involve
errors. You can launch a goroutine on a function that returns an error
and it will return the first error that happens when invoking wait. In
the normal standard library, this functionality can be difficult to
achieve because it then has to rely heavily on closures.

fix: to_http will return any errors that happen during execution

---

functions/transformations/filter.go

A cyclic dependency was introduced between the `transformations` and `inputs` packages. This is the fix.

remove cyclic dependency bug

---

influxql/decoder.go
influxql/decoder_test.go
influxql/response.go

The json decoder will decode the influxql json format and allow it to be
used as a result decoder. This will make it easy to integrate it as an
alternative source method similar to `fromCSV`.
Fixes #138.

feat: add an influxql json decoder as a library

---

functions/inputs/from.go
functions/inputs/from_test.go
plan/plantest/plan.go

Fixes #214 
This enables push down of `group` and `distinct` so queries like the following can work:
```
from(bucket:"telegraf") 
|> range(start: -1d)
|> group(by: ["_measurement"]) 
|> distinct(column: "_measurement") 
|> group(none: true)
```

Use planner rule to enable no-points optimization in storage

---

functions/transformations/join.go

This addresses a panic that's been occurring in `queryd` in the 2.0 cloud.
The offending query sent to the transpiler was this one:
```sql
select 
SUM(inodes_free) as sum1,
SUM(inodes_total) as sum2
FROM "disk" 
WHERE mode = 'rw' 
AND (device = 'disk1s1' OR device = 'disk1s4' OR device = 'disk2s1') 
AND fstype != 'hfs' 
AND time >= '2018-11-01 12:00:00' 
AND time < '2018-11-01 13:00:00' 
GROUP BY device
```
With this fix in place, the code no longer panics, but instead produces this error: `unsupported aggregate column type string`.
Previously we were panicking before getting the planner, and now we're getting to execution, so this is progress.

Don't use non-exported OperationSpec field outside of parsing codepath

---

functions/inputs/from_test.go
plan/format.go
plan/logical_test.go
plan/types.go

This adds log output for plans when the `Verbose` flag is set in the Controller.  Output looks like this:
```dot
digraph {
from0
range1
filter2
filter3
group4
sum5
generated_yield
from0 -> range1
range1 -> filter2
filter2 -> filter3
filter3 -> group4
group4 -> sum5
sum5 -> generated_yield
}
```

Implement Formatted for plans

---

control/controller.go

When a query is requeued multiple times, it will return an error on the
second attempt. This is because it tries to transition into the
requeueing state, but it's already in that state so there is nowhere to
go and it thinks a fatal error has happened.
This fix patches things so if it is already in the requeueing state it
does nothing.
Fixes #239.

fix(control): fix when a query is requeued multiple times

---

compile.go
interpreter/interpreter.go
interpreter/interpreter_test.go
semantic/walk.go

This PR addresses a bug that was discovered through #216 .
Previously when evaluating a Flux program, type inference would infer the types of all expressions in the program and store them in a `TypeSolution`. However a `TypeSolution` was tied to a single instance of the Flux interpreter, and Flux programs use at least two distinct instances of the interpreter - one for builtin evaluation and one for program evaluation. Whenever a new interpreter was instantiated the previous `TypeSolution` was effectively discarded.
This PR adds a `TypeScope` object that is passed to a new Flux interpreter as a way to keep the `TypeSolution` information from previous builtin evaluations.

type scope for interpreter

---

time.go
time_test.go

Add some unit tests for time marshaling and unmarshaling to ensure that
it works properly. Additionally, this modifies the time struct unmarshal
process so it doesn't modify the struct if unmarshaling fails.

tests: add tests for time marshaling and unmarshaling

---

control/controller.go
control/controller_test.go
csv/result.go
execute/aggregate.go
execute/allocator.go
execute/executetest/allocator.go
execute/executor.go
execute/selector.go
execute/table.go
execute/transformation.go
functions/inputs/from_generator.go
functions/transformations/join.go
functions/transformations/percentile.go
influxql/decoder.go
memory/allocator.go
memory/allocator_test.go
mock/executor.go

This allocator is a simplification of the existing allocator in the
execute package, but moved to a new package for simplicity and without
the default panic behavior or array manipulation primitives. This
creates a lower surface area for the implementation and allows it to
focus on just tracking memory usage rather than also on array
manipulation.
The simpler interface allows us to integrate this with other allocators
like the arrow allocator which has no use for the array primitives in
the existing allocator.

feat: create memory package with a memory allocator

---

array/base.go
array/bool.go
array/float.go
array/int.go
array/string.go
array/time.go
array/uint.go
array/value.go
internal/staticarray/bool.go
internal/staticarray/constants.go
internal/staticarray/float.go
internal/staticarray/int.go
internal/staticarray/string.go
internal/staticarray/time.go
internal/staticarray/uint.go

The staticarray package did not use the allocator so it would not track
memory usage. The table builder will track usage so this adds that
functionality to these utilities so the two are equivalent.

feat: staticarray supports using the allocator for tracking memory usage

---

cmd/flux/main.go
control/controller.go
csv/result.go
csv/result_test.go
influxql/decoder.go
query.go
querytest/execute.go
repl/repl.go
result_iterator.go

The ResultIterator interface had a Cancel method, but it was mostly used
to free resources and ResultIterator was used asynchronously. This
solidifies the API and removes the cancel connotation of the method name
to have a resource release connotation instead.
This also fixes things so that the Query interface is used correctly by
all ResultIterator implementations to always call `Done()` at least
once.

refactor: rename ResultIterator.Cancel to ResultIterator.Release

---

cmd/flux/main.go
querytest/execute.go
result_iterator.go

The query result iterator should not take a context. The context passed
to Query should be the one that controls whether or not a query gets
canceled.
This reverts the API back, but keeps the cancel stuff removed since
cancel was never used for actually canceling a query. The context was
always used for that.

fix: revert the change to query result iterator

---

values/binary.go
values/binary_test.go

Previously, `x < y`, `x <= y`, `x > y`, and `x >= y` were rejected when
x and y were both strings. Now they are accepted, and they operate on
lexicographic comparison like any other language.

feat: add support for string comparison operators

---

parser/gofuzz.go

The Fuzz method is added to a separate file with the `gofuzz` tag so it
is not included in non-gofuzz builds. The Fuzz method is not considered
part of the public API.

feat: add Fuzz method for go-fuzz into the parser

---

functions/transformations/covariance.go
functions/transformations/testdata/covariance_missing_column_1.flux
functions/transformations/testdata/covariance_missing_column_1.in.csv
functions/transformations/testdata/covariance_missing_column_1.out.csv
functions/transformations/testdata/covariance_missing_column_2.flux
functions/transformations/testdata/covariance_missing_column_2.in.csv
functions/transformations/testdata/covariance_missing_column_2.out.csv

The covariance function would panic if one of the columns that were
referenced did not exist. This checks for that and returns an error
instead of panicking.
Fixes #240.

fix: return error in covariance when a column doesn't exist

---

control/controller.go
control/controller_test.go

The parent span is closed when entering a final state and removed to
signal that it has been finished and to prevent it from being finished
multiple times. But, it did not copy the duration to the statistics and
instead tried to read the statistics from a nil span.
It now copies the total duration when the span is closed.

fix: controller statistics should not panic

---

internal/parser/parser.go
internal/parser/parser_test.go

It includes the NewAST method which would replace the old one and it
mocks out the expected interface from the scanner. It introduces a
mock scanner so that the parser is testing only the parser rather than
the parser and the scanner.

feat: introduce the parser package and outward interfaces

---

internal/parser/parser.go
internal/parser/parser_test.go

We have decided that `Scan` and `ScanWithRegex` will be used instead so
switching the interface to use that.

fix: switch the scanner interface for the parser

---

execute/executetest/result.go
execute/executetest/table.go
execute/executetest/transformation.go
go.mod

Related to #236 .
This PR exposes some utility functions for comparing Flux tables for equality. All values are compared for exact equality except floating point values - they are compared using a combination of absolute tolerance and ULPs (units in the last place).
When two values fail an equality comparison, a table formatter along with an appropriate error message is returned. This allows the caller of the function to print out both formatted tables along with the row and column number where the equality comparison failed.

compare flux tables for equality

---

control/controller.go
control/controller_test.go

Closes #306 .
Closes #311 .
Cancelling a query's context during execution will cause that query to return and any blocking ResultIterator calls will become unblocked. The PR adds a test case to the controller to assert that this does indeed happen. The godoc for `Ready()` is also updated to reflect this.
Note: If a query's context is cancelled mid-execution, that query should expose an appropriate error via its `Err()` method. See the godoc for:
https://github.com/influxdata/flux/blob/e4b1864ea4e87065fa23c178e178c6dd97f93d37/control/controller.go#L499
This currently is not the case. The TODO for this behavior has been added to the most recent test case:
https://github.com/influxdata/flux/blob/e4b1864ea4e87065fa23c178e178c6dd97f93d37/control/controller_test.go#L298

cancelling query context stops execution

---

interpreter/interpreter_test.go
semantic/poly_types.go

This PR fixes #226 . However it seems to add a lot of mental gymnastics to the logic for unifying function types in the presence of pipe arguments. Perhaps this logic could be moved to the constraint phase of type inference? Not sure yet.

more restrictions for function type unification

---

internal/parser/grammar.md
internal/parser/parser.go
internal/parser/parser_test.go
parser/parser_test.go

The new parser uses the new scanning package to parse the flux AST. The
parser is constructed as a collection of various state machines that
match a pattern of tokens into an AST construction.
It passes all of the tests for the original parser.
This parser does not handle errors yet. We are still working on how we
wish to represent errors in the AST and a future commit will handle both
errors and position information for the AST.

feat: initial pass at the new parser

---

execute/executetest/result.go
result.go

The stats PR (https://github.com/influxdata/platform/pull/1265) required some refactoring to avoid race conditions. One necessary change was to expose stats from the `TableIterator` so `platform` could read stats after `Close()` instead of during iteration.

fix: Add TableIterator.Statistics()

---

control/controltest/controller.go
querytest/execute.go

controltest.Controller associates a finalizer with returned queries,
which panics if Query.Done is not called.
When triggered, this panics with a stack trace of where the query was
created, which pinpoints exactly where there is a missing Done call.
This is not a complete solution, because short tests may not trigger a
garbage collection; see also #328.

feat(control/controltest): add controltest.Controller

---

internal/parser/parser.go
internal/parser/parser_test.go
internal/scanner/scanner.go
internal/token/fileset.go

The parser fills out the base node for each AST production with
information from the scanner and token fileset.
This information will likely require a refactor at some point to make
it more like the `go/ast` package as a lot of extra information (like
symbol positions) gets dropped on the floor, but this should get us to
feature parity with the existing parser.

feat: record all position information for nodes generated by the parser

---

internal/parser/parser.go

A literal may fail to parse when it is syntactically valid, but does
something like overflowing an integer. We will need to handle these more
gracefully in the future.

fix: do not panic when literals fail to parse

---

internal/scanner/scanner.gen.go
internal/scanner/scanner.go
internal/scanner/scanner.rl
internal/scanner/scanner_test.go

The state machine was not being reset in between runs correctly. The
initialization needs to happen on every iteration of the machine and not
just the first one. This caused a problem when a previous action had
been selected and the state machine went into an error mode. It would
return an empty token instead of recognizing the state machine had
errored.

fix: ensure the scanner state machine is initialized correctly

---

internal/parser/parser.go

The previous implementation used `parseExpression` because it was easier
to do that than to read the identifier, read the next token, and then
try to inject the identifier into the expression parsing stack.
After this was written, `parseExpressionSuffix` was added for another
part of the grammar. It is more correct to use that function here since
it is referenced in the EBNF.
It should be functionally the same.

fix(parser): fix the ident statement to use expression suffix

---

internal/parser/grammar.md
internal/parser/parser.go
internal/parser/parser_test.go

The unary logical expression covers the `not` keyword so that it can be
used more easily. The following expression may be used:
not -1 == a
In the previous parser, `not` had the same precedence as the prefix
operator so it would be parsed as:
(not (-1)) == a
This seems obviously incorrect. The `not` keyword has now been placed
right above `and` and `or` in the operator precedence and below
everything else so the above is now parsed as:
not ((-1) == a)
This is more intuitive.

fix(parser): add unary logical expression to the parser

---

parser/doc.go

This removes the mention of the PEG parser and removes the mention at
all of how the parser is implemented. That is an implementation detail
anyway.

docs(parser): update the godoc for the parser

---

ast/ast.go
ast/asttest/cmpopts.go
ast/format.go
ast/json.go
ast/json_test.go
ast/walk.go
internal/parser/parser.go
internal/parser/parser_test.go
semantic/analyze.go
semantic/graph_test.go

There is only one type of function expression remove the redundant
description Arrow from the name.

refactor: rename ArrowFunction* -> Function

---

functions/inputs/from_test.go
plan/plantest/plan.go
plan/plantest/rules.go

update from_test.go to use new rule test helper
The rule tests in `from_test.go` were getting unwieldy, and soon we will want to test rules for other types of operations, so I refactored this.

test(plan): add RuleTestCase and helper method to package plantest

---

execute/executetest/output.go
execute/executor.go
execute/executor_test.go
plan/logical.go
plan/registration.go

Fixes https://github.com/influxdata/platform/issues/1311
Output or side effect producing functions operate as pass-throughs.
They don't transform the data they consume. They perform their
intended side effect and then pass the data along to the next
transformation.
Previously if an output function was a terminal node in a plan,
a result transformation was not generated for that plan. All
queries must have an associated result transformation, otherwise
the query context will be cancelled immediately and execution
will be cancelled before any work for the query has been done.
With this fix, a result transformation is generated for every
terminal node in a plan. Queries with terminal output functions
will now perform their side effects before the query returns.
Note that terminal output …

fix(execute): terminal output functions must produce results

---

functions/inputs/from.go
functions/inputs/from_test.go

Storage can only group by tag keys, so Flux will need to evaluate
grouping operations over `_value` or `_time`.
Fixes #349

fix(functions): suppress group push down for _time and _value

---

semantic/constraints.go
semantic/inference_test.go

Fixes #263.
Type inference replaces any external free type variables with new
fresh type variables. The result is a new but completely equivalent
type expression. Previously during the substitution process
collisions could occur between the names of old type variables and
the names of the new freshly generated type variables. This would
render the new type expression invalid.
To remedy this problem, fresh type variables are now generated
before being substituted into the original type expression. If
there is a collision, that type variable is discarded and a new
one is generated.
Note: Not sure how to create a test case for this. Although the flaky test from #263 that this
PR fixes is no longer flaky.

fix(semantic): collision between external and fresh type vars

---

docs/SPEC.md
execute/allocator.go
execute/table.go
execute/table_test.go
functions/transformations/assert_equals.go
functions/transformations/assert_equals_test.go
functions/transformations/helpers.go
functions/transformations/testdata/simple_max.flux
functions/transformations/testdata/simple_max.out.csv

* added assertEquals, as well as extensions to the execute package to support the feautre.
* added builtin helper function testingTest to cover common usage of assertEquals
* updated functions/transformations/simple_max.flux to demo testingTest usage.
* added unit tests for assertEquals
closes #358

feat(transformations): add function assertEquals to transformations

---

cmd/flux/main.go
control/controller.go
control/controller_test.go

Previously planner errors would be returned at runtime, even though
execution had not yet begun.  This change makes it so that errors will
be returned (with http error code 400) for unplannable queries.
Fixes #149

fix(control): make controller return planner failures

---

docs/VirtualMachine.md

This PR adds a document on a proposed virtual machine implementation of Flux.
It is written as if the virtual machine already exists. I will use this PR comment to discuss how this differs from the current design and its strengths and weakness.
The current design at a high level looks like this:
```
Flux Source Code -> AST -> Semantic Graph -> Query Spec -> Plan -> Execution
```
The parser produces the AST, the analyzer produces the semantic graph, the interpreter produces the spec, the planner produces the plan and the query engine executes the plan.
Currently external systems can submit programmatically generated queries by generating  Flux source code or by generating a query spec to execute a query. For example the transpiler directly produces the query spec and submits it for …

docs: Add rough draft of virtual machine design

---

docs/SPEC.md

The virtual machine design removes the abstraction between the query specification and Flux functions acting as transformations. I have updated the wording in the SPEC accordingly.
Also I documented how many of the pure built in helper functions now work since they are no different from Go backed builtins.

docs(SPEC): update SPEC for virtual machine design

---

internal/scanner/Makefile

The problem is that the Makefile target for generating the scanner had
`unicode.rl` as a dependency in it. This file gets generated by the same
command so I didn't want to include it twice because then we would call
`go generate` twice. Since `unicode.rl` is an intermediate output,
removing it from the list of inputs and keeping `unicode2ragel.rb` as an
input works for the intended purpose.
Fixes #380.

fix(scanner): makefile for generating the scanner after clean was incorrect

---

plan/heuristic_planner_test.go
plan/physical.go
plan/plantest/rules.go
plan/types.go
plan/yield.go

Currently the physical planner never actually produces physical nodes.  It just inherits the logical nodes from logical planning.  This commit addresses that, by adding a rule that does the conversion.
Currently all of our procedure specs are both logical and physical because they implement a `Cost` method, so this is just a refactoring with no change in behavior.  The next step will be to separate `from` into distinct logical and physical procedure specs.

refactor(plan): make physical planning convert logical nodes to physical

---

control/controller.go

This commit cancels all queries if a shutdown has occurred but has not completed before `ctx.Done()` returns. This can occur when a long running query is executing during shutdown.

fix(control): Cancel all queries after timeout elapses.

---

functions/inputs/from.go

Sometimes it happens that the planner cannot push `range` to storage and complains that the query is unbounded:
```
result from0 is unbounded. Add a 'range' call to bound the query
```
Now the message helps the user to better understand what's happening and proposes solutions:
```
impossible to bound results from "telegraf/autogen" (from0).
Add a 'range' call to bound the query or move any 'range' call as close as possible to 'from'
```
Fixes #302

refactor(inputs): better error message for unbounded from

---

arrow/bool.go
arrow/float.go
arrow/int.go
arrow/string.go
arrow/uint.go
execute/executetest/table.go
execute/table.go

This adds utility methods for converting a slice into an arrow array
buffer. These implementations were previously inside of the
`ColListTableBuilder` and have now been exposed for other
implementation to use.
This also updates the `executetest` package to implement `DoArrow`. This
was previously missed and would cause any test that used arrow buffers
to fail with a panic.

feat(arrow): add utility methods for converting a slice into an arrow array buffer

---

arrow/col_reader.go
execute/table.go

This was previously an internal package but it would be useful in the
other projects during the migration.

refactor(arrow): export the ColReader wrapper for ArrowColReader

---

internal/parser/parser.go
internal/parser/parser_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

A set of unbalanced parenthesis caused the new parser to eventually hit
an EOF while it was looking for it. Because it assumed it found the
right parenthesis, it advanced the end position beyond the end of the
slice and caused a runtime panic.
This change does two things:
1. It verifies that the EOF token will have the proper position information.
2. The parser uses the literal length returned by `expect` when finding the end position.

fix(parser): do not panic with unbalanced parenthesis

---

ast/ast.go
ast/format.go
ast/format_test.go
internal/parser/parser.go
internal/parser/parser_test.go

Byte values in strings are now fully unescaped.
Fixes #544

feat(parser): add tests for multi-line and escaped strings

---

execute/row_fn.go
execute/table.go
functions/transformations/filter.go
functions/transformations/map.go
functions/transformations/state_tracking.go

These three functions all use row predicates so they are related to
each other. They have been converted over to use arrow buffers instead
of the old column reader.
Fixes #497, #509, and #523.

refactor(functions): convert filter, map, and state tracking to use arrow

---

arrow/bool.go
arrow/float.go
arrow/int.go
arrow/string.go
arrow/uint.go

Using `int` is more common than `int64` for lengths so, even if arrow
uses `int64`, the slice lengths should still use `int`. Additionally,
the arrow `Len()` method for slices uses `int` as the return value so
this is better for that anyway.

refactor(arrow): switching the slice utilities to use int instead of int64

---

functions/inputs/buckets.go
functions/outputs/to_http.go
functions/outputs/to_kafka.go

This addresses issues about "failed to create physical plan" in
input/output functions.  This was not caught earlier because there
are no end-to-end tests for input/output functions.
Fixes #584

fix(functions): embed plan.DefaultCost in input and output functions

---

functions/transformations/window.go

Fixes #530.
There are some inconsistencies between the SPEC and the code in `window.go`.  I don't have enough context to know what parameters are required, so I'm just submitting this PR to progress with the Arrow refactoring.  I will file a separate issue for updating `window` parameters and the SPEC.

refactor(functions): Make window() use arrow buffers

---

docs/SPEC.md

I originally planned on mentioning the default for difference's columns,
but I noticed derivative and distinct nearby had some missing defaults
as well. The default values I used were pulled directly from the code
for those functions.

docs(SPEC): mention more defaults

---

control/controller.go
control/controller_test.go

There were a few problems in the controller shutdown test that caused it
to be flaky.
First, it didn't wait for all 10 queries to get into the controller
queue before checking the queue length. This caused it to call `Fatal`
and abort the test, but `Shutdown` had already been called and the
active queries needed to be finished.
After that, it attempted to run a query before the shutdown may have
been initiated so the query got enqueued correctly even though it was
not expecting that to happen. It now attempts to create the query and
tries multiple times to get the failure with a wait in between if it
can't.
It now succeeds when run with the following command line:
go test -c ./control
cpulimit -z -i -l 100 ./control.test -test.v -test.cpu 1
I was able to reproduce the issue by using the …

fix(control): fix a flaky test in the controller shutdown

---

ast/ast.go
ast/asttest/cmpopts.go
ast/edit/option_editor_test.go
ast/errors.go
ast/errors_test.go
ast/format_test.go
ast/json.go
ast/walk.go
compile.go
internal/parser/parser.go
internal/parser/parser_test.go
interpreter/interpreter_test.go
interpreter/package_test.go
parser/gofuzz.go
parser/parser.go
repl/repl.go
semantic/inference_test.go
semantic/package_test.go
spec_test.go

The `Check` function will annotate the AST with errors in the AST
construction. The parser will be modified to make a best effort to
produce an AST, but it will produce an invalid AST when it gets an
invalid input.
The `GetErrors` method will traverse the AST and report any errors it
finds within the AST construction that were added a result of `Check`.
Related to #305.

feat(ast): add a function for checking for errors within the AST

---

arrow/arrow_test.go
arrow/bool.go
arrow/float.go
arrow/int.go
arrow/string.go
arrow/uint.go
execute/executetest/aggregate.go
execute/executetest/table.go

If the memory allocator is nil, that means we don't care to track the
memory usage and it will pass the default go allocator directly instead
of acting as a proxy.

fix(arrow): allow the memory allocator to be nil for arrow arrays

---

execute/executetest/table.go

The memory allocator is now optional for the arrow builders so we can
pass nil if we don't care to track memory usage.
This functionality was added in #610, but this code was added after the
PR was tested so this specific test code wasn't caught and changed.

fix(execute/executetest): remove unneeded use of memory allocator

---

ast/ast.go
internal/parser/parser.go
internal/parser/parser_default.go
internal/parser/parser_test.go

This change embeds errors into the AST when it is produced by the
parser.
Ideally, we want to have the parser generate the best AST it can and the
current parser doesn't do that. But, making that parser will take too
long at the current moment and we still need to record when we see an
invalid token. This change modifies `expect()` to record that it saw the
wrong token and then continue doing what it was already doing. When a
node is materialized, these aggregated errors are attached to the node.
Expect this functionality to change in the future while the mechanisms
for accessing errors will stay the same. This method does not give very
informative error messages and also does not retain the ability to
recreate the source code from the AST, but it does tell you if there's
a valid or …

feat(parser): embed errors into the ast from the parser

---

docs/SPEC.md

According to the official SPEC we are following the empty string indicates a `null` value. It is not possible to distinguish an empty string from a `null` when the column type is a string type. 
See https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#dfn-core-annotations scroll down to the `null` annotation bullet under the `4.3 Columns` heading.

docs(SPEC): specify nulls in the csv format

---

compile.go
compiler/runtime.go
csv/result.go
csv/result_test.go
execute/executetest/table.go
execute/group_key.go
execute/group_lookup_test.go
execute/row_fn.go
execute/table.go
functions/transformations/histogram.go
functions/transformations/typeconv.go
interpreter/interpreter.go
interpreter/interpreter_test.go
interpreter/package_test.go
result.go
values/array.go
values/function.go
values/object.go
values/values.go
values/values_test.go

feat(csv): treat omitted values with no defaults as null in csv

---

ast/format.go
ast/format_test.go

When a package is composed of multiple files, the flux script is formatted by appending the content of each AST and preceding with a comment containing the file name. This fix add newline in between each file.
Before:
```
package foo
// a.flux
a = 1// b.flux
b = 2
```
After:
```
package foo
// a.flux
a = 1
// b.flux
b = 2
```

fix(ast): prettier formatting for package

---

docs/SPEC.md
execute/table.go
execute/table_test.go
functions/transformations/cumulative_sum.go
functions/transformations/data_test.go
functions/transformations/derivative.go
functions/transformations/difference.go
functions/transformations/group.go
functions/transformations/group_test.go
functions/transformations/keys.go
functions/transformations/pivot.go
functions/transformations/pivot_test.go
functions/transformations/schema_functions.go
functions/transformations/state_tracking.go

feat(execute/table): Refactored the table builder interfaces to support null value creation.

---

docs/SPEC.md
functions/transformations/filter_test.go

This test does not validate that a null value is actually used as part
of the function. It only asserts that if a null value is in a row that
it will get copied over if the row passes the filter.
Evaluating nulls in functions will be part of a different issue.
Fixes #674.

test(functions): add test confirming that filter works with null values

---

functions/transformations/map.go
functions/transformations/map_test.go

The map eval does not support null yet and that is a separate issue.
Since all of the columns that aren't part of the group key are produced
by the result of the function, this doesn't include a test for that.
It does test if `mergeKey: true` is set and the value is null.
Fixes #682.

test(functions): add unit test for nulls in map

---

docs/SPEC.md
stdlib/universe/histogram_quantile.go
stdlib/universe/histogram_quantile_test.go

If a null value is found while reading the histogram in
`histogramQuantile`, an error will be returned.
Fixes #670.

refactor(functions): error on null values in histogramQuantile

---

stdlib/universe/group_test.go

Added test that panics because:
```
panic: column _value:float is not of type int
```
For now it is skipped, it should pass once #439 has been fixed.  
The test has been added to have a concrete piece of code that refers to that particular bug for future reference.

fix(universe): adding test for type mismatch in group

---

internal/gen/input.go

This library acts similar to inch, but it generates data for multiple
types (instead of only float) and can be customed to mix data types and
add additional tags.
It generates a `flux.ResultIterator` but also has a utility to generate
the csv string for use in tests.

feat(gen): added a new utility library for generating test data

---

docs/SPEC.md
execute/aggregate.go
execute/aggregate_test.go
execute/executetest/aggregate.go
stdlib/universe/count.go
stdlib/universe/count_test.go
stdlib/universe/mean.go
stdlib/universe/mean_test.go
stdlib/universe/percentile.go
stdlib/universe/percentile_test.go
stdlib/universe/skew.go
stdlib/universe/skew_test.go
stdlib/universe/spread.go
stdlib/universe/stddev.go
stdlib/universe/stddev_test.go
stdlib/universe/sum.go
stdlib/universe/sum_test.go

fix(stdlib): count nulls in the count aggregate

---

docs/SPEC.md
execute/table.go
stdlib/universe/sort_test.go

When sorting, null values are always first so they are less than in
ascending mode and greater than in descending mode. This is to match
with the behavior of SQL.
Fixes #652.

refactor(stdlib): add null support to sort

---

stdlib/universe/limit_test.go

Fixes #664 
Is it ok to return the `N` records let them be null or not?  
Should I add an option for discarding null values from the count?

refactor(functions): add test confirming that limit works with null values

---

docs/SPEC.md

Fix the outdated example to use group(columns) instead.

docs(SPEC): fix examples with group(by)

---

execute/group_key.go
execute/group_lookup_test.go
result.go
stdlib/testing/end_to_end_test.go
stdlib/testing/testdata/show_all_tag_keys.flux

This PR changes the sort order of group keys to match the order of series keys emitted from InfluxDB.
In InfluxDB series keys are sorted in lexicographic order. Currently in flux however grouping keys are sorted first by the number of columns and then only lexicographically if both keys have the same number of columns.
For example, InfluxDB stores the following series keys in this order:
```
_f=temp,_m=cpu,region=east,server=a
_f=temp,_m=cpu,region=east,server=a
_f=value,_m=cpu,region=west,server=a,yaba=dabadoo
_f=value,_m=cpu,region=west,server=b
```
However, Because flux currently considers the number of columns in keys before looking at those column names, it will re-sort these keys to the following:
```
_f=temp,_m=cpu,region=east,server=a
_f=temp,_m=cpu,region=east,server=a …
```

refactor(execute): change sort order of group keys to match InfluxDB

---

execute/table.go
stdlib/testing/testdata/derivative.flux
stdlib/testing/testdata/fill_time.flux
stdlib/testing/testdata/increase.flux
stdlib/universe/derivative.go

The previous code had a typo that caused it to compare the right buffer
to the right buffer for time columns which meant that time columns were
never actually checked when comparing tables.

fix(execute): check for equality in time columns correctly

---

internal/scanner/scanner.go
internal/scanner/scanner_test.go

When an invalid utf8 sequence was encountered, a `RuneError` would be
returned. When this was passed to `fmt.Sprintf("%c")` it would return a
string of size 3 and this size was used instead of the size of 1 that
the scanner actually read.
This fixes the scanner so instead of using `fmt.Sprintf("%c")`, it just
believes the size that was returned by the `utf8.DecodeRune` call and
references the byte slice from the source.

fix(scanner): handle rune errors correctly when decoding an illegal token

---

execute/executetest/transformation.go
stdlib/universe/pivot_test.go

If a `Test*_Process` expected an error, that should happen at the first input table processing iteration, otherwise the test failed with `expected error, got none`.
Now the helper performs the processing, and later checks for the error.
The test for `pivot` has been moved because it was a check on the function arguments and not on the `Process` function. It passed because it provided no data and `Process` wasn't invoked, so, `got == want == nil`. The error provided wasn't checked.

fix(executetest): process test helper had bad logic to check for errors

---

execute/table.go
stdlib/universe/group_test.go

Must be merged after #877, the second commit is the relevant one.
Fixes the Flux side of #321 by checking column types when columns are added to an existing table and returning a meaningful error if they have the same label and different type.
Still, the InfluxDB side of #321 has to be fixed.

fix(execute): check for schema collision when appending columns to a table

---

stdlib/testing/testdata/window_null.flux

It used the `testFn = testing.test` trick because calling it directly
was broken at the time the test was created. This removes that.

refactor(stdlib): fixup the window null test

---

docs/SPEC.md
internal/parser/grammar.md
internal/parser/parser.go
internal/parser/parser_test.go

The multiplicative operators are a higher precedence, but were accidentally put in the EBNF at a lower precedence. This adds a precedence table to the docs and fixes the EBNF so multiplication/division are higher precedence than addition/subtraction.
Fixes #903.

fix(parser): multiplicative operators are above additive operators in precedence

---

cmd/flux/cmd/execute.go

Command to execute a script without passing through the repl.
E.g.
```
$ flux execute 'import "generate"
generate.from(start: 1993-02-16T00:00:00Z, stop: 1993-02-16T00:03:00Z, count: 5, fn: (n) => 1)'
```
Or:
```
$ flux execute @./query.flux
```

feat(cmd): execute command

---

ast/strconv.go
internal/parser/parser.go

The literal parsers take the raw literal that is tokenized by the
scanner and returns the appropriate value type to be used with the ast
literals.
Fixes #921.

feat(ast): expose literal parsers used within the parser

---

execute/executetest/transformation.go
stdlib/testing/assert_empty.go
stdlib/testing/assert_empty_test.go
stdlib/testing/assert_equals.go
stdlib/testing/diff.go
stdlib/testing/diff_test.go
stdlib/testing/end_to_end_test.go
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

This modifies `testing.test` to use `testing.diff` and a new
`testing.assertEmpty` function.
Diff has now been modified so it does not emit a table when the table is
empty and `assertEmpty` will return an error when one of the tables is
not empty. `testing.test` has been modified to include a yield and the
end to end tests have been modified to use the console-friendly
formatter so any output from `diff` will be output with the test
failure.

feat(testing): add assertEmpty method and use it with testing.test

---

execute/row_fn.go
execute/row_fn_test.go

`rowFn` evaluation returns an error when referencing a null value. This prevents a panic when a lambda references a null value and logs the error instead.
This PR also adds testing for `rowFn`.

fix(execute): skip lambda evaluation when referencing nulls

---

ast/format.go
ast/format_test.go

The member expression should be closed by `]`, but it was accidentally
closed with `[`.

fix(ast): member expressions using a string literal use the incorrect end bracket

---

cmd/flux/cmd/compile.go

This PR introduces a `compile` subcommand that translates a flux script into a spec.

Add compile subcommand that compiles flux to spec

---

ast/edit/option_editor.go
ast/edit/option_editor_test.go

This adds a key to options if the key doesn't already exist in the option instead of erroring.
Closes #974 
- [x ] Test cases written

bug(options): Add key instead of erroring when option doesn't have key

---

execute/format.go
internal/cmd/builtin/cmd/generate.go
stdlib/flux_test.go
stdlib/testing.go
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

This change allows for ensuring that the reported diff is complete,
because a query that errors is not guaranteed to return all results
before the error is encountered.

refactor(testing): use testing.run and testing.inspect as separate phases

---

control/controller.go
control/controller_test.go
csv/result.go
execute/executetest/output.go
execute/executetest/result.go
execute/executetest/source.go
execute/executetest/table.go
execute/executor.go
execute/executor_test.go
execute/result.go
execute/source.go
execute/table.go
influxql/decoder.go
internal/gen/input.go
line/result.go
mock/executor.go
query.go
result.go
result_iterator.go

A source node can expose statistics for its execution and the executor
will attach this metadata to the query returned from the controller.
This metadata can be any arbitrary set of key/value pairs. The metadata
is formatted similar to http headers where one key may have multiple
values. This means that a consumer can decide what to do with multiple
values with the same key such as whether to average or sum the values.
This removes the `flux.Statistics` from arbitrary `flux.Result` values
and the table iterators because the statistics are mostly meaningless
for most iterators.
BREAKING CHANGE: The `Statistics() flux.Statistics` method has been
removed from all interfaces not related to `flux.Query` or
`flux.ResultIterator`. The `flux.ResultIterator` should be considered a
wrapper of …

feat(control): support attaching arbitrary query metadata from the executor

---

docs/SPEC.md

Document that logical operators "and" and "or" are short-circuiting.

docs(SPEC): document short-circuiting

---

stdlib/csv/from.go
stdlib/testing/flux_gen.go
stdlib/testing/testdata/cov.flux
stdlib/testing/testdata/join.flux
stdlib/testing/testdata/join_across_measurements.flux
stdlib/testing/testdata/meta_query_keys.flux
stdlib/testing/testdata/task_per_line.flux
stdlib/testing/testdata/union.flux
stdlib/testing/testdata/union_heterogeneous.flux
stdlib/testing/testdata/yield.flux
stdlib/testing/testing.flux

The diff property from `testing.inspect` now only yields a single result `result: "diff"`. Previously it yielded the result of the query as well as the diff between actual and expected result. Now it is much easier to read in the flux repl.
**UPDATE:** `csv.from` produces tables that wrap around a csv reader. As a result, these tables cannot be shared among goroutines. Now `csv.from` creates a deep copy of each table before sending it to one of its downstream transformations. As a side effect, all end-to-end tests that needed to use `assertEquals` have been updated to the standard test case format.

refactor(testing): remove multiple yields from diff

---

lang/compiler.go
lang/compiler_test.go

BREAKING CHANGES: ASTCompiler.Now is of type time.Time and no longer
a function type. This ensures it can be marshaled.

fix(lang): make ASTCompiler marshalable

---

csv/result.go
csv/result_test.go

The table name(index) and the result name are represent the first
two slots of a csv row. Previously these two slots were only being
written (incorrectly) when the schema headers were written. And
the schema headers are only written when the schema changes from
table to table. This caused a bug where if you had consecutive
tables where the column schema didn't change, those tables would
be encoded in csv as one big table.
This change fixes that issue by always encoding the table index
and result name into each row of csv regardless of which annotations
are present.
Note that for really large tables we are writing out the same result
name and the same table index in each row. In this situation it would
be better to write a default annotation once for the whole table with
the result and …

fix(csv): write table and result name in each row of csv output

---

execute/group_key.go
execute/group_key_test.go
execute/table.go
stdlib/socket/from_test.go
stdlib/universe/join.go

Group keys are considered identical if they have the same set of columns
and these columns have the same values. They are also sorted by a
similar metric where any missing column is considered null and nulls
sort before anything.
Previously, the sort algorithm that was employed assumed that the
columns were already sorted which only worked if the group key was
constructed that way. Otherwise, it would compare them as different.
The group key maintains its ordering for the purpose of a call to
`Cols()` so it is order preserving, but they are considered identical as
if to compare the values in a map so order doesn't matter.
Fixes #1023.

fix(execute): group key comparison works regardless of column ordering

---

docs/SPEC.md
execute/group_lookup.go
execute/group_lookup_test.go

This optimizes group lookup for the common scenario of ordered and
interweaved additions with some benefits to unordered. It reduces the
number of allocations and the usage of `sort.Search` by creating groups of
entries that are appended to.
The data structure contains a slice of time ranges. When adding a new
value, it will find which of the time ranges it can append to easily. So
when we are adding new values in sorted order, this results in a single
slice that is continuously appended to.
If the new value is sorted before all of the existing groups, it will
create a new group at the beginning and add the value to that group instead
of attempting to shift all of the values in the existing group like you
would have to do for a single slice.
If the new value would get inserted into the …

perf(execute): optimize group lookup for non ordered access patterns

---

complete/complete_test.go
values/object.go

A Flux object has a type associated with it. Instead of updating that
type for each entry added to the object, a Flux object would update
its type lazily. Only when its Type and PolyType methods were called
would it construct the corresponding types. This way was not thread-
safe however.
In particular if an object was ever declared inside of the Flux prelude,
its fields would be set during construction of the prelude, but its
type and polytype would not be constructed until they were needed.
Unfortunately this construction would occur when the next bit of Flux
source was compiled.
The interpreter's Eval method accepts a scope object with pre-computed
values. The interpreter then calls the PolyType method on each one of
these values when it builds an enclosing extern block for the program …

fix(values): make read-like access patterns for objects thread-safe

---

query.go

The scanned bytes and values are recorded in the metadata. We originally
thought they would go in statistics, but we made it source specific
instead of modifying the struct.
BREAKING CHANGE: Removing struct fields from flux.Statistics.

fix: remove unused statistics from the struct

---

ast/errors.go
internal/parser/parser.go
internal/parser/parser_test.go

The pipe requires a call expression, but the ebnf does not explicitly
state this for ease of implementation. So we need to do some extra work
in the parser to catch when the pipe destination is not a call
expression.
Fixes #969.

fix(parser): handle when a non-call expression is parsed as the pipe destination

---

cmd/flux/cmd/repl.go
compiler.go
control/controller.go
control/controller_test.go
internal/cmd/refactortests/cmd/refactortests.go
lang/compiler.go
lang/query.go
query.go
result_iterator.go
stdlib/flux_test.go

I did as little as possible to enable the vanilla Flux REPL to work.
Unit tests are not yet passing, I thought I would get feedback before I went to the trouble of fixing them to avoid unnecessary work.
I made `Controller.Query()` just trivially compile and run the `Program` produced by its `Compiler` argument.  As a result, `Controller.compileQuery` is totally unneeded now and caused compiler errors, so I just deleted its body.
Fixes #1086.

refactor(lang): Update Compiler interface to produce a Program

---

control/controller.go
control/controller_test.go
internal/cmd/refactortests/cmd/refactortests.go
lang/compiler.go
lang/compiler_test.go
lang/query.go
mock/compiler.go
plan/builder.go
plan/logical.go
plan/logical_test.go
plan/plantest/cmp.go
querytest/compiler.go
result_iterator.go
stdlib/flux_test.go

These changes allow flux unit tests to pass on `refactor/private-spec`.
I made changes to the controller so `controller_test` would compile, but I disabled the tests there.  Clearly controller will need a lot of attention.
I updated callers of the `Query` interface to reflect the change.
I also updated the mock Compiler and the RepaceSpecCompiler to use the new compiler interface.  `influxdb` and `idpe` will still be broken, but this moves things forward.
Fixes #1099.

fix: Allow flux unit tests to pass on refactor/private-spec

---

ast/format.go
ast/format_test.go

This makes it so Flux is formatted more natually, e.g, `range(start: -30s)`
In other words, no space between `-` and `30s`.
This difference was causing some tests to fail in influxdb.

fix(ast): omit space between unary operator and operand

---

lang/compiler.go
lang/compiler_test.go
lang/query.go

The execution of a program now happens in a goroutine and correctly
responds to the cancel signal.
The program and query implementations are also now hidden since they are
not used by anyone outside of lang.
Fixes #1119.

refactor(lang): run the executor for a program in a goroutine

---

control/controller.go

Queryd wants to set the per-query memory quote when it starts up.  The controller's config still seems to be the right place to keep this info.
Previously this per-query memory quota as replayed to the planner as a planner option, but it didn't actually affect planning in any way.

refactor(control): add per-query mem quota to Config

---

stdlib/csv/from.go

`err` was not correctly scoped, and so the decode error wasn't returned on `Finish`.
This made fromCSV fail silently.

fix(stdlib/csv): make csv.from return decode error

---

control/controller.go
lang/compiler.go
lang/compiler_test.go
mock/source.go

If an error occurred when setting up execution state, it would not be reported.  This
was causing a test to fail for a query like `from(bucket:"non-existent")`.
The call the `Execute` just walks the plan, creates the execution state, and returns, allowing
query execution to continue asynchronously, so it's okay to start execution synchronously to allow
errors to be reported.
Fixes influxdata/idpe#3073.

fix(lang): make Program.Start start execution synchronously

---

lang/compiler.go
repl/compiler.go
repl/repl.go

Closes #13220 .
Once https://github.com/influxdata/influxdb/pull/13222 is merged, the flux version can be updated on the `refactor/private-spec` branch.

refactor(lang): rename SpecCompiler to ReplCompiler

---

release.sh

The release would fail when attempting to upload release notes if a
github token wasn't in the environment. This will check the environment
before running the commands so we don't have to back out a tag midway
through.

fix: require a github token to perform a release

---

Dockerfile_build

And use --no-install-recommends flag to apt-get install, and clear out
apt lists cache at the end to reduce image size, like various official
Docker images do.
----
If I'm following this correctly:
- CircleCI uses Docker image nathanielc/flux-build
- Docker image nathanielc/flux-build uses master of flux as the source of the Dockerfile
- There is no `make` step to build from the local Dockerfile_build
- Therefore CI did not actually test these changes
That being said, I ran the tests locally with go1.12 and they passed.

ci: use go1.12 for builds

---

ast/ast.go
ast/asttest/cmpgen/main.go
semantic/graph.go

I removed calls to `regexp.Copy()`, since the warning says they are unneeded except
fpr when using `Longest` which is not called anywhere in this repo.
I also update the `cmpgen` tool to use `importer.ForCompiler` since `importer.For`
is deprecated.

fix: make staticcheck pass

---

stdlib/influxdata/influxdb/v1/flux_gen.go
stdlib/influxdata/influxdb/v1/v1.flux

The full chain is to look only at distinct keys. This seems to have not
been included. This changes `v1.tagKeys()` to include `distinct()` at the
end.

fix(stdlib): tagKeys should include a call to distinct

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
control/controller.go
control/controller_test.go
examples/library/library_example_test.go
mock/program.go
mock/query.go
querytest/execute.go

This set of changes adds three tunable "knobs" to the Flux controller:
- ConcurrencyQuota
- MemoryBytesQuotaPerQuery
- QueueSize
And also adds unit tests that ensure that these parameters are enforced.  This should address the OOMs being observed in queryd.

fix(control): enforce memory and concurrency limits in controller

---

stdlib/influxdata/influxdb/v1/flux_gen.go
stdlib/influxdata/influxdb/v1/v1.flux

This pattern will help the planner so it can recognize that this is a
tag values call in the upcoming planner rules.

refactor(stdlib): modify the v1.tagValues method to a different pattern

---

control/controller.go

This just makes it so these important configuration parameters appear in logs when a query service starts up.

chore(control): log controller config when starting up

---

arrow/arrow_test.go
arrow/string.go
execute/table.go
go.mod
go.sum
stdlib/universe/mean.go
stdlib/universe/sum.go

The string array data would not be preallocated which could lead to a
lot of allocations that lead to cruft for the garbage collector. This
fixes the most common helpers where we allocate string arrays to use the
new `ReserveData(int)` call to preallocate the buffer for the string
data.
Fixes #1209.

fix(arrow): preallocate data when constructing a new string array

---

execute/executetest/table.go
stdlib/universe/join.go
stdlib/universe/join_test.go

When an error occurred in one of the two datasets that compromised a
join, this error would cause `Finish()` to be called even when there
were more tables to process. This meant that the second call to
`Finish()` would cause a panic in some implementations because
`Finish()` is only supposed to be called a maximum of once.
The test for join never called `Finish()` as part of the test so that
has been added to ensure the correct functionality.
Along with that, an error when processing the table would be discarded
except in the case where a join was happening on a null group key. So
many possible errors were never even detected.

fix(stdlib/universe): an error when joining could result in two calls to finish

---

docs/SPEC.md

This updates the `columns` parameter on the the highest/lowest functions to `column`. This change was introduced when aggregates were updated to only accept one column.
_Sorry for all the whitespace removal. My editor did it automatically._

Updated parameters for highest/lowest functions in the SPEC

---

ast/errors.go
internal/parser/parser.go
internal/parser/parser_test.go
stdlib/testing/testdata/totime.flux

When the parser is in a context where it is expecting a single expression,
the parser will now check to see if more tokens should be read. If more
tokens can be read before reaching the end of a block, it will parse
another expression and create a binary expression with no operator to
signify that the operator was missing.
The parser has also been tested and works properly with a missing left hand
side or right hand side operator. This will now properly produce an error.

feat(parser): construct invalid binary expressions when given multiple expressions

---

execute/executor.go

When a query has had its context canceled, the query should abort with
the error contained within the context instead of swallowing the error
and returning `context done` as the error.

fix(execute): return the error from the context in the executor

---

stdlib/universe/last.go
stdlib/universe/last_test.go

I was looking at the implementation of first and last, and I noticed
that first was an index selector while last was a row selector. It
seemed strange that they weren't a nearly identical implementation. Now
they are both index selectors, which improved the benchmarks for last:
```
name    old time/op    new time/op    delta
Last-4     395ns ± 6%     262ns ±13%  -33.61%  (p=0.000 n=8+8)
name    old alloc/op   new alloc/op   delta
Last-4      224B ± 0%      185B ± 0%  -17.41%  (p=0.000 n=8+8)
name    old allocs/op  new allocs/op  delta
Last-4      9.00 ± 0%      2.00 ± 0%  -77.78%  (p=0.000 n=8+8)
```

refactor(stdlib/universe): convert last to index selector

---

stdlib/testing/testdata/aggregate_window_median.flux
stdlib/testing/testdata/median.flux
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

The `median()` function now exposes the `column` from `quantile()` which
makes it compatible with `aggregateWindow()`. This also adds test cases
for median and using `median()` inside of `aggregateWindow()`.
Fixes #1244.

fix(stdlib): modify median to work with aggregateWindow

---

stdlib/testing/testdata/join_agg.flux
stdlib/universe/join.go
stdlib/universe/join_test.go

Fixes influxdata/idpe#3275.
BREAKING CHANGE: queries that made use of default "on" behavior will break.
However, this behavior was never described in the SPEC and had bugs.

fix(stdlib): make "on" a required parameter to join()

---

execute/dataset.go
execute/result.go
execute/transport.go

The consecutive transport and the result both use goroutines to process
the tables and so need to have their own references to the tables. But,
previously, the dataset was the only one that increased the reference
count even though there was no guarantee it was using the consecutive
transport and no guarantee that the reference count would be
decremented.
This modifies these two areas so that the reference count is increased
on the call to `Process()` to signal that it will keep a reference to
the table and then it decrements the reference count after it discards
its usage of the table.

fix(execute): properly use RefCount to reference count tables

---

csv/result.go
execute/executetest/table.go
execute/result.go
execute/table.go
execute/transport.go
result.go
stdlib/universe/table_fns.go

The table interface has been changed to make it more explicit about its
purpose. The `Do` call has been specified to work exactly once so that
interfaces can begin to implement this contract. The `Done` method has
been added to indicate that the table will not be processed or as a
no-op if it has already been processed. `RefCount` has been removed
because tables are streamed and `RefCount` can't actually be
implemented.
The `ColReader` interface has been modified to include a `Retain` and
`Release` methods that correspond to the arrow buffers themselves. This
is mostly as a convenience to keep the in buffer contents.

refactor: change the table interface

---

execute/dataset.go
execute/executetest/source.go
execute/executetest/table.go
execute/table.go
execute/table_test.go
internal/gen/input.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go

This changes the code that sends a table to multiple downstream
transformations to copy the table into a buffered table and then to use
a new copy of the table for each transformation.

fix(execute): copy the table when a table is used multiple times

---

execute/result.go
execute/transport.go

When `Process` is called, it is responsible for calling `Do` or `Done`.
The original idea was that the `Process` method would call `Do` and the
call to `Done` would be for safety, but implementations like the
consecutive transport and result violate that assumption.

fix(execute): do not call done after calling the function

---

execute/dispatcher.go

This removes the "panic: " from the message when a query uses too much memory.
Fixes #influxdata/idpe#3645.

fix(execute): identify memory limit exceeded errors in dispatcher

---

semantic/constraints.go
semantic/inference_test.go
semantic/poly_types.go
semantic/solve.go
values/values.go

The nullable kind is used for marking that a type variable may be null
in the semantic graph. This kind constraint is added to any values
retrieved using a `MemberExpression` because these are retrieved from
records and records can return null values if the key isn't present.
The nullable kind will unify with anything and it will discard itself if
it is unified with any other kind constraint. At that point, it is
determined that the type cannot be nullable anymore because the other
kind constraint says it cannot be.
If a type variable that is nullable never resolves itself to a concrete
type, it will determine itself to be the null type when used.
Fixes #1353.

feat(semantic): add nullable kind

---

compiler/compiler_test.go
compiler/runtime.go
stdlib/generate/from.go
stdlib/universe/schema_mutators.go
values/binary.go
values/binary_test.go
values/object.go
values/values.go

BREAKING CHANGE: This updates the compiler function so there is only one
`Eval` function instead of one for each type. This may break code that
called these other methods.
Fixes #1329.

feat(compiler): implement nulls in the compiler runtime

---

internal/rust/ast/Cargo.lock
internal/rust/ast/Cargo.toml
internal/rust/ast/src/lib.rs
internal/rust/parser/Cargo.lock

Closes #1350 
Tests pass locally.
What I did here is to port the tests we had in Go to Rust and make them succeed.  
It seems to me that our swagger API isn't explicit in which missing fields we tolerate.
It seems that our Go implementation would be fine with empty JSONs, such as:
```
{"type": "Package"}
```
Because our Go implementation would deserialize a `Package` and fill the fields to their zero value (included `nil`).  In other words, in Go this:
```
{"type": "Package"}
```
is the same of this:
```
{"type": "Package", "path": "", "package":"", "files": null}
```
once deserialized.
This comes in handy, because, in Rust, objects are not nullable and so we must give default values to every field for an AST node. Those default values would be deserialized as expected, so there is no …

feat(internal/rust): ast marshalling

---

compiler/compiler_test.go
execute/row_fn.go
execute/row_fn_test.go
interpreter/interpreter.go
interpreter/interpreter_test.go
semantic/inference_test.go
semantic/semantictest/cmp.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go
values/objects/table.go

The interpreter has been updated for the work on nulls. The row and
table functions now work with nulls.
Unfortunately, some potential issues were found. It seems type inference
doesn't resolve some types for the interpreter correctly specifically
related to functions so certain type constraints don't get identified.
This causes them to erroneously be marked as null types rather than
their appropriate type and so there's currently a hack included to make
it work while still allowing us to evaluate null types in the interim.

feat(interpreter): nulls work in table and row functions

---

execute/table.go
execute/table_test.go

Copying a table resulted in it retaining each of the column readers for
that table. It was possible for a table to be empty though and it would
still copy all of the column readers and report itself as not empty.
Now copy table will recognize when a table is empty and not attempt to
retain empty column readers.

fix(execute): copy table will report if it is empty correctly

---

stdlib/strings/compat.go
stdlib/strings/strings.go

The `strings.ReplaceAll` function was added in go 1.12 and InfluxDB 1.x
still uses go 1.11 for the moment so this changes the strings library to
use `strings.Replace` with `-1` as the final parameter which is the same
thing as the standard library.

fix(stdlib): use strings.Replace instead of strings.ReplaceAll for compatibility

---

stdlib/sql/postgres.go

- Changed sql.from() to correctly identify PostgreSQL float database type names

fix(stdlib/sql): parse float types with PostgreSQL

---

ast/errors.go
docs/SPEC.md
internal/cmd/builtin/cmd/generate.go
plan/logical_test.go
stdlib/testing/testdata/filter_by_regex.flux
stdlib/testing/testdata/filter_by_regex_compile.flux
stdlib/testing/testdata/filter_by_regex_match.flux
stdlib/testing/testdata/filter_by_tags.flux
stdlib/testing/testdata/group.flux
stdlib/testing/testdata/map.flux
stdlib/testing/testdata/map_with_obj.flux
stdlib/testing/testdata/regexp_replaceAllString.flux
stdlib/testing/testdata/simple_max.flux
stdlib/testing/testdata/string_trimLeft.flux
stdlib/testing/testdata/string_trimRight.flux
stdlib/testing/testdata/strings_joinStr.flux
stdlib/testing/testdata/strings_length.flux
stdlib/testing/testdata/strings_substring.flux
stdlib/testing/testdata/totime.flux
stdlib/testing/testdata/window.flux
stdlib/testing/testdata/window_offset.flux
stdlib/universe/flux_gen.go
stdlib/universe/map.go
stdlib/universe/map_test.go
stdlib/universe/universe.flux

BREAKING CHANGE: The removal of the mergeKey parameter is a breaking
change. Users will either need to use the `with` operator to preserve
columns or explicitly list all columns they wish to preserve through the
map function.
Several other test cases that used map have been simplified to remove
their use of the map function as we want the test cases to focus on
testing the function they are designed to test.

fix(stdlib/map): remove mergeKey parameter from the map function

---

lang/compiler.go
stdlib/flux_test.go

It needs to copy the package before adding the testing calls because
otherwise it adds the tests multiple times.
Ideally, this would be done before the benchmark, but a bit of
refactoring has to be done to separate that.

tests(stdlib): fix the e2e benchmarks

---

execute/executetest/result.go
execute/executetest/table.go
execute/executetest/table_test.go
execute/table_test.go
stdlib/universe/histogram_quantile_test.go

The table tests are a common set of tests that should test the basic
functionality of the table interface because the interface itself can be
tricky to get right. Any valid implementation of table should pass these
tests and the tests also act as an example of how to use the table
properly.
Implements part of #1317.

tests(execute): add an initial version of table tests

---

go.mod

This directive will be mandatory starting with go 1.13 and it specifies
the minimum version a module can be built with. We currently support
back to go 1.11, but there's no directive to say that because 1.11 only
had experimental support.
Since the only location where we use go 1.11 is InfluxDB 1.x and that
uses dep instead of go modules, this should be safe and we will specify
go 1.12 as our minimum for systems using modules since we would set that
as the minimum if InfluxDB 1.x was using go 1.12 anyway.

chore: add go 1.12 directive to the go.mod file

---

execute/allocator.go
execute/table.go
execute/table_internal_test.go
execute/table_test.go
internal/gen/input.go

This fixes some allocation issues with the `ColListTable` and also
forces it to conform properly to the `Table` interface.

fix(execute): miscounted allocations in the `ColListTableBuilder`

---

codes/codes.go
errors.go
internal/errors/errors.go
internal/errors/errors_test.go
internal/errors/unwrap_test.go
semantic/solve.go

We need a common way of categorizing and understanding errors returned
from InfluxDB. We model the errors based on the same concepts that
InfluxDB uses, but we create our own error codes that are modeled on the
grpc error codes.
Each native flux error will have a code that represents the category or
type of error and a message that gives detailed and human-readable
output about the error.
The errors library is included as an internal library and the error
struct itself is exposed using a type alias in the top level package.
This allows the errors to be used by packages that cannot depend on the
top level package (like semantic), but still have the error type be
exposed.
Related to #1364.

feat: add enriched error interface to flux

---

codes/codes.go

The ok error code doesn't make much sense for flux since the ok error
code is mostly for grpc where the error is always present and there is
no such thing as null so there needs to be a default.
Inherit has been changed to be the default which should also make it
easier to use without the utility wrapping library. A wrapped error
would be `flux.Error{Err: err}` instead of requiring that
`codes.Inherit` be present or accidentally setting the code to ok.
Additionally, it means the default code returned would be unknown in
cases where one wasn't specified and could not be inherited.

refactor: make inherit the default error code and remove ok

---

docs/SPEC.md
stdlib/testing/testdata/moving_average.flux
stdlib/testing/testdata/timed_moving_average.flux
stdlib/universe/flux_gen.go
stdlib/universe/moving_average.go
stdlib/universe/moving_average_test.go
stdlib/universe/universe.flux

Added the go version of `movingAverage`, which follows the spec used by InfluxQL. It means over `n` points.
The pure flux implementation is changed to `timedMovingAverage` for the time being, since it means over a time window.

feat(stdlib/universe): added go movingAverage

---

.circleci/config.yml

This must be rebased and merged to master after https://github.com/influxdata/flux/pull/1477 has merged.

chore(circleci): use latest image now that changes are in master

---

execute/executetest/transformation.go
stdlib/universe/map.go
stdlib/universe/map_test.go

Map will panic in two situations:
1. The entire column is null.
2. The first record is null.
This is because it attempts to create a column with the nil type which cannot
be represented on a record.
Ideally, the properties would be determined after compiling the function
since we should know the complete return type. Unfortunately, type
inference isn't currently capable of getting all of the types that will
be part of the return value when those values aren't directly referenced
such as in the case of merge key or using the `with` keyword.
In order to fix this, we use a hybrid approach where we determine the
types which are referenced from type inference and add or update these
types based on the first record that is returned. This should get us a
correct type for each of the values in …

fix(stdlib): map will not panic when a record is null

---

execute/executetest/result.go

Adds new helper method that operate on flux.Result and flux.ResultIterators so we can leverage the rest of the executetest types when dealing with  flux.ResultIterators.

fix(executetest): add helper methods for comparing entire result sets

---

csv/result_test.go
result.go
result_test.go

The `DelimitedMultiResultEncoder` now returns errors from the query and
the results if nothing has been written to the writer yet instead of
writing them to the stream. This allows the caller to determine what to
do with the error rather than forcing the output to be written to the
stream.
#1513

feat: return query and result errors in the multi result encoder

---

docs/SPEC.md
stdlib/universe/moving_average.go
stdlib/universe/moving_average_test.go

The previous implementation incorrectly accounted for the case where a chunk ends but the specified period has not beed reached. This was being called at the end of every chunk, which produced the unwanted behavior of appending even if there are more rows in different chunks ([see here](https://github.com/influxdata/flux/pull/1443/files#r302745293)). The solution is to check if the specified period has been reached after iterating through all the chunks, at the end of the `Process` method.
In addition, an arrayContainer interface is created to reduce the number of functions needed for different column types.

fix(stdlib): correct moving average behavior with chunking

---

internal/mutable/numericarray.go
internal/mutable/numericarray_test.go

The mutable arrow array builders use the arrow library's allocator
interface and the memory buffer, but it exposes the ability to set
values as part of the builder such as the ones that would be exposed if
the values were in a slice.
This is only included for the numeric targets at the moment because
those are the most simple to implement. String builders would likely not
be possible and boolean values can be included in the future when we
need them.
These builders do not support null values. We may support that in the
future if it is needed.
These builders are being added as an internal package while we
experiment with this idea in order to avoid adding it as a publicly
exposed API.
#1532

feat: add mutable arrow array builders

---

stdlib/universe/typeconv.go
stdlib/universe/typeconv_test.go

If a null type is received by the type conversion functions, it will
output null because null is a valid value for the inputs and also a
valid value for the outputs.
It previously would return an error that the value was not a recognized
type.
#1567

fix(stdlib): make type conversions work when converting null types

---

execute/source_iterator.go
stdlib/generate/from.go
stdlib/sql/from.go
stdlib/sql/sql_test.go

This enables us to pass a context down to sources, which is needed for authz checking in influxdb.

refactor(execute): add context arguments to SourceDecoder methods

---

internal/parser/parser.go
internal/parser/parser_test.go
internal/rust/parser/src/lib.rs
internal/rust/parser/src/tests.rs

The parser will now report an error when parsing an integer fails
because the value is out of range. The rust parser also now does the
same.
#1560

fix(parser): catch integer overflow and underflow for literals

---

docs/SPEC.md
stdlib/testing/testdata/difference_keepfirst.flux
stdlib/universe/difference.go
stdlib/universe/difference_test.go

- keepFirst is an optional parameter for whether to keep the first row or not
- default behavior is to drop the first row
This parameter would allow for `tripleExponentialDerivative` to be written in pure flux. Currently, this can't be done because `join` after using `difference` causes the first row to be lost.

feat(stdlib/universe): add keepFirst to difference

---

parser/parser_test.go

added test case to check that time literals are parsed as midnight on that date
(see #152)

test(parser): parse time literals

---

docs/SPEC.md
internal/parser/grammar.md

The grammar now includes a `StringExpression`. The scanner will be
updated so that a string literal cannot contain a left bracket in the
string. The scanner will also be updated to include a double quote as a
possible token so that the parser can recognize that the quote begins a
string expression.
A string expression is then processed with an alternate scanner
implementation which recognizes a text token, which is the literal
component of the string expression, and an ability to recognize when a
left bracket occurs.
#1620

docs(parser): design how string expressions will work

---

stdlib/http/flux_gen.go
stdlib/http/http.flux
stdlib/http/post.go

Adds no-op http.post so we can unblock work on developing endpoints.
This specifically unblocks  unblock #1689 and #1690

feat(http): add skeleton http.post function

---

docs/SPEC.md
go.mod
go.sum
stdlib/testing/testdata/tail.flux
stdlib/testing/testdata/tail_offset.flux
stdlib/universe/flux_gen.go
stdlib/universe/tail.go
stdlib/universe/tail_test.go
stdlib/universe/universe.flux

- for each input table, tail returns the last `n` records before the last `offset` records

feat(stdlib/universe): Tail function

---

compiler/compiler.go
interpreter/interpreter.go
stdlib/experimental/experimental.flux
stdlib/experimental/flux_gen.go
stdlib/experimental/object_keys.go
stdlib/experimental/object_keys_test.go
values/array_test.go
values/binary.go
values/binary_test.go
values/object.go
values/object_test.go

Adds objectKeys function to extract the keys as a list.
Fixes two bugs found when writing a test case:
1. Binary functions are now indexed by Nature not Type.
2. Object Equal function has been fixed.
Tests have been added.

feat(stdlib): add objectKeys function

---

stdlib/http/post.go
stdlib/http/post_test.go

Uses http.DefaultClient for now.
We can inject a custom shared client later.
Only reports the status code, the response body is otherwise ignored.

feat(stdlib/http): add post method implementation

---

stdlib/testing/testdata/map_extern_dynamic_var_test.flux

There was already a test for seeing if a local variable worked inside of
a map, but it was not complete since it only tested if a literal could
be used. It seems that some part of the instantiation of the compiler
allowed literals to be passed in, but other values couldn't.
This adds a test case that is the same one, but uses a function to get
the constant value instead. This prevents whatever inlining happened and
ensures that local variables of all kinds will work inside of a compiled
function.
#1508

tests(stdlib): verify that using a local variable inside of a compiled function works

---

interpreter/interpreter.go
interpreter/interpreter_test.go

This change fixes a race condition when the function is shared via a
scope across many interpreters (i.e. builtin functions)

fix(interpreter): use non-pointer receiver for interpreter.function

---

release.sh

The release process is changing to create specific release branches per minor version.
As such the maint branch no longer needs to be maintained via the release script.

build(release.sh): remove the logic around maint

---

dependencies/secret_service.go
dependencies/secret_service_test.go
mock/secret_service.go

service takes a key and a context which are known at the flux level.  In influxdb or other services, we have utilities that can process the context for proper authentication.   This design prevents a dependency on an external service.

feat(dependencies): added a SecretService interface and a new dependencies package and a basic test of functionality

---

stdlib/influxdata/influxdb/monitor/flux_gen.go
stdlib/influxdata/influxdb/monitor/flux_test_gen.go
stdlib/influxdata/influxdb/monitor/monitor.flux
stdlib/influxdata/influxdb/monitor/state_changes_test.flux
stdlib/universe/map.go

The objective of stateChanges is to detect when the level changes from
one level to another. At a macro level the idea is to split the incoming
table into two. One sequence contains all to levels and the other all
from levels. The `to` sequence is assigned a `level_value` of `1` and
the `from` sequence is assigned a `level_value` of `0`.
The sequences are then merged together and sorted by the time column.
We then take the difference of the merged sequences `level_values` and
filter the result for records where `level_value > 0`.
Finally, we add back the `_level` column that was previously dropped.

feat(stdlib/influxdata/influxdb/monitor): add stateChanges function

---

stdlib/influxdata/influxdb/monitor/flux_gen.go
stdlib/influxdata/influxdb/monitor/monitor.flux

Closes #1805
Previously, the data from monitoring would include both the statuses and notifications measurements.
This resulted in odd results in which it looked like more events were happening in the system then there
really was.

feat(stdlib/influxdata/influxdb/monitor): add measurement filtering

---

stdlib/http/basic_auth.go
stdlib/http/basic_auth_test.go
stdlib/http/flux_gen.go
stdlib/http/http.flux

The `basicAuth(u, p)` function will take a username and password and
compute the basic authentication header for that username/password
combination.
#1808

feat(stdlib): add a function that creates the basic auth authorization header

---

compiler/runtime.go

This line was supposed to be commented out with the pagerduty endpoint but must have been missed. This should fix #1814 .

fix(compiler): panic from CheckKind in memberEvaluator

---

interpreter/interpreter.go
stdlib/universe/sleep.go
stdlib/universe/sleep_test.go

The current version of the sleep function will continue sleeping
indefinitely even if the context is canceled. This prevents the sleep
function from running indefinitely and causing the query queue from
being stalled forever.

fix(stdlib): sleep function now gets canceled when the context is canceled

---

stdlib/pagerduty/flux_gen.go
stdlib/pagerduty/pagerduty.flux
stdlib/pagerduty/pagerduty_test.go

Severity levels on status objects can be one of the following: `ok, info, warn, crit, unknown` according to the spec shown here: https://github.com/influxdata/idpe/blob/master/docs/content/rfcs/alerts_and_notifications.md#bucket-data-model
However, pagerduty only accepts: `critical, error, warning, info`
This PR adds a helper function called `severityFromLevel` turns a level from the status object into a pagerduty severity
For example, changing `warn` -> `warning`
The `endpoint` and `sendEvent` functions will both take data in the form that Pagerduty expects. This means that the user or the generated monitoring code will need to call the helper functions `severityFromLevel` and `actionFromLevel` if passing data directly from a status object

fix(pagerduty): add severity level formatting helper function

---

dependencies/dependencies.go
stdlib/http/post.go

The `http.post` function now will respect the context so it will cancel
an outgoing request if its own context gets canceled.
This also updates the idle connect timeout to a much lower value since
any longer than 10 seconds likely indicates an error condition.

fix(stdlib): ensure http.post respects the context

---

internal/spec/build.go
lang/compiler.go
lang/query.go
stdlib/http/post.go

This adds additional spans to track the individual components involved
with compiling, planning, and executing a query so we can get more
accurate traces.
It also adds a trace to the `http.post` and ensures the response body is
discarded and the response size and status code are in the opentracing
logs.
Backport of #1835.

fix: additional opentracing spans for debugging query flow

---

internal/spec/build.go
internal/spec/build_test.go

The conversion from an AST to a spec would evaluate the AST and then
return a spec from the side effects that were related to table objects.
In order to do this, the code that converted a table object into a spec
would also check to see if that table object had already been seen
before.
This caused a performance problem because the `Equal` method for a
`TableObject` would recursively check the `TableObject` which also
included checking the parents. If you had a reasonably complex query,
this could take a very long time as that code was not very efficient and
involved lots of small memory allocations.
This changes it so that instead of recursively checking, it just checks
the memory location which should be the same when they are duplicates
anyway.

fix(internal/spec): do a pointer comparison for table objects instead of a deep compare

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
dependencies/dependencies.go
dependencies/filesystem/ioutil.go
dependencies/filesystem/service.go
dependencies/filesystem/systemfs.go
dependencies/filesystem/systemfs_test.go
stdlib/csv/from.go
stdlib/influxdata/influxdb/v1/from_influx_json.go

This adds a filesystem service for accessing files and changes the file
access functions inside of flux to use it. This allows the user who is
running queries to control the kinds of files that can be accessed or
whether they can access files at all.

fix(stdlib): add a filesystem service

---

stdlib/internal/promql/flux_gen.go
stdlib/internal/promql/promql.flux
stdlib/testing/testdata/promql_quantile_neg_test.flux
stdlib/testing/testdata/promql_quantile_pos_test.flux
stdlib/testing/testdata/promql_quantile_test.flux

Updates the flux quantile function so that it accounts for quantile values that are above 1 by returning `+Inf` and for quantile values that are below 0 by returning `-Inf` in the same way that the promQL quantile aggregate function does. 
Closes #1044

feat(stdlib/internal/promql): make flux quantile() function account for quantile values above 1 or below 0 in the same way the promQL version does

---

arrow/allocator.go
arrow/bool.go
arrow/float.go
arrow/int.go
arrow/string.go
arrow/uint.go
execute/allocator.go
memory/allocator.go
memory/allocator_test.go

This converts the flux memory allocator to support the same interface as
the arrow memory allocator so the two can be used interchangeably.
The purpose of this is to allow greater integration of arrow allocators
and to open up the possibility of pooled memory for buffers to reduce
memory load. At the moment, the flux memory allocator is shared among
the entire query and is commonly wrapped by a temporary arrow allocator
that combines the two. This change reverses that dynamic by having the
flux memory allocator invoke the arrow allocator directly since that is
now possible with the changed interface.
This will allow us to set a single arrow allocator for the entire query
instead of creating a new one for each builder like we currently do.
BREAKING CHANGE: The `*memory.Allocator` interface …

feat: convert the flux memory allocator into an arrow allocator

---

.circleci/config.yml

The go/pkg/mod will contain the files from modules and will be populated
mostly from the contents of `go.sum` which is informed by `go.mod`.
Instead of saving the cache for every new branch and revision
combination, which makes the build noticeably slower, it will only save
the cache when the cache could reasonably be different because `go.sum`
has changed.

ci: save the go/pkg/mod cache only when it would reasonably be changed

---

csv/result.go
csv/result_internal_test.go
csv/result_test.go
execute/table.go
execute/table_test.go
internal/gen/input.go
stdlib/csv/from.go

This should be the final of the table implementations to implement the
full contract for the `flux.Table` so that it passes the common table
tests with no memory leaks.
This involved changing the `TableBuilder` slightly to expose a new
`Release()` method. The `ClearData()` method was being overloaded to
both free memory and clear data. Clearing data can be useful when
reusing the buffers since `TableBuilder` doesn't use the arrow buffers
for legacy reasons so it is more efficient to reuse its internal ones,
but it meant there was no way to signal that you did not want those
buffers anymore.
That meant the old version decreased the allocated memory without
actually freeing it and then reusing that memory led to the system
thinking it had double freed the memory.
The new method makes it …

refactor(csv): csv table iterators now pass the table tests

---

stdlib/experimental/mqtt/to.go

Topic was only being used for fixed messages. Fixed it so it is always used.

fix(stdlib/experimental/mqtt): Change usage of Topic for all messages

---

arrow/table_buffer.go

The `arrow.TableBuffer` can be used as a building block for other tools
that are directly building out tables using the underlying arrow
utilities. It has compatibility with the `flux.ColReader` interface and
mostly follows the same criteria that already existing tables use to
construct their own column readers. It can likely replace those usages
with one common usage.
It does not provide much in terms of safety mechanisms. It is expected
that table building utilities will build safety mechanisms to prevent
programming error on top of it and it does provide a simple mechanism
that can be triggered by those building blocks to ensure the generated
buffers are correct.
The intention behind this is to start building the libraries so that we
can directly produce arrow arrays in the …

feat(arrow): add an arrow backed version of the table buffer

---

lang/query.go
memory/allocator.go
query.go
stdlib/flux_bench_go112_test.go
stdlib/flux_bench_test.go
stdlib/flux_test.go

This adds a custom metric for the max and total allocations as recorded
by the memory allocator to the flux end to end benchmarks.
It also adds a `total_allocated` to the statistics struct which records
a counter of all allocations without accounting for released memory.

refactor(stdlib): add max and total allocations metrics to benchmarks

---

stdlib/flux_test.go
stdlib/testing.go
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

The benchmark function will execute a test case but without running it
through `testing.diff`. In the future, we may add a way that a benchmark
can use a different input than the default input. This allows us to use
the same test cases and benchmark them without rewriting each one of
them, but to also allow custom code to execute for the benchmark instead
of the `testing.run` code.

feat(stdlib): add a benchmark function to the testing package

---

stdlib/testing/diff.go
stdlib/universe/triple_exponential_derivative.go

Fix some of the remaining leaks within the standard library and enable
tests to ensure that memory leaks are checked for every end to end test.
There were two functions that I could not figure out how to fix for
memory leaks. The `join` function was too complex for me to feel
comfortable with deciding when to release memory. The `cov` function
uses the `join` function so I similarly could not fix that one. These
tests are specially skipped until we are able to address the memory
leaks in `join` with a possible refactor.

fix(stdlib): fix some of the memory leaks within the standard library

---

arrow/utils.go

This adds additional utilities for constructing arrow builders based on
the flux column type and appending values using the same signature as is
used in the table builders.

feat(arrow): additional arrow builder utilities

---

arrow/table_buffer.go
csv/result.go

The csv iterator has been switched to it builds arrow buffers directly
instead of using the `ColListTableBuilder`. This makes it more efficient
since it will just allocate the types as it is built instead of building
it once and then copying it.

refactor(csv): switch csv to use the arrow table buffer directly

---

compiler/runtime.go
execute/dataset.go
execute/executetest/transformation.go
execute/row_fn.go
execute/row_fn_test.go
execute/table.go
execute/transformation.go
stdlib/universe/filter.go
stdlib/universe/filter_test.go
stdlib/universe/state_tracking.go

The filter transformation has been optimized to pass through the entire
table without copying when it is possible and, in other circumstances, pass
through the constructed table immediately to the next transformation rather
than to buffer it in memory until it receives a trigger.
First, the filter transformation uses type inference to know which
attributes from the record will be accessed. If all of these attributes are
part of the group key, it knows it can evaluate the function once to
determine if it the entire table should pass or if the table should be
cleared. This means we do not have to allocate any additional memory and we
can send an empty table to the next transformation when it is filtered.
If filter cannot make this optimization, it will now construct the table
and …

feat(stdlib): optimize filter to pass through tables when possible

---

plan/format.go
plan/format_test.go
semantic/format.go
semantic/format_test.go
stdlib/universe/filter.go

This provides a way for ProcedureSpecs to add details to debug output.
E.g., for showing the filters that have been pushed into a source.

refactor(plan): add a WithDetails() option to plan.Formatted

---

stdlib/universe/filter.go

It looks like f6fa52a removed the fmt import, and then 843bb95 was
merged and included a call to fmt.Sprintf, but unfortunately the
resultant merge left the file with a missing import. Duly noted as
another case of outdated PRs causing a broken master branch.

fix(stdlib/universe): add back missing import

---

execute/dataset.go
execute/executor.go

This switches to using discarding mode with the transformations. The
intention of discarding mode was that it would discard the data after it
had been processed. For the current query engine, we do not have any
other stream primitives that would cause us to need the data after it
had been completed because we have no other triggers that actually
function.
But this hadn't caused a problem mostly because accumulating mode, the
previous method that was used, didn't actually accumulate anything.
Since tables will automatically release any memory they are using after
being processed, accumulating mode was essentially the same as
discarding mode, but didn't bother to remove anything from the group
lookup cache.
This change makes it clear that accumulating mode does not function as
it is stated …

feat(execute): switch to using discarding mode for the transformations

---

execute/executetest/source.go
execute/executor_test.go
memory/allocator.go
memory/allocator_test.go

This adds a `memory.Manager` interface that will allow the
`memory.Allocator` to request more memory when more is needed. If this
value is not set, the previous behavior of failing instantaneously will
continue.
This is needed for influxdata/influxdb#15265.

feat(memory): add a memory manager to the memory allocator

---

csv/result.go

This EOF was read by another portion of the code and it was swallowed to
ensure that an EOF in the proper location did not result in an error.
This is readding code that was previously there in `v0.49.0`.

fix(csv): return the EOF error when reading metadata

---

internal/rust/parser/src/lib.rs
internal/rust/scanner/src/lib.rs
internal/rust/scanner/src/scanner.h
internal/rust/scanner/src/tests.rs

#1599 
I simply renamed the C enum to `TOK`.
I tried to see if it was possible to change the prefix for the generated constants (from the default `TOK` to `T`), but I couldn't find a way to do so (see https://docs.rs/bindgen/0.36.0/bindgen/struct.Builder.html).
I tried to use `rustified_enum`, but then I couldn't pass it `as u32` to the lexer.
So, I opted to keep the current method of using constants, but with a different prefix.
This leads to refactors in token names everywhere.
__UPDATE__
There seems to be a way to do that,  but it complicates things. I tried to generate the tokens in a separate file and import it, but that brings 2 new files in the repository: `scanner.c` and `bindings.rs` that can be generated during the  build process. I don't  see any value in the alternative …

refactor(internal/rust): rename T to TOK

---

compiler/runtime.go
execute/bounds.go
execute/trigger.go
execute/window.go
internal/gen/input.go
interpreter/interpreter.go
stdlib/experimental/durations.go
stdlib/universe/state_tracking.go
values/binary.go
values/time.go

This changes everywhere inside of flux to use duration methods instead
of math on the duration value itself.
This also moves the offset normalization code to a utility in
`values.Duration` so that there aren't any sections of code that rely on
`values.Duration` being a `time.Duration` for them to function.
Fixes #1982.

refactor(values): use the duration methods throughout flux

---

compile.go
stdlib/json/encode_test.go
stdlib/universe/derivative_test.go
stdlib/universe/integral_test.go
stdlib/universe/state_tracking_test.go
time.go
values/time.go

The duration value is meant to be a vector of the necessary components
for implementing a duration. This changes `values.Duration` into a
struct which will be that vector.
The only attribute implemented is nanoseconds because we have not
implemented any other dimension of the vector.
BREAKING CHANGE: JSON encoding of duration values will now be output as
string instead of an integer.
Fixes #1981.

feat(values): turn duration value into a vector

---

docs/SPEC.md

Duration addition and subtraction aren't possible with how we have
defined durations. While it is possible to combine multiple units to
form a single time, it is not possible to combine these because the
entire unit would need to keep the same sign.
Multiplication is safe because it is scalar and will only change the
magnitude or it would change the sign of all components of the vector at
the same time.
Addition and subtraction aren't safe because one component of the vector
could become a different sign than another one. In particular, imagine
the following:
1mo - 29d
It would not be possible to determine if this is a positive or negative
number because it depends on the context of the time that it is being
added to. And because it would be possible to add a negative duration to
a …

docs(spec): update the flux spec to remove duration addition and subtraction

---

internal/cmd/test_rewriter/add_measurement.go
internal/cmd/test_rewriter/add_range.go
internal/cmd/test_rewriter/main.go

I had to update several `.flux` tests for this issue:
https://github.com/influxdata/flux/pull/2013
I found it useful to write a tool to automate the changes that I needed to make.  This is that tool.
It has two subcommands:
- Add `_measurement` column to tests that need them
- Add a call to `range()` to tests that need it

feat(test_rewriter): create a tool for updating .flux tests in-place

---

Dockerfile_build

We need to run `flatc` as part of the `checkgenerate` target in CI.  This adds commands to get and install the FlatBuffers package in `Dockerfile_build`.

ci: download and install flatbuffers in Dockerfile_build

---

.circleci/config.yml
Dockerfile_build

Also made CircleCI config point at quay.io instead of nathanielc's Docker hub.

ci: include required libtinfo dependency in Dockerfile_build

---

internal/parser/strconv.go
stdlib/json/encode_test.go
stdlib/universe/typeconv_test.go
values/time.go
values/time_test.go

The duration value is now composed of the months, nanoseconds, and
whether the value is negative or not. This completes making the duration
value month-aware and moving negative into a flag makes it so that we
can ensure the sign of the entire value is the same as specified in the
spec.
This does not implement any of the month behavior. It modifies the
duration function, which returns a `time.Duration`, to treat each month
as 30 days. All of the time operations use `time.Duration` to compute
the final value.
BREAKING CHANGE: The string output of a duration has been modified to use the
flux representation of the value rather than the go representation.
Fixes #1985.

feat(values): updated the duration value to include months and negative flag

---

go.mod
go.sum
memory/allocator.go

The variables used by atomic operations have to be byte aligned for
these operations to succeed. The easiest way to ensure this happens is
to put these variables at the top of the struct.

fix(memory): reorder variables in the allocator for atomic operations

---

docs/SPEC.md
stdlib/universe/schema_functions.go
stdlib/universe/schema_functions_test.go

This fixes an issue that happens when we are keeping or dropping columns such that we lose a column in the group key.  When this happens we may need to merge separate tables that now have the same group key.
Previously we would not detect if the tables had different schemas and an internal error would be thrown in `AppendMappedRecordWithNulls`.  The fix here is to throw a more user-friendly error.

fix(stdlib): make keep/drop throw an error if merging tables with different schemas

---

execute/aggregate.go
execute/row_fn.go
execute/selector.go

The aggregate, selector, and row functions get used within the universe
package. While we annotated the errors in universe, this didn't effect
transformations that had the bulk of their implementation within the
execute package.
This specifically targets very common errors that could occur so that
they don't show up as internal errors in InfluxDB.

fix(execute): add annotated errors to the execute package where it effects normal usage

---

libflux/build.rs
libflux/go/libflux/parser.go
libflux/go/libflux/parser_test.go
libflux/include/influxdata/flux.h
libflux/src/lib.rs
parser/go_parser.go
parser/libflux_parser.go
parser/parser.go

The libflux parser can be optionally enabled by using `-tags libflux`. If
that tag is used, the `libflux` go wrapper will be used to perform the
parsing which is written in Rust with a C ABI.
This adds a marshal json method to the Rust code as we are still working on
creating a flatbuffers API and using it within both Go and Rust.
This also updates the C API to generate bindings to the C types from the
header file so these types can be formally used instead of types that don't
match. The semantics are still the same. A pointer to a Rust type is cast
in an unsafe way to a mutable raw pointer that gets managed outside of
Rust, but the type names are more consistent which should lend itself to
readability.
Fixes #2009.

feat(libflux): integrate libflux parser with the go parsing api

---

libflux/src/semantic/infer.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/sub.rs
libflux/src/semantic/types.rs

#1953 .
This PR does several things.
1. It defines empty structs for each of the basic types. Previously each of the basic types (int, float, string, ...) were just variants of the `MonoType` enum.
2. Defines the data structure for type substitutions as well as the `Substitutable` trait.
3. Defines the data structure for mapping type variables to their kind constraints.
4. Defines the `Constraint` enum which represents either a type constraint or a kind constraint. Type inference will produce a set of these constraints for each expression.

Type inference plumbing

---

README.md

A few of the statements did not work properly. The `math.pow` function
had different arguments and the influxdb import was at a different path.
The influxdb import also only works if running within the InfluxDB REPL
so that has been added as a comment and the method without the import
has also been included.
Fixes #2039.

docs(README): update the readme so all statements work properly

---

interpreter/interpreter.go
libflux/src/parser/tests.rs
libflux/src/scanner/mod.rs
libflux/src/scanner/scanner.h
libflux/src/scanner/scanner.rl
libflux/src/scanner/tests.rs
result.go

Using `unsigned char` instead of `char` in Ragel C generated function will fix this issue!!

fix(libflux): correctly lex µs

---

CONTRIBUTING.md
compile.go
compile_internal_test.go
semantic/analyze.go

A naive implementation to satisy #2051, this PR adds a new `EvalOptions` function that calls `EvalAST` with a filtered deep copy of the AST that excludes all statement types except options. This will allow options to be extracted and inspected without evaluating the full AST. A simple test is included to validate the option filtering logic.

feat(compile): add EvalOptions

---

libflux/src/ast/check/mod.rs
libflux/src/ast/walk/mod.rs

given that the visitor might want to keep a reference to a node
the visit function and done function should be called with a Rc
to that node so the visitor can clone.

feat(flux): Visitor uses Rc for nodes

---

ast/ast.go
compiler/compiler.go
interpreter/interpreter.go
semantic/analyze.go
semantic/graph.go
semantic/graph_test.go
semantic/json.go
semantic/json_test.go
values/time.go
values/time_test.go

This changes the semantic duration literal to keep the months and other
duration units from the AST rather than converting it into a
`time.Duration`.
This also updates the semantic node's json encoding to emit these
magnitudes and units similar to the AST rather than a string
representation of the duration.
In total, this causes the semantic analyzer to create the
`Duration` value properly.
BREAKING CHANGE: The semantic node's duration literal has a different
json encoding and a different struct signature.
Fixes #2069.

feat(semantic): interpret months as part of the semantic duration

---

docs/SPEC.md

The spec now specifies that the base units for a duration unit are
months and nanoseconds and each of the other units corresponds to one of
these two rather than leaving this unspecified. It also continues to say
that both of these may be used with each other.
It adds a restriction for intervals, which are used for windows, that
says that a duration used for an interval can only correspond to one of
these base units. This is because it is possible for us to have regular
intervals when only one of these base units is used, but it would be
difficult to reason and verify about what each window should look like
when these are mixed and there isn't a compelling reason to allow the
duration units to be mixed when it concerns intervals.

docs(spec): restrict intervals to only use one type of base unit for a duration

---

docs/SPEC.md
execute/window.go
execute/window_test.go
stdlib/date/date.go
stdlib/universe/window.go
stdlib/universe/window_test.go
values/time.go
values/time_test.go

The `Add` method follows the rules as specified in the spec for how
adding a duration to a time value should happen. It also clarifies that
adding a duration value twice is not the same thing as adding the
equivalent value once. For example, `t + 1mo + 1mo` is not the same as
`t + 2mo`. This is because of the rules regarding the end of the month.
At the same time, doing `t + 1mo * 2` is the same thing as adding `2mo`
because of the rules for how multiplication works with duration values.
The `Add` method is now aware of month boundaries and can be used
properly with years and months now.
This also adds support for using months for a window interval. If you do
`window(every: 1mo)`, it will create windows on month boundaries. The
`every` parameter for `window()` is limited to only using one …

feat(values): add month support when adding durations to a time value

---

libflux/src/semantic/mod.rs
libflux/src/semantic/parser/grammar.md
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/types.rs

This is a parser to test polytype expressions for our implementation of Algorithm W. 
This parser provides the ability to lex a given PolyType string value, create tokens and parse those tokens into semantic types. Future work is still required as outlined in my comments on #1973. 
The output AST represents a 1 to 1 mapping to the types defined in #1951. 
Further notes and details are outlined as comments within `semantic/parser.mod.rs`.

feat(libflux/semantic): allow lexing and parsing of string polytypes

---

dependencies.go
dependencies/http/http.go
dependencies/http/http_test.go

Replace concrete `*http.Client` dependency with an interface.
Necessary for https://github.com/influxdata/influxdb/pull/15713

refactor(depedencies): use http client interface

---

libflux/src/semantic/analyze.rs
libflux/src/semantic/env.rs
libflux/src/semantic/fresh.rs
libflux/src/semantic/infer.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/sub.rs
libflux/src/semantic/types.rs

This PR adds the type environment used for looking up an identifier's polytype during inference. It also adds unimplemented `infer` methods for generating constraints from each expression. Finally I implement constraint generation for function blocks as an example of how type environments are consumed.

feat(semantic): type environment

---

libflux/src/semantic/infer.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/types.rs

The first commit renames the field `free` to `vars` in the `PolyType` struct. This is so there's no ambiguity between quantified variables and free variables. `vars` represents quantified variables.
The second commit instantiates the quantified variables of a polytype. Previously it instantiated the free variables of a polytype, which are the type variable that are present in the type minus the quantified variables. This was incorrect.
The third commit applies a substitution to both sides of a constraint before unifying. Previously it applied the substitution to only the left side by mistake.
The fourth commit fixes the type expression parser so that it stops parsing type variable constraints if the last kind is not terminated with a comma.

fix: type-checker

---

release.sh

There was an issue with `make release` being able to cut a release without local changes being up to date and in sync with remote. 
These changes check the current commit against the latest commit on the remote version of the branch. They also check that all the tags on both local and remote are the same. If there are inconsistencies, then the script will error. 
**For reviewers:** I was not sure how to test this file without accidentally cutting a bunch of releases. If you have suggestions on how I can test these changes, please let me know. Otherwise, please keep that in mind as you review.

fix: update make release to make sure local and remote are in sync 

---

Makefile
libflux/Cargo.toml
libflux/src/ast/mod.rs
libflux/src/lib.rs
libflux/src/scanner/scanner.rl
libflux/src/semantic/analyze.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs
libflux/src/semantic/walk.rs

This adds a strict mode to compiling libflux that will turn any warning
into an error. This means that the developer will either have to
explicitly handle the warning in code by using `#[allow(warning_name)]`
or they will have to follow the text of the warning to fix it.
This adds certain `#[allow]` statements into the code because we are
still filling in implementation.

refactor(libflux): remove warnings from libflux and set ci to use strict mode

---

libflux/src/semantic/types.rs

This fixes an issue where polytypes would be incorrectly formatted
with a where clause even though its quantified variables were not
constrained with any kinds.

fix(semantic): do not constrain type variables with empty kinds

---

libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

Two polytypes are equivalent modulo their quantified variables, i.e their parameter names. For example, the following two polytypes should compare as equal.
forall [t0, t1] (<-: [t0], fn: (x: t0) -> t1) -> [t1]
forall [t5, t9] (<-: [t5], fn: (x: t5) -> t9) -> [t9]
This PR implements the PartialEq trait for polytypes. It calculates the max type variable of each polytype and then instantiates fresh types with a fresher derived from this type variable. By using a fresher derived from the maximum type variable we are ensured to generate equivalent polytypes.

feat(semantic): custom PartialEq for polytypes

---

libflux/src/semantic/infer.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

Semantic expression constraints have been added for most expression
types in libflux. The only ones missing are member expressions, object
expressions, and function/call expressions.
This also slightly modifies the ragel scanner so it does not emit
warnings anymore for unused variables.
Fixes #1956.

feat(libflux): added semantic expression constraints to libflux

---

libflux/src/ast/flatbuffers/mod.rs
libflux/src/ast/flatbuffers/tests.rs
libflux/src/ast/mod.rs

The flatbuffer module has some autogenerated code that will send out
warnings due to stylistic issues, e.g. variables named `init__type` instead
of `init_type`.
This patch addresses those issues by renaming the variable `init__type`
to `init_type` in `mod.rs` and then suppressing all warnings that may
come from the generated code by allowing non_snake_case in the generated
file. The warnings for the module are quieter now.
Additionally, this patch also adds `#[allow(dead_code)]` to
`print_expr_stack`, which is helpful for debugging. It also uses the
underscore prefix on a parameter that is not used in a function.

Chore: Fix or suppress warnings in flatbuffers

---

libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs

First commit constrains unary expressions to be the same type as their operands. The second commit adds greater type inference test converage.

test: type inference coverage

---

execute/table.go
result.go

The `BufferedTable` now exposes the buffers within the table through two
new methods that give the number of buffers and return the buffers
themselves.
BREAKING CHANGE: The interface for `BufferedTable` changed so
implementors of the interface will need to implement the two new
methods.

refactor: expand the interface for BufferedTable

---

libflux/src/ast/flatbuffers/tests.rs

This just adds testing for every kind of operator that we support, and also adds a check for the operator type for unary expressions that I had forgotten.

test(libflux): add missing test cases to flatbuffers testing

---

arrow/repeat.go
internal/execute/tableutil/stream.go
internal/execute/tableutil/stream_test.go
internal/gen/input.go
internal/gen/input_test.go

This creates a new utility for constructing a table stream. Its primary
focus is to allow sources that create tables to easily create buffered
table streams. This is demonstrated by updating the internal point
generator so that it will now natively construct arrow arrays using the
arrow table buffer and stream the chunks downstream using the stream
method.
These utilities are being kept as internal packages while we experiment
with possible methods of constructing tables quickly and efficiently.

feat(tableutil): add internal table utility for streaming tables

---

libflux/Dockerfile
libflux/build.sh
libflux/src/parser/mod.rs
libflux/src/scanner/mod.rs
libflux/src/scanner/scanner.h
libflux/src/scanner/scanner.rl
libflux/src/scanner/tests.rs

We currently use a linked list (which needs `alloc` and `free`) to keep track of where newlines are when scanning tokens.  This was problematic because the wasm build has poor support for these C library functions.
This PR does the following:
- Avoids using `malloc` inside of the C code that hosts the Ragel scanner, by tracking newlines in- and outside of tokens.  The returned token now contains both offset and line/column for its beginning and end.
- Makes some minor tweaks to the docker file that does the wasm build on Mac.
- Removes the `Scanner::pos()` method (which translates from buffer offset to line/col) from the public interface of the scanner, since this info is now available directly from the token.
- The parser still needs to go from line/column back to an offset to get the …

refactor(libflux): remove usage of malloc from Rust scanner

---

cmd/flux/main.go
go.mod
go.sum
stdlib/sql/from.go
stdlib/sql/from_private_test.go
stdlib/sql/postgres.go
stdlib/sql/source_validator.go
stdlib/sql/sql_test.go
stdlib/sql/sqlite.go
stdlib/sql/sqlite_test.go
stdlib/sql/to.go
stdlib/sql/to_privates_test.go
stdlib/sql/to_test.go

Adds support for SQLite3 to the stdlib/sql package. SQLite is a fully SQL compliant relational DB, in a file (or in memory, if preferred). Adding this to flux would allow it to interact with this DB, and present a lot of opportunity to extract information from many 3rd party "infrastructure tools", and combine this with Influxdb, or other data sources.
- SQLite3 to() and from() are both supported.
- Slight refactor of common sql stuff (specifically from CreateInsertComponents() column types) to allow for easier addition of other flavours of SQL DB. Main area is move of "type logic" into the driver files themselves, as these are often very specific to any given DB. This also allows for returning driver-specific type errors (i.e. when you try to create a column of an unsupported type)
- SQL …

feat(stdlib/sql): add sqlite3 support

---

stdlib/testing/usage/api_test.flux
stdlib/testing/usage/writes_test.flux

Updating the flux tests for usage api count and writes to filter out metrics with hostnames containing gateway-internal.

test(usage): Update usage tests to filter out metrics with hostnames containing gateway-internal

---

.circleci/config.yml
Makefile
libflux/README.md

This adds a `libflux-wasm` target to the Makefile and builds adds that target to the CircleCI configuration.

ci: build libflux wasm target in CI

---

docs/SPEC.md

The description of the `stop` parameter for the `range` function makes it a little unclear if it's an exclusive or inclusive upper bound.  This addresses that.

docs(SPEC): clarify language for range function

---

libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs

Some work had been done to flag warnings as errors, and to handle some
of the warnings in libflux. There was still an `#[allow(warnings)]` with
a note about coming back to address some of the issues.
This patch fixes most of those warnings, leaving only a single unused
`ReturnStmt.infer` call. Unused `Fresher` arguments were removed, rather
than prefixed with `_`.

chore(libflux): address all warnings in semantic

---

arrow/bool.go
arrow/float.go
arrow/int.go
arrow/repeat.go
arrow/string.go
arrow/uint.go

Reserve is meant for appending when you don't know the final size of the
array. Resize is meant for when you know the exact size. When using
Reserve, it changes the size to the closest power of 2 that fits the
elements you are going to append while Resize gives you the exact
amount.
When using Reserve, the buffers are very likely to trigger a
reallocation so it can resize the buffers to a smaller amount and incur
a copy between these buffers. To avoid this, it is better to use Resize
when we know the exact size which is true of all of these functions.

perf(arrow): use resize instead of reserve

---

libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/sub.rs
libflux/src/semantic/walk/mod.rs
libflux/src/semantic/walk/test_utils.rs
libflux/src/semantic/walk/walk.rs
libflux/src/semantic/walk/walk_mut.rs
libflux/tests/analyze_test.rs

This PR adds type injection in the semantic graph.
- `inject.rs` injects types
- `semantic::analyze_source` now inject types in the analyzed source;
- added e2e test for `analyze_source`
- `Substitutable` change to take `&self` -> this allows to avoid unnecessary type cloning.
- util methods in `walk::{Node, NodeMut}`.

feat(libflux): inject types in the semantic graph

---

Makefile
go.mod
internal/cmd/flux-config/build.go
internal/cmd/flux-config/main.go
libflux/go/libflux/flux.h
libflux/go/libflux/parser.go

The utility program will build libflux in the go build cache and then
print out command line options to be used with a compiler. This matches
the same interface as `pkg-config` and can be used in a similar way.

feat(libflux): create utility program for building libflux

---

execute/executetest/table.go
internal/execute/tableutil/buffered.go
stdlib/universe/pivot.go
stdlib/universe/pivot_test.go

This allows the planner to add methods to determine if the new pivot can
be used to the pivot procedure spec.
These methods may be temporary at the moment.
This also adds an additional table test to ensure that `Empty()`
continues functioning and returning the same value after the table has
been read.
#2133

feat(stdlib): expose the optimized pivot

---

.circleci/config.yml

The `>` in a yaml file ensures that the line is treated as a single
line. The `|` will preserve newlines and since it is a single command
split over multiple lines, the `>` is more appropriate.

ci(release): fix the ci release to use `>` instead of `|`

---

.circleci/config.yml

Backslashes need to be used to escape the newlines for the release
script. I previously tried to use `>` because I was under the impression
it would make it one line, but it only does that if all of the
indentations are the same. Since I would like to keep the current
indentation because I find it more readable, this reverts back to using
`|` and adds backslashes so the line is escaped.

ci(release): use backslashes to escape newlines for the release scripts

---

stdlib/testing/usage/api_test.flux
stdlib/testing/usage/writes_test.flux

The original version of the queries used a function invocation that broke being pushed down to storage.
This is a workaround to make everything work.
FYI @ischolten heads up if the queries look good to you.

fix(e2e-tests): fix e2e usage write test so that its query is properly pushed down

---

libflux/src/semantic/flatbuffers/semantic_generated.rs
libflux/src/semantic/flatbuffers/types.rs
libflux/src/semantic/parser/grammar.md
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs
semantic/internal/fbsemantic/Type.go
semantic/semantic.fbs

This adds the `bytes` monotype to the Rust type code.  This was pretty straightforward, following the examples of the other simple monotypes.
I also fixed an issue discovered during testing with the type expression parser where 0-argument functions did not parse correctly.

fix(semantic): add bytes monotype to Rust semantic module

---

Makefile
libflux/src/flux/ast/flatbuffers/mod.rs
libflux/src/flux/lib.rs
libflux/src/flux/semantic/flatbuffers/mod.rs

This patch adds clippy linting to the `test-rust` target. As a result, it will
be run as part of the CI process. There is a not insignificant amount of
existing lint that must be ignored as part of this patch, though that lint
should be driven down to zero bit-by-bit.

chore(libflux): Add clippy to test-rust target

---

libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/strconv.rs

This patch addresses a line of outstanding clippy lints, notable `useless_format`, `cmp_owned`, and `while_let_loop`.

fix(flux): Address some clippy lints

---

libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/strconv.rs
libflux/src/flux/semantic/env.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/types.rs

This patch addresses three more clippy lints: `len_zero`, `or_fun_call`, and `collapsible_if`. The details of these lints can be found at the following links:
- [len_zero](https://rust-lang.github.io/rust-clippy/master/index.html#len_zero)
- [of_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#or_fun_call)
- [collapsible_if](https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if)

fix(flux): Address more clippy lints

---

libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/parser/grammar.md
libflux/src/flux/semantic/parser/mod.rs

This adds Flux types for some of the stdlib builtins (Flux functions and constants that are defined in Go code).  The unit test ensures that the type expressions all parse to polytypes correctly.
Not all of the builtins are here, I will file followup issues for what remains.
The `modf` function returns an object with a field named `int`, so I had to extend the type expression parser to allow quoted identifiers to resolve conflicts with keywords.

feat(semantic/builtins): add types for some builtins

---

Makefile
libflux/src/flux/semantic/builtins.rs

This patch fixes an issue where `cargo clippy` returns a zero exit code
unless explicitly told to fail on clippy lints. Additionally, it fixes a
recently introduced lint that caused me to noticed the issue.

chore(flux): fail make on clippy lint

---

internal/cmd/flux-config/build.go

fix: properly use a fake version with flux-config when no version is present

---

docs/SPEC.md

The power operator was added a while back but it was missed in the SPEC. This fixes that.

docs(SPEC): add power operator to SPEC

---

libflux/src/flux/semantic/parser/mod.rs

This makes it so an invalid monotype will produce a specific message instead of `Monotype was not in valid format` if that's possible.

refactor(semantic): minor change to type expr parser to produce better errors

---

libflux/src/flux/lib.rs
libflux/src/flux/scanner/mod.rs
libflux/src/flux/semantic/analyze.rs

This patch addresses the following clippy lints:
- [`clippy::try_err`](https://rust-lang.github.io/rust-clippy/master/index.html#try_err)
- [`clippy::ptr_offset_with_cast`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_offset_with_cast)
- [`clippy::clone_on_copy`](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)

fix(libflux): Address even more clippy lints

---

libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/flatbuffers/semantic_generated.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/parser/mod.rs
libflux/src/flux/semantic/types.rs
semantic/internal/fbsemantic/Kind.go
semantic/semantic.fbs

This adds two new kind constraints to type inference:
- `Numeric` for int, uint and float.  There are a few transformations where we would error if a certain column like `_value` is not numeric.
- `Row` to indicate a TVar must be a Row type.
I also updated the builtin types that were already merged to reflect the changes.

feat(semantic): add Numeric and Row kind constraints

---

libflux/src/flux/semantic/builtins.rs

This patch adds type declarations for for `runtime`, `slack`, `socket`,
and `sql`. This is part of the work addressed in #2229.

feat(libflux): add type declarations for builtins

---

Makefile
libflux/src/flux/Cargo.toml

`cargo` doesn't seem to pass `--features` flags to the sub-crates. This
patch enables the strict mode by default on the crate.

fix(libflux): enable strict mode by default

---

libflux/src/flux/semantic/builtins.rs

This is another part of work that was started here: https://github.com/influxdata/flux/pull/2228
This includes the builtins in the `universe` package, from letters I through Z.

feat(semantic/builtins): add types for some universe builtins

---

values/bool.go
values/object.go
values/values.go

An object will now cache the type for an object and not recompute it as
long as the type doesn't change. This includes a change to `Set` which
will check the old value's type and the new value's type and it will not
force the type to be recomputed as long as the type doesn't change. This
helps to reduce memory allocations when using `Set` to change the value
inside of functions like `filter()` where the type doesn't change.
Previously, it was using a lot of memory to recompute the type over and
over again.
This also changes `values.NewBool` to return one of two memoized values
for true and false. This avoids an interface allocation each time that a
boolean is created.
Fixes #2211.

feat(values): reduce memory allocations for operations in values

---

libflux/src/flux/ast/mod.rs
libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/strconv.rs
libflux/src/flux/scanner/mod.rs
libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/nodes.rs

This patch addresses the [`needless_return`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return) lint.

chore(libflux): address needless_return lint

---

compile.go
compiler.go
compiler/compiler.go
compiler/runtime.go
dialect.go
operation.go
semantic/analyze.go
semantic/check.go
semantic/constraints.go
semantic/flatbuffers.go
semantic/json.go
semantic/poly_types.go
semantic/solve.go
semantic/types.go
semantic/walk.go
spec.go
stdlib/kafka/to.go
stdlib/slack/slack.go
values/array.go
values/binary.go
values/binary_test.go
values/values.go

This covers all of the packages that are in active use within the flux
repository. It doesn't cover all of the packages, but enough that we
should have good enough coverage for most code paths that get hit.
Fixes #2218.

feat: categorize more flux errors with codes

---

libflux/src/flux/semantic/analyze.rs
libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/import.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/tests.rs

This commit adds a new module `bootstrap` whose main function is `infer_pkg`. This function infers the types in a package/file. If said package/file imports other packages, it first recursively infers the types those imported packages, before type checking the original package.
Note, once all builtin identifiers have had their types defined, this function will be used by the `libstd` crate to infer the types of the entire standard library.

feat(bootstrap): methods for type checking package dependencies

---

libflux/src/flux/ast/check/tests.rs
libflux/src/flux/ast/mod.rs
libflux/src/flux/ast/tests.rs
libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/tests.rs
libflux/src/flux/semantic/analyze.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/tests/analyze_test.rs

This patch addresses the [`large_enum_variant`](https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant) lint.

chore(libflux): address large_enum_variant lint

---

libflux/src/flux/semantic/flatbuffers/semantic_generated.rs
semantic/internal/fbsemantic/NativeVariableAssignment.go
semantic/semantic.fbs

This is just a very simple change to the flatbuffer schema for the semantic graph.  It's not actually used anywhere on master yet, so there are no test changes.

fix(semantic): annotate variable assignment with polytype (not monotype)

---

docs/SPEC.md

The `filter` transformation has been changed so it will drop empty
tables by default. This matches with the influxdb behavior for pushing
down a filter to the storage engine. If the user wants to keep the empty
tables, they can switch the empty behavior to keep the table.
Related to #45.

docs(spec): update the spec to clarify filter's behavior with empty tables

---

ast/flatbuffers_test.go
internal/parser/parser.go
internal/parser/parser_test.go
internal/token/fileset.go
libflux/scanner.c
libflux/src/flux/scanner/mod.rs
libflux/src/flux/scanner/scanner.rl
libflux/src/flux/scanner/tests.rs

If a flux program has a stray `/` in a place where a regexp literal might appear, the scanner will scan to the end of the input looking for the closing `/`.  During scanning we keep track of where newlines appear so we can determine the line/column info for the end of the token returned by the scanner.
In this situation we were getting the location wrong because the token was just TOKEN_DIV, not a regexp literal.  I updated the logic in the Rust scanner to reset the pointer to the last newline for this case.
I also made two changes to how Go parses Flux so that the roundtrip test can now pass:
- if we cannot parse the RHS of a binary expr, we use the location info of the buffered token, so we can propagate location info up the AST
- I added logic to preserve the sortedness of the lines …

fix(scanner): fix token location for scan_with_regex

---

internal/cmd/flux-config/build.go

The verbose flag would set the output to be `os.Stderr`. The code
assumed that this wouldn't be usable as an `io.Reader` and so the
`io.Copy` would only occur when the output was not verbose. But,
`os.Stderr` uses `*os.File` and `*os.File` does implement `io.Reader`,
but blocks forever because `os.Stderr` doesn't have anything to read.
This removes the incorrect code and replaces it by just checking to see
if verbose is set. If verbose is set, there is no need to copy the
buffer to stderr because it already is on stderr.
Fixes influxdata/influxdb#16267.

fix: do not stall forever in flux-config when an error happens with verbose

---

lang/compiler_test.go
libflux/src/flux/semantic/builtins.rs
stdlib/universe/filter.go
stdlib/universe/filter_drop_empty_test.flux
stdlib/universe/filter_keep_empty_test.flux
stdlib/universe/filter_mixed_empty_test.flux
stdlib/universe/filter_test.go
stdlib/universe/join_missing_on_col_test.flux

The `filter()` function now accepts an `onEmpty` parameter that will
determine the behavior of filter when the filter causes all rows to be
filtered.
Fixes #2278.

feat(stdlib): implement onEmpty parameter for filter

---

internal/cmd/fbgen/cmd/semantic.go
libflux/src/flux/ast/flatbuffers/mod.rs
libflux/src/flux/semantic/flatbuffers/mod.rs
libflux/src/flux/semantic/flatbuffers/semantic_generated.rs
libflux/src/flux/semantic/flatbuffers/tests.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/walk/walk.rs
libflux/src/flux/semantic/walk/walk_mut.rs
semantic/flatbuffers.go
semantic/flatbuffers_gen.go
semantic/internal/fbsemantic/CallExpression.go
semantic/semantic.fbs

Semantic graph Flatbuffers need to be serialized in Rust. This commit serializes and performs testing. 
Additional testing may be added to support round trip with deserialization on the Go side. 
The Rust semantic graph `DurationLit` node only contains a single `Duration` value, while the AST and the Go Semantic Graph allow for a list of type `Duration` to accommodate the possible multiple duration values. To temporarily work around this difference, I'm serializing the Flatbuffers `DurationLiteral` with a single duration value stored in a vector. This needs to be fixed before Algorithm W can be deployed in order to not break calendar durations. I'll open another PR to handle that fix to the Rust semantic graph. 
I also worked with @wolffcm to make changes to the code that generates …

feat(libflux/semantic): serialize semantic graph flatbuffers

---

libflux/src/flux/ast/flatbuffers/mod.rs
libflux/src/flux/ast/mod.rs
libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/strconv.rs
libflux/src/flux/semantic/analyze.rs
libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/env.rs
libflux/src/flux/semantic/flatbuffers/mod.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/fresh.rs
libflux/src/flux/semantic/infer.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/parser/mod.rs
libflux/src/flux/semantic/sub.rs
libflux/src/flux/semantic/types.rs

The following clippy lints are addressed in this patch:
- [`single_char_pattern`](https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern)
- [`chars_last_cmp`](https://rust-lang.github.io/rust-clippy/master/index.html#chars_last_cmp)
- [`chars_next_cmp`](https://rust-lang.github.io/rust-clippy/master/index.html#chars_next_cmp)
- [`unnecessary_operation`](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_operation)
- [`wrong_self_convention`](https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention)
- [`useless_let_if_seq`](https://rust-lang.github.io/rust-clippy/master/index.html#useless_let_if_seq)
- [`implicit_hasher`](https://rust-lang.github.io/rust-clippy/master/index.html#implicit_hasher)
- …

chore(libflux): continue driving down lint

---

libflux/src/flux/semantic/flatbuffers/mod.rs

There was an unnecessary line of code cloning the reference counter in the semantic Flatbuffers serializer. This removes that line.

fix(semantic/libflux): removes unnecessary rc clone in semantic serializer

---

libflux/src/flux/semantic/builtins.rs

This change makes fill expect a single value to fill instead of a list of values
Fixes #2306

fix(libflux/semantic): update fill builtin type

---

libflux/src/flux/semantic/builtins.rs

The `to` function is a passthrough, the `t1` from the `fieldFn` parameter does not effect the return type of the `to` function.

fix(libflux/semantic): update the type of influxdb.to to be a passthrough

---

libflux/src/flux/semantic/builtins.rs

This change makes it so that count expects a single column instead of a list of columns
Fixes #2304

fix(libflux/semantic): update count builtin type

---

stdlib/universe/limit.go
stdlib/universe/limit_test.go

The limit transformation has been optimized to use a passthrough dataset
and to use arrow slices rather than copying the input to a new table.
This reduces the number of memory allocations which makes the
transformation use a more consistent amount of memory and speeds up the
transformation because it doesn't have to wait for memory allocations to
finish.

perf(stdlib): optimize limit transformation

---

internal/cmd/flux-config/build.go

fix(libflux): correctly skip the stdlib symlink in libflux

---

internal/cmd/flux-config/build.go

The stdlib directory didn't get created when extracting the archive in
flux config because the cleaned path didn't include an ending slash.

fix(libflux): ensure stdlib directory is created

---

internal/cmd/flux-config/build.go

fix(libflux): skip stdlib symlink was removed erroneously

---

semantic/flatbuffers.go
semantic/monotype.go
semantic/polytype.go

The flatbuffers code sends the table struct as the struct itself and the
copy is largely inconsequential because the struct is composed of a
slice and an offset. This will simplify some of the APIs since it was
common to assign the table to a variable just to get a pointer value.
Now we can just pass the struct itself after the builder constructs the
table.

refactor(semantic): new monotype should take a table struct not a pointer

---

Makefile
ast/fbuffers.go
ast/flatbuffers_test.go
libflux/go/libflux/analyze.go
libflux/go/libflux/analyze_test.go
libflux/go/libflux/bench_test.go
libflux/go/libflux/flux.h
libflux/go/libflux/liblibstd.a
libflux/go/libflux/parser.go
libflux/go/libflux/parser_test.go
libflux/include/influxdata/flux.h
libflux/src/flux/ast/mod.rs
libflux/src/flux/lib.rs
libflux/src/flux/semantic/analyze.rs
libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/convert.rs
libflux/src/flux/semantic/flatbuffers/mod.rs
libflux/src/flux/semantic/flatbuffers/tests.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/tests.rs
libflux/src/flux/semantic/walk/test_utils.rs
libflux/src/flux/tests/analyze_test.rs
libflux/src/libstd/Cargo.toml
libflux/src/libstd/lib.rs
parser/libflux_parser.go
semantic/analyze_libflux.go
semantic/analyze_libflux_test.go
semantic/flatbuffers_test.go

I also added a simple (to be expanded) test case for calling type inference from Go.
I wanted to be able to have access to types from the builtins, standard library and prelude, so I had to implement `analyze` in libflux and make that linkable from CGO.  This API lets Go pass in Flux source and get a type-inferred semantic graph (that uses types from the stdlib and prelude).
I think that we'll want to refine the Go/Rust API a bit more than what's on this branch:
- It seems strange that Go needs to call into both `liblibstd` and `libflux`.   Seems like we should encapsulate everything we need from Go into a single crate.
- We'll somehow want to avoid having to copy the prelude and stdlib types very time we type-infer a program.

feat(libflux): add Go/Rust API for getting semantic graph

---

interpreter/interpreter.go
interpreter/package.go
semantic/monotype.go
stdlib/experimental/set.go
stdlib/experimental/set_test.go
values/object.go
values/object_test.go
values/scope.go

This modifies the API for creating object values since the object's type
needs to be known before we create the object now. It also adds a
utility method for building an object that is easier for creating an
object.
Fixes #2318.

refactor(values): mutable object values with the new semantic object

---

execute/executetest/dataset.go
execute/group_lookup.go
execute/group_lookup_test.go
internal/execute/table/buffered_builder.go
internal/execute/table/builder_cache.go
internal/execute/table/dataset.go
stdlib/universe/window.go
stdlib/universe/window_test.go

This optimizes the window transformation to be more efficient than the 
current window transformation. It changes the access pattern so the time 
values are iterated over in sorted order and the windows are created in 
sorted order. This reduces the amount of random access used when iterating
over values so memory is more efficient.
It also adds a new `RandomAccessGroupLookup` that uses another method for
storing values based on their group key. The window method had a bad access
pattern for the standard `GroupLookup` because the `_start` and
`_stop` values changing would commonly result in an access pattern like 
this:
1 2 3 4 5 6 -> 1 4 2 5 3 6
This hit one of the group lookups worst access patterns and caused a lot of
time to be spent copying memory to maintain the sorted order of the …

perf(stdlib): optimize window transformation

---

csv/result.go
csv/result_test.go

This patch provides a better error message for malformed CSV files.
Prior to this patch, if the metadata is missing from the CSV, an error
about EOF was returned, which was not helpful. A more helpful error
message is now returned (with test).
Fixes #2201

fix(stdlib): better messaging for malformed csv

---

internal/cmd/fbgen/cmd/semantic.go
libflux/src/flux/semantic/convert.rs
libflux/src/flux/semantic/flatbuffers/mod.rs
semantic/analyze_libflux.go
semantic/flatbuffers.go
semantic/flatbuffers_gen.go
semantic/flatbuffers_test.go
semantic/types/monotype.go
semantic/types/polytype.go

This PR adds roundtrip testing for FlatBuffers serialization of the semantic graph, and also fixes some issues that I found while writing these tests.
I also added some utilities that help with reindexing type variables starting from zero so that changes in the standard lib or the order that that expressions are analyzed do not make the test fail.

test(semantic): add roundtrip testing for Flatbuffers serialization

---

release.sh

The `release.sh` file was recently updated (https://github.com/influxdata/flux/issues/2084) to properly compare local and remote tags. This PR updates the file to remove the `refs/tags/list` line from the local tags since this line does not appear in the remote tags list.

fix: remove 'tags' line from local tags

---

libflux/src/flux/semantic/convert.rs
libflux/src/flux/semantic/flatbuffers/tests.rs
libflux/src/flux/semantic/walk/test_utils.rs

The 0-argument method `convert()` uses a default fresher that starts from 0,
but that is generally not what most callers want, outside of special cases
like bootstrapping the standard library and testing.
If one tries to type-infer a flux program with the wrong fresher, strange
behavior can result.  This commit removes this method to make it more
difficult to make such a mistake.

refactor(libflux/semantic): remove convert() method that doesn't take a fresher

---

libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/tests.rs

This patch addresses a panic discovered when an unclosed string literal
is passed to the parser.
Fixes #2375

fix(libflux): handle invalid string literals

---

semantic/lookup.go
semantic/lookup_test.go

`LookUpBuiltinType` was creating the entire TypeEnvironment and using linear search for every single lookup. This attempts to create the TypeEnvironment once and store it in a map. Then `LookUpBuiltinType` can be called for every stdlib builtin that needs to be looked up.

fix(semantic): optimize lookup function using hashmap

---

compile.go
compile_internal_test.go
result_test.go
spec_test.go
stdlib/generate/from.go
stdlib/influxdata/influxdb/v1/databases.go
stdlib/internal/promql/join.go
stdlib/math/math.go
stdlib/sql/to.go
stdlib/strings/strings.go
stdlib/universe/cumulative_sum.go
stdlib/universe/filter.go
stdlib/universe/histogram.go
stdlib/universe/holt_winters.go
stdlib/universe/relative_strength_index.go
stdlib/universe/schema_functions.go
stdlib/universe/schema_mutators.go

This fixes some miscellaneous typos in the `stdlib` code, and also lets code compile.
This commit will make it trivial to reproduce #2404 by running the test `TestValidatePackageBuiltins`.

fix(stdlib): misc stdlib fixes

---

values/object.go

Previously, attempting to set an invalid key in an object would result
in it silently ignoring the failure. This makes it explicitly a problem
that must be addressed because it will panic if the key could not be
found.

refactor(values): ensure that setting an invalid key in the object panics

---

compile.go
compile_test.go
interpreter/interpreter.go
interpreter/interpreter_test.go
interpreter/interptest/eval.go
interpreter/package_test.go
libflux/go/libflux/analyze.go
libflux/go/libflux/flux.h
libflux/go/libflux/parser.go
libflux/include/influxdata/flux.h
libflux/src/flux/lib.rs
libflux/src/flux/semantic/tests.rs
libflux/src/libstd/lib.rs
parser/libflux_parser.go
parser/parser.go
result_test.go
semantic/analyze_libflux.go
stdlib/internal/promql/empty_table.go
stdlib/internal/promql/instant_rate.go
stdlib/internal/promql/join.go
stdlib/universe/schema_functions.go
values/scope.go

The test `flux/compiler_test.go` tests these new methods.
I also made sure that the interpreter tests now pass:
- Some of the tests were verifying that type inference produces errors.
Since the interpreter no longer runs inference itself, I moved these tests
into the Rust code.
- Some of the test cases did not pass due to other issues.  I skipped them with the issue number.

feat(flux): make Eval() and EvalAST() use libflux for parsing and analysis

---

libflux/src/flux/semantic/flatbuffers/semantic_generated.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/tests.rs
libflux/src/flux/semantic/types.rs
semantic/internal/fbsemantic/Kind.go
semantic/semantic.fbs

This patch enables uints to be subtractable, both as a binary expression
and as a unary expression.
Fixes #2242

fix(libflux): allow uint to be subtractable

---

csv/result.go
csv/result_test.go

This patch restores the original EOF functionality (and adds a test to
ensure that functionality doesn't break again). It also checks a line of
csv to see if the annotation actually is an annotation, rather than
data, before trying to parse it as an annotation. If it isn't an
annotation, and we're not expecting data yet, _then_ the "missing
expected annotations" error occurrs.
Additionally, another test for unsupported/ignored annotations was
added.

fix(csv): handled malformed data as well as eof

---

libflux/src/flux/ast/mod.rs
libflux/src/flux/formatter/mod.rs
libflux/src/flux/lib.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/scanner/mod.rs
libflux/src/flux/semantic/mod.rs

This patch add `missing_docs` to the `strict` configuration attribute,
meaning the build will fail if the documentation is missing for any
function or type. As a result, more than 2400 errors were raised.
Additionally, this patch adds the ignore rules for all root modules, and
adds documentation for all functions and types in `lib.rs`.
Fixes #2099

docs(libflux): fail build when docs are missing

---

libflux/src/flux/ast/mod.rs
libflux/src/flux/ast/tests.rs

The go serialization does not serialize the arguments if they are empty,
but the rust deserialization required the arguments to exist for
deserialization to work.

fix(libflux): deserialize call expressions when arguments are missing

---

compile.go
interpreter/interpreter.go
interpreter/package.go
runtime.go
values/option.go

The builtin registration was previously happening incrementally so the
order of how things got registered was uncertain. The registration has
now been changed so it encapsulates the work in a runtime builder struct
and it constructs the final runtime when finalize is called instead of
gradually as the packages are registered.
This also modifies the scope so there is a special `values.Option` which
wraps another value. This signals that a variable was defined in a
package as an option. This allows us to evaluate a flux file and
determine from the scope which values were defined as options and which
as normal variables.
The refactor removes most of the need for the global variables by
encapsulating those globals into a single struct which can be used as if
it were not a global variable. …

refactor(runtime): refactor the builtin registration

---

libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/env.rs
libflux/src/flux/semantic/import.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/tests.rs
libflux/src/libstd/lib.rs

This exposes the builtin polytypes when analyzing a package in the
standard library. It also flattens the builtin map to make it easier to
index. The old code that iterated through flattened the map anyway so it
is easier to read and index if we just refer to each package by their
full package name instead of by each component.

fix(libflux): expose the builtin polytypes when analyzing a stdlib package

---

execute/executetest/compile.go
execute/executor_test.go
execute/row_fn.go
stdlib/universe/filter.go

The unit tests for the execute package are now passing. This required
some fixes to filter which weren't previously capable of being tested
because the filter test cases couldn't be run because of the builtins
not being registered yet.

refactor(execute): execute tests are now passing

---

lang/compiler_test.go

I missed a test case that didn't compile due to the new TableObject updates.

fix: get TableObject test case to compile

---

libflux/src/flux/lib.rs
libflux/src/flux/semantic/check.rs
libflux/src/flux/semantic/mod.rs
libflux/src/libstd/lib.rs

This is a Rust port of the semantic checks that live here in Go:
https://github.com/influxdata/flux/blob/f6d79c9a6635d60f216b0e595acbbefc10ceedd4/semantic/check.go
All the tests are ported as well.

refactor(semantic): add semantic checks to libflux

---

libflux/src/flux/ast/mod.rs
libflux/src/flux/ast/tests.rs

The libflux json deserialization now uses type properly instead of the
untagged property. That causes the enums to consult the type of the enum
instead of trying to do pattern matching.
A consequence of this though is that parts of the AST that hard-code a
specific type, not the enum, won't have their type serialized. But, this
doesn't matter because since the type is hard-coded in both the Go and
Rust AST's, the correct type gets deserialized anyway. The type was
only needed for interfaces anyway.

fix: libflux json deserialization uses type properly

---

libflux/src/flux/semantic/builtins.rs

This just adds a parameter to the builtin `to()` that somehow got omitted.

fix(builtins): add missing parameter to type of "to()"

---

compile_test.go

fix: use LocalRange in compile tests

---

semantic/flatbuffers_test.go
semantic/lookup_test.go
semantic/monotype.go
semantic/polytype.go

This adds a method called `CanonicalString()` to `MonoType` and `PolyType` that returns a string representation of types, with contiguous type variable numbers starting at zero.
A couple of tests were using this to verify correct types, these changes make canonicalization more robust and encapsulates the logic a bit better.
I also fixed an issue with a flatbuffers test where there was a missing function monotype.

refactor(semantic): encapsulate logic for producing canonical strings for types

---

libflux/go/libflux/analyze.go
libflux/go/libflux/parser.go

The go docs for `SetFinalizer` indicate that an object can be garbage
collected even if it is currently within scope as long as the object
itself isn't used anymore. If the garbage collector runs in this
circumstance, it is possible for it to run the finalizer while a cgo
call is happening.
The `runtime.KeepAlive` function forces the compiler to have a reference
to the object until the method is called which forces the object to
remain alive. If this is placed after the call into the C library, it
prevents the handle from being freed while it is in use.

refactor(libflux): use runtime.KeepAlive to prevent finalizer race conditions

---

compile.go
compiler/compiler.go
interpreter/importer.go
interpreter/interpreter.go
interpreter/interpreter_test.go
interpreter/package.go
interpreter/package_test.go
runtime.go
spec_test.go
stdlib/flux_test.go
stdlib/universe/state_count_test.flux
stdlib/universe/state_duration_test.flux
values/objects/table.go
values/option.go
values/package.go
values/scope.go
values/valuestest/scope.go

The previous method for the interpreter was to eval each package and
then keep the package for future use. But each usage involved creating a
clone of the package and it would involve fixing the objects to refer to
the new package objects in order to keep things like options using the
original reference value.
This modifies the workflow so imports are evaluated each time instead of
attempting to share the values. This greatly simplifies the interpreter
code because we no longer have to clone values before execution and
worry about whether we are referring to the correct object.

refactor(interpreter): modify the interpreter to eval imported packages each time

---

compile.go
libflux/src/flux/semantic/builtins.rs
plan/logical_test.go
plan/plantest/cmp.go
querytest/compile.go
semantic/semantictest/cmp.go
values/valuestest/scope.go

When comparing `ProcedureSpec` objects as we do in planner tests, we need to compare `ResolvedFn` members for stream functions that use lambdas.  `ResolvedFn` contains a scope that has all of the `universe` and `influxdb` packages.  Comparing scopes works just fine, but when there are differences, producing the human-readable diff takes a long time, and this was causing some of the planner and `QueryTest` tests to appear to hang.

fix(valuestest): replace ScopeComparer with ScopeTransformer

---

compiler/compiler.go
compiler/runtime.go
interpreter/interpreter.go
libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/nodes.rs
semantic/flatbuffers_gen.go
semantic/graph.go
stdlib/universe/map.go
values/values.go

This contains various fixes to the stdlib to make the tests pass with
algorithm w. It updates some of the builtins with the correct type
signature. Some of them did not match the Go code.
It updates `map` to work with compiled functions.
It also updates an end to end test which relied on polymorphic literals.

refactor: various stdlib fixes for algorithm w

---

stdlib/influxdata/influxdb/monitor/monitor.flux

Type inference cannot unify an explicitly empty object with a non empty object. Using a default didn't make sense anyway as the data is required.
Fixes #2456

fix(monitor): remove default value from notify data as it is required

---

libflux/src/flux/lib.rs
libflux/src/flux/semantic/builtins.rs

We use the builtins to type the standard library, which happens at build time, so this was keeping libflux from building.

fix(builtins): fix typo in builtins

---

libflux/src/flux/semantic/tests.rs

Recently a change was made to not constrain the operands of a binary comparison
operator to be of equal types. This commit updates the tests that failed as a
result of that change.

fix(libflux): type inference tests for binary comparison operators

---

execute/row_fn.go
stdlib/universe/reduce.go
stdlib/universe/reduce_test.go
stdlib/universe/union.go
values/values.go

This fixes reduce so it works with the refactored row functions and
algorithm w.
This also changes union to expect an array of arrays instead of an array
of objects. This is because table streams are now represented in the
type system with arrays instead of table objects.

refactor(stdlib): fix reduce implementation for algorithm w

---

libflux/src/libstd/lib.rs

The `==` operator no longer requires both operands to be of the same type.
The commit updates the test in libstd accordingly and also adds one for
union.

fix(libstd): update type inference test case - add one for union

---

stdlib/universe/derivative.go
stdlib/universe/derivative_test.go
stdlib/universe/difference_test.go

The `derivative()` function would improperly compute the derivative if a
series was split across multiple buffers. In that case, it wouldn't keep
the previous value from the last buffer and it would select the first
value from each buffer to be used as the previous value. In the case of
a single row, it would constantly discard the output.
This also adds tests to `difference()` to ensure it doesn't contain the
same bug. It does not.
Fixes #2298.

fix(stdlib): derivative works properly across multiple buffers

---

.dockerignore
Dockerfile_release

This patch adds the start of a Dockerfile to be used for releasing flux,
complete with cross compilers for all triples except
`x86_64-apple-darwin` and `x86_64-pc-windows-gnu`, which require a bit
more setup.
The intent here is to start with the Dockerfile, add support for using
`pkg-config` (and ditching `flux-config`), and being able to build flux,
including `libflux`, for any architecture by invoking `go build`. This
docker image will be used similar to `Dockerfile_build` is converted
into `quay.io/influxdb/flux-build`.

feat: create a docker environment for flux release

---

libflux/src/flux/semantic/tests.rs
libflux/src/flux/semantic/types.rs

fix: allow array and row types to be equatable

---

libflux/src/flux/ast/mod.rs

The go code will serialize an empty array as null sometimes and the rust
code needs to accept that.

fix: deserialize the default vector if array elements are null

---

stdlib/slack/flux_gen.go
stdlib/slack/slack.flux
stdlib/slack/slack_test.go

The Slack notification rule apis have some fields that no longer used by InfluxDB. There are unification errors caused by the presence of these fields in the Flux api. We are removing these fields to see if that fixes type checking.

fix(stdlib): remove unused notification rule fields from slack api

---

semantic/ast.go
semantic/ast_test.go

This allows converting semantic nodes back to ast nodes. The original
structure of the ast nodes cannot be restored because information is
lost when converting from ast to semantic, but the structure can be
recovered so that it can be transformed back into semantic.
This method will succeed when comparing:
semantic -> ast -> semantic
It will not succeed when doing:
ast -> semantic -> ast
Fixes #2530.

feat(semantic): transform semantic nodes back to ast nodes

---

lang/dependencies.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go

In the repl, a tablefind result that is captured to a variable, then used in a
map or a filter, causes the repl to attempt to execute a query. It fails with a
panic when it attempts to get the execution context.
A proper solution is part of a bigger design discussion. This patch simply
fails the query gracefully so we can identify the problem more easily and cause
less confusion. The user can be directed to execute on the server process when
encountering this issue.
Design discussion: https://github.com/influxdata/influxdb/issues/13976
Users experiencing this problem: #2442 #2387
Docs: https://github.com/influxdata/docs-v2/issues/735

fix: fail gracefully when tableFind does not have an execution context

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
interpreter/interpreter_test.go
repl/repl.go

The querier interface will no longer work properly for algorithm w and
so it has been removed in favor of implementing the needed functionality
within the repl itself.
This removes the querier interface which is now dead code.

refactor(repl): remove the querier interface

---

ast/errors.go
ast/errors_test.go

Errors in the AST are represented as a simple wrapper around a `string` and have no code.  When we return errors to callers, we wrap them in our `errors.Error` struct with `code.Inherit`.  But since the underlying error has no code, we defaulted to `codes.Internal` for errors in the AST.  This change just forces the code to be `codes.Invalid`, since errors in the AST result from parse errors in invalid Flux source code.

fix(ast): properly categorize parse errors as "invalid"

---

colm/flux.lm
colm/influxql.lm
colm/parseflux/.gitignore
colm/parseflux/Makefile
colm/parseflux/input.flux
colm/parseflux/parseflux.lm
colm/transpile/.gitignore
colm/transpile/Makefile
colm/transpile/q01.ql
colm/transpile/q02.ql
colm/transpile/q03.ql
colm/transpile/q04.ql
colm/transpile/q05.ql
colm/transpile/q06.ql
colm/transpile/q07.ql
colm/transpile/q08.ql
colm/transpile/q09.ql
colm/transpile/q10.ql
colm/transpile/q11.ql
colm/transpile/q12.ql
colm/transpile/q13.ql
colm/transpile/query.ql
colm/transpile/run
colm/transpile/transpile.lm

This patch adds a colm-based grammar for Flux, derived from the SPEC. It also
adds a partial grammar for InfluxQL, with a focus on the SELECT statement.
Also added is a colm-based transpiler experiment, with limited functionality.
It is useful for experimenting with transpiler techniques. The transpiler:
1. Extracts time constraints from the where clause.
2. Adds filters using measurement, where clause and select clauses.

feat: initial grammar for flux and a partial grammar for influxql

---

stdlib/flux_test.go

These tests used to hang but are no longer. One test (storage) was
kept skipped as it is failing now with another error (map type error).

test(stdlib): unskip usage tests

---

lang/compiler_test.go
plan/logical_test.go
plan/plantest/rules.go
plan/rules_test.go
stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/rules_test.go

The error messages for the influxdb source have been improved to give
better hints about what to do when rules cannot be rewritten to the
proper physical forms for whatever reason.

refactor(stdlib): improve the post physical validation error messages for the influxdb source

---

stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/from_test.go
values/time.go

The duration literal `AsValues()` function was confusing. It would
write the values as negative magnitudes, but there was another portion
of code that would then use the unary negative operator on those values
when resolving times.
Instead of confusingly serializing negative magnitudes, which isn't done
by the parser, the `AsValues()` method has been changed to only use
positive magnitudes and the sections of code that turn that into a
literal have been changed to use the unary negative operator.

fix(stdlib): influxdb source would serialize the wrong sign duration literal

---

compiler/compiler.go
compiler/runtime.go
execute/row_fn_test.go
interpreter/interpreter.go
interpreter/package_test.go
lang/compiler.go
runtime/builtins_test.go
runtime/runtime.go
runtime/runtime_test.go
values/function.go
values/values.go

This PR fixes the remaining algow TODOs and removes the ones that are no longer relevant. Non-blocking TODOs (such as user-defined packages and binary operator constraints) still remain with their issues linked.
Closes https://github.com/influxdata/flux/issues/2586.

fix: remove algow todos

---

cmd/flux/cmd/compile.go
compiler.go
complete/complete.go
internal/cmd/refactortests/cmd/refactortests.go
internal/cmd/test_rewriter/main.go
internal/spec/build.go
internal/spec/build_test.go
lang/compiler.go
lang/compiler_test.go
lang/dependencies.go
lang/query_test.go
plan/logical_test.go
plan/rules_test.go
querytest/compile.go
querytest/execute.go
repl/compiler.go
repl/repl.go
runtime.go
runtime/global.go
runtime/runtime.go
stdlib/flux_test.go
stdlib/pagerduty/pagerduty_test.go
stdlib/slack/slack_test.go
stdlib/universe/typeconv.go

The lang package has been refactored to refer to the runtime using the
`flux.Runtime` interface instead of direct references. This prevents it
from have a dependency on the runtime and allows the structs to be used
without incurring a dependency on the runtime.
The `flux.Runtime` interface has been created to facilitate access to
the runtime. It is a wrapper around the existing runtime struct that is
in the `runtime` package.
The `complete` package has also had its reference to the runtime
removed. It was only used by one convenience method so that method has
been removed.
Fixes #2595.

refactor(lang): remove dependency on runtime

---

compiler/compiler_test.go
compiler/runtime.go
execute/row_fn_test.go
stdlib/universe/table_fns_test.go

In the case of the influx query command, it is possible for a nil scope to be
present in the Spec. In this case the system attempts to build a
compiler.compilerScope using a nil value.Scope as the embedded anonymous field,
resulting in an eventual panic when passed to interface methods that use it as
the receiver object.
Instead return nil when attempting to use nil as the base scope,
indicating there is no scope. The function evaluation copes with with this and
creates an empty scope if none is present.
refs influxdata/influxdb#17062

fix: don't construct a compiler.compilerScope with a nil value.Scope

---

mock/compiler.go

refactor: mock compiler needs to implement the compiler interface

---

.gitignore
Makefile
libflux/c/main.c
libflux/go/libflux/flux.h
libflux/include/influxdata/flux.h

This creates a simple program that exercises our C API, and adds some targets to our Makefile to build it and run it in valgrind.
Fixes #2289.

test(libflux): C program for exercising C API

---

Dockerfile_build

This just adds valgrind to the build container, so it can run in CI.  I seem to recall that we need to to update the build container and merge to master before anything we add to it can be used.

chore: add valgrind to build container

---

libflux/c/main.c
libflux/go/libflux/analyze.go
libflux/go/libflux/flux.h
libflux/go/libflux/parser.go
libflux/include/influxdata/flux.h
libflux/src/flux/build.rs
libflux/src/flux/lib.rs
libflux/src/libstd/lib.rs
stdlib/README.md

This PR updates the Go/Rust API to address memory leaks found by valgrind.
It turns out that the Rust source code generated from `flux.h` by bindgen was mostly unused, so I removed it.
We were not actually freeing memory allocated from Rust in calls to `flux_free` from the Go side because freeing `void*` doesn't let the Rust compiler know that it should also free pointer fields embedded within structs.
To address this I created separate `flux_free*` functions for each unique type that must be freed.  I tried to use `Box<dyn Any>` to work around this, but `Any` is not sized, so it didn't work right. See the documentation for `std::boxed`, linked just below, for details.
I based these changes on material here:
https://doc.rust-lang.org/std/boxed/index.html#memory-layout
And here: …

fix(libflux): simplify libflux C API and resolve memory leaks

---

.circleci/config.yml
Makefile

This just adds a new job called `test-valgrind` to the CircleCI config.

test: add test-valgrind to CI

---

libflux/site/package.json
libflux/site/yarn.lock

The current version of `webpack` that is installed depends on an insecure
version of `serialize-javascript`.
This was discovered by running `yarn why serialize-javascript`.
```
$ yarn why serialize-javascript
yarn why v1.19.1
warning package.json: No license field
[1/4] 🤔  Why do we have the module "serialize-javascript"...?
[2/4] 🚚  Initialising dependency graph...
warning No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "serialize-javascript@1.7.0"
info Reasons this module exists
- "webpack#terser-webpack-plugin" depends on it
- Hoisted from "webpack#terser-webpack-plugin#serialize-javascript"
✨  Done in 0.30s
```

chore(libflux/site): bump version of webpack

---

stdlib/universe/pivot.go

Fixes https://github.com/influxdata/flux/issues/2592.
The query engine's internal message queue requires that for every
dataset ID, `process` messages are pushed first and `finished`
messages pushed last. The optimized version of pivot invalidated
this requirement.
This commit fixes pivot so that `watermark` and `processing time`
messages are sent downstream after `process` messages.
Note the message queue itself should error if it recognizes that
the above invariant has been violated.
See https://github.com/influxdata/flux/issues/2623.

fix(stdlib): pivot message passing

---

.gitignore
README.md
libflux/go/libflux/gen.go
libflux/go/libflux/genhack.sh
libflux/go/libflux/hack.gen.go.tmpl

A generate script has been added that will inject the current time into
the libflux go wrapper to force Go to recompile the wrapper. This will
force `pkg-config` to rerun and ensure that Go is using the version of
the Rust code from the current directory.
The output of the script is never meant to be checked into version
control and isn't listed on the list of build outputs. It will never be
up to date because the output isn't consistent.
This is a hopefully temporary hack until we get a better method of
generating this output in a way that is consistent. But, this is being
done because it is the easiest method of forcing a build and this
problem only occurs when building locally from source.
Fixes #2511.

fix(libflux): force the go libflux wrapper to rebuild using go generate

---

libflux/go/libflux/parser_test.go
libflux/src/flux/lib.rs

This just allows us to merge packages that have no package clauses, which is commonly the case for the web UI.
Fixes #2622.

fix(libflux): make merge_packages allow no package clauses

---

libflux/c/main.c
libflux/go/libflux/parser.go
libflux/go/libflux/parser_test.go
libflux/include/influxdata/flux.h
libflux/src/flux/ast/check/mod.rs
libflux/src/flux/ast/check/tests.rs
libflux/src/flux/lib.rs

This adds a `flux_ast_get_error()` to the libflux API to get the first error from an AST. We'll need this to return errors to users without deserializing the AST.

refactor(libflux): add method to retrieve errors from AST

---

stdlib/influxdata/influxdb/testing.go

As part of some work, some code was in that file. During development and
testing, that code was moved to a different file and package and this
file was left empty. It was accidentally left inside of the PR even
though it had no content.
Removing this file as it was never supposed to be committed.

refactor: remove an empty file from the influxdb package

---

Dockerfile_release
go.mod
go.sum

This patch adds all the tools and configuration needed to cross compile
flux from a docker container. The image generated from
`Dockerfile_release` can be used with goreleaser to build final binaries
for all the linux targets (windows and macOS binding still TBD)

feat: add all linux cross to release docker image

---

lang/compiler_test.go
libflux/go/libflux/analyze_test.go
libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/fresh.rs
libflux/src/flux/semantic/infer.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/parser/mod.rs
libflux/src/flux/semantic/tests.rs
libflux/src/flux/semantic/types.rs
libflux/src/flux/tests/analyze_test.rs
runtime/analyze_libflux_test.go
runtime/runtime_test.go
semantic/flatbuffers_test.go

This PR adds source location to type error messages. Note there appears to be a lot of additions. Most of them come from `rustfmt` in `nodes.rs` where I have added `SourceLocation` to each type constraint.
I have also updated record and function unification in `types.rs`. The unification process hasn't changed, but I have updated the code to give more descriptive error messages.

feat: add location information to type error messages

---

libflux/Cargo.lock
libflux/src/flux/Cargo.toml

This patch updates the flatbuffers dependency from `0.6.0` to `0.6.1`.
The `0.6.0` version of flatbuffers had a vulnerability in it where it
read arbitrary bytes as a bool. This resulted in [RUSTSEC-2019-0028](https://rustsec.org/advisories/RUSTSEC-2019-0028)
being filed, as it could potentially result in undefined behavior.
Version `0.6.1` has a fix for this specific issue.

fix: update flatbuffers dependency

---

Makefile

This changes the valgrind test to use static linking. It makes our test link methods align with production and allows us to convert HashMaps to BTreesMaps in the semantic package without breaking the test.
When dynamic linking, the distinct data segments between the two libs causes problems for the BTreeMap, which is using a static var deep in it implementaiton.
Related to #2636, #2585 and #2655. Is the first step in applying #2657

fix: use static linking when creating the valgrind test

---

.circleci/config.yml
.goreleaser.yml
go.mod
go.sum

`goreleaser` uses the `flux-build` image and will perform cross
compilation using rust and cgo.
Fixes #2245.

ci: goreleaser cross compilation

---

libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/check.rs
libflux/src/flux/semantic/env.rs
libflux/src/flux/semantic/flatbuffers/types.rs
libflux/src/flux/semantic/fresh.rs
libflux/src/flux/semantic/import.rs
libflux/src/flux/semantic/infer.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/nodes.rs
libflux/src/flux/semantic/parser/mod.rs
libflux/src/flux/semantic/sub.rs
libflux/src/flux/semantic/tests.rs
libflux/src/flux/semantic/types.rs
libflux/src/flux/tests/analyze_test.rs

The artifacts of Algorithm W, specifically the final fresher value and the TVar
values in the envrironment, were changing from run-to-run of the algorithm.
This was a result of use of HashMap in Algo W, probably caused by an iteration
embedded in the algorithm. Since the environment is serialized and included in
each build, we lost repeatable builds.
This patch adds type aliases for all hash maps in the semantic package and then
changes the type to BTreeMap. This stabilizes the algorithm and gives us
repeatable builds.
This patch changes all hash maps to btree maps. It is possible that a more
selective switch would suffice, however there is some common generic code
shared among the map types (found in use of the SemanticMap type). That code
would need to be cloned to complete a selective …

fix: convert HashMap in semantic package to BTreeMap (#2585)

---

Makefile
lang/compiler.go
lang/compiler_test.go
libflux/go/libflux/parser.go
parser/parser.go
parser/parser_test.go
runtime.go
runtime/analyze_libflux.go
runtime/global.go
runtime/parse.go
runtime/runtime.go
semantic/format_test.go
stdlib/flux_test.go
stdlib/pagerduty/pagerduty_test.go
stdlib/slack/slack_test.go

Also, make FluxCompiler and ASTCompiler use json.RawMessage instead
of *ast.Package, so deserialization can be delayed.

refactor: refactor eval methods to avoid roundtrips

---

stdlib/universe/filter.go

This patch addresses an issue where the semantic graph changed and the
logic for detected `BooleanLiteral` function expresses that return
`false` and removes them.
Fixes #2661

fix: address issues in RemoveTrivialFilterRule

---

lang/compiler.go
lang/compiler_test.go

The implementations of `Compiler` contain an `Extern` field that is a `json.RawMessage`.  If there is data present, then we need to wrap the file in a package for it to be deserialized by Rust.
The problem was that it is valid JSON to put the `null` keyword in the `Extern` field, but when we wrap `null` in a package, Rust's JSON unmarshaling complains that it's expecting a `File`.
The fix is to not attempt to unmarshal if the `Extern` field is set to a `null` JSON literal.

fix: make compilers robust to "null" keyword in extern field

---

lang/compiler.go

The converting a byte slice to a string can be expensive and result in a memory allocation, so I just added a length check before doing it, in case the slice was large.

fix: add length check to avoid allocs checking for JSON "null"

---

go.mod
go.sum

The mainline pkg-config now has the one-crate patch merged in, which is
is now necessary to build on the use-algo-w branch.

refactor: go back to mainline pkg-config

---

libflux/go/libflux/parser_test.go
libflux/src/core/ast/mod.rs
libflux/src/core/ast/tests.rs
parser/parser_test.go

If we serialize the Flux empty object `{}` from Go, and deserialize in Rust, an error occurred because the JSON contained `null` for the properties.  This fixes that and some other minor issues, and adds tests.

fix(libflux): tweak Rust JSON serialization and add tests

---

.gitignore
Makefile
libflux/c/.gitignore
libflux/c/Makefile

Also moved the Makefile rules for the valgrind testing to libflux/c.
Fixes #2657

feat: added a dynamically linked valgrind test

---

libflux/src/flux/ast/check/tests.rs
libflux/src/flux/ast/flatbuffers/tests.rs
libflux/src/flux/ast/mod.rs
libflux/src/flux/ast/tests.rs
libflux/src/flux/ast/walk/mod.rs
libflux/src/flux/formatter/mod.rs
libflux/src/flux/formatter/tests.rs
libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/tests.rs
libflux/src/flux/scanner/mod.rs
libflux/src/flux/scanner/tests.rs
libflux/src/flux/semantic/convert.rs

Collecting comments during scanning and storing them in the AST. Including the
comments in AST formatting. In general, comments are placed on their own line
and are therefore assumed to apply to the code that follows. Updates to the
formatting rules can be added as desired.
Comments are collected in the scan function, where they were previously
discarded. The comments are arranged into a linked list as they are encountered
and then attached to the next real token that is generated by the parser.
Comments at the end of the file are attached to the EOF token.
During parsing, these comments are extracted from the tokens and stored in the
AST, generally at locations where the tokens they were attached to would be
stored in the AST, if they were kept. This requires adding comment list …

feat: storing comments in the AST and preserving on format

---

.circleci/config.yml
Makefile
stdlib/universe/filter_test.go

1. Run static checking in two passes. As of this commit, running on everything
uses just over 4G of memory. Breaking stdlib out keeps memory under 3G.
2. Reduce the number of iterations of BenchmarkFilter_Values. Brings memory
usage of benchmarking down from 3.8 to ~ 2G.
3. Use -p=1 for the benchmarking. The Filter_Values benchmark uses over 2G,
sometimes compiling and doing other things can fail if also run while this test
is going.

fix: reduce memory usage during CI testing

---

execute/executetest/compile.go
interpreter/interpreter_test.go
plan/format_test.go
plan/logical_test.go
semantic/flatbuffers_test.go
semantic/graph.go
stdlib/experimental/bigtable/bigtable_rewrite.go
stdlib/experimental/bigtable/bigtable_test.go
stdlib/universe/filter.go
stdlib/universe/filter_test.go

The tests using semantic graph will now use the rust analyzer so that
the semantic graph is the same as the one constructed from the rust
analyzer. This will make our tests more robust.
This also fixes the `bigtable` package to use the same technique as the
other filter push downs when evaluating the expression. It also moves
the code to retrieve the simple expression to a method function so it
can be reused in multiple locations.
This does not remove all usage of semantic graph. There are still some
flatbuffers tests that need semantic graph to be hand-written since the
tests are valid and testing the deserialization of the graph. After
those are hand-written, we can remove `semantic.New` and the tests for
testing `semantic.New`.
Fixes #2664.

tests(semantic): update tests using semantic graph to use the rust analyzer

---

libflux/src/flux/semantic/convert.rs

These test cases ensure that errors and not panics are produced when BadExpr and BadStmt are encounred in the AST

fix(libflux): add test case for errors when AST is bad

---

execute/group_lookup.go
execute/group_lookup_test.go
internal/execute/table/buffered_builder.go
internal/execute/table/builder_cache.go
internal/execute/table/dataset.go

The random access group lookup is a group lookup that works better with
random access rather than sorted inserts. It creates a key and then
indexes into that key rather than attempting to keep the group lookup
sorted.
This is a partial reapplication of 922f531 by only reapplying the parts
that allowed multiple group lookup implementations but doesn't include
the window changes.

feat(execute): add random access group lookup

---

lang/compiler_test.go
libflux/go/libflux/analyze_test.go
libflux/src/core/lib.rs
libflux/src/core/semantic/bootstrap.rs
libflux/src/core/semantic/infer.rs
libflux/src/core/semantic/mod.rs
libflux/src/core/semantic/nodes.rs
libflux/src/core/semantic/tests.rs
libflux/src/core/semantic/types.rs
runtime/analyze_libflux_test.go
runtime/runtime_test.go
semantic/flatbuffers_test.go

Updates the error type in `types.rs` and `nodes.rs` to be an enum. Also gives a better error message in the case of a missing record label.

fix(semantic): more descriptive error messages

---

execute/group_lookup.go
execute/group_lookup_test.go

When `GroupLookup` needs to insert an item in the middle of a group key,
it must split it into to group keys. When the split happens, the
`deleted` property is not decremented for items moved to another
`groupKeyList`. This patch decrements for those items.

fix: address deleted state GroupLookup

---

libflux/src/core/formatter/mod.rs
libflux/src/core/semantic/flatbuffers/types.rs

This patch makes a (very) small performance change by embracing
iterators in rust, making it more idiomatic.
Consider the following:
for i in 0..my_vec.len() {
let value = my_vec.get(i).unwrap();
// do something with value
}
Since rust prioritizes safety, a call to `get` does a bounds check in
both directions on each call. For a small vector, that's probably not
too much of a performance hit, but a larger sampling would certainly see
the impact of those continued bounds checks. By using rust's iterators,
one can guarantee the safety of the operation with the bounds checks
around `get` as well as the potential runtime failure of `unwrap`.

feat(libflux): add small performance optimizations

---

stdlib/testing/diff.go

This patch changes `DiffTransformation` to use
`execute.RandomAccessGroupLookup` for its cache. Since
`DiffTransformation` treats group lookup like a map, where it might not
have the groups in order, `RandomAccessGroupLookup` is better for the
transformation.
Fixes #2700

fix: use RandomAccessGroupLookup in testing.diff

---

compiler/compiler.go
compiler/runtime.go
stdlib/universe/map_test.go

Fixes https://github.com/influxdata/flux/issues/2690.
The identify function's type is `forall [t0] (r: t0) -> t0`. However when evaluating the identity function inside `map`, we instantiate it with a new type for every table. Previously we were not using the instantiated type and so `map` would error when it saw a type variable as the output type. Now `compiledFn` returns the instantiated type as its return type.

fix(compiler): compute function's return type after substitution

---

libflux/Cargo.lock
libflux/src/flux/Cargo.toml
libflux/src/flux/benches/builtins.rs

This patch adds a small number of benchmark tests. It takes the flux
from the builtin string tests and runs it through the parser. Criterion
is a library for handling the bench tests, which backports the benchmark
tooling in rust nightly to stable rust.
This patch is mostly to start a conversation about how `libflux` can be
profiled and how patches might be able to ensure changes don't have
performance regressions in them.

test(libflux): add a small set of benchmark tests

---

libflux/go/libflux/parser_test.go
libflux/src/flux/lib.rs

Fixes an issue with package clauses where one file had `package main` and the other had no package clause.  In this case we would not merge the packages. Since `package main` is implied, this should succeed.
I also updated the error messages to include source location info.

fix(libflux): fixed logic for merging packages with no package clause

---

interpreter/interpreter.go
stdlib/universe/contains.go
stdlib/universe/contains_test.go

The contains function would throw an error if called with an empty set. Since
the set can be computed by other functions, which may supply an empty set, it
makes sense to simply return false.

feat: return false if contains is called with an empty set

---

Makefile

This patch adds `cargo bench` to the `test-bench` make target.

chore: add rust bench tests to test-bench target

---

docs/SPEC.md
libflux/src/core/semantic/builtins.rs
stdlib/universe/flux_gen.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go
stdlib/universe/universe.flux

Add findColumn and findRecord functions, which are semantically equivalent to
```
tableFind(...) |> getColumn(...)
tableFind(...) |> getRecord(...)
```
Except that they are allowed to not find a table, column or record. In these
cases they return an empty array or an empty object. The tableFind and friends
functions will return an error in these cases.
The rationale for combining these two steps into one is that it eliminates the
need to return something from tableFind which represents "no table found".
Doing that means we need to enhance the type system with a concept of a table
(not a stream) so we can prevent this thing from becomming the input to other
functions. This is a bigger undertaking and can be considered part of the next
generation of flux. Combining the two functions into …

feat: add findColumn and findRecord functions

---

docs/SPEC.md

Previously type checking could not determine when an object property was missing as it assumed all records could have any fields.
Now there are cases where we know that an object is bounded and explicitly does not contain a property.
In those cases we can now report a type checking error.
Closes #2532

docs(SPEC): update SPEC for new type checking behavior

---

docs/NewFlux_Comentary.md

This PR adds a doc that adds commentary on the new Flux design. The intent of the document is to help seed how this would work in the context of existing Flux features and start a more informed discussion among the Flux team.

docs: add commentary on new Flux design

---

libflux/src/core/semantic/convert.rs
libflux/src/core/semantic/flatbuffers/mod.rs
libflux/src/core/semantic/infer.rs
libflux/src/core/semantic/nodes.rs
libflux/src/core/semantic/walk/_walk.rs
libflux/src/core/semantic/walk/walk_mut.rs

Semantic nodes for bad statement and bad expression have been added so
that bad statement and bad expression can be translated into the
semantic graph. They contain the location information and a list of
errors that are associated with the inner statement or expression.
Fixes #2708.

feat(semantic): add semantic nodes for bad statement and bad expression

---

libflux/src/core/semantic/convert.rs
libflux/src/core/semantic/flatbuffers/mod.rs
libflux/src/core/semantic/infer.rs
libflux/src/core/semantic/nodes.rs
libflux/src/core/semantic/walk/_walk.rs
libflux/src/core/semantic/walk/walk_mut.rs

This reverts commit 7ce9cef4eaacffbf9265f7675c2ac84f794676c2.

revert: add semantic nodes for bad statement and bad expression

---

stdlib/math/math.go
stdlib/math/math_test.go

Flux has typed nulls, meaning it is insufficient for functions in the `math` package to just assert that input values are of the expected type. They must also handle null values explicitly.

fix(math): functions do not panic on null values

---

lang/compiler.go
lang/compiler_test.go
plan/builder.go
plan/heuristic_planner.go
plan/heuristic_planner_test.go
plan/logical.go
plan/logical_test.go
plan/physical.go
plan/physical_test.go
plan/plantest/rules.go
plan/rules.go
plan/rules_test.go
plan/types.go
repl/compiler.go
stdlib/experimental/bigtable/from.go
stdlib/universe/filter.go
stdlib/universe/group.go
stdlib/universe/window.go
stdlib/universe/window_test.go

This changes the planner rule interface to pass the context to the
rewrite rules so the planner has access to any of the dependencies that
are present.
Fixes #2755.

feat(plan): pass the context to the rewrite rules in the planner

---

cmd/calls/main.go

Added a program that can be used in packages that consume flux to determine
what the entry points are. It lists flux functions and their call points from
outside flux. It excludes:
* init functions
* anonymous functions
* methods on objects
It is based off the callgraph program from go/tools.
https://github.com/influxdata/influxdb/issues/17789

feat: static analysis tool for listing entry points to flux

---

compiler/compiler.go
semantic/monotype.go
stdlib/universe/map_nulls_test.flux

Fixes an issue where `map` would drop a column if the first value in that column was null. The following query exhibited the bug:
```
... |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
|> map(fn: (r) => ({_time: r._time, _value: r.a / r.b}))
```
Flux cannot infer the type of any expression following pivot. It waits till it gets an input record and calculates the output type from there. The type substitution that was constructed to do this was not applied fully to all types in map's lambda function, resulting in an unknown type which was subsequently dropped by `map`. The type substitution is now being applied fully to all types.

fix(compiler): apply substitution fully when compiling lambda

---

stdlib/system/time.go
stdlib/system/time_test.go

`system.time()` did not check its context to see if the `now` time was overridden. This meant tasks as well as any other external system could not override the default `now` time.

fix(stdlib/system): system.time() should check context for override

---

repl/repl.go

Upon the merge from master into algo-w, this work was lost in a merge
conflict resolution, because algo-w is diverging more and more from
master. The change was originally in #2759. This patch restores that
functionality while making the change slightly more compact.

fix: support execution contexts in the repl

---

plan/heuristic_planner.go
plan/pattern.go
plan/plantest/rules.go
plan/registration.go
plan/rules_test.go

Modified the planner Pattern interface to supply a set of ProcedureKind roots.
The pattern matcher adds the rule to multiple entries in the root-kind -> []rule
map.
The OneKindPattern was modfied to store a set of roots and was renamed to
UnionKindPattern. It is still used to implement plan.Pat and is now also used
to implement plan.UnionPat.
This change lets us create a pattern that is rooted at a set of ProcedureKind,
allowing us to make a single rule covering many window-aggregate combinations.

feat: planner Pattern interface supplies a set of ProcedureKind as root

---

stdlib/gen.go

A change to the standard library generally involves recompiling libflux.
Instead of requiring the developer to remember that, this changes the
`go generate` step for stdlib to trigger a generate for libflux to force
a rebuild.
This hack will be needed until we consolidate the standard library
either into only Go or only Rust.

fix(stdlib): run go generate on libflux when go generate is run on stdlib

---

libflux/src/core/semantic/builtins.rs
stdlib/experimental/chain.go
stdlib/experimental/chain_test.go
stdlib/experimental/experimental.flux
stdlib/experimental/flux_gen.go

This function adds a `chain` function for executing two queries, where
the first query produces a side effect needed by the second query.
Fixes #1799

feat: add experimental chain function

---

stdlib/universe/window.go

Complete the Copy() function of WindowProcedureSpec. This is necessary for the 
PushDownWindowAggregate rewrite rule tests to pass.

fix: copy all fields of WindowProcedureSpec in Copy()

---

plan/plantest/rules.go

If supplied, the logical and physical planner test helpers will use the context,
otherwise they will use context.Background()

feat: add a context to plantest.RuleTestCase

---

execute/group_lookup_test.go
execute/table_test.go
internal/gen/input.go
internal/gen/input_test.go
stdlib/internal/gen/tables.go
stdlib/universe/filter.go
stdlib/universe/filter_test.go
stdlib/universe/group_test.go
stdlib/universe/limit_test.go
stdlib/universe/pivot_test.go

The filter transformation reused the same function between multiple
table process calls. This shared state meant that multiple tables could
be processed at the same time and use the same state when processing
rows within the tables.
The filter transformation should be fixed to use distinct state for each
table. There's no reason why they need to share state and it is not for
performance. It is an oversight from the original design which doesn't
process tables concurrently. But, that code is more complicated than the
process code so it is easier for us to prevent multiple tables from
being processed in filter. This prevents the race condition by
preventing multiple tables from being processed at the same time.
This also addresses a similar problem in the `internal/gen` package.
The table …

fix(stdlib): fix concurrent map write in filter transformation

---

docs/StandardLibrary.md
stdlib/influxdata/influxdb/v1/flux_gen.go
stdlib/influxdata/influxdb/v1/flux_test_gen.go
stdlib/influxdata/influxdb/v1/measurement_field_keys_test.flux
stdlib/influxdata/influxdb/v1/show_field_keys_test.flux
stdlib/influxdata/influxdb/v1/v1.flux

Introduces `fieldKeys()` and `measurementFieldKeys()` into the v1 package for querying lists of fields in a bucket/measurement. These provide graceful equivalents to `SHOW FIELD KEYS` in InfluxQL.

feat(stdlib/v1): add fieldKeys and measurementFieldKeys to v1 package

---

stdlib/experimental/http/get_test.go
stdlib/experimental/http/http_experimental.go

This patch ensures that DNS information is not disclosed via DNS
validation failures or raw lookups (where the DNS server address is
added to the error message).

fix: do not disclose dns info in http

---

dependencies.go
dependencies/http/http.go
dependencies/http/http_test.go

This patch uses dependency injection to add the url validator to the
http client.
Fixes #2841

fix: inject the url validator into NewDefaultClient

---

stdlib/influxdata/influxdb/from.go

`influxdb.fromRemote()` was not setting bounds the way that normal `from() |> range()` does. This PR implements `TimeBounds` for `influxdb.fromRemote()` so that bounds are properly set in the REPL and can be passed to downstream transformations like `window()`. 
Closes influxdata/influxdb#17458.

fix(stdlib/influxdb): implement TimeBounds for influxdb.fromRemote

---

stdlib/planner/bare_agg_eval_test.flux
stdlib/planner/bare_agg_push_test.flux
stdlib/planner/flux_test_gen.go

This adds a Flux end-to-end test that ensures that the rule for pushing down bare aggregates gets the right answer.
Related to https://github.com/influxdata/influxdb/issues/17994

test(stdlib): add flux end-to-end test for bare agg push down

---

lang/compiler_test.go
libflux/go/libflux/analyze_test.go
libflux/src/core/semantic/infer.rs
libflux/src/core/semantic/nodes.rs
libflux/src/core/semantic/tests.rs
libflux/src/core/semantic/types.rs
runtime/analyze_libflux_test.go
runtime/runtime_test.go

Fixes https://github.com/influxdata/flux/issues/2808.
Previously if a function was not passed the required arguments it was expecting an error would be presented of the form:
```
missing required argument ...
```
Constraints now have an expected and an actual type which means we can now distinguish between a function that was passed too few arguments vs too many.

refactor: constraints now have an expected type

---

values/object.go
values/object_test.go

The previous implementation ignored differences in the field names of objects

fix(values): fix bug in object equal method

---

libflux/src/core/ast/mod.rs
libflux/src/core/semantic/flatbuffers/types.rs
libflux/src/core/semantic/nodes.rs
libflux/src/flux/lib.rs
stdlib/planner/flux_test_gen.go
stdlib/planner/window_group_agg_eval_test.flux
stdlib/planner/window_group_agg_push_test.flux

Closes influxdata/idpe#7118.
There were some clippy linter errors in this update. It seems like this might be due to a recent patch release.
Two were easily resolved through code changes. One required disabling the rule.
New issue to reenable that clippy linter rule #2869.

test(stdlib/planner): add end to end test for group window aggregate

---

libflux/Cargo.lock
libflux/src/core/Cargo.toml
libflux/src/core/ast/mod.rs
libflux/src/core/lib.rs
libflux/src/core/semantic/flatbuffers/types.rs
libflux/src/flux/build.rs
libflux/src/flux/lib.rs

Just needed an update of the `derivative` crate. Also removed a few redundant imports as required by clippy. 
Undoes this blanket `allow`: https://github.com/influxdata/flux/pull/2868/files#diff-206e3b6ebbc29523ed43fdcacc3d52e7
Closes #2870.

fix(libflux/src): reenable clippy linter rule match single binding

---

stdlib/date/date.go
stdlib/date/date_test.go

This patch modifies the errors returned by the data package to use `errors.New` rather than `fmt.Errorf`.
As well, it is hardened to handle null values.
Fixes #2877

fix: adjust error handling in flux date package

---

stdlib/gen.go

The `go generate` call compiles and runs a program that uses libflux so
this switches the go generate call that forces libflux to rebuild to be
before the call to generating the builtins. Without this, the
`go generate ./stdlib` will sometimes fail because it will be using an
old version of the rust library and embedded stdlib instead of the new
one so it can't parse the files and generate the builtins. Since
generating the builtins fails, the `go generate` command never touches
the libflux package and never triggers a rebuild. This sticks you in a
circular loop of running `go generate ./stdlib` and it will never fix
itself without knowing ahead of time that you have to call `go generate
./libflux/go/libflux` first which defeats the purpose of adding that
generate call to `stdlib` anyway.

fix: reorder go generate call to libflux in stdlib

---

csv/result.go
csv/result_test.go
execute/executetest/result.go
execute/executetest/table.go
execute/executetest/table_test.go
influxql/decoder_test.go
stdlib/experimental/prometheus/prometheus_test.go

Closes #2893. 
Previously table stream checked with `NormalizeTables()` were only registering as equal when both the tables and columns were in the exact same order. This PR will put tables and columns in a consistent order so that they can be properly checked for equality.

fix(execute): check stream equality

---

.circleci/config.yml
runtime/runtime.go

This moves the semantic analysis to the finalize step like it was
previously. For applications that avoid finalizing unless they are using
the interpreter, this should restore the quicker startup time because
package registration will store the AST and move on.
In the longer term, we probably want to stop using `init()` so much and
switch to a system where the application explicitly pulls packages into
the runtime. For now, this is more simple and doesn't involve any
changes to existing applications and restores the previous speed for
commands that do not use flux but import the flux runtime.
influxdata/influxdb#18292

fix(runtime): move semantic analysis to the finalize step
