functions/distinct.go
functions/distinct_test.go
functions/testdata/distinct.flux
functions/testdata/distinct.in.csv
functions/testdata/distinct.out.csv
functions/testdata/keys.flux
functions/testdata/keys.in.csv
functions/testdata/keys.out.csv

bug was minor.  added plenty of tests to verify correct behavior.

Fix distinct bug when column is outside table key

---

functions/count.go
functions/count_test.go
functions/group.go
functions/sum.go
functions/sum_test.go
plan/physical_test.go

closes #15 
also:  removed TestPhysicalPlanner_Plan_PushDown_Mixed as it's no longer relevant

* removed pushdowns from count and sum and updated the tests that this affected.

---

repl/repl.go

Using the result iterator makes it possible to consume network implentation of the Querier. As of now no network backed implementations of the flux.Query interface exist.

fix: Update repl to use ResultIterator

---

docs/SPEC.md
execute/executetest/transformation.go
functions/keyValues.go
functions/key_values.go
functions/key_values_test.go

so far:   spec updated,  required structs spec'd out and registered.  keyCols list version completed.  
todo: implement schema function support.

keyValues function  colKeys list only. 

---

functions/query_test.go
functions/testdata/to.flux
functions/testdata/to.in.csv
functions/testdata/to.out.csv

The tests are currently being skipped until #77 has been closed.

Add "to" tests to the query test framework.

---

docs/SPEC.md

the spec was not correctly updated to track changes to `percentile` as well as work that dropped `timeSrc` and `timeDst` from all parameters.  This catches up the spec. 
fixes #69

update spec to be consistent with code changes to aggregates

---

docs/SPEC.md

Previously the join spec did not follow the typical template that other function specs follow. In particular it did not list its properties after its initial description. This PR updates the join spec to follow the convention of other function specs. It also adds links to features that have yet to be implemented.

update join spec to follow set convention

---

planner/logical.go
planner/logical_operations.go
planner/pattern.go
planner/physical.go
planner/plan_traversal_test.go
planner/planner.go
planner/types.go

Also:
- Added a new `ID()` method to `PlanNode`
- Added ability to add rules that match any node
- Added plan traversal test

Modify plan-traversal algorithm

---

execute/group_key.go
execute/group_key_builder.go
execute/group_key_builder_test.go
result.go

closes #109 
needs docs and some tests

feat: added GroupKeyBuilder for constructing a new group key

---

docs/SPEC.md

closes https://github.com/influxdata/platform/issues/769

update spec for buckets function

---

control/controller.go
execute/executor.go
execute/executor_test.go
functions/transformations/range.go
planner/logical.go
planner/logical_test.go
planner/physical.go
planner/physical_test.go
planner/plantest/plan.go
planner/types.go
planner/walk_test.go

* Remove stream context for right now and replace with bounds
* Have controller insert planning resources into physical plan
* Validate logical plan has correct number of yields

remove stream context and resource errors

---

builtin/builtin.go
functions/group_mode.go
functions/inputs/from.go
functions/inputs/from_test.go
functions/transformations/group.go
functions/transformations/group_test.go
plan/heuristic_planner_test.go
plan/pattern.go
plan/physical.go
plan/types.go

push range into from

---

array/base.go
array/bool.go
array/float.go
array/int.go
array/string.go
array/time.go
array/uint.go
internal/staticarray/bool.go
internal/staticarray/float.go
internal/staticarray/int.go
internal/staticarray/string.go
internal/staticarray/time.go
internal/staticarray/uint.go

The array builder interfaces roughly matches the arrow interface and is
a reasonable beginning point for constructing tables in a columnar
method.

feat: array builder interface for constructing an array

---

functions/transformations/keys.go

The `keys` function would sort the table columns. The problem is it
would return the column information from the table and it would modify
the mutable copy of the table. This changes things so it copies the
information out before it iterates over the columns.
Likely, it would be better if this function did not sort the data.
There's a sort function for that and it would likely be much easier if
this returned the columns in order rather than as sorted.
This also simplifies the use of except. A small map will not cause any
performance issues and it clarifies the intent so it is much easier to
follow and verify the logic. In cases without except, no additional
memory is allocated for the map.

fix: simplify and fix a problem in the keys function

---

csv/result.go

The `Do()` method for decoding csv results could potentially result in a
data race. If the entire table in a stream had more entries than the
maximum buffer size, the table decoder would pause and wait for the
decoder to read the next batch of entries for the table. At the same
time, the multi result decoder would attempt to use the same buffer to
read the next table.
This prevents the multi result decoder from trying to read the next
table until after the current table has finished being read.
Fixes #44.

fix: csv decoder data race

---

functions/inputs/buckets.go
functions/inputs/buckets_test.go

fix: Fix buckets funciton signature

---

control/controller.go

This is most likely to catch panics within the planner instead of having
the error swallowed and sent to the client.

feat: log when a panic happens inside of the controller logic

---

functions/transformations/range.go

fix: better error message when one of the range bounds is not set

---

control/controller.go
control/controller_test.go

feat: shutdown method for the controller

---

internal/token/token.go

It covers the various primitives for tokenizing a file and for using
those primitives in the scanner and parser.

feat: initial token package

---

docs/SPEC.md
functions/transformations/histogram.go
functions/transformations/histogram_test.go
functions/transformations/testdata/histogram.flux
functions/transformations/testdata/histogram.in.csv
functions/transformations/testdata/histogram.out.csv

chore: Rename histogram buckets to bins

---

internal/parser/parser_test.go

This will allow us to easily test the new parser functionality to match
the old one and ensure the project can be done in multiple commits
instead of as one gigantic commit.

feat: copy parser tests to the internal parser package

---

control/controller.go

Also, removed the now-unused "verbose" flag.  It is already unreferenced in dependencies.

Log flux.Spec and plans in log level "debug"

---

internal/parser/parser.go

It still doesn't handle errors, but it avoids panicking in certain
situations.

fix: ensure the new parser does not panic on unexpected input

---

parser/parser_test.go

parser test case for empty array

---

docs/SPEC.md
functions/transformations/key_values.go
functions/transformations/key_values_test.go

update keyValues with better error messages

---

docs/SPEC.md

Fixed formatting and added `all` and `none` parameters for `group` operation.  
I don't know if I got well the meaning of `group(all: true)` is it really equivalent to not grouping at all?

Fix in GroupBy spec

---

docs/SPEC.md

docs(spec): InfluxFieldsAsCols specification

---

docs/SPEC.md
internal/parser/grammar.md

This PR only updates the SPEC, there are several renames that need to
occur in order for the code to match this update to the SPEC.
Those changes will follow in separate PRs.
Closes https://github.com/influxdata/platform/issues/246

docs: update SPEC for official grammar

---

ast/walk.go

Must be merged to master after #383

Walk pattern for AST

---

ast/ast.go
ast/asttest/cmpopts.go
ast/format.go
ast/json.go
ast/json_test.go
ast/walk.go
compiler/compiler.go
compiler/compiler_test.go
internal/parser/parser.go
internal/parser/parser_test.go
interpreter/interpreter.go
semantic/analyze.go
semantic/annotator.go
semantic/constraints.go
semantic/graph.go
semantic/inference_test.go
semantic/json.go
semantic/json_test.go
semantic/semantictest/cmp.go
semantic/walk.go

BlockStatements were not statements and were not used as such.

refactor: rename BlockStatement to Block

---

result_iterator.go

Fixes https://github.com/influxdata/platform/issues/1750

fix(flux): check nil results when computing stats

---

functions/transformations/group.go
functions/transformations/group_test.go

feat(transformations): rule to chain group operations

---

ast/edit/option_editor.go
ast/edit/option_editor_test.go

Must be merged to master after #386

AST Option Editor

---

.github/pull_request_template.md

This PR adds a checklist for requirements on changes before they are considered "done".
A change must be "done" before it can be merged.
This checklist only lists items that cannot be verified via automation of some kind. As such we expect this list to stay small and be a simple reminder before merging.

chore: add PR template for definition of done

---

plan/heuristic_planner.go
plan/logical.go
plan/logical_test.go
plan/physical.go
plan/physical_test.go
plan/plantest/rules.go
plan/types.go
plan/types_test.go
plan/walk.go
plan/walk_test.go

feat(plan): plan validation

---

cmd/changelog/cmd/generate.go

We do not have tests for change log generation.

build(changelog): update changelog comment to only log invalid commit messages

---

cmd/changelog/cmd/generate.go

Changelog has no tests, we will add them before it gets its own repo.

build(changelog): fix changelog time format

---

semantic/poly_types.go

docs(semantic): add doc to NewObjectPolyType

---

functions/outputs/to_http.go

And fix some other copy-and-paste errors discovered while reading
through the code.

fix(functions/outputs): respect positive timeout for toHTTP

---

docs/SPEC.md
internal/parser/grammar.md

Closes https://github.com/influxdata/platform/issues/212 .

docs: update grammar spec with new object literal syntax

---

README.md

docs(README): update README with whirlwind Flux tour

---

execute/table.go

feat(execute): arrow helper method

---

functions/transformations/range.go

refactor(functions): convert range to use arrow

---

ast/ast.go
ast/edit/option_editor.go
ast/format.go
ast/format_test.go
ast/json.go
ast/json_test.go
compiler/compiler.go
internal/parser/parser.go
internal/parser/parser_test.go
interpreter/interpreter.go
semantic/analyze.go
semantic/constraints.go
semantic/graph.go
semantic/graph_test.go
semantic/json.go
semantic/json_test.go

feat(parser): parse string literal object keys

---

functions/transformations/distinct.go

refactor(functions): convert distinct to use arrow buffers

---

arrow/bool.go
arrow/float.go
arrow/int.go
arrow/string.go
arrow/uint.go

feat(arrow): slice utils

---

.circleci/config.yml

chore(ci): enable checkgenerate in CI

---

arrow/arrow_test.go

Tests for boolean and string slices have been skipped due to arrow bugs. Un-skip or remove tests entirely when the following apache arrow issues have been fixed:
* https://issues.apache.org/jira/browse/ARROW-4126
* https://github.com/apache/arrow/issues/3270
* https://github.com/apache/arrow/issues/3273

test(arrow): slice utils

---

functions/tests/testdata/histogram.flux
functions/tests/testdata/histogram.out.csv
functions/tests/testdata/histogram_normalize.flux
functions/tests/testdata/histogram_normalize.in.csv
functions/tests/testdata/histogram_normalize.out.csv
functions/tests/testdata/prepcsvtests/prepcsvtests.go
functions/transformations/histogram.go

refactor(functions): make histogram() use arrow arrays

---

functions/inputs/from.go
functions/inputs/from_test.go
functions/transformations/first_test.go

feat(functions): add no-points optimization for from() |> keys()

---

functions/tests/testdata/histogram_quantile.flux
functions/tests/testdata/histogram_quantile_minvalue.flux
functions/transformations/histogram_quantile.go

refactor(functions): make histogramQuantile use DoArrow

---

functions/transformations/join.go

refactor(functions): convert join to use arrow

---

go.mod
go.sum

This PR updates the flux dependency on arrow to include the fixes to boolean and binary arrow arrays.

dep: binary and boolean arrow slices

---

docs/SPEC.md
functions/transformations/keys.go
functions/transformations/keys_test.go

Fixes #506 
@jsternberg I selected you as reviewer because I saw that there are some TODO's of yours.

refactor(functions): convert keys to use arrow arrays

---

docs/SPEC.md
functions/tests/end_to_end_test.go
functions/tests/testdata/drop_fn.flux
functions/tests/testdata/drop_non_existent.flux
functions/tests/testdata/keep_non_existent.flux
functions/tests/testdata/rename_fn.flux
functions/transformations/schema_functions.go

Fixes #517 
Must be merged after #590 for arrow utils.

refactor(functions): convert schema mutations to use arrow arrays

---

execute/executetest/table.go
functions/transformations/first.go
functions/transformations/first_test.go

refactor(functions): make the first transformation nil-aware

---

execute/executetest/aggregate.go
functions/transformations/count_test.go
functions/transformations/mean.go
functions/transformations/mean_test.go
functions/transformations/percentile_test.go
functions/transformations/skew_test.go
functions/transformations/spread_test.go
functions/transformations/stddev_test.go
functions/transformations/sum_test.go

refactor(functions): support null values in the mean aggregate

---

functions/transformations/min.go
functions/transformations/min_test.go

refactor(functions): support null values in the min selector

---

functions/transformations/count.go
functions/transformations/count_test.go

refactor(functions): support null values in the count aggregate

---

functions/transformations/max.go
functions/transformations/max_test.go

refactor(functions): support null values in the max selector

---

execute/format.go

feat(execute): show nulls in REPL as empty string

---

functions/transformations/derivative.go

refactor(functions): convert derivative to use arrow arrays

---

ast/ast.go
ast/json_test.go

fix(ast): change Package.Path to be json omitempty

---

execute/table.go
functions/tests/testdata/percentile.flux
functions/transformations/percentile.go
functions/transformations/percentile_test.go

refactor(functions): support null values in percentile

---

functions/transformations/limit.go

Limit didn't release created slices.

fix(functions): memory leak in limit when slicing

---

docs/SPEC.md

docs: variables, options, packages, and imports

---

docs/SPEC.md
functions/transformations/distinct.go
functions/transformations/distinct_test.go

refactor(functions): support null values in distinct

---

docs/SPEC.md
functions/transformations/key_values.go
functions/transformations/key_values_test.go

refactor(functions): support null values in keyValues

---

functions/transformations/limit.go

refactor(functions/transformations): update limit to use new builder arrow API

---

docs/SPEC.md

design(functions/fill): add design for fill operation

---

functions/transformations/histogram.go
functions/transformations/histogram_test.go

refactor(functions): support null values in histogram

---

docs/SPEC.md
functions/transformations/pivot.go
functions/transformations/pivot_test.go

refactor(functions): add null support to pivot

---

docs/SPEC.md
stdlib/tests/assert_equals_test.go

test(functions): added a test confirming that assert equals works with null values

---

docs/SPEC.md

docs(SPEC): add syntax for type expressions

---

docs/SPEC.md

This PR requires #587 to be accepted first.
Fixes #473

 docs(SPEC): add specification of builtin statement 

---

docs/SPEC.md
stdlib/universe/integral.go
stdlib/universe/integral_test.go

refactor(stdlib): add null support to integral

---

stdlib/universe/covariance.go
stdlib/universe/covariance_test.go

refactor(stdlib): add null support to covariance

---

execute/group_lookup.go

This PR improves the performance of `GroupLookup`, by making the
sorting of the underlying keys lazy. As such, the set of keys will only
need to be sorted when a key is added that is less than the last
existing key.
Previously, adding keys to a `GroupLookup` could be a quadratic
endeavour due to sorting after each insertion, even if it was not
needed.
The impetus of this PR is to help improve the performance problems seen in https://github.com/influxdata/influxdb/issues/10988. 
Local testing shows that in my case, when testing against 200,000 points across one measurement with 2,000 tags, these changes reduce the query execution time from **12s** to **~4s**.
Larger gains will be seen with larger cardinalities.

perf: Improve performance of GroupLookup

---

docs/SPEC.md
stdlib/tests/testdata/derivative_nonnegative.flux
stdlib/universe/derivative.go
stdlib/universe/derivative_test.go

refactor(functions): add null support to derivative

---

docs/SPEC.md
stdlib/tests/testdata/columns.flux
stdlib/universe/columns.go
stdlib/universe/columns_test.go

feat(functions): columns function

---

docs/SPEC.md
stdlib/tests/testdata/keys.flux
stdlib/tests/testdata/meta_query_keys.flux
stdlib/tests/testdata/show_all_tag_keys.flux
stdlib/universe/keys.go
stdlib/universe/keys_test.go

Fixes #625 
Must be merged after #506 
Maybe this could be turned into a built-in once we have schema introspection functions.

fix(functions): fix keys to output group key

---

docs/SPEC.md
stdlib/universe/shift.go
stdlib/universe/shift_test.go

refactor(stdlib): add null support to shift

---

docs/SPEC.md
stdlib/universe/stddev.go
stdlib/universe/stddev_test.go

refactor(functions): add null support to stddev

---

docs/SPEC.md
stdlib/universe/skew.go
stdlib/universe/skew_test.go

refactor(stdlib): add null support to skew

---

stdlib/universe/spread.go
stdlib/universe/spread_test.go

refactor(stdlib): add null support to spread

---

stdlib/universe/unique.go
stdlib/universe/unique_test.go

refactor(universe): add null support to unique

---

docs/SPEC.md
stdlib/universe/sample.go
stdlib/universe/sample_test.go

test(stdlib): added a test confirming that sample works with null values

---

stdlib/universe/columns_test.go

test(universe): validate columns null support

---

docs/SPEC.md
stdlib/universe/schema_functions_test.go

test(universe): validate schema mutations null support

---

docs/SPEC.md
stdlib/universe/cumulative_sum.go
stdlib/universe/cumulative_sum_test.go

refactor(functions): null support for cumulative sum

---

stdlib/universe/union.go
stdlib/universe/union_test.go

Fixes #647 
And adds testing to union's Process.

test(universe): add test process union

---

stdlib/tests/testdata/group_nulls.flux
stdlib/universe/group_test.go

refactor(universe): add tests to validate null support for group

---

stdlib/testing/testdata/group_nulls.flux

Most tests got moved into that folder, but a new test was based off an
older commit and was added to the wrong directory.

fix: move a test file into the testing/testdata folder

---

docs/SPEC.md
execute/table.go
stdlib/universe/join.go
stdlib/universe/join_test.go
stdlib/universe/last_test.go
stdlib/universe/max_test.go
stdlib/universe/min_test.go
stdlib/universe/set_test.go
stdlib/universe/state_tracking_test.go
stdlib/universe/unique_test.go
values/values.go

refactor(stdlib): add null support to join function

---

docs/SPEC.md
stdlib/testing/testdata/increase.flux
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

Adds SPEC entry and updates test to use columns parameter.
Fixes #502

refactor(functions/increase): convert increase to use Arrow

---

docs/SPEC.md
stdlib/universe/set_test.go

test(stdlib): added a test confirming that set works with null values

---

plan/rules.go
stdlib/universe/filter.go
stdlib/universe/filter_test.go

feat(plan): add rule to remove filter true nodes

---

repl/repl.go

fix(repl): clear return for each repl command

---

execute/executor_test.go

test(execute): add tests to confirm that yield supports null

---

stdlib/testing/assert_equals.go

fix(stdlib/testing): fix edge case panic in assertEquals

---

stdlib/influxdata/influxdb/v1/flux_gen.go
stdlib/influxdata/influxdb/v1/v1.flux

feat(stdlib): adds various v1 meta queries helper functions

---

ast/ast.go
interpreter/interpreter.go
repl/repl.go
semantic/inference_test.go
semantic/solve.go

The REPL will print types of functions.
The AST location prints the File name.
The semantic package exposes a way to print type solutions.

fix: fixes various UX issues

---

stdlib/testing/testdata/aggregate_empty_window.flux
stdlib/testing/testdata/aggregate_fill_window.flux
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

test(stdlib/testing): add tests for empty window nulls and fills

---

compile.go

fix(flux): copy packages for importer copy

---

control/controller.go
control/metrics.go

Closes https://github.com/influxdata/influxdb/issues/11180

feat(control): add query function count metrics

---

stdlib/testing/testdata/window_null.flux

test(stdlib): add an end to end test to validate window supports null

---

stdlib/testing/testdata/prepcsvtests/prepcsvtests.go

test(stdlib): update prepcsvtests tool for new e2e format

---

interpreter/interpreter.go
interpreter/package.go
interpreter/package_test.go

fix(interpreter): cannot access imports of imports

---

docs/SPEC.md
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

feat(stdlib/universe): update aggregateWindow to include createEmpty as parameter to allow for null results.

---

internal/parser/parser.go
internal/parser/parser_test.go

The parser now tracks nested blocks so when it sees something like:
a[b(]
It will now be able to identify that the `]` closes the index expression
and recognize that the parenthesis was never closed. Previously, it
would aggressively search for the end parenthesis and would exhaust the
input. This would cause any part of the AST after the unbalanced
parenthesis to be completely useless even though we can reasonably guess
that `]` isn't a valid token for an expression and the `]` is obviously
closing the index expression.

feat(parser): track nested blocks in the parser

---

control/controller.go
control/metrics.go

Closes https://github.com/influxdata/influxdb/issues/11333
To track the count of queries the metric `query_control_requests_total` is added.
The metric has label `result` whose values can be
* `success`
* `compile_error`
* `queue_error`
The `result` label allows us to create ratios between success and error as well as sum to get the total number of queries.

feat(control): add query success and error metrics

---

semantic/graph.go
stdlib/testing/testdata/map.flux

fix(semantic): fix panic when copying lambda

---

docs/StandardLibrary.md

docs: add a proposal for a standard library

---

docs/SPEC.md
stdlib/universe/derivative.go
stdlib/universe/derivative_test.go

refactor(stdlib): make derivative return error for null or out-of-order times

---

execute/source_iterator.go
stdlib/generate/from.go
stdlib/sql/from.go

Close is required to close the opened connection

fix(execute): add Close to SourceIterator

---

docs/SPEC.md
stdlib/testing/assert_equals.go
stdlib/testing/assert_equals_test.go
stdlib/testing/diff.go
stdlib/testing/diff_test.go
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

This function is contained within the testing package and it will take a
got and want table and produce a diff between the two.
Details have been added to the spec.
Fixes #911.

feat(stdlib): add testing.diff function

---

csv/result.go
csv/result_test.go

fixes #898 
related issue: #919

fix(csv/result): fix decoder bug where a default table id is given when none is required.

---

ast/edit/option_editor.go
ast/edit/option_editor_test.go

bug: options editor should use ast.Expression

---

control/controller_test.go
plan/plantest/rules.go
plan/rules_test.go
querytest/compiler.go
stdlib/influxdata/influxdb/from.go
stdlib/influxdata/influxdb/from_test.go

InfluxDB PR: https://github.com/influxdata/influxdb/pull/11515.

refactor(influxdb): remove from implementation to move it to influxdb

---

ast/ast.go
semantic/analyze.go

This is needed for options handling.

feat: make duration conversion public

---

compile.go
csv/result_test.go
lang/compiler.go
lang/compiler_test.go

refactor(lang): add an AST compiler

---

control/controller.go
control/controller_test.go

This refactors the controller query and how the controller interacts
with that query. Previously, the query had an ill-defined lifecycle and
it could be arbitrarily canceled at any time that caused race conditions
when transitioning between states. The transition touched values that
were not protected by a mutex which caused a data race.
The query has now been changed so the `Cancel()` method only _signals_
that the query should be canceled and does that by using the query
context and sending that downstream. This causes the state to transition
lazily so when the query attempts to transition to a different state,
it will automatically transition to the canceled state and report that
it failed to transition to a new state. When the query controller
attempts to report an error, it realizes …

fix(control): refactor the controller to remove data races

---

docs/SPEC.md
execute/bounds.go
execute/window.go
execute/window_test.go
plan/types.go
stdlib/testing/testdata/window_offset.flux
stdlib/testing/testdata/window_start_bound.flux
stdlib/universe/window.go
stdlib/universe/window_test.go
values/time.go

refactor(stdlib): make window() parameters match SPEC

---

ast/edit/match.go
ast/edit/match_test.go

ast.Match allows to get nodes from an ast from a pattern.

feat(ast/edit): ast match

---

stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

fix(stdlib/testing): change loadStorage and loadMem to be options so that they are modifiable

---

stdlib/flux_test.go

refactor(stdlib): replace test compiler with ASTCompiler

---

lang/compiler.go
lang/compiler_test.go

refactor(lang): add now time to ASTCompiler

---

lang/compiler.go
lang/compiler_test.go

refactor(lang): add extern to ast compiler

---

control/controller_test.go

It uses more channels to control when it will be in the executing state
and when the cancellation occurs along with more leniency in when the
timeouts happen so that we can ensure that the `Cancel()` function will
propagate into the execution function and transition the query to the
canceled state.
Fixes #989.

fix(control): fix a controller test to be less flaky

---

lang/compiler.go

fix(lang): add AST compiler to mappings

---

internal/parser/parser.go
internal/parser/parser_test.go

fix(parser): prevent a deadlock in the array expression parser

---

compiler/compiler.go
compiler/runtime.go
interpreter/interpreter_test.go
stdlib/csv/from.go
stdlib/universe/filter.go
stdlib/universe/map.go
stdlib/universe/map_test.go

fix(compiler): return errors when evaluating functions

---

stdlib/testing/testdata/totime.flux
stdlib/universe/typeconv.go

Fixes influxdata/influxdb#12176.

fix(stdlib): make time() function accept any format that parser accepts

---

csv/result_test.go
stdlib/testing/testdata/totime.flux

fix(test): fix test to pass in influxdb

---

stdlib/testing/testdata/pivot.flux
stdlib/testing/testdata/pivot_col_order.flux
stdlib/universe/pivot.go

fix(stdlib): pivot orders rowKey and columnKey by the input parameters, rather than the table column order

---

stdlib/testing/testdata/union.flux

fix(stdlib/testing): test union.flux correctly uses sort

---

execute/group_lookup.go

docs(execute): document the new group lookup structure

---

compiler/compiler.go
compiler/runtime.go
interpreter/interpreter.go
stdlib/flux_test.go
stdlib/testing/testdata/map_with_obj.flux
stdlib/testing/testdata/string_trim.flux

feat(stdlib): row function now includes local identifier scope.  

---

compiler/compiler.go
docs/SPEC.md
execute/row_fn.go
stdlib/testing/testdata/reduce.flux
stdlib/universe/flux_gen.go
stdlib/universe/reduce.go
stdlib/universe/reduce_test.go
stdlib/universe/universe.flux
values/values.go

feat(stdlib): added reduce function and supporting go API for implementation

---

internal/parser/parser.go
internal/parser/parser_test.go

fix(parser): report the error received when parsing a bad regex literal

---

parser/strconv.go
parser/strconv_test.go

A public function to parse signed durations.
closes #1081

feat: parse-signed-duration

---

values/binary.go
values/binary_test.go

Signed-off-by: Julius Volz <julius.volz@gmail.com>

feat: define comparison operators between time types

---

compile.go
compile_test.go

fix(lang): Add error message to Compile methods for empty Spec

---

control/controller.go
control/metrics.go

fix(control): Remove dead code in controller so staticcheck passes

---

docs/SPEC.md
internal/parser/grammar.md
internal/parser/parser.go
internal/parser/parser_test.go

fix(parser): fix logical operators precedence

---

ast/format.go
ast/format_test.go

fix(ast): format AST preserving operator precedence

---

lang/compiler.go

The metadata channel needs to be read after the results are closed and
one way to do that is to read it in a different goroutine so reading the
metadata doesn't block closing the results.

fix(lang): read the metadata channel in a separate goroutine

---

control/controller.go
lang/compiler.go

This is a temporary change until #1126 is fixed.

refactor(control): make controller assign dependencies to program

---

docs/SPEC.md
stdlib/testing/testdata/duplicate_overwrite.flux
stdlib/universe/schema_functions_test.go
stdlib/universe/schema_mutators.go

feat(stdlib/universe/duplicate): duplicate will now overwrite a column if the as label already exists

---

plan/logical_test.go
plan/plantest/cmp.go

refactor(plantest): use plantest.ComparePlans to compare logical plans

---

lang/compiler.go
lang/compiler_test.go
plan/builder.go

feat(lang): add planner options to compile options

---

lang/compiler.go

feat(lang/compiler): added a WalkIR function that external programs can use to traverse an opSpec structure

---

examples/README.md
examples/library/README.md
examples/library/library_example_test.go

Signed-off-by: Lorenzo Fontana <lo@linux.com>

feat(examples): add example on how to use flux as a library

---

examples/library/library_example_test.go

fix(examples): change example name to make go vet pass

---

control/controller.go

This modifies the controller in two ways. First, it ensures the current
context is always set to a valid value. The second and more important is
that it treats the current context as something that has to be
synchronized and, instead of reading it from the query, each state
returns the context it will run in so there isn't a potential race
condition involved with its usage.

fix(control): the controller pump could reference a nil pointer

---

execute/aggregate.go

fix(execute): rename json tag so go vet passes

---

.circleci/config.yml

Fix issue with new Go compiler in CI, per Mark's comment:
https://github.com/golang/go/issues/26186#issuecomment-435544512
Fixes #1179.

ci: add GOFLAGS -p=8 circleci config

---

ast/format.go
ast/format_test.go
internal/parser/parser_test.go

Closes https://github.com/influxdata/flux/issues/1012

fix(ast): format with good parens

---

semantic/analyze.go
semantic/constraints.go
semantic/inference_test.go

feat(semantic): add handling for conditional expressions to type inference

---

lang/compiler_test.go
lang/query_test.go
mock/program.go
mock/query.go
result_iterator_test.go

test(lang): add tests for query

---

compiler/compiler.go
compiler/compiler_test.go
compiler/runtime.go
interpreter/interpreter.go
interpreter/interpreter_test.go

feat(interpreter): add conditional expression handling to interpreter

---

ast/format.go
ast/format_test.go

fix(ast): format conditional expression

---

docs/SPEC.md

docs(SPEC): Add description of conditional expressions to SPEC

---

stdlib/sql/from.go

refactor(stdlib/sql): prefer type switch over repeated assertions

---

docs/SPEC.md
execute/aggregate.go
stdlib/universe/stddev.go
stdlib/universe/stddev_test.go

Fixes https://github.com/influxdata/flux/issues/1010
Signed-off-by: Julius Volz <julius.volz@gmail.com>

feat(stdlib): Allow choosing sample/population mode in stddev()

---

execute/executor.go
memory/allocator.go

fix(execute): make executor respect memory limit from caller

---

execute/executetest/source.go
execute/executor_test.go

This adds a unit test for the fix that was added here:
https://github.com/influxdata/flux/pull/1213

test(execute): add test for memory limits

---

control/controller.go
control/controller_test.go
query.go

Also make the controller append any runtime errors to stats.

refactor: add runtime errors to flux.Statistics

---

control/controller.go
control/controller_test.go
control/metrics.go
go.mod

fix(control): fix request results labels to count runtime errors

---

internal/parser/grammar.md
internal/parser/parser.go
internal/parser/parser_test.go
stdlib/math/flux_gen.go
stdlib/math/math.flux
stdlib/strings/flux_gen.go
stdlib/strings/strings.flux
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

Fixes #1102.
BREAKING CHANGE: adds additional errors to parser.

fix(parser): add error handling for property list

---

plan/physical.go
plan/triggers.go
plan/triggers_test.go

This is needed in the fix for #1224.

refactor(plan): do not error for logical node when setting trigger specs

---

stdlib/testing/testdata/pivot_fields.flux
stdlib/universe/pivot.go
stdlib/universe/pivot_test.go

fix(stdlib/pivot): pivot now uses the correct column type when filling nulls

---

docs/SPEC.md
stdlib/testing/testdata/median_column.flux
stdlib/testing/testdata/median_compression.flux
stdlib/testing/testdata/median_method.flux
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

fix(universe/median): add column parameter to median

---

docs/SPEC.md
stdlib/testing/testdata/aggregate_window_median.flux
stdlib/testing/testdata/median.flux
stdlib/testing/testdata/median_column.flux
stdlib/testing/testdata/median_compression.flux
stdlib/testing/testdata/median_method.flux
stdlib/universe/flux_gen.go
stdlib/universe/last.go
stdlib/universe/last_test.go
stdlib/universe/max_test.go
stdlib/universe/min_test.go
stdlib/universe/universe.flux

merge-dev-to-master

---

internal/parser/grammar.md

docs(grammar): fix typos

---

release.sh

The `maint` branch will hold the last release. The script will also
ensure that the current branch has `maint` as an ancestor so any
commits made to the `maint` branch are ensured to be in the next
release.

refactor: modify the release script to push the latest tag to a maint branch

---

docs/SPEC.md
stdlib/universe/flux_gen.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go
stdlib/universe/universe.flux
values/objects/table.go

Closes #1089 
Closes #1168 
Closes #1169

feat(universe): add stream table index functions

---

stdlib/universe/table_fns_test.go

fix(universe): fix table functions test

---

control/controller.go
control/controller_test.go

If cancel and done were called in quick succession, it could result in a
race condition because there was no lock over the state transition
inside of done. It was assumed that done was called after results were
read, but that's not part of the interface and you are allowed to call
done without having read the results. This became most obvious when
cancel was called and then done immediately afterwards.
This modifies it so that cancel is asynchronous and signals that the
execution should be halted, which is how it was previously. It modifies
done to wait for the task to actually be completed before the call
returns.
Fixes influxdata/influxdb#13867.

fix(control): remove the race condition within the (*Query).Done method

---

stdlib/testing/testdata/dynamic_query.flux
stdlib/universe/table_fns.go
values/objects/table.go

feat(universe): support for dynamic queries

---

.circleci/config.yml
.gitignore
Makefile

ci: add codecov.io support to flux

---

ast/errors.go
internal/parser/parser_test.go

fix(ast): return count of errors when checking AST

---

internal/cmd/changelog/cmd/generate.go

When the git log contained merges, the changelog generator didn't
necessarily work correctly. First, it would attempt to parse the message
in merge commits which was always wrong and always printed an error
message. Now, the changelog generator is told to just skip those commits
and move on since merge commits won't contain the message we're looking
for anyway.
The second happened with patch releases and feature branches that were
under work for more than a release. If a release was performed on the
maint branch and another commit was done on master before merging
maint back to master, the tree could be constructed in a way where the
previous version commit could not be clearly found such as in this
example from the `v0.31.0` release.
* 3204dd2d ci: add codecov.io support to flux (#1273) …

fix(changelog): changelog generator now handles merge commits better

---

docs/SPEC.md

Closes #1302.
This PR specifies how nulls behave in Flux.
I saw two ways of doing this. The first was to define null as a predeclared identifier without a default type but which could take on any basic type (similar to go). This had the advantage of not being able to assign `null` directly to a variable as all Flux variables must be typed. However accessing a non-existent property of an object would have to return typed `null` which is just not feasible.
Therefore the second way the, and the way I ultimately chose, was to define null as both a value and a type. The `null` value being the only value that comprises the _null type_. By introducing a null type to the language it becomes possible to assign `null` directly to a variable which is not ideal. However it also allows us to return …

docs: null specification

---

docs/SPEC.md

docs: aggregates skip nulls by default

---

stdlib/universe/fill.go
stdlib/universe/fill_test.go

fix(stdlib/fill): add length check for empty tables in fill

---

docs/SPEC.md

feat(stdlib/string-fns) update SPEC.md

---

compiler/compiler_test.go
compiler/runtime.go

feat(compiler): add the exists operator to the compiler runtime

---

lang/compiler.go
lang/compiler_test.go

Related influxdb PR:
https://github.com/influxdata/influxdb/pull/14135

refactor(lang): add extern and now fields to FluxCompiler

---

stdlib/strings/strings.go
stdlib/testing/testdata/strings_joinStr.flux

fix(stdlib/strings): fix joinStr, including adding an EndToEnd Test

---

execute/row_fn.go

fix(execute/row_fn): row function resets records map with each call to prepare

---

stdlib/testing/testdata/map_extension_with.flux

fix(stdlib/testing): add range to map_extension_with.flux

---

stdlib/testing/testdata/reduce_noref.flux

test(stdlib/reduce): test showing that recent changes fixed an issue  with missing references in a reduce function

---

internal/rust/ast/src/lib.rs
internal/rust/parser/src/lib.rs

feat(rust): implement more production rules

---

execute/rowreader.go
go.mod
stdlib/sql/from.go
stdlib/sql/mysql.go
stdlib/sql/postgres.go
stdlib/sql/sql_test.go

feat(stdlib): added MySQL type support

---

stdlib/testing/diff.go

fix(stdlib): diff should track memory allocations when it copies the table

---

stdlib/sql/postgres.go

- custom types in PostgreSQL (received as byte arrays) are now parsed and appended

feat(stdlib): add custom PostgreSQL type support

---

stdlib/universe/typeconv_test.go

test(universe/typeconv): wrote test cases for type conversions

---

docs/SPEC.md
stdlib/testing/testdata/moving_average.flux
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

feat(stdlib/universe): moving average function

---

go.mod
go.sum
stdlib/sql/flux_gen.go
stdlib/sql/sql.flux
stdlib/sql/to.go
stdlib/sql/to_test.go

feat(stdlib/sql): added SQL to() function

---

ast/format.go
ast/format_test.go

fix(ast): suport formatting "with"

---

stdlib/universe/map.go
stdlib/universe/map_test.go

The transpiler relies heavily on the mergeKey behavior. As such we are
adding it back. It will remain undocumented and will default to false.

fix(stdlib): readd mergeKey parameter to map in deprecated state

---

stdlib/universe/flux_gen.go
stdlib/universe/sleep.go
stdlib/universe/universe.flux

This is a trivial implementation of the sleep function.
There is no way to interrupt the execution of this function.

feat(stdlib): add sleep function

---

stdlib/testing/testdata/range_stop.flux

test(stdlib/range): added test for range stop parameter correctness

---

internal/rust/ast/Cargo.lock
internal/rust/ast/Cargo.toml
internal/rust/ast/src/lib.rs
internal/rust/ast/src/tests.rs
internal/rust/parser/Cargo.lock
internal/rust/parser/Cargo.toml
internal/rust/parser/src/lib.rs
internal/rust/parser/src/strconv.rs
internal/rust/parser/src/tests.rs
internal/rust/scanner/src/lib.rs
internal/rust/scanner/src/scanner.h
internal/rust/scanner/src/scanner.rl
internal/rust/site/index.html

Full draft of Rust parser

---

codes/codes.go
errors.go
execute/dispatcher.go
execute/executetest/table.go
execute/executor.go
execute/executor_test.go
execute/table.go
internal/errors/errors.go
internal/errors/errors_test.go
memory/allocator.go
semantic/analyze.go
semantic/json.go
stdlib/math/math.go
stdlib/regexp/regexp.go
stdlib/sql/to.go
stdlib/universe/fill.go
stdlib/universe/group.go
stdlib/universe/key_values.go
stdlib/universe/union.go

This converts many places where errors happen to use the new error type
so that errors are enriched.
It does not cover all places where errors are created and is not
intended to cover all places where errors are created. It also doesn't
handle adapting outside errors.

feat: modify error usage in places to use the new enriched errors

---

docs/SPEC.md
stdlib/universe/flux_gen.go
stdlib/universe/mode.go
stdlib/universe/mode_test.go
stdlib/universe/universe.flux

feat(stdlib/universe): added mode() function

---

docs/strings.md

docs(strings): add discussion on flux strings library to docs/strings.md

---

docs/SPEC.md
stdlib/testing/testdata/elapsed.flux
stdlib/universe/difference.go
stdlib/universe/elapsed.go
stdlib/universe/elapsed_test.go
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

feat(stdlib/universe): add elapsed to flux

---

docs/SPEC.md
execute/row_fn.go
execute/row_fn_test.go
stdlib/testing/testdata/show_all_tag_keys.flux

fix(execute): make row map fn error if return type is not object

---

stdlib/flux_test.go
stdlib/strings/strings.go

fix(stdlib/strings): fix implementation of replaceAll from strings

---

docs/SPEC.md

#985 
I also update call expressions with the short notation.

docs(SPEC): explain matching params in higher-order functions

---

stdlib/testing/testdata/time_to_int.flux
stdlib/testing/testdata/time_to_uint.flux
stdlib/testing/testdata/to_int.flux
stdlib/testing/testdata/to_uint.flux

test(stdlib/typeconv): make to_time tests runnable on influxdb

---

stdlib/testing/testdata/elapsed.flux
stdlib/testing/testdata/moving_average.flux

fix(tests): add range call to some e2e tests

---

docs/SPEC.md
stdlib/testing/testdata/exponential_moving_average.flux
stdlib/universe/array_container.go
stdlib/universe/exponential_moving_average.go
stdlib/universe/exponential_moving_average_test.go
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

feat(stdlib/universe): added exponential moving average

---

docs/SPEC.md

fix(docs/covarianceSpec): fix the example for covariance

---

stdlib/testing/testdata/mode.flux
stdlib/testing/testdata/mode_string.flux
stdlib/universe/mode.go
stdlib/universe/mode_test.go

fix(stdlib/universe): mode displays multiple modes for multi-modal data

---

CONTRIBUTING.md
README.md

docs: update contributing doc with information about the rust parser

---

compiler/runtime.go
docs/SPEC.md
interpreter/interpreter.go
values/binary.go
values/binary_test.go

fix(values): throw appropriate error for division by zero

---

internal/mutable/numericarray.go
internal/mutable/numericarray_test.go

test(internal/mutable): add test for mixed reserve and resize

---

stdlib/universe/typeconv.go
stdlib/universe/typeconv_test.go

fix(stdlib): allow converting a duration to a duration

---

stdlib/testing/testdata/date_truncate.flux
stdlib/testing/testdata/universe_truncateTimeColumn.flux

fix(truncate): add range to tests to pass in influxdb

---

interpreter/interpreter.go
stdlib/testing/testdata/map_extern_var.flux
stdlib/testing/testdata/map_local_var.flux
stdlib/testing/testdata/map_shadow_var.flux

fix(interpreter): function resolver now keeps track of local assignments that may be evaluated at runtime

---

values/binary.go
values/binary_test.go

- added support for adding durations, subtracting durations and times, and dividing durations

feat(values): same-type time literal arithmetic

---

internal/rust/scanner/src/lib.rs
internal/rust/scanner/src/scanner.h
internal/rust/scanner/src/scanner.rl
internal/rust/scanner/src/tests.rs

feat(rust/scanner): scanner returns positioning

---

csv/result_test.go
stdlib/flux_test.go
stdlib/testing/testdata/drop_non_existent.flux
stdlib/testing/testdata/keep_non_existent.flux
stdlib/testing/testdata/keep_non_existent_only.flux
stdlib/universe/schema_functions_test.go
stdlib/universe/schema_mutators.go
values/binary_test.go

feat(universe): allow keep to run regardless of nonexistent columns given. if all columns given are nonexistent, return empty table

---

stdlib/testing/chronograf/buckets.flux
stdlib/testing/chronograf/flux_test_gen.go

influxdata/influxdb-templates#7

tests(stdlib): add the buckets template variable to the chronograf test queries

---

docs/Alerts.md

docs: initial document for an alerts package

---

docs/DeadmanAlert.md

docs: calculate deadman alerts in Flux

---

docs/DeadmanAlert.md

docs: implement deadman with max instead of sort |> last

---

execute/selector.go
execute/selector_test.go
stdlib/testing/testdata/max_time.flux
stdlib/universe/first.go
stdlib/universe/last.go
stdlib/universe/max.go
stdlib/universe/min.go
stdlib/universe/sample.go

feat(execute):time selectors

---

docs/SPEC.md
stdlib/date/date.go
stdlib/date/date_fns.flux
stdlib/date/date_test.go
stdlib/date/flux_gen.go
stdlib/testing/testdata/date_year.flux

feat(stdlib/date): added year function to date package

---

docs/SPEC.md
stdlib/testing/testdata/hour_selection.flux
stdlib/universe/flux_gen.go
stdlib/universe/hour_selection.go
stdlib/universe/hour_selection_test.go
stdlib/universe/universe.flux

feat(stdlib/universe): added hourSelection function

---

docs/SPEC.md
stdlib/testing/testdata/cmo.flux
stdlib/universe/chande_momentum_oscillator.go
stdlib/universe/chande_momentum_oscillator_test.go
stdlib/universe/flux_gen.go
stdlib/universe/universe.flux

feat(universe/chande): add cmo from influxql to flux

---

stdlib/sql/to.go
stdlib/sql/to_test.go

- Connection to database is closed after Process() is finished

fix(stdlib/sql): Close connection after sql.to() & Postgres datetime fix

---

docs/Outputs.md
docs/SPEC.md

docs(outputs): design for external services in Flux

---

compile.go
compiler/runtime.go
execute/row_fn.go
interpreter/interpreter.go
interpreter/interpreter_test.go
interpreter/package.go
semantic/types.go
stdlib/universe/histogram.go
stdlib/universe/typeconv.go
values/array.go
values/function.go
values/object.go
values/objects/table.go
values/values.go

feat: bytes type

---

docs/SPEC.md

docs: the bytes type is not nullable

---

docs/SPEC.md
internal/moving_average/array_container.go
stdlib/testing/testdata/triple_exponential_derivative.flux
stdlib/universe/flux_gen.go
stdlib/universe/triple_exponential_derivative.go
stdlib/universe/triple_exponential_derivative_test.go
stdlib/universe/universe.flux

- Triple Exponential Derivative is a momentum indicator
- append `null` if not enough values exist for a proper TRIX

feat(stdlib/universe): Triple Exponential Derivative

---

execute/executetest/result.go
stdlib/experimental/experimental.flux
stdlib/experimental/flux_gen.go
stdlib/experimental/to.go

feat(stdlib): add an experimental "to" function

---

compiler/compiler.go
compiler/runtime.go
interpreter/interpreter.go
stdlib/flux_test.go
stdlib/testing/testdata/math_fn_constant_test.flux
stdlib/testing/testdata/rowfn_with_import_test.flux

This changes the compiler so that it will not fail if it cannot resolve
a function since it is not an error for a function to not be
resolvable in the compiler.
#1509

tests(stdlib): ensure that package functions can be used in the compiler

---

compiler/runtime.go
semantic/inference_test.go
semantic/poly_types.go
stdlib/testing/testdata/map_polymorphism_test.flux

fix(compiler): calling polymorphic values

---

stdlib/influxdata/influxdb/alerts/alerts.flux
stdlib/influxdata/influxdb/alerts/flux_gen.go

feat(stdlib): add the notify function to the influxdb alerts library

---

compiler/runtime.go
stdlib/flux_test.go
stdlib/influxdata/influxdb/alerts/alerts.flux
stdlib/influxdata/influxdb/alerts/check_test.flux
stdlib/influxdata/influxdb/alerts/flux_gen.go
stdlib/influxdata/influxdb/alerts/flux_test_gen.go

feat(stdlib): add an alerts.check function

---

csv/result.go
csv/result_test.go

The csv encoder erroneously wrapped some table errors as encoder errors.
This not only created a confusing error message, it also confused any
code that attempted to check if a `*flux.Error` was returned from the
encoder to give a more descriptive error message because the
`EncoderError` is not a `*flux.Error`.

fix(csv): avoid wrapping table errors in the csv encoder

---

stdlib/testing/testdata/holt_winters_panic_test.flux
stdlib/universe/holt_winters/holt_winters.go

fix(stdlib/universe): resolved holt-winters panic

---

dependencies/dependencies.go
dependencies/dependenciestest/dependencies.go
dependencies/environment_secret_service.go
repl/repl.go
stdlib/http/post_test.go
stdlib/slack/slack_test.go

feat(dependencies): added secret service interface

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
repl/repl.go

refactor(repl): repl now gets its context and dependencies set at startup and passed down.

---

cmd/flux/cmd/execute.go
cmd/flux/cmd/repl.go
dependencies/dependencies.go
stdlib/http/post_test.go
stdlib/slack/slack_test.go

refactor(dependencies): changed dependencies to be more generally constructable

---

interpreter/interpreter.go
stdlib/flux_test.go
stdlib/influxdata/influxdb/monitor/check_test.flux
stdlib/influxdata/influxdb/monitor/flux_gen.go
stdlib/influxdata/influxdb/monitor/flux_test_gen.go
stdlib/influxdata/influxdb/monitor/monitor.flux
stdlib/influxdata/influxdb/monitor/notify_test.flux

This change fixes various bugs in order to get the notify test function
passing.
* Changes alerts.log to an option
* Changes alerts.write to use experimental.to
* Fixes bug with overriding option used in the same package

fix(stdlib/alerts): add test case for notify function

---

compiler/compiler.go
compiler/compiler_test.go
compiler/runtime.go
interpreter/interpreter.go
interpreter/interpreter_test.go
semantic/analyze.go
semantic/constraints.go
semantic/graph.go
semantic/json.go
semantic/json_test.go
semantic/semantictest/cmp.go
semantic/walk.go

feat: evaluate string interpolation

---

stdlib/influxdata/influxdb/monitor/flux_test_gen.go
stdlib/influxdata/influxdb/monitor/notify_test.flux

test(stdlib/notify): change notify to use unpivoted data

---

values/binary.go
values/binary_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/influxdata/flux/1787)

fix(interpreter): support bool equality expressions

---

dependencies/dependencies.go

fix(dependencies): changed the default http client to be more robust

---

interpreter/interpreter.go
semantic/constraints.go

fix(errors): categorize the undefined identifier as an invalid status code

---

.gitignore
execute/transformation.go

Adding documentation to the Transformation interface since there was none before.

docs(execute): add documentation to Transformation interface

---

stdlib/pagerduty/flux_gen.go
stdlib/pagerduty/pagerduty.flux
stdlib/pagerduty/pagerduty_test.go

See: https://github.com/influxdata/influxdb/pull/15043
And https://github.com/influxdata/influxdb/pull/15048
Removes unused token from pagerduty endpoint
Closes #1828

fix(alerts): remove token parameter from endpoint

---

internal/parser/parser.go
internal/parser/parser_test.go
internal/rust/parser/src/lib.rs
internal/rust/parser/src/tests.rs

fix(parser): push error for bad string expression

---

internal/spec/build.go
lang/compiler.go
lang/query.go
stdlib/http/post.go

fix: additional opentracing spans for debugging query flow

---

release.sh

fix: push the tag before running goreleaser

---

dependencies/dependenciestest/dependencies.go

Tests need the filesystem service.

fix(dependenciestest): add filesystem to default test dependencies

---

Makefile

fix(Makefile): make fmt runs cargo fmt on rust dirs

---

execute/executetest/selector.go
stdlib/flux_test.go
stdlib/universe/data_test.go
stdlib/universe/mean_test.go
stdlib/universe/quantile_test.go
stdlib/universe/skew_test.go
stdlib/universe/spread_test.go
stdlib/universe/stddev_test.go
stdlib/universe/sum_test.go

chore: fix the benchmarks so they pass

---

.circleci/config.yml
Makefile

ci: run go benchmarks at least once in ci

---

.circleci/config.yml

ci: add bench-test to the workflow jobs

---

lang/compiler.go

fix(lang): passing deps to WalkIR

---

lang/compiler.go

fix(lang): passing context to WalkIR

---

README.md

docs: update README to reflect the new world of 2.0

---

execute/rowreader.go
execute/source_iterator.go
go.mod
go.sum
stdlib/experimental/bigtable/bigtable_test.go
stdlib/experimental/bigtable/rowreader.go
stdlib/sql/from.go
stdlib/sql/mysql.go
stdlib/sql/postgres.go
stdlib/sql/sql_test.go

fix(stdlib): sql does not leak connections anymore

---

interpreter/interpreter.go
stdlib/universe/pivot.go

This annotates the intepreter errors to return flux errors with an
appropriate code.
This also updates pivot as an extra piece of code that was also
annotated at the same time.
#1897

fix(interpreter): have the interpreter return annotated flux errors

---

stdlib/internal/promql/join.md

https://github.com/influxdata/flux/issues/1881.

docs(promql): group key join for promql

---

internal/parser/parser.go
internal/parser/parser_test.go
internal/parser/strconv.go
internal/rust/parser/src/lib.rs
internal/rust/parser/src/strconv.rs
internal/rust/parser/src/tests.rs

fix(parser): escape char parsing for string interpolation expressions

---

ast/ast.go

docs(ast): add doc comment to ParenExpression

---

docs/SPEC.md

fix(spec): fix broken links in SPEC

---

libflux/src/ast/mod.rs
libflux/src/ast/tests.rs
libflux/src/parser/mod.rs
libflux/src/parser/tests.rs

refactor(libflux/ast): rename AST enums to be consistent with type names

---

libflux/Cargo.lock
libflux/Cargo.toml
libflux/src/semantic/analyze.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/types.rs
semantic/analyze.go

feat(internal/rust): add semantic analysis

---

Makefile

chore: fix the makefile so it does not attempt to create a file when it doesn't exist

---

libflux/Cargo.lock
libflux/Cargo.toml
libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

This PR defines macros for writing type inference test cases. Along with a few small examples.
Closes #2072 .

feat: type inference test macros

---

libflux/src/ast/walk/mod.rs

fix(flux): make walk_rc public

---

libflux/src/semantic/infer.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

feat: extensible record unification and constraint generation

---

stdlib/testing/usage/api_test.flux
stdlib/testing/usage/storage_test.flux

Closes #2107 
This pr updates the usage tests to reflect changes made to the usage queries in the attached pr.

fix(tests): Update usage tests to filter on _field

---

libflux/src/semantic/tests.rs

The `test_infer` macros have been changed to call a common `infer_types`
function that is in the test module. This should make it easier for
editors to analyze the function and help with readability.
The syntax for specifying type variables has changed to use a map macro.
You can now specify things like this:
map!{
"var1" => "forall [] t0",
"var2" => "forall [] t1",
}
This should be clearer to read.

refactor(libflux): refactor the test_infer macros for more complete type checking

---

libflux/src/semantic/analyze.rs
libflux/src/semantic/mod.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/walk.rs

feat(libflux): expose function to analyze from string

---

libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs

test: type inference with function types

---

libflux/src/semantic/infer.rs
libflux/src/semantic/nodes.rs
libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

Ok, this is a first PR with the port of the algorithm.
There is one test that passes, but I'd like the algorithm to be reviewed and to add many more tests.

feat(rust/algw): unify function types

---

libflux/src/semantic/nodes.rs
libflux/src/semantic/tests.rs
libflux/src/semantic/types.rs

feat(semantic): infer imported package types

---

.circleci/config.yml

ci: perform github release using circleci workflow

---

libflux/src/semantic/types.rs

Constraints are not ordered, hence we cannot assume record properties
will be unified in a deterministic order. This means we cannot assume
record types are constructed in a deterministic fashion during
inference and unification.
Therefore this commit re-introduces a non-derived PartialEq
implementation for record types that compares any permuation of a
record's non-shadowed labels as equal. Shadowed labels, that is
labels that occur multiple times in a record, are scoped and
therefore implicitly ordered. Permutations of shadowed labels do not
compare as equal.
Closes #2168 .

fix(semantic): ignore order when comparing record types

---

libflux/src/semantic/parser/mod.rs
libflux/src/semantic/tests.rs

test(libflux/semantic): add test case for psuedo query

---

CONTRIBUTING.md
README.md

docs: update contributing document with information about our workflows

---

libflux/Cargo.lock
libflux/src/libflux/Cargo.toml

chore(flux): update wasm-bindgen

---

internal/execute/tableutil/stream.go
internal/execute/tableutil/stream_test.go
internal/gen/input.go

The stream implementation now takes the key and columns when creating
the stream instead of using the first column reader. This makes it
easier to write the functionality and it makes it easier to construct an
empty table by just not sending anything. It is also possible to now
repeatedly send nothing and still get an empty table.

refactor(tableutil): modify the stream implementation

---

internal/cmd/flux-config/build.go
internal/cmd/flux-config/main.go

feat: teach flux-config how to download the sources when using vendor

---

libflux/src/flux/semantic/builtins.rs

This patch adds the final type declarations for universe, specifically
the builtins A-H.

feat(libflux): add type declarations for universe

---

libflux/src/flux/lib.rs

This patch addresses the following lints:
- [`not_unsafe_ptr_arg_deref`](https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref)
- [`missing_safety_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc)
The first lint was done as a result of having the public functions.
Public functions that use unsafe calls must be declared entirely unsafe.
This change also caught a second lint that requires a "Safety" section
of the documentation. Since there was no documentation for these
functions, they now _only_ contain a safety function. The documentation
for them is relatively generic, because the unsafe nature of these
functions is pretty plain.
Since unsafe code can be somewhat questionable, this is its own patch
for the clearest review …

chore(libflux): address unsafe code-related lint

---

libflux/src/flux/semantic/builtins.rs

It turns out there are a couple of type errors in the builtin types, this fixes the ones that were found.

fix(builtins): fix a couple errors in builtin types

---

libflux/src/flux/parser/mod.rs
libflux/src/flux/parser/strconv.rs
libflux/src/flux/semantic/bootstrap.rs
libflux/src/flux/semantic/types.rs

fix(libflux): remove redundant clones found by a new version of clippy

---

libflux/src/flux/semantic/builtins.rs

This changes makes it so that set expects a list of records instead of a single record
Fixes #2303

fix(libflux/semantic): update experimental.set builtin type

---

semantic/types/monotype.go
semantic/types/polytype.go

This PR concerns the new `PolyType` and `MonoType` structs that are backed by flat buffers.
This change updates the `String()` method for `PolyType` and `MonoType` to make them more useful, so that output is always consistent. This will make them easier to use in tests.

chore: update PolyType and MonoType String() method to be deterministic

---

compile.go
interpreter/interpreter_test.go
interpreter/package_test.go
semantic/package.go
stdlib/regexp/regexp_test.go

This gets the interpreter tests compiling. The object builder is required to get tests passing.

refactor(interpreter): get interpreter tests compiling

---

compiler/runtime.go
interpreter/interpreter_test.go
semantic/monotype.go
semantic/types.go
values/array.go
values/binary.go
values/binary_test.go
values/object.go
values/values.go
values/values_test.go

The values package is passing tests now. Note there are no more un-typed nulls, only typed nulls.

refactor(values): tests passing

---

compiler/compiler.go
compiler/compiler_test.go
compiler/runtime.go
semantic/flatbuffers.go
semantic/monotype.go
stdlib/regexp/regexp_test.go
values/array.go
values/binary.go
values/object.go
values/scope.go
values/values.go

refactor(compiler): update the compiler for algorithm w

---

execute/executetest/dataset.go
execute/executetest/source.go
go.mod
go.sum

Update to remove dependency on insecure version of uuid library
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488

fix: uuid security

---

dependencies/url/validator.go
dependencies/url/validator_test.go

Security fix to prevent connections to private address space.
Test written, but not sure it works as it should. Would love feedback!

fix(stdlib/http): add 169.254/16 range to URL validator

---

execute/row_fn.go
execute/row_fn_test.go
execute/table.go

refactor(execute): update execute package to work with algorithm w

---

parser/parser_test.go
repl/repl.go
values/objects/table.go

refactor: get values and repl packages passing tests

---

internal/cmd/flux-config/build.go

fix: flux-config correctly copies stdlib when using a module

---

internal/cmd/flux-config/build.go

fix: link libstd into the lib directory instead of libflux

---

internal/cmd/flux-config/build.go

fix: link both libflux and liblibstd for flux-config

---

compile.go

fix(flux): expect monotypes for function values

---

libflux/src/flux/ast/mod.rs
libflux/src/flux/formatter/mod.rs
libflux/src/flux/formatter/tests.rs
libflux/src/flux/lib.rs

feat(libflux/flux): add formatter lib

---

stdlib/experimental/http/get_test.go
stdlib/experimental/object_keys_test.go
stdlib/http/post_test.go
stdlib/json/encode_test.go
stdlib/universe/group_test.go
stdlib/universe/length_test.go
stdlib/universe/reduce_test.go
stdlib/universe/table_fns_test.go

More updates to stdlib. It compiles now but still fails tests.

fix(stdlib): make stdlib compile

---

complete/complete.go
complete/complete_test.go

fix(complete): complete package compiles and passes tests

---

CONTRIBUTING.md

Added Security Vulnerability Reporting section

docs(CONTRIBUTING): add vulnerability reporting section

---

stdlib/universe/typeconv.go

fix(universe): return proper types for type conversion functions

---

result_test.go
stdlib/universe/schema_mutators.go
stdlib/universe/table_fns.go

fix: schema mutators and miscellaneous todos

---

execute/row_fn.go
stdlib/generate/from.go
stdlib/internal/promql/join.go
stdlib/universe/filter.go
stdlib/universe/schema_functions.go
stdlib/universe/schema_mutators.go

This updates the stdlib package to work with algorithm w by using the
compiler in the new method.

refactor(stdlib): update stdlib for algorithm w

---

compile.go

This fixes a panic but still has a few TODOs left

fix(flux): use array type method correctly

---

runtime.go

refactor(runtime): initialize the stdlib using the interpreter

---

compile.go
internal/spec/build.go
stdlib/internal/promql/join.go
stdlib/regexp/regexp_test.go
stdlib/testing/assert_equals.go
stdlib/testing/diff.go

fix: change TableObjects from type Object to type Array

---

libflux/go/libflux/analyze.go
libflux/go/libflux/analyze_test.go
libflux/go/libflux/flux.h
libflux/go/libflux/parser.go
libflux/go/libflux/parser_test.go
libflux/src/flux/lib.rs

feat(libflux): handle multi-file packages

---

lang/compiler_test.go

fix(lang): type errors in tests

---

libflux/src/flux/semantic/builtins.rs

fix(holtwinters): update holtWinters type to make seasonality optional.

---

libflux/src/flux/semantic/fresh.rs

When updating a Row type with fresh type variables, it is important that
we iterate over its properties in a deterministic fashion. Here we sort
a row's properties by their labels before generating fresh type variables.
Note this code is only exercised during testing when comparing PolyTypes for equality.

fix(libflux): freshen row types using deterministic property order

---

libflux/src/flux/semantic/check.rs

When assigning two options from a different external package,
a semantic check was failing, since it was looking at the package name,
rather than the package and option name to find option reassignments.

fix(semantic): fix semantic check for option reassignment

---

stdlib/math/math_test.go

refactor: fix math test function

---

stdlib/universe/contains_test.go

refactor: fix test for contains

---

compiler/compiler.go
stdlib/generate/from.go

refactor: fix stdlib generate to use new the compiler

---

examples/library/library_example_test.go
internal/spec/build_test.go
lang/compiler_test.go
libflux/src/flux/lib.rs
libflux/src/libstd/lib.rs
stdlib/experimental/object_keys_test.go
stdlib/http/post_test.go
stdlib/internal/promql/join_test.go
stdlib/json/encode_test.go
stdlib/pagerduty/pagerduty_test.go
stdlib/slack/slack_test.go
stdlib/universe/contains_test.go
stdlib/universe/filter_test.go
stdlib/universe/group_test.go
stdlib/universe/length_test.go
stdlib/universe/map_test.go
stdlib/universe/schema_functions_test.go
stdlib/universe/state_tracking_test.go
stdlib/universe/table_fns_test.go

This issue was created to make all tests on the `feat/use-algo-w` branch pass in CI. Tests that were failing have been skipped and issues have been created to tackle them. 
Issues that were created include: 
#2496, #2494, #2492, #2490, #2482, #2481, #2479, #2476, #2475, #2474 and #2473

test: fix failing tests and make CI green

---

stdlib/universe/contains_test.go
stdlib/universe/length_test.go

Fixes https://github.com/influxdata/flux/issues/2481.

fix(stdlib): type assertion error in length tests

---

stdlib/universe/group_test.go
stdlib/universe/schema_functions_test.go
values/valuestest/scope.go

Fixes https://github.com/influxdata/flux/issues/2490.

fix(values): do not call LocalRange on nil scope

---

libflux/src/flux/semantic/builtins.rs
libflux/src/flux/semantic/mod.rs
libflux/src/flux/semantic/types.rs
libflux/src/libstd/build.rs

The window function contains two type variables but only one of them was universally quantified. Now both are.

fix(semantic): update type of window function

---

execute/executetest/compile.go
stdlib/internal/promql/join_test.go
stdlib/universe/filter_test.go
stdlib/universe/map_test.go
stdlib/universe/schema_functions_test.go
stdlib/universe/state_tracking_test.go

test: fix and unskip tests that create function expressions

---

lang/compiler_test.go

Fixes https://github.com/influxdata/flux/issues/2479.

fix(lang): update TableObject test

---

internal/spec/build_test.go

Fixes https://github.com/influxdata/flux/issues/2496.

fix: type error in benchmark test

---

stdlib/universe/filter_test.go
stdlib/universe/map_test.go

Fixes https://github.com/influxdata/flux/issues/2492.

fix(universe): remove tests for marshalling semantic graph

---

interpreter/package_test.go

This PR updates a test showing that one can import and mutate an option from an external package.
Fixes https://github.com/influxdata/flux/issues/2410.

fix(interpreter): test option assignment

---

stdlib/universe/map.go
stdlib/universe/map_test.go

Fixes https://github.com/influxdata/flux/issues/2497.

fix(universe): unskip map tests with null values

---

values/time.go

The values package used the parser for parsing the duration even though
this parser is written in pure Go. This refactors the code a bit so that
it references the Go parser and does not depend on the top level parser
package which depends on `libflux`.
Fixes #2520.

refactor(values): remove the values dependency on the parser

---

stdlib/experimental/query/flux_gen.go
stdlib/universe/table_fns.go
stdlib/universe/table_fns_test.go

Fixes https://github.com/influxdata/influxdb/issues/16810.

fix(universe): array builders must take array types as input

---

stdlib/pagerduty/flux_gen.go
stdlib/pagerduty/pagerduty.flux
stdlib/pagerduty/pagerduty_test.go

fix(pagerduty): remove component field from api

---

stdlib/flux_test.go

test(stdlib): unskip dynamic query end to end test

---

stdlib/testing/diff.go

refactor(testing): diff should compare floats with tolerance

---

libflux/src/flux/parser/mod.rs

fix: handle unfinished option statement without panic

---

libflux/c/main.c

fix: fix valgrind test code

---

go.mod
go.sum
libflux/go/libflux/link_dynamic.go
libflux/go/libflux/link_static.go
libflux/go/libflux/parser.go

This patch adds support for static linking libflux and flux.

feat: add support for static linking

---

.circleci/config.yml

fix: adjust test-bench config for circle ci

---

README.md

docs: update the readme with better pkg-config instructions

---

Makefile
libflux/Cargo.lock
libflux/src/flux/Cargo.toml

Bump version for npm and add make tasks to publish

chore: bump version to 0.4.0 of flux parser

---

Makefile

The `libflux-go` target will generate a hack file that forces go to
rebuild the libflux wrapper. This target is added as a dependency for
any target that invokes a go build command. This will force go to rebuild.

ci: add a libflux-go target to ensure libflux-go will get rebuilt

---

xcc.sh

fix: remove the set -x in the xcc script

---

interpreter/interpreter.go

Needed to fix https://github.com/influxdata/influxdb/issues/17065.

fix(interpreter): bind appropriate interpreter when evaluating functions

---

stdlib/testing/diff.go

fix(testing): calculate diff's watermark using both predecessors

---

stdlib/universe/pivot.go

fix(stdlib): pivot will send update watermark and processing time exactly once

---

interpreter/interpreter.go
interpreter/interpreter_test.go

A string expression of the form `"... ${r.foo} ..."` where `r.foo` either does not exist or has a type other than `string` previously produced a panic. This fix now checks the type and produces an appropriate message.

fix: check types of parts when evaluating StringExpression

---

execute/executetest/source.go
stdlib/csv/from.go
stdlib/csv/from_test.go

feat(execute/executetest): add a helper for testing an execute.Source

---

interpreter/interpreter.go
interpreter/interpreter_test.go

This allows the query planner to be able to push predicates like:
r.env == v.env
down to storage.

fix(interpreter): resolve member expressions

---

docs/new_flux_ideas_and_guide.md

Ideas for changes to Flux to aid in usability and make common queries easier with less ceremony.

docs: create new guide and ideas for Flux changes

---

stdlib/experimental/alignTime_test.flux
stdlib/experimental/flux_test_gen.go

fix: add bounds to alignTime tests

---

compiler/compiler.go
compiler/runtime.go
internal/fbsemantic/semantic.fbs
internal/fbsemantic/semantic_generated.go
libflux/src/core/semantic/convert.rs
libflux/src/core/semantic/flatbuffers/mod.rs
libflux/src/core/semantic/flatbuffers/semantic_generated.rs
libflux/src/core/semantic/nodes.rs
libflux/src/core/semantic/tests.rs
libflux/src/core/semantic/walk/_walk.rs
libflux/src/core/semantic/walk/walk_mut.rs
libflux/src/core/tests/analyze_test.rs
semantic/flatbuffers_gen.go
semantic/flatbuffers_test.go
semantic/graph.go
stdlib/universe/filter_partial_pushdown_test.flux

refactor: remove type annotations from literal expressions

---

libflux/README.md
libflux/site/package.json
libflux/site/yarn.lock

chore(libflux): update minimist yarn dep for libflux WASM module

---

CONTRIBUTING.md
docs/new_flux_ideas_and_guide.md
stdlib/README.md
stdlib/contrib/README.md

docs(stdlib/contrib): add docs on how to contribute third party packages

---

go.mod
go.sum
stdlib/sql/from.go
stdlib/sql/from_private_test.go
stdlib/sql/snowflake.go
stdlib/sql/source_validator.go
stdlib/sql/to.go
stdlib/sql/to_privates_test.go

This PR adds Snowflake support to `sql` package.

feat(sql): add Snowflake support

---

libflux/Cargo.lock
libflux/src/flux/Cargo.toml

chore: bump version to publish to npm

---

dependencies/http/http.go
dependencies/http/http_test.go

This patch adds a callback to the default http client that will validate
URLs on redirect.

fix: validate http redirects against private ips

---

stdlib/planner/flux_test_gen.go
stdlib/planner/group_count_eval_test.flux
stdlib/planner/group_count_push_test.flux
stdlib/planner/group_sum_eval_test.flux
stdlib/planner/group_sum_push_test.flux

test: added end-to-end planner tests for group-count and group-sum

---

Makefile
libflux/Cargo.lock
libflux/src/core/Cargo.toml
libflux/src/flux/Cargo.toml

- fix version number
- remove old build before rebuilding

chore: update publish workflow to ensure clean publish

---

libflux/src/core/formatter/mod.rs
libflux/src/core/formatter/tests.rs

fix(libflux): add builtin formatting

---

compiler/compiler.go
compiler/compiler_test.go

When one of the arguments for the compiler function was a record and the
record was used with the `with` operator, the compiler function would
learn that the return type extended a record, but not what the record
was.
This fixes the compiler so if the extended record is one of the
arguments, the type that was passed into the compiler is included in the
substitutions for extended records. This allows type inference to be
more accurate in the compiler with a return value like this:
map(fn: (r) => ({r with _value: r._value * 2.0}))
If the record contains a `_time` column, that previously would not have
been included in the resolved return value. This prevented functions
like `map` from relying on the return value from type inference.

fix(compiler): fix the compiler's return type when with is used

---

lang/compiler.go
libflux/go/libflux/buildinfo.gen.go
libflux/src/core/semantic/convert.rs

…lize()
Changes needed for the OSS API to extract option reference PR https://github.com/influxdata/influxdb/pull/18796

refactor: AstProgram.GetAst()

---

stdlib/universe/window.go

fix(window): add a check to ensure that every is nonnegative

---

internal/spec/build.go

fix: classify spec build errors as user errors

---

ast/edit/task_editor.go
ast/edit/task_editor_test.go
ast/helpers.go
compiler/compiler_test.go

Closes influxdata/influxdb#17386.

feat(ast/edit): crud options and properties

---

execute/table.go
execute/table_test.go

fix(execute): multiple do calls will fail with the empty table

---

execute/table/diff.go
internal/cmd/tablediff/tablediff.go

feat(internal/cmd): internal command utility for comparing csv tables

---

ast/edit/task_editor.go
ast/edit/task_editor_test.go

Updates options/properties api to be able to blindly return all options and properties.

feat(ast/edit): get all options and props

---

ast/edit/task_editor.go
ast/edit/task_editor_test.go

revert(ast/edit): get all options and props (#3044)

---

libflux/go/libflux/buildinfo.gen.go
libflux/src/core/semantic/convert.rs
stdlib/sql/to_privates_test.go

feat(libflux/semantic/convert.rs): add convert_polytype

---

ast/ast.go

Added Copy functionality to monotype using reflect.

added monotype copy functionality using reflect. <stackoverflow>

---

docs/SPEC.md

docs: add kind constraints to the spec

---

interpreter/interpreter_test.go

chore: fix interpreter test for line information

---

go.mod
go.sum

feat: update apache arrow to 1.0.1

---

docs/SPEC.md

docs(SPEC): escape pipe forward in operator table

---

stdlib/universe/elapsed.go
stdlib/universe/elapsed_test.go

fix: elapsed with multiple buffers per table

---

libflux/go/libflux/internal/buildinfo/main.go

The buildinfo utility prior to this change only considered files that
were part of the git cache. This meant that new files had to be added to
git before it would build them and files that were deleted from the
filesystem but not git would cause an error.
Now the utility will correctly find new untracked files and skip files
that have been deleted while still skipping files ignored by git.

fix(buildinfo): update buildinfo script to handle new and deleted files

---

libflux/Dockerfile

Also install gpg in Dockerfile. (This worked locally. 🤞 )

fix(libflux): Add gpg verification for ragel dependency

---

Dockerfile_build

Ports work from https://github.com/influxdata/flux/pull/3235, https://github.com/influxdata/flux/pull/3236, https://github.com/influxdata/flux/pull/3237 to this file.

fix: Verify dependencies in Dockerfile_build

---

docs/user_docs/flux-by-example.md

Calculating a percentage - 1 pass over the data

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/tasks/flux_gen.go
stdlib/influxdata/influxdb/tasks/flux_test_gen.go
stdlib/influxdata/influxdb/tasks/last_success_duration_no_option_test.flux
stdlib/influxdata/influxdb/tasks/last_success_duration_option_test.flux
stdlib/influxdata/influxdb/tasks/tasks.flux
stdlib/influxdata/influxdb/tasks/tasks.go
stdlib/influxdata/influxdb/tasks/tasks_test.go

feat: orTime argument of lastSuccess is timeable

---

metadata/metadata.go
stdlib/influxdata/influxdb/tasks/tasks.go
stdlib/influxdata/influxdb/tasks/tasks_test.go

fix: execute dependencies have moved, update tasks stdlib module

---

.codecov.yml
query.go

I also made a small change to a file to see how this changes
behavior of the coverage bot.

ci(coverage): update codecov.yml to make patch coverage informational

---

interpreter/interpreter_test.go

Adds a suite of tests around operator precedence to the interpreter.

chore(interpreter): adds tests for operator precedence

---

stdlib/universe/pivot.go
stdlib/universe/pivot_test.go

fix(stdlib): do not panic when the value column for pivot does not exist

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/schema/flux_test_gen.go
stdlib/influxdata/influxdb/schema/show_tag_values_empty_test.flux

This is a regression test for https://github.com/influxdata/flux/issues/3300.

test: add regression test for tagValues returning nothing

---

lang/compiler.go
lang/compiler_test.go

This changes the `AstProgram` to retrieve the now option before it runs
the flux script. The reason is because the now option is placed into the
scope before the script is executed, but it can be reassigned to a
different value during execution. When we tried to retrieve the option
afterwards, it resulted in selecting the local now instead of the one
from the universe package.
We now retrieve the option ahead of time. If the option is redefined
with `option`, then the retrieved option will be modified in a mutable
way that we can access anyway and it avoids accidentally using a similar
variable with the same name.
Fixes influxdata/influxdb#18883.

fix(lang): retrieve now option before running the flux script

---

cmd/flux/cmd/test.go

This patch refactors the new flux test runner to use structs to form a
cleaner organization and architecture for expansion into downstream
consumers. The intention is to layout out pieces that should be
composable. As such, the `TestRunner` and `TestReporter` are new in this
patch, though not in any sort of final form.
Additionally, cli arguments for the basic needs of the test runner were
introduced in this patch.

refactor: clean up flux test runner

---

stdlib/universe/difference.go

This prepares for implementing https://github.com/influxdata/flux/issues/3400
by regularizing the implementation somewhat.
The `difference` type is now responsible only for returning
values and validity of those values (including dealing with `nonNegative`);
the `Process` method deals with removing the first row.
We rename the `difference.first` field to `difference.valid` (reversing
its sense in the process) because it's currently a little misleading,
because it might be true even when an update method is called
for a record that's not first.
Also reduce indentation somewhat by returning/continuing early
when appropriate.

chore: stdlib/universe: simplify difference implementation

---

docs/SPEC.md

docs: dictionary type

---

libflux/fluxdoc/templates/base.html
libflux/fluxdoc/templates/package.html

- Removes an extraneous div
- puts the values back into the content block

fix: Fixes fluxdoc layout

---

libflux/fluxdoc/templates/base.html

Adds a link to the navbar for the playground site

feat: Add link to play.fluxlang.dev

---

cmd/flux/cmd/repl.go
cmd/flux/cmd/test.go
cmd/flux/main.go

feat(cmd): expose test command so it can be used by external libraries

---

interval/window.go

feat: reintroduce IsZero method on windows

---

execute/executetest/dataset.go
interval/bounds.go
interval/window.go
interval/window_test.go
stdlib/universe/range.go
stdlib/universe/window.go
stdlib/universe/window_interval.go
stdlib/universe/window_test.go

feat(stdlib/universe): add interval package to window transformation

---

interval/window.go

feat: getters for a window's every and period

---

execute/executetest/result.go

When `executetest.EqualResultIterators` fails, it's not clear exactly where
the error is, because the error doesn't make it clear how far through the
iteration the failure happens.
Rather than add a load of annotations, instead use a simpler implementation
that just reads all the data from both iterators and uses `cmp.Diff` to show any
differences.
This might not be appropriate for use in a running service (because it uses O(n)
memory), it should be fine in a testing scenario.

chore: execute/executetest: better error messages on failure

---

libflux/core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

fix(libflux): Fix typo in comment

---

Dockerfile_build
libflux/Dockerfile

Added a environment variable RUST_LATEST_VERSION which will be updated manually after every new stable release.

fix: change rust version to be updated manually

---

stdlib/universe/map_test.go
stdlib/universe/typeconv.go
stdlib/universe/typeconv_test.go

The PR converts all internal error messages to user messages for all type conversion methods. It also refactors and removes decent chunks of boilerplate code for said type conversion methods.

fix(universe): refactored type conversion code and fixed error messages

---

Dockerfile_build

fix(build): install the default toolchain for rust with the environment variable

---

libflux/core/src/parser/mod.rs
libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/jsternberg/aggregate/window.go

I noticed a questionably `if` statement that did `else if` on the same
conditions. After chatting with @jsternberg, I made this fix.
Additionally, I found some clippy lints to update, as I'm a bit ahead of
the curve on the clippy that we keep in CI.

fix(stdlib/contrib): fix a logic error

---

libflux/flux-core/src/lib.rs

A few formatting fixes and edits.

docs(libflux): edit crate docs

---

stdlib/slack/slack_test.go

chore: run go fmt on stdlib/slack/slack_test.go

---

Dockerfile_build

chore: update ci to use go 1.16

---

stdlib/universe/map.go
stdlib/universe/map_test.go

fix(map): Return error if we map over mismatched types

---

.circleci/config.yml

fix: Remove codecov job

---

execute/dataset.go
execute/executor.go

This modifies the execution engine to wait for the dispatcher to finish
before the query is finally closed. It also adds a cancel context to the
execution engine that gets threaded into the dispatcher so the
dispatcher can be interrupted. This gets attached to the default dataset
which will abort processing tables.

fix(execute): wait for the dispatcher to finish before finishing query

---

values/dict.go

feat(values): add string formatting to dict type

---

README.md

fix(README.md): updated Go version requirements

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/range_nsecs_test.flux

Adding [the test coverage requested here](https://github.com/influxdata/flux/issues/3668) by @lesam. 
Closes #3668

test(stdlib): test range to nsec precision - bare and group cases

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/range_nsecs_test.flux

test(stdlib): fix tests to pass in storage

---

libflux/go/libflux/buildinfo.gen.go
stdlib/pagerduty/pagerduty_test.flux

fix(stdlib): pagerduty tests did not include _value column

---

Dockerfile_build

Update to new stable rust version

chore: update to rust 1.53

---

libflux/flux/FLUXDOC.md
libflux/go/libflux/buildinfo.gen.go

Some suggestions for the fluxdoc spec in https://github.com/influxdata/flux/pull/3803/.

docs: Edit fluxdoc spec

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/distinct.go
stdlib/universe/distinct_test.flux

fix(stdlib): distinct appends null values without creating invalid tables

---

libflux/go/libflux/buildinfo.gen.go
stdlib/runtime/flux_gen.go
stdlib/runtime/runtime.flux
stdlib/testing/flux_gen.go
stdlib/testing/testing.flux

docs: documented testing stdlib package

---

libflux/go/libflux/buildinfo.gen.go
stdlib/regexp/flux_gen.go
stdlib/regexp/regexp.flux

added documentation to `stdlib/regexp`

docs: document regexp pkg

---

libflux/go/libflux/buildinfo.gen.go
stdlib/pagerduty/flux_gen.go
stdlib/pagerduty/pagerduty.flux

docs: pagerduty.flux

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/secrets/flux_gen.go
stdlib/influxdata/influxdb/secrets/secrets.flux

added documentation to `stdlib/influxdata/influxdb/secrets`

docs: document influxdb secrets pkg

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/tasks/flux_gen.go
stdlib/influxdata/influxdb/tasks/tasks.flux

added documentation to `stdlib/influxdata/influxdb/tasks`.

docs: document influxdb tasks pkg

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/monitor/flux_gen.go
stdlib/influxdata/influxdb/monitor/monitor.flux

docs: indluxdb/monitor docs

---

libflux/go/libflux/buildinfo.gen.go
stdlib/interpolate/flux_gen.go
stdlib/interpolate/interpolate.flux

added documentation for `stdlib/interpolate`.

docs: document interpolate pkg

---

cmd/flux/cmd/test.go

This adds a `--skip` flag to the `flux test` command, which takes a comma-separated list of test case names.

feat: add command line flag to skip tests to "flux test"

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/pivot.go
stdlib/universe/pivot_internal_test.go
stdlib/universe/pivot_table_test.flux
stdlib/universe/pivot_test.go

feat(stdlib): optimize pivot transformation

---

libflux/go/libflux/buildinfo.gen.go
stdlib/influxdata/influxdb/v1/flux_gen.go
stdlib/influxdata/influxdb/v1/v1.flux

added documentation for `stdlib/influxdata/influxdb/v1`

docs: document influxdb v1 pkg

---

stdlib/experimental/to.go
stdlib/experimental/to_test.go
stdlib/influxdata/influxdb/provider.go

fix(stdlib/experimental): to() function properly closes the writer on error

---

.circleci/config.yml

ci: disable the windows build until it uses the same rust version as the linux build

---

stdlib/universe/pivot.go

fix(stdlib): update sortedPivot kind

---

stdlib/universe/pivot.go

fix(stdlib): register sorted pivot

---

array/array.go
array/array_test.go

feat(array): modify the string array builder to support constant data

---

internal/pkg/feature/feature_test.go

chore(feature): run gofmt on feature test

---

execute/README.md

docs(execute): add documentation for the execution engine and creating transformations

---

docs/SPEC.md

docs(SPEC): add examples of type expressions to SPEC

---

libflux/flux-core/src/semantic/tests.rs
libflux/go/libflux/buildinfo.gen.go

test: Correct the type now that the parser reports errors in arguments

---

stdlib/universe/reduce.go
stdlib/universe/reduce_test.go

fixes: https://github.com/influxdata/flux/issues/4085

fix(stdlib): update null check with clear error message

---

Dockerfile_build
go.mod
go.sum

chore: update rust and pkg config

chore: update rust and pkg config

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/window_location_test.flux

fix(stdlib): add range transformation before window to set bounds

---

dependencies.go
dependencies/bigtable/bigtable.go
go.mod
stdlib/experimental/bigtable/bigtable_rewrite.go
stdlib/experimental/bigtable/from.go
stdlib/experimental/bigtable/rowreader.go

This creates a bigtable dependency that the bigtable package now uses.
Fixes #4143.

feat(dependencies/bigtable): create bigtable dependency

---

libflux/flux-core/src/doc/mod.rs
libflux/go/libflux/buildinfo.gen.go

feat(libflux): ignore docs for values prefixed with underscore

---

libflux/flux-core/src/doc/mod.rs
libflux/go/libflux/buildinfo.gen.go

fix(fluxdoc): add support for pipe parameters to fluxdoc

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/bin/fluxdoc.rs
libflux/flux-core/src/doc/example.rs
libflux/go/libflux/buildinfo.gen.go

Tried running it and encountered some bad errors. This should give some additional context.

fix: Give better error messages when fluxdoc errors

---

go.mod
go.sum

feat: update pkg-config to support aarch64-apple-darwin

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/shift.go
stdlib/universe/shift2.go

This optimizes shift to use arrow tables and the narrow transformation
transport.

feat(stdlib): add an optimized version of the shift transformation

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/union.go
stdlib/universe/union2.go

feat(stdlib): optimize union transformation

---

stdlib/universe/union2.go

fix(stdlib/universe): optimized union needs a mutex

---

execute/aggregate.go
execute/group_transformation.go
execute/narrow_state_transformation.go
execute/narrow_transformation.go
execute/transport.go

This consolidates the code around the transformation wrapper so that
transports do not have to implement it themselves. It wraps a transport
into something compatible with the transformation and transport
interfaces in one place instead of spread out into multiple places.

refactor(execute): consolidate transformation wrapper for transport

---

stdlib/influxdata/influxdb/to.go
stdlib/influxdata/influxdb/to_test.go

feat(stdlib): update the to transformation to use narrow transformation

---

metadata/metadata.go

Some minor refactorings, see commits.

refactor: Add some helper functions

---

dependencies/influxdb/http.go

fix(dependencies/influxdb): support writing uint with the http provider

---

values/types.tmpldata
values/vector_values.gen.go
values/vector_values.gen.go.tmpl

fix(values): add time vector to the values package

---

stdlib/experimental/http/requests/requests_test.go

Getting a different error locally so the test would fail.

test: Make TestDo_DNSFail work on ubuntu (or my computer at least)

---

cmd/flux/cmd/test.go

Today, `TestExecutor`s that depend on being able to run code on teardown by
implementing `Close()` are unable to since `os.Exit()` will terminate the
process before any deferred functions are able to run.
The exiting, if deemed necessary, should probably be the responsibility
of the actual binary rather than deep in the test runner.
While it would be preferred to simply hand errors back to the caller,
this diff avoids updating the signatures of public functions by
converting the previous `Exit` calls into `panic`s. The benefit of this
is a panic will still allow deferred functions to be called as the stack
unwinds.
~~In the future, we may elect to clean this up further by refactoring public
functions like `Finish()` to return errors.~~ The future is _now_. This has been updated to return …

fix(test): remove `os.Exit` calls, allow defer `executor.Close` to run

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/aggregate_window.go

feat(stdlib): optimized version of aggregate window for specific aggregates

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/quantile.go
stdlib/universe/quantile_tdigest_test.flux

feat(stdlib): allow quantile with tdigest to process any numeric

---

libflux/flux-core/src/semantic/types.rs
libflux/go/libflux/buildinfo.gen.go

feat: Expose the Record::fields iterator

---

Makefile

chore(build): test Rust API docs build in CI

---

execute/parallel_test.go
plan/plantest/rules.go

Moved helpers for creating plan nodes with attributes into plantest so we can
use those in planner rule tests.
Including output and required physical attributes in the want/got diff in
PhysicalRuleTestHelper. This lets us specify attributes in planner rule tests
for the parallelization rules.

test: support for testing parallelization planner rules

---

stdlib/universe/narrow_state_tracking.go

This [PR](https://github.com/influxdata/flux/pull/4520) was created before the apache arrow upgrade to v7.
So fixed it for the v7

fix: replaced old version of apache arrow with v7

---

docs/SPEC.md
stdlib/json/encode.go
stdlib/json/encode_test.go

Replacement for https://github.com/influxdata/flux/pull/3606, rebased on latest master.

fix(json): dictionary encoding

---

stdlib/universe/parallel.go

The parallel merge receives data from multiple input datasets. The execution
engine does not force these to be sequential, therefore we must protect
ourselves against calling finish on the single output dataset multiple times.
This PR adds a finished state tracker and uses the mutex to protect it in all
functions (Process included). In Process we can delay the locking to after the
output data is built. This doesn't appear to impact performance in practice.
This PR protects against recoverable panics when something in the execution
pipeline before the merge produces an error at execution time. It forces data
messages to immediately stop and guarantees a single output finish message.
Note that this transformation should really use the new narrow chunk processing
API. At this time, that is …

feat: added a finish state to parallel-merge, always protect with lock

---

dependencies/mqtt/mqtt.go
internal/feature/flags.go
internal/feature/flags.yml

This reverts commit dc08c571a0220d3b7cd99d90e5dfcc2a416acb7f.

revert: "feat(mqtt): enable dialer pool for everyone (#4565)"

---

execute/transport.go
lang/compiler_test.go

This will create a new span for each Flux transformation in a query. There will be one span per for each transformation that is planned (not once for each table or each chunk) so the size of the trace should remain manageable.

feat: add opentracing spans to the Flux runtime

---

Makefile
cmd/flux/main.go
runtime/runtime.go
stdlib/experimental/http/requests/requests_test.go

See commits for reasons. Extracted from #4388

refactor: Extract some general tweaks from the label polymorphism PR

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/map_test.flux

Test fails in IDPE, this will fix it

fix(map): update test case to have range

---

libflux/go/libflux/buildinfo.gen.go
stdlib/types/types.flux

chore(docs): corrected version for types package

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/moving_average.go
stdlib/universe/moving_average2.go

perf(stdlib): create optimized version of moving average

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/cumulative_sum.go
stdlib/universe/cumulative_sum2.go

perf(stdlib): optimize cumulative sum transformation

---

.github/workflows/semantic.yml

- [N/A ] docs/SPEC.md updated
- [ N/A] Test cases written
When this is approved, merged and I've validated it's working correctly, I will remove semantic-pull-requests from this repo.

feat: add influxdata semantic commit and PR title validator.

---

execute/executetest/dependencies.go
internal/feature/flags.go
internal/feature/flags.yml
stdlib/universe/set.go

perf(stdlib): add a version of set that uses table chunks

---

etc/fixup_docs_version.sh
libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/experimental.flux

build(flux): prepare Flux release for v0.167.0

---

plan/heuristic_planner.go
plan/heuristic_planner_test.go

The change to the planner conflicted with another concurrent change
causing tests to fail. We should re-apply the change against new master.

revert(plan): revert https://github.com/influxdata/flux/pull/4614

---

execute/executor.go

fix(execute): metadata in flux statistics needs to be initialized

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/drop_fn_test.flux

refactor: Update drop_fn_test to an acceptance test

---

cmd/flux/cmd/test.go
cmd/flux/test.go

The test harness has been updated so that more of the handling of the
results is handled by the test harness rather than the individual test
executor implementations.
This changes the interface so it returns a `flux.ResultIterator` rather
than handling the checking of the result.
This also removes the requirement for the error output yield to exist.
If the yield returns nothing, there's a chance it might not be emitted
at all because the csv encoder doesn't encode empty results. We might
want to fix that, but there's no way with the existing behavior and the
previous test harness didn't have this requirement.

refactor(test): update test harness for error output

---

libflux/go/libflux/buildinfo.gen.go
stdlib/universe/yield_test.flux

fix(stdlib): remove testing.load from yield test

---

cmd/flux/cmd/test.go
cmd/flux/test.go

The previous changes to the test executor worked in one environment, but
was too difficult to refactor with the defers in the second test
environment. This changes the flow back so the entire test is executed
inside of run and handles reading the result by using a callback
function instead.

refactor(test): second refactor of the test executor

---

CODEOWNERS

chore(CODEOWNERS): do not request docs team for test changes

---

Dockerfile_build

Needed to read sqlite databases in https://github.com/influxdata/flux/pull/4938

chore: Add libsqlite3-dev to the docker image

---

cmd/flux/cmd/test.go
go.mod
go.sum

feat: Make the test output easier to read

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/polyline/polyline.flux

build(flux): prepare Flux release for v0.181.0

---

internal/function/function.go
interpreter/interpreter.go

The utility uses the function package to make creating a source or
transformation easier.

feat: add utility to register source and transformation

---

libflux/go/libflux/buildinfo.gen.go
stdlib/internal/testing/testing.flux

build(flux): prepare Flux release for v0.182.0

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/experimental.flux

Updates the `experimental.unpivot()` documentation to describe the behavior of the function and add an example.
---
- [ x 📖 If **language features** are changing, ensure `docs/Spec.md` has been updated

chore(docs): update unpivot documentation and add example

---

libflux/go/libflux/buildinfo.gen.go
stdlib/contrib/RohanSreerama5/naiveBayesClassifier/bayes_test.flux

Created an issue to track the skipped test: https://github.com/influxdata/flux/issues/5194

build(flux): prepare Flux release for v0.183.0

---

docs/SPEC.md

fix(docs): Minor edit to SPEC.md

---

docs/SPEC.md

fix(spec): Fix typo

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/array/array.flux

build(flux): prepare Flux release for v0.184.0

---

Dockerfile_build
compiler/runtime.go

ci: upgrade ci builder to go 1.19

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/dynamic/dynamic.flux

build(flux): prepare Flux release for v0.185.0

---

libflux/go/libflux/buildinfo.gen.go
stdlib/experimental/json/json_test.flux

This seems to have been fixed now
Closes #4479

test: Add a test for array.from usage with json.parse

---

libflux/flux-core/src/doc/mod.rs
libflux/go/libflux/buildinfo.gen.go

No code besides tests change so this should ensure we have the same coverage.

refactor: update doc tests to use expect

---

CODEOWNERS

chore(codeowners): automation-team

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/flux-core/src/ast/tests.rs
libflux/flux-core/src/parser/strconv.rs
libflux/flux-core/src/semantic/flatbuffers/tests.rs
libflux/go/libflux/buildinfo.gen.go

Update a number of dependencies. Some of these were flagged by dependabot as containing securilty issues. The chrono update resulted in a number of deprecated methods needing to be updated, mostly in tests.
- https://github.com/influxdata/flux/security/dependabot/33
- https://github.com/influxdata/flux/security/dependabot/60
- https://github.com/influxdata/flux/security/dependabot/47

chore: update dependencies

---

.circleci/config.yml
Dockerfile_build

Update the rust version to support newer versions of dependencies that require updated rust toolchains. Also update the go version to a supported one.

chore: update build tools

---

.circleci/config.yml

This packs the nupkg first, then installs it locally.

chore: Fix Windows CI

---

.circleci/config.yml
Dockerfile_build

chore: fix build-ci-image job

---

go.mod
go.sum

This upgrades `pkg-config` in order to fix windows builds (https://github.com/influxdata/pkg-config/pull/44)

chore: upgrade pkg-config

---

libflux/Cargo.lock
libflux/flux-core/Cargo.toml
libflux/go/libflux/buildinfo.gen.go

Update lsp-types in libflux to get more up-to-date dependencies.

build(deps): update lsp-types in libflux
